### ISSUE TITLE
'You must supply options.moduleName for IIFE bundles'

### ISSUE THREAD

**Issue by laduke** [rollup/rollup#1157] opened 2016-12-18 06:20 UTC
Hi, 
Just a documentation note. 
Today is my first day opening rollup. I was getting `You must supply options.moduleName for IIFE bundles` when I tried to bundle with `format: 'iife'`

It was pretty obvious what the issue was, after I found it in the [wiki,](https://github.com/rollup/rollup/wiki/JavaScript-API) but it took longer than it should've. Maybe I'm just tired. 

I was following this:
https://github.com/rollup/rollup/wiki/Quickstart-Tutorial
and it doesn't mention   setting `moduleName: 'foo'` anywhere, even though it uses IIFE in the examples(?)

I dunno. Just wanted to give the feedback of a brand new person. Maybe I've gotten used to API docs being in README.md

**Comment by proyb6** [comment] 2016-12-19 12:40
Yes, with compiled to IIFE, need to supply moduleName at least that I found on the search too
https://github.com/bahmutov/rollem/commit/441c9464b562b75f9bc6d45c05e786d79e567882

**Comment by Victorystick** [comment] 2016-12-20 16:13
So long as your entry doesn't export anything there isn't a need to supply a `moduleName`; the bundle is completely self-contained. But if you export things, Rollup needs to know what variable to export to. Which is why it'll ask for a `moduleName`.

Take a look at the different examples over on https://rollupjs.org/ with the output format set to Globals. You'll see what I mean. :smile:

**Comment by magwas** [comment] 2017-03-02 17:44
I am here because I have encountered the same problem, and this issue is on the top of google.
However I cannot understand what you are talking about.
Where should I put moduleName: 'foo' ?

**Comment by applecool** [comment] 2017-03-14 00:07
@magwas Just add it inside the export default like this:
```
export default {
  entry: 'src/app.js',
  format: 'iife',
  moduleName: 'foo',
  dest: 'src/build.js',
...
}
```
That should work 😃

**Comment by jhabdas** [comment] 2017-03-15 14:36
> Take a look at the different examples over on https://rollupjs.org/ with the output format set to Globals. You'll see what I mean.

The HTTPs link here is insecure. Also, `Globals` is not an option for module format. I'm assuming you meant something else, but it's not clear. The OP is asking for fresh eyes on the documentation. And I understand why because I ran into the same problem creating my IIFE had had to weed around looking for the answer.

**Comment by jhabdas** [comment] 2017-03-15 15:11
Duplicate of https://github.com/rollup/rollup/issues/385

**Comment by shellscape** [comment] 2017-04-19 14:29
I'm gonna go ahead and +1 this as the docs are painfully sparse. The error output doesn't point to anything and a google search for "You must supply options.moduleName for IIFE bundles" yielded only 4 results of which this issue was the top result.

**Comment by cipri-tom** [comment] 2017-07-02 02:21
same issue here (I've been using rollup for 2 days, tho' haha).

what @applecool means is to put that in your config file (`rollup.config.js`). It is needed in case you want to refer to your entry point as if it was a module.

So if you do 
```
export default {
  entry: 'src/App.js',
  format: 'iife',
  moduleName: 'App',
  dest: 'src/build.js',
...
}
```
then somewhere else in your code, like in a `<script>` tag (which doesn't support modules yet), you can say `var app = new App();` (I'm not sure about the `new`).

Please anyone correct me if I got something wrong.

**Comment by jhabdas** [comment] 2017-07-02 02:48
@cipri-tom you may find the following post from Rich Harris of value: https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

**Comment by shellscape** [comment] 2017-07-02 03:45
How is this not in the documentation yet?

**Comment by jhabdas** [comment] 2017-07-02 03:59
@shellscape while programs are in development it's typical for docs to fall out of date. In those cases it's best to look for the information and, if not capable of finding it, find ways to help the project move forward constructively. The sheer fact this issue exists is documentation itself. It's _living_ documentation. Because nothing in life is finite or static.

**Comment by jhabdas** [comment] 2017-07-02 04:01
https://github.com/rollup/rollup/wiki/Troubleshooting#ambiguous-default-export

Here's where you can help improve the documentation right now, @shellscape, should you desire.

**Comment by Diti** [comment] 2017-11-01 14:56
I came here to say what others have already said—as a newcomer, this error message is confusing, the documentation still doesn’t mention anything about setting a name and what it is useful for.

Thanks @cipri-tom for answering this issue in clear terms!

**Comment by guybedford** [comment] 2018-02-11 10:16
This definitely reads `options.name` in the message now.

**Closed by guybedford** 2018-02-11 10:16 UTC
Labels: closing for inactivity, dev-x, documentation, support

**Comment by LeeeeeeM** [comment] 2018-11-27 09:46
what if the module i will just read from file and get the iife module from new Function, the moduleName  option just bothers me

**Comment by dheerajsuthar** [comment] 2019-01-17 06:04
> @magwas Just add it inside the export default like this:
> 
> ```
> export default {
>   entry: 'src/app.js',
>   format: 'iife',
>   moduleName: 'foo',
>   dest: 'src/build.js',
> ...
> }
> ```
> That should work 😃

**moduleName** is just **name** now

**Comment by michaelprescott** [comment] 2019-01-30 03:47
> > @magwas Just add it inside the export default like this:
> > ```
> > export default {
> >   entry: 'src/app.js',
> >   format: 'iife',
> >   moduleName: 'foo',
> >   dest: 'src/build.js',
> > ...
> > }
> > ```
> > That should work 😃
> 
> **moduleName** is just **name** now

What is it today?   moduleName failed and now name fails with `Unknown input option: name.`

**Comment by lukastaegert** [comment] 2019-01-30 15:51
It has been an output option for more than 1 1/2 years now and 25 Rollup versions which is about the same time when entry and dest became deprecated 😉

The current documentation on rollupjs.org is now always up to date: https://rollupjs.org/guide/en#output-name

**Comment by cube-dan** [comment] 2021-02-07 20:57
Adding my two cents here as this post is [still on top of "teh googles"](https://github.com/rollup/rollup/issues/1157#issuecomment-295289823) for the warning: `(!) If you do not supply "output.name", you may not be able to access the exports of an IIFE bundle.` ... Sorry for the threadjack. 

I was trying to build [Ladda](https://github.com/hakimel/Ladda#module-bundling) on the command line, as an IIFE, and working in the UMD version of [Spin.js](https://spin.js.org/), with a global variable name of Spin — as required in the Spin.js docs docs (see header "Installation" » "JS bundling"). 

To use the rollup transpiled version of Ladda you have to give the IIFE a var name to call from your js code. I chose to stick with what the [Ladda docs](https://github.com/hakimel/Ladda#javascript) specify; `Ladda`.

From [the Ladda js source directory](https://github.com/hakimel/Ladda/tree/master/js), the whole command line invocation turned out to be: 
```sh
rollup --name Ladda --globals spin.js:Spin --input ladda.js --format iife --file ladda.iife.js
```

Rollup kicked ass and I'm now sportin' a shiny new Ladda, on a old school (LAMP) website. Thanks for the sweet bundler team Rollup!

#### **NOTES:**
**Ladda:**
`--name Ladda` resolves the warning:
`
(!) If you do not supply "output.name", you may not be able to access the exports of an IIFE bundle.
`

`--globals spin.js:Spin` resolves the warning:
`
(!) Unresolved dependencies
`
... and sets the dependencies imported variable name to what Spin exports in it’s [UMD version](http://spin.js.org/spin.umd.js). ... Which I didn't end up using because of the Spin.js authors super scary warning: "Note that the UMD version is only available as a temporary workaround."

**Spin:**
To get this all working with the sources provided by [composer](https://asset-packagist.org/) via [asset-packagist.org](https://asset-packagist.org/package/search?query=spin.js&platform=npm), I also had to transpile spin.js as a UMD. For the sake of future googleers, you'll need to do this also:

```sh
rollup --silent --name Spin --input spin.js --format umd --file spin.umd.js
```

`--silent` keeps rollup from barfing out this important, but unnecessary for my use case, message:
```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
spin.js
1: var __assign = (this && this.__assign) || function () {
                    ^
2:     __assign = Object.assign || function(t) {
3:         for (var s, i = 1, n = arguments.length; i < n; i++) {
...and 1 other occurrence
```
