### ISSUE TITLE
Execution order with inlineDynamicImports

### ISSUE THREAD

**Issue by Topthinking** [rollup/rollup#4735] opened 2022-12-02 04:33 UTC
# Expected Behavior / Situation
When using inlineDynamicImports, dynamically imported modules should not be executed until the relevant import() is reached in code.

With the minimal setup below, the expectation is for the log message to appear after at least a second, since the import() is within a setTimeout and the module is not expected to be loaded until then.

```js
// entry.js
setTimeout(() => {
	import('./foo.js');
}, 1000);
```
```js
// foo.js
console.log('foo');
```
```shell
$ rollup entry.js --inlineDynamicImports
```
Actual Behavior / Situation
Dynamically imported modules are executed immediately in Rollup output.

Running Rollup on entry.js in the example above results in the console.log() call being moved outside the callback and being executed earlier than expected. The resulting bundle looks like this:
```js
setTimeout(() => {
        Promise.resolve().then(function () { return foo; });
}, 1000);

console.log('foo');

var foo = /*#__PURE__*/Object.freeze({
        __proto__: null
});
```
This appears to be intentional behavior; the docs for the inlineDynamicImports option states:

Note that this will change the execution order: A module that is only imported dynamically will be executed immediately if the dynamic import is inlined.

# Modification Proposal
I would suggest modifying the way that dynamic imports are inlined to delay their execution until the first time they are imported. This would make the behavior of the resulting bundle more closely match the semantics of native dynamic imports. An acceptable output, modified from the above output, might look like this:

```js
setTimeout(() => {
        Promise.resolve().then(function () { return import_foo(); });
}, 1000);

var foo;
function import_foo () {
        if (typeof foo !== 'undefined') return foo;

        console.log('foo');

        foo = /*#__PURE__*/Object.freeze({
                __proto__: null
        });
        return foo;
}
```

Output like this ensures that the module is only executed when the first import() statement referencing it would have been executed, and also ensures that the module is cached once executed once so it can be imported multiple times without being re-executed. No modification is needed for modules which are referenced from both static and dynamic imports, since they should still be executed immediately by the static import.

**Comment by Topthinking** [comment] 2022-12-02 04:35
+1

**Comment by Topthinking** [comment] 2022-12-02 04:35
https://github.com/rollup/rollup/issues/4166

**Comment by Tanimodori** [comment] 2023-03-16 07:18
Duplicate of #4166

**Closed** 2023-03-16 10:50 UTC

**Comment by xboy2012** [comment] 2023-06-08 09:04
This issue is closed, but https://github.com/rollup/rollup/issues/4166 is still not fixed, which is open for almost 2 years

please pay attention, thanks.
