### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by electerious** [rollup/rollup#594] opened 2016-04-05 14:52 UTC
Hey,

I tried to bundle [my Node.js module](https://github.com/electerious/rosid-handler-scss) using rollup. I never used it yet, so it's hard to tell if this is a problem of rollup or some of its plugins (node-resolve, commonjs, json).

The following error shows up when trying to run the bundled file with `node dist/index.js`:

```
/Users/tobiasreich/Sites/JS/rosid-handler-scss/dist/index.js:3680
function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a
function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writa
ble: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
                                                                                                          ^

TypeError: Super expression must either be null or a function, not undefined
    at _inherits (/Users/tobiasreich/Sites/JS/rosid-handler-scss/dist/index.js:3680:113)
    at /Users/tobiasreich/Sites/JS/rosid-handler-scss/dist/index.js:3683:5
    at /Users/tobiasreich/Sites/JS/rosid-handler-scss/dist/index.js:3753:2
    at __commonjs (/Users/tobiasreich/Sites/JS/rosid-handler-scss/dist/index.js:16:68)
    at Object.<anonymous> (/Users/tobiasreich/Sites/JS/rosid-handler-scss/dist/index.js:3659:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

Here's how the configuration looks:

``` js
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import json from 'rollup-plugin-json'

export default {
    entry: 'src/index.js',
    format: 'cjs',
    plugins: [
        resolve({
            extensions: [ '.js', '.json' ]
        }),
        json(),
        commonjs()
    ]
}
```

Used command to roll-up:

```
rollup -c -o dist/index.js
```

Here's the output:

[index.js.zip](https://github.com/rollup/rollup/files/204715/index.js.zip)

Facts & What I tried so far:
- Reinstalling all dependencies
- Experimented with available rollup and plugin options
- The bundling itself works fine and doesn't show any errors

Thanks for the help!

**Comment by electerious** [comment] 2016-04-05 14:57
Here's my module with the current implementation: https://github.com/electerious/rosid-handler-scss/tree/feature/bundle

`npm i && npm run build && node dist/index.js` to reproduce the problem.

**Comment by Victorystick** [comment] 2016-04-14 16:33
@electerious It's because `AtRule` is defined _before_  it's super class `Container` which makes Babel's `inherits`-check throw. The problem is most likely caused by some ordering issued of the `commonjs` plugin. The issue _may be_ solved by rollup/rollup-plugin-commonjs#43.

**Comment by electerious** [comment] 2016-04-15 13:34
Thanks for letting me know! I will keep an eye on the issue and retry it after it has been merged.

**Comment by Rich-Harris** [comment] 2016-12-22 16:39
Closing – feel free to reopen on the commonjs repo if there are still problems

**Closed by Rich-Harris** 2016-12-22 16:39 UTC
Labels: wrong repo
