### ISSUE TITLE
rollup with babel-polyfill - TypeError: undefined is not an object! (test case included)

### ISSUE THREAD

**Issue by rosskevin** [rollup/rollup#766] opened 2016-07-05 13:55 UTC
This is a continuation of https://github.com/rollup/rollup/issues/616#issuecomment-229823063.  We can continue here or reopen the old issue and close this one.

> I updated the test case specifically with what you have mentioned in your comment, though I receive the same exact error in Firefox.
>
> Here is the branch with the pure test case:
https://github.com/rosskevin/test-rollup-616-babel-polyfill/tree/rich-changes

**Comment by Rich-Harris** [comment] 2016-07-08 03:42
Least helpful response ever, I know, but it works for me (in Chrome 51 and Firefox 47). Can you provide a more specific reproduction?

**Comment by rosskevin** [comment] 2016-07-08 13:44
More info - It was failing in Firefox 34.  I updated to 47 and it works.  It also is confirmed working in Chrome 51, and Safari (desktop) 9.1.1 i.e. all current browsers.

If you have a minimum expectation for browser re: Firefox, this can be closed.  The FF 34 was released 12/1/14, which I would consider to be reasonably old, but then again, transpiled code with a babel-polyfill should probably reach back that far. If this is an issue introduced by Rollup then we might want to leave it open.

**Comment by Rich-Harris** [comment] 2016-07-09 14:34
It *sounds* like babel-polyfill is using something unsupported in Firefox 34 (which wouldn't surprise me, it's ancient and its market share is less than a rounding error) – I can't imagine why Rollup would be introducing something untoward. So I'll close this until further evidence presents itself

**Closed by Rich-Harris** 2016-07-09 14:34 UTC
