### ISSUE TITLE
Reexports not always getting renamed to avoid collisions

### ISSUE THREAD

**Issue by jbt** [rollup/rollup#1861] opened 2018-01-11 12:27 UTC
I'm running into a pattern where anything being imported through at least one `export * from 'blah'` isn't getting safely renamed, causing some weird collisions:

Here's the smallest repo I could come up with: [REPL](https://rollupjs.org/repl?version=0.53.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGJhciUyMGZyb20lMjAnLiUyRnJlZXhwb3J0LmpzJyUzQiU1Q24lNUNudmFyJTIwYmF6JTIwJTNEJTIwZnVuY3Rpb24lMjBmb28oKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwYmFyLmZvbygpJTNCJTVDbiU3RCUzQiU1Q24lNUNuY29uc29sZS5sb2coYmF6KCkpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMGZvbygpJTIwJTdCJTIwcmV0dXJuJTIwdHJ1ZSUzQiUyMCU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJyZWV4cG9ydC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAqJTIwZnJvbSUyMCcuJTJGZm9vLmpzJyUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**foo.js**
```js
export function foo() { return 1; }
```

**reexport.js**
```js
export * from './foo.js';
```

**main.js**
```js
import * as bar from './reexport.js';

var baz = function foo() {
	return bar.foo();
};

console.log(baz())
```

**output**
```js
function foo() { return true; }

var baz = function foo() {
	return foo();
};

console.log(baz());
```

Notice how the final output doesn't rename either occurrence of `foo`. This doesn't seem to be a problem if `baz` is changed to `foo` (i.e. so `foo` exists in the top scope of `main.js`) or if the function is imported from `./foo.js` directly.

This is fine in older versions of rollup (I ran into this upgrading from 0.41.6 to latest) - a quick git bisect suggests https://github.com/rollup/rollup/commit/671757eff4be49a52d034d43a3f5a89d619ce275 is where this first started happening.

(In case `var baz = function foo(){...}` seems a little contrived - my own use case comes from things like `Something.prototype.foo = function foo(){...}` so `foo` is similarly undeclared in the top scope but still collides with an imported function)

**Comment by guybedford** [comment] 2018-01-11 12:43
Thanks so much for reporting. Will be interesting to look into this further.

If you happen to have the time to write this up as a failing test case PR (tests/form/samples) that would be a huge help, otherwise I will look into this when I can too.

**Comment by lukastaegert** [comment] 2018-01-11 12:47
Don't have the time to check properly today but this issue sounds somewhat familiar. I recently spent some time labelling issues. Might be helpful to look at issues with labels "bug" + "scope-hoisting" when investigating, maybe there is some low-hanging fruit to be fixed together with this one.

**Comment by tomkel** [comment] 2018-01-12 20:38
This might be related to #1783

**Comment by guybedford** [comment] 2018-01-15 20:07
Will be interesting to see if this is affected by the code splitting work at all, as that rewrites some parts of this code.

**Comment by tomkel** [comment] 2018-01-18 20:13
Ran into this again today..

**Comment by guybedford** [comment] 2018-02-10 12:06
This seems to be an exact duplicate of https://github.com/rollup/rollup/issues/1580. Moving to that issue.

**Comment by guybedford** [comment] 2018-02-10 12:07
This seems to be an exact duplicate of https://github.com/rollup/rollup/issues/1580. Moving to that issue.

**Closed by guybedford** 2018-02-10 12:06 UTC
Labels: bug, scope-hoisting
