### ISSUE TITLE
File hash is not updated when changing code in renderChunk

### ISSUE THREAD

**Issue by isidrok** [rollup/rollup#2739] opened 2019-03-05 21:44 UTC
- Rollup Version: 1.4.1
- Operating System (or Browser): Linux
- Node Version: 10.10.0

### How Do We Reproduce?

Follow the steps on https://github.com/isidrok/rollup-hashing-bug

### Expected Behavior

When code changes in a plugin hook, the file hash should be updated to match the new content.

### Actual Behavior

The file hash is not updated with the new content, instead keeps the hash of the original one which can lead to incorrect hashes when modifying the build process but not the source  or when some plugin in the build process modifies the source due to external factors.

Note that renaming `chunkInfo.fileName` from within the plugin will not work since dependent chunks will keep referencing the old `fileName`.

Let me know if you could use some help for a PR!

**Comment by lukastaegert** [comment] 2019-03-06 05:13
Thank you @isidrok. Yes, this is expected and a core architectural problem that stems from the fact that we do not have a dedicated runtime to resolve imports but render them inline.

> Note that renaming chunkInfo.fileName from within the plugin will not work since dependent chunks will keep referencing the old fileName

This is exactly the reason why hashing happens before the renderChunk hook. After this hook, we have no way to fix the file names of the imported files. Thus, hashing only works reliably if your renderChunk hook is `pure` i.e. it returns the same output for the same output. Unless you have a brilliant idea how to handle this e.g. for cyclic dependencies, I fear this will be a wontfix.

**Comment by lukastaegert** [comment] 2019-03-06 05:15
But in any case, I guess this should be mentioned in the documentation.

**Comment by isidrok** [comment] 2019-03-06 07:15
Well, when the `outputBundle` is finished in [this](https://github.com/rollup/rollup/blob/91ce9812626f90198db523927bb53f105f98ad62/src/rollup/index.ts#L275) line we may have the opportunity to re-calculate chunk hashes since plugins can no longer modify the sources (?) so my not so brilliant idea is:

1. Wait for the final version of the outputBundle.
2. Hash all chunks again using the `code` and store a map of oldName:newName.
3. For each chunk: 
3.1 If newName !== oldName
3.2 Replace all references to oldName by newName (this includes `chunk sourcemap`, dependent chunks `code`, and all internal references in rollup data structures)

Probably some recursive acrobatics would be needed since replacing an import in a chunk would have to update its hash, e.g. 

- `a` imports `b`
- `b` imports `c`

**First run**

- `c` hash changes updating `b`

 **Second run**

- `b` hash changes updating `a`

 **Third run**

- `a` hash changes triggering no updates

 **Fourth run**

- No changes found, end


This could be optimized and would need special handling for cyclic dependencies but I think is doable

**Comment by lukastaegert** [comment] 2019-03-06 07:27
> Replace all references to oldName by newName

The problem is that we have no idea what happened in `renderChunk`. For instance, chunks could have an entirely different format, variables have been renamed, imports have been suppressed etc. So there is no bullet-tight way of finding the references in the generated chunks. And as you see yourself, even without this the logic is not too trivial.

As long as we allow arbitrary transformations in `renderChunk`, I see no good way of fixing this on Rollup side that is not a huge maintenance mess.

**Comment by lukastaegert** [comment] 2019-03-06 07:30
One thing we could do is allow plugins to add some bits to the generated hash at an earlier stage. I.e. they could add a hash of their config or a hash of things they plan on adding to the code.

**Comment by isidrok** [comment] 2019-03-06 07:36
You are right, if someone relied on the imports found in the code that would break. About the second option, that seems pretty good.

**Comment by lukastaegert** [comment] 2019-03-06 07:44
I think of something like

```js
augmentChunkHash(<parameters>) => string
```

The returned string will just be added to the hash generation. Options could include things like outputOptions, modules in the chunk and other things we know before the hashes are generated.

**Comment by isidrok** [comment] 2019-03-06 07:46
For example, if writing a plugin that applies `PostCSS` and then inlines a loader on top of the chunk to load the generated file, i.e.

```js
loadCSS('chunk.asd123.css');
// chunk code
```
Knowing which `.css` files are imported by that chunk, the options passed to the plugin plus maybe the plugin version would work perfectly fine.

**Comment by isidrok** [comment] 2019-05-14 13:05
Hi @lukastaegert , I'm planning to start working on this soon. Wondering if [computeContentHashWithDependencies](https://github.com/rollup/rollup/blob/master/src/Chunk.ts#L778) is the right place to call this hook and update the hash and which kind of information would be good to expose.

**Comment by lukastaegert** [comment] 2019-05-14 14:46
Great to hear! My feeling is that `getRenderedHash` would be a better place as changes in `computeContentHash` will only change the hash of the current chunk but not the hashes of chunks that depend on the current chunk while `getRenderedHash` reflects the hash of what is actually rendered and will also change the hashes of dependent chunks.

As for the information, my feeling is that the most important information would be the modules of that chunk. As for more information, that depends on what is available and what people need. Adding more information later is always possible, so I would not start with too much stuff that needs to be implemented, tested and maintained. As for the format, I think it would be nice if the user could get a reduced version of the ChunkInfo we give them in `renderChunk` and `generateBundle`.

**Comment by isidrok** [comment] 2019-06-10 19:52
After experimenting with this API it seems a bit difficult to use for plugin developers, for example:

```js
// rollup-plugin-babel
{
  agumentChunkHash(update){
    const pkgPath = path.join(require.resolve('rollup-plugin-babel'), 'package.json')
    const version = require(pkgPath).version;
    const config = fs.readFileSync(options.babelrc);
    update(version + config);
  }
}
```

That setup would invalidate chunk hashes whenever a new plugin version is installed or the babel config changes, but in this case there are lots of `implicit dependencies` that would be pretty difficult to track such as `@babel/core`, all babel plugins and presets installed, etc... The same would apply to any other plugin based tool.

What are your thoughts?

I've a fork with a basic implementation of the API, can open a PR in WIP so we can discuss about it.

**Comment by lukastaegert** [comment] 2019-06-11 08:15
> What are your thoughts?

In the end, this will be the responsibility of plugin writers. Of course, babel is difficult due to its many dependencies, though babel versions are usually somewhat aligned. A more common use-case may be uglify (as babel is usually applied as a transform hook) which has fewer dependencies.

**Comment by lukastaegert** [comment] 2019-06-11 08:16
Other important use cases I see is adding e.g. timestamps, commit hashes etc. which should work nicely with your suggestion.

**Comment by isidrok** [comment] 2019-06-12 08:41
> Other important use cases I see is adding e.g. timestamps, commit hashes etc. which should work nicely with your suggestion.

That's indeed pretty cool, some nice plugins such as `implicit-dependencies` or `i-messed-it-up` aka `build-hash` could be quite useful to invalidate cache without needing to change code and would give the opportunity to recover in case incorrect hashes arrive to the client.

> In the end, this will be the responsibility of plugin writers

It will and if someone doesn't get it right can always release a fix which would invalidate the hash so its not that bad.

**Comment by shellscape** [comment] 2019-08-11 13:40
@isidrok is this issue still a valid concern?

**Comment by lukastaegert** [comment] 2019-08-11 18:11
There is actually a pending pull request to address this

**Comment by isidrok** [comment] 2019-08-11 20:13
Yeah this is still important. Ill find some time this week to get that PR done with the synchronous behaviour we talked about last time.

Thank you both!

**Comment by shellscape** [comment] 2019-08-11 22:35
Thank you @isidrok!

**Closed** 2019-08-13 15:16 UTC
Labels: pr⁴ 🔧 fix, x⁵ ⋅ in progress
