### ISSUE TITLE
TODO: Idiomatic way to write out files

### ISSUE THREAD

**Issue by Crisfole** [rollup/rollup#2930] opened 2019-06-12 12:34 UTC
On a mission to turn TODO comments in code to issues. This tracks the TODO in https://github.com/rollup/rollup-plugin-svelte/blob/master/index.js#L296 about making a more idiomatic way to write out the css file.

If this already exists please close and either a) create a rollup-plugin-svelte issue, or b) ping me to do it.

**Comment by lukastaegert** [comment] 2019-06-12 12:49
I think this would need a little more context about what "idiomatic" is supposed to mean to be actionable on Rollup side. It seems @funkybob added the comment here: https://github.com/rollup/rollup-plugin-svelte/commit/1b541b3cfa35486c50e3a59c3d50f59d6f03b6da maybe someone could you give a little more context about what was intended?

**Comment by Crisfole** [comment] 2019-06-12 12:52
@lukastaegert I definitely agree. Just wanted to get the comment out of code and into an issue. My only goal is getting the TODO deleted! ;)

**Comment by lukastaegert** [comment] 2019-06-12 12:59
I totally understand, which is why I tried to pull in @funkybob 😜
I he does not remember, then I guess we can close the issue ultimately until someone remembers and opens a new one.

**Comment by Crisfole** [comment] 2019-06-12 17:34
I wonder if the svelte plugin should be using `emitAsset` or `emitChunk` here? That's the idiomatic way to indicate you want a new file created, right? (This is a bit unclear from the docs, tbh).

**Comment by lukastaegert** [comment] 2019-06-12 17:38
True, `emitAsset` was practically made to handle CSS. Maybe some features are missing?

**Comment by funkybob** [comment] 2019-06-12 22:19
My intent was I wanted a more "in the pipeline" way of emitting a new file. IME rollup is excellent at ingesting and producing JS files in the pipeline, but falters somewhat when handling other content. This may have improved since I last looked, as I'm not a FED and thus don't spent a lot of time keeping up to date with front-end tools.

From memory I did try to use emitAsset but it did not work at all as I expected.

It's been a long time since I did this, and sadly I don't remember the details.

**Comment by lukastaegert** [comment] 2019-06-13 07:15
In that case I would suggest to close this issue here and open an issue for rollup-plugin-svelte to "use Rollup's asset emission for CSS files or open an issue for Rollup if something is missing to make this happen". The intention would be that if someone picks up that ticket, they may stumble upon the same things encountered by @funkybob but create a more helpful Rollup issue fresh from experience (or maybe it is just a documentation issue?)

Otherwise I feel this issue here will not help matters.

**Comment by funkybob** [comment] 2019-06-13 08:01
Looking again at it, I believe the issue was there was no way to control the output filename. calling emitAsset will guarantee it's written, but with a name along the lines of "asset/{name}-{hash}.{ext}", whereas that plugin was trying to let users specify the target name.

**Comment by lukastaegert** [comment] 2019-06-13 08:06
Ah, that is one thing I hope to finally add soon, basically a function to add arbitrary files to the bundle. In a non-official way this is already possible by adding things in the `generateBundle` hook but of course a function that works in any hook would be better.

**Comment by funkybob** [comment] 2019-06-14 07:36
FWIW in another plugin of mine [which injects script and link tags into a source html document] I resorted to the following:
```
      let targetDir = (options.dir) ? options.dir : path.dirname(options.file);
      fs.writeFileSync(path.join(targetDir, source), output)
```
where "source" is the filename of the source document.

**Comment by lukastaegert** [comment] 2019-06-14 14:43
Opened #2938 to address this.

**Comment by funkybob** [comment] 2019-06-14 21:35
Looks viable to me!

**Comment by shellscape** [comment] 2019-08-15 14:18
Closing citing completion of #2938

**Closed by shellscape** 2019-08-15 14:18 UTC
Labels: t³ ✨ enhancement
