### ISSUE TITLE
Angular 4 application  Error: 'Subject' is not exported by node_modules\rxjs\Subject.js

### ISSUE THREAD

**Issue by hamzahamidi** [rollup/rollup#1581] opened 2017-08-25 13:16 UTC
"node_modules/.bin/rollup" -c rollup-config.js
The following options have been renamed — please update your config: options.entry -> options.input, options.dest -> options.output.file, options.format -> options
.output.format

src/main.js → src/build.js...
[!] Error: 'Subject' is not exported by node_modules\rxjs\Subject.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
node_modules\@angular\core\@angular\core.es5.js (10:9)
 8: import { merge } from 'rxjs/observable/merge';
 9: import { share } from 'rxjs/operator/share';
10: import { Subject } from 'rxjs/Subject';
             ^
11: /**
12:  * Creates a token that can be used in a DI Provider.

**Comment by hamzahamidi** [comment] 2017-08-25 13:17
rollup-config.js
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify';

export default {
    entry: 'src/main.js',
    dest: 'src/build.js', // output a single application bundle
    sourceMap: false,
    format: 'iife',
    onwarn: function(warning) {
        // Skip certain warnings

        // should intercept ... but doesn't in some rollup versions
        if (warning.code === 'THIS_IS_UNDEFINED') { return; }

        // console.warn everything else
        console.warn(warning.message);
    },
    plugins: [
        nodeResolve({ jsnext: true, module: true }),
        commonjs({
            include: 'node_modules/**',
            include: 'node_modules/moment/**'
        }),
        uglify()
    ]
};

**Comment by hamzahamidi** [comment] 2017-08-25 13:18
rollup-config.js
`import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify';

export default {
    entry: 'src/main.js',
    dest: 'src/build.js', // output a single application bundle
    sourceMap: false,
    format: 'iife',
    onwarn: function(warning) {
        // Skip certain warnings

        // should intercept ... but doesn't in some rollup versions
        if (warning.code === 'THIS_IS_UNDEFINED') { return; }

        // console.warn everything else
        console.warn(warning.message);
    },
    plugins: [
        nodeResolve({ jsnext: true, module: true }),
        commonjs({
            include: 'node_modules/**',
            include: 'node_modules/moment/**'
        }),
        uglify()
    ]
};`

**Comment by raghuSanapathi** [comment] 2017-09-04 06:55
getting same issue any solution for this?

**Comment by lukastaegert** [comment] 2017-09-04 08:01
I am not sure but it is quite possible this might be fixed by the changes in #1604 as I have a feeling this might be related to Promises. Not sure when/if @Rich-Harris will merge this but you should check if you still experience this issue with the next minor/patch release of rollup once it is out.

**Comment by lukastaegert** [comment] 2017-09-08 04:01
Hi @hamzahamidi @raghuSanapathi would you please check if you are still having this issue with 0.49.3? Thanks!

**Comment by unoframille** [comment] 2017-09-14 12:42
I've same issue with 0.49.3

**Comment by lukastaegert** [comment] 2017-09-14 16:57
Would it be possible to provide a minimal repository that produces this error when built?

**Comment by lukastaegert** [comment] 2017-09-15 04:57
Actually, it does not need to be minimal, just some repo that I can build an start tracing the problem. I tried running [this repo](https://github.com/OasisDigital/angular-aot-es2015-rollup) against v0.49.3 but it does not seem to exhibit this error.

**Comment by dgroh** [comment] 2017-09-19 10:36
I got this to work by using in node resolve:

`modulesOnly: true`

Now the error is gone, but I get the wollowing warning:

https://github.com/rollup/rollup/issues/1642

**Comment by lukastaegert** [comment] 2017-09-19 11:20
Hi @hamzahamidi, @unoframille,

I dug a little further into this issue and it appears that this is in fact not an issue with rollup but an issue with your configuration of [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) which is required for `rxjs` to work. For its `include` parameter, this plugin accepts either
* a filename (in quotes)
* a "glob" filename, e.g. `include: "node_modules/**"` to denote all files in `node_modules`
* a regular expression that is denoted by slashes instead of quotes, e.g.  `include: /node_modules/` to denote all files that have `node_modules` somewhere in their path or filename

When you write `include: "node_modules/"`, rollup-plugin-commonjs interprets this as a filename that does not exist i.e. it will not be applied to any file. If you write `commonjs({include: 'node_modules/**'})` instead, everything should work as intended.

Btw., you probably do not want to include moment.js but exclude it instead since moment.js already has proper ES6 exports that rollup can access without any plugin.

**Comment by unoframille** [comment] 2017-09-20 07:58
I've been studying Angular for a few days and I've made a mistake as a beginner. I inserted the rollup-config file inside the src folder. As a result, the plugin configuration must be:

```
commonjs ({
    include: "../node_modules/**",
})
```

instead of:

```
commonjs ({
    include: "node_modules / **",
})
```

**Comment by lukastaegert** [comment] 2017-11-07 06:11
Am I correct in assuming this issue has been resolved?

**Comment by unoframille** [comment] 2017-11-07 07:15
yes, in my case the problem was mine

**Comment by lukastaegert** [comment] 2017-11-07 07:49
Thanks for the quick feedback, I will close this now.

**Closed by lukastaegert** 2017-11-07 07:49 UTC
