### ISSUE TITLE
Build output is different when building on Windows or Mac

### ISSUE THREAD

**Issue by mabramishvili** [rollup/rollup#4496] opened 2022-05-11 17:40 UTC
### Rollup Version

2.70.1

### Operating System (or Browser)

Windows

### Node Version (if applicable)

14.16.1

### Link To Reproduction

not available

### Expected Behaviour

Seems like on Windows, **preserveModulesRoot: 'src'** will only work on entry files (files defined in "input"). While on OSX it will work on all files.

I would expect it to be consistent between different environments.

Found this question but there is no working answer:
https://stackoverflow.com/questions/64570174/rollup-preservemodulesroot-not-working-as-expected 

### Actual Behaviour

I have a build output defined like:

```
{
  input: 'src/index.ts',
  output: [
    {
      dir: 'dist/cjs',
      format: 'cjs',
      preserveModules: true,
      preserveModulesRoot: 'src',
      sourcemap: true,
      exports: 'named',
    },
    {
      dir: 'dist/esm',
      format: 'esm',
      preserveModules: true,
      sourcemap: true,
      preserveModulesRoot: 'src',
      exports: 'named',
    },
  ],
}
```

When building on Windows, the output in **dist** is like:

```
dist
    -- esm
        --components
        --src
            --components
       index.d.ts
       index.js

```
esm/components will only include d.ts files and esm/src/components will actually include .js files

When building on OSX, the output in **dist** is like:

```
dist
    -- esm
        --components
       index.d.ts
       index.js
```

notice there is no "src" folder and all files are placed inside esm/components.

**Comment by cleverpp** [comment] 2022-07-28 09:10
+1， i have same problem。

after debugging, I found that it is caused by the following code

at 'rollup/src/utils/options/normalizeOutputOptions.ts'
```
...
preserveModulesRoot: getPreserveModulesRoot(config),
....

const getPreserveModulesRoot = (
	config: OutputOptions
): NormalizedOutputOptions['preserveModulesRoot'] => {
	const { preserveModulesRoot } = config;
	if (preserveModulesRoot === null || preserveModulesRoot === undefined) {
		return undefined;
	}
	return resolve(preserveModulesRoot);
};
```

but, at ''src/chunk.ts" 中
```
const currentPath = `${currentDir}/${fileName}`;
const { preserveModulesRoot } = options;
if (preserveModulesRoot && currentPath.startsWith(preserveModulesRoot)) {
	path = currentPath.slice(preserveModulesRoot.length).replace(/^[\\/]/, '');
} else {
	path = relative(preserveModulesRelativeDir, currentPath);
}
```

currentPath not resolve， but preserveModulesRoot had resolve， so  in windows platform，currentPath.startsWith(preserveModulesRoot) always be false。

**Comment by Tanimodori** [comment] 2022-08-01 08:53
+1 This bug leads to preserveModuleRoot not working. That `startsWith` is definitely the smoking gun. Until this pr get merged, my temp fix (see https://github.com/Tanimodori/generator-vite-electron-builder/commit/ae8351a6d59aad89d9c143b44df31cd48ed5f17e) is adding plugin to fix:

```ts
const config = {
  plugins: [
    {
      name: 'fixPreserveModulesRoot',
      renderStart(options) {
        options.preserveModulesRoot = options.preserveModulesRoot?.replace(
          new RegExp(/\\/, 'g'),
          '/',
        );
      },
    },
  ],
};
```

**Closed** 2022-08-11 05:35 UTC
Labels: t¹ 🐞 bug, t⁸ ⋅ triage
