### ISSUE TITLE
Angular 'default' is not exported... V0.41.2+

### ISSUE THREAD

**Issue by kcmecum3** [rollup/rollup#1277] opened 2017-01-20 01:09 UTC
Hi,

I am importing Angular (1.6.1) with the line (and variations thereof):

import angular from 'angular';

This works fine in Rollup 0.41.1 and below (at least those I've tried), but 0.41.2 on gives me the message:
```
??   'default' is not exported by 'node_modules\angular\angular.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
 commonjs-proxy:D:\Temp\angular-rollup-boilerplate-master\angular-rollup-boilerplate-master\node_modules\angular\angular
.js (1:178)
1: import * as angular from "D:\\Temp\\angular-rollup-boilerplate-master\\angular-rollup-boilerplate-master\\node_module
s\\angular\\angular.js"; export default ( angular && angular['default'] ) || angular;
```

The Angular code is still included in the bundle.

The package.json devDependencies are:

```
    "babel-preset-es2015-rollup": "^3.0.0",
    "rollup": "0.41.2", // etc.
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-commonjs": "^7.0.0", // Also tried V6
    "rollup-plugin-node-resolve": "^2.0.0",
```
The index.ts from the Angular package is:

```
require('./angular');
module.exports = angular;
```
Is this intended behavior? Based on the message doc on the wiki, it looks like it could be the commonjs plugin, but the fact that it started with a rollup version, I wanted to check that. I'm still pretty new to JS modules, so I may be missing something obvious.

Thanks.

**Comment by budcribar** [comment] 2017-01-20 22:12
I have the same problem. rollup 41.4 does NOT work.  rollup  41.0 works 

It appears that something may be wrong when index['default']  is parsed (that is where the ^ appears in the error message). also since 'default' is a string constant, you wouldn't think it would need to be exported...


 'default' is not exported by 'node_modules\@angular\forms\index.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
 commonjs-proxy:C:\Users\budcr\Source\Workspaces\CloudForestWebSite\CloudForest\wwwroot\node_modules\@angular\forms\index.js (1:178)
1: import * as index from "C:\\Users\\budcr\\Source\\Workspaces\\CloudForestWebSite\\CloudForest\\wwwroot\\node_modules\\@angular\\forms\\index.js"; export default ( index && index['default'] ) || index;
                                                                                                                                                                                     ^

**Comment by gouegd** [comment] 2017-01-23 10:04
@budcribar
> also since 'default' is a string constant, you wouldn't think it would need to be exported...

'default' is the name of the export, not the export itself.
default exports are just like normal exports with the name set to 'default'.

**Comment by finleysg** [comment] 2017-01-25 02:23
I was seeing the same behavior with 41.4 - angular forms, common and core. Didn't seem to cause any problems in the compiled file, but downgraded for now.

**Comment by iici-vsimha** [comment] 2017-02-27 03:21
I have the same issue you too. Here is the repo that reproduces this issue if it helps.

https://github.com/iici-vsimha/angular-redux-store

There are two directories in this repo. redux-store directory shows the problem, when you run the build. I have created a simple read file that has instructions on what to do. If its not enough glad to clarify.

**Comment by Facius** [comment] 2017-04-26 08:29
i have the same issue. with angular 1.6.4 and rollup 0.41.6

**Comment by yaoyonstudio** [comment] 2017-05-09 08:55
same issue

**Comment by stevencohn** [comment] 2017-05-10 11:41
same

**Comment by olsonpm** [comment] 2017-05-17 01:49
This is just a warning right?  It has popped up a few times
rollup-plugin-commonjs issues:  
[198](https://github.com/rollup/rollup-plugin-commonjs/issues/198)  
[186](https://github.com/rollup/rollup-plugin-commonjs/issues/186)

I'm hoping to squash this warning with #1408.  Just hoping for direction on how.

**Comment by bfred-it** [comment] 2017-06-21 18:45
Closing in favor of #1408. Hoping to see a solution in there :)

**Closed by bfred-it** 2017-06-21 18:45 UTC
Labels: duplicate
