### ISSUE TITLE
Side-effect detection is imprecise.

### ISSUE THREAD

**Issue by mbostock** [rollup/rollup#305] opened 2015-11-14 16:30 UTC
[Original title: Imports of re-exports may pull in unused code.]

Given the [index.js](https://github.com/d3/d3-scale/blob/master/index.js) in [d3-scale](https://github.com/d3/d3-scale), I expect the following two entry modules to be equivalent. Here’s [indirect.js](https://gist.github.com/mbostock/61e37a526c99b0aa3135#file-indirect-js):

``` js
import {category10} from "d3-scale";

export default {
  scale: {
    category10: category10
  }
};
```

And [direct.js](https://gist.github.com/mbostock/61e37a526c99b0aa3135#file-direct-js):

``` js
import category10 from "./node_modules/d3-scale/src/category10";

export default {
  scale: {
    category10: category10
  }
};
```

However, the resulting bundles are very different: direct.bundle.js is 7,406 bytes and indirect.bundle.js is 70,126 bytes (9.5× as big)!

The full code is at https://gist.github.com/mbostock/61e37a526c99b0aa3135.

I think this issue might be a duplicate of #179, so feel free to close. My guess is even though those re-exports are unused, their initialization could have side-effects and so Rollup is including them to be safe. For example [src/time.js](https://github.com/d3/d3-scale/blob/master/src/time.js) in d3-scale initializes some time formats that will be used by time scales. Those formats are never used because time scales are not included in the bundle, but their initialization could have side-effects.

Perhaps this suggests that I should avoid greedy initialization of static variables, and instead somehow defer them until they are needed (such as upon the first instantiation of a time scale). Alternatively, some flag lets me tell Rollup to do the right (if unsafe) thing automatically would be cool. :)

**Comment by Rich-Harris** [comment] 2015-11-14 17:01
I just published 0.21.0, which includes #253. It does a *slightly* better job of ignoring irrelevant side-effects – 52,885 bytes versus 70,126 – but still nowhere near as good as the direct approach.

0.21 does have an `aggressive: true` option that ignores side-effects that don't contribute to the bundle's exports, but it turns out it's a little *too* aggressive – the result is 4,968 bytes because it's missing some essential code! Going to look into it and figure out if that's expected behaviour.

I don't yet know whether the answer will be more sophisticated analysis or more granular control. In the meantime importing directly from a file probably isn't the worst thing in the world in a situation like this. With the npm plugin you could omit the `./node_modules/` prefix.

**Comment by mbostock** [comment] 2015-11-14 17:29
Thanks for your hard work. Glad we’re making progress.

Another quirk that I noticed is that this line from d3-array’s [src/set.js](https://github.com/d3/d3-arrays/blob/master/src/set.js#L5) is included, even in the direct and aggressive cases:

```js
var proto = map.prototype;
```

And yet, the aggressive case is missing the `Map.prototype` definition, as you mention. Strange!

**Comment by mbostock** [comment] 2015-11-16 23:03
I think I learned a little bit about why Rollup isn’t considering the pulled-in code to be free of side-effects. First, consider this example, where Rollup correctly detects some pure code and doesn’t pull it into the bundle. Here’s main.js:

```js
function foo() {
  console.log("foo");
}

function bar() {
  // pure
}

foo();
bar();
```

The resulting bundle:

```js
function foo() {
  console.log("hello");
};

foo();
```

Note that it dropped the statement `bar()`, presumably because it saw that `bar` was pure. However, if I change the definition of `bar` slightly in main.js:

```js
function foo() {
  console.log("foo");
}

var Bar = {
  bar: function() {
    // pure?
  }
};

foo();
Bar.bar();
```

The resulting bundle looks identical (modulo a trailing newline) as main.js: the “pure” `Bar.bar` is pulled in. And if this function happened to reference any other code—even if that code, too, was considered pure by Rollup—that code gets pulled in, too. For example:

```js
function foo() {
  console.log("foo");
}

function baz() {
  // pure
}

var Bar = {
  bar: function() {
    baz();
  }
};

foo();
Bar.bar();
```

The case in D3 is slightly more complicated in that instead of a statically-defined `Bar` you have a default [locale format](https://github.com/d3/d3-time-format#localeFormat) instance, and then I’m re-exporting a method on this instance. (So, Rollup would presumably need to understand the prototype chain.)

There’s probably a way I can restructure my code to make it more amenable to static analysis, so I’ll try to think of strategies. I would be interested to know if there are ways Rollup can be smarter about this analysis, too. Thanks!

**Comment by mbostock** [comment] 2015-11-16 23:17
Also, in some ways Rollup is a bit too aggressive about eliminating “pure” code. Consider this entry, which gets rolled up into nothing:

```js
function bar() {
  throw new Error;
}

bar();
```

**Comment by mbostock** [comment] 2015-11-16 23:25
Closures are also not detected as pure:

```js
function foo() {
  console.log("foo");
}

var bar = newBar();

function newBar() {
  return function() {
    // pure closure
  };
}

foo();
bar();
```

Unless you immediately evaluate them, in which case they are! :grin: 

```js
function foo() {
  console.log("foo");
}

function newBar() {
  return function() {
    // pure closure
  };
}

foo();
newBar()();
```

**Comment by Rich-Harris** [comment] 2015-11-17 04:17
I'd like for Rollup to be able to handle unambiguous cases like `Bar.baz` – at the moment it gets skittish because there are so many ways that `Bar` could be mutated. If we could be certain that `Bar` *wasn't* being mutated, then we could link the `Bar.baz` identifier to the correct function expression, and do the appropriate analysis. There's a lot of work between here and there but I think it's possible. Of course, understanding the prototype chain is another story...

> There’s probably a way I can restructure my code to make it more amenable to static analysis

Quite possibly, and as a bonus, other tools would (such as minifiers) would also have an easier time of it – but it's definitely better if Rollup can understand and deal with these patterns. I hate the idea of a wiki page called 'How to rewrite your code for the benefit of a tool that even the original author hopes will be unnecessary in a couple of years once everything is HTTP/2 and we don't need to transpile stuff any more'.

> Also, in some case Rollup is too aggressive eliminating “pure” code.

Yeah, I treated thrown errors as a [special case](https://github.com/rollup/rollup/blob/12323c0ce3e4d281a51b038ffdf656740c4f5e28/src/utils/run.js#L72-L76), because a lot of Lodash code was otherwise being included unnecessarily when I tested it. I can't remember the specifics but the error was thrown inside a block – `if (argumentsAreInvalidSomehow) {...}` – and was causing the inclusion of a function that definitely didn't need to be there. But now that you bring it up I'm not sure I can defend that decision in the general case.

> Unless you immediately evaluate them, in which case they are!

Ah, yes – it's not tracking the value of `bar`. (Rollup doesn't really track values at all, and in some cases obviously it can't track values statically, but in cases like these I think we could, at least in theory.) Filed under 'more sophisticated analysis' along with the `Bar.baz` stuff.

> Edit: that appears to be a bug, because it will also drop code that has side-effects

Whoops! Labelled accordingly. Thanks.

**Comment by kzc** [comment] 2017-01-06 04:45
The code from [above](https://github.com/rollup/rollup/issues/305#issuecomment-157205468):
```js
function bar() {
  throw new Error;
}
bar();
```
is fixed by this patch:
```patch
--- a/src/ast/nodes/ThrowStatement.js
+++ b/src/ast/nodes/ThrowStatement.js
@@ -2,6 +2,6 @@ import Node from '../Node.js';
 
 export default class ThrowStatement extends Node {
        hasEffects ( scope ) {
-               return scope.findLexicalBoundary().isModuleScope; // TODO should this just be `true`? probably...
+               return true;
        }
 }
```
Note: [test/form/side-effect-h/main.js](https://github.com/rollup/rollup/blob/master/test/form/side-effect-h/main.js) currently produces the wrong result with rollup 0.40.2:
```js
function foo ( ok ) {
	if ( !ok ) {
		throw new Error( 'this will be ignored' );
	}
}

foo();

export default 42;
```
rollup 0.40.2 [produces](https://github.com/rollup/rollup/blob/master/test/form/side-effect-h/_expected/es.js):
```js
var main = 42;

export default main;
```
The side effect `if` and `throw` was incorrectly removed.

With the patch above it produces the correct result.

**Comment by Avaq** [comment] 2017-05-17 09:30
Hello! I'm working on [Fluture](https://github.com/Avaq/Fluture), to which I recently added a `module` entry for tree shakers. Currently all bundles will needlessly include the entire dependency tree hanging from [here](https://github.com/fluture-js/Fluture/blob/892ae9244764920cf1d4664362d4d69c782738aa/index.es.js#L29), because it's assumed that the function [here](https://github.com/fluture-js/Fluture/blob/892ae9244764920cf1d4664362d4d69c782738aa/src/par.js#L52) contains side-effects, which I know it does not.

It would be nice if I could just override the assumptions Rollup is making about effects, in a fashion similar to eslint or istanbul hints:

```js
export const Par =
/* rollup-assume-pure */
concurrify(Future, never, race, function pap(mval, mfunc){
  return new ParallelAp(mval, mfunc);
});
```

Disclaimer: I'm quite new to Rollup and its technical challenges. Please go easy on me if this is a silly idea. ;)

**Comment by mbostock** [comment] 2017-05-17 14:29
@Avaq There is a proposal for a pure annotation here: #1293.

**Comment by guybedford** [comment] 2018-02-10 19:31
I can confirm that all cases described in https://github.com/rollup/rollup/issues/305#issuecomment-157202867, https://github.com/rollup/rollup/issues/305#issuecomment-157205468 and https://github.com/rollup/rollup/issues/305#issuecomment-157207397 here are now working perfectly thanks to Lukas' work here.

Perhaps this issue can be closed then, unless there are other scenarios missing that capture the original problem statement.

**Closed** 2018-03-27 23:06 UTC
Labels: treeshaking
