### ISSUE TITLE
Implement start hook for plugins

### ISSUE THREAD

**Issue by haraldrudell** [rollup/rollup#1643] opened 2017-09-19 22:49 UTC
Some plugins want to do housekeeping prior to starting the Rollup run

For example, you may want to implement clean as the first step of build.

Today this has to be hacked as a fake resolver or loader since during initial execution and load of rollup.config.js, async invocations are not possible.

rollup should have a start-hook that allows for an async function to execute, that triggers just prior to starting to resolve the input file id.

**Comment by linjinying** [comment] 2018-01-21 11:36
@haraldrudell Hi, I also have the same problem,  how do you handle it?

**Comment by guybedford** [comment] 2018-05-22 22:56
This seems like a duplicate of #1611, tracking progress there.

**Closed by guybedford** 2018-05-22 22:56 UTC
