### ISSUE TITLE
Dead code

### ISSUE THREAD

**Issue by binjospookie** [rollup/rollup#3531] opened 2020-05-03 21:13 UTC
Hi! I have a project with Rollup, Lerna and TypeScript.
Package A export function from package B and export smth like `!fnFromB()`.
Package B have a dependency (ramda for example). It export 2 functions. One of them just return true (package A import this function). Another function return `pick(['1'])` (pick imports from ramda).
After build I expect that A package have only one function from B, but in fact it have 2 functions and ramda's part.
Is it possible to say Rollup that B package have no side-effects? 
https://github.com/binjospookie/rollup (minimal repo to reproduce it. bundles includes)

**Comment by shellscape** [comment] 2020-05-03 21:26
This is a duplicate of #3528, which was closed for the same reasons; Issue templates are required.

_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.

**Closed by shellscape** 2020-05-03 21:26 UTC
