### ISSUE TITLE
Invalid output when moduleName contains a dash & format: iife

### ISSUE THREAD

**Issue by RyanZim** [rollup/rollup#1345] opened 2017-03-25 14:36 UTC
When `moduleName` contains a dash, the module has a default export, and you are building to `iife` format, invalid JS is generated.

Input:
```
export default function () {}
```

`moduleName: 'my-bundle'` & `format: 'iife'`

Output:
```js
var my-bundle = (function () {
'use strict';

var main = function () {};

return main;

}());
```

(Sorry, couldn't get the rollupjs.org repl working)

**Comment by bfred-it** [comment] 2017-04-23 01:39
`moduleName` is the name of a JavaScript variable. If you pass an invalid name, the result will be invalid. Is rollup supposed to validate its input?

A workaround would be to pass a valid variable name.

**Comment by RyanZim** [comment] 2017-04-24 11:57
Related: https://github.com/rollup/rollup/issues/584

At this time, I can't submit a PR ATM; I'm quite busy, and this issue isn't a blocker for me.

**Comment by Rich-Harris** [comment] 2017-06-03 22:07
I'll close this as it's effectively a dupe of #584

**Comment by RyanZim** [comment] 2017-06-03 22:43
@Rich-Harris This wasn't fixed by https://github.com/rollup/rollup/pull/1144; it still has this problem in v0.42.

Test case:
http://rollupjs.org/?version=0.42.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXktYnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwNSUyMiU3RCU1RCU3RA==

**Comment by Rich-Harris** [comment] 2017-06-04 04:29
Sorry, I didn't notice #584 was already closed. Will leave it that way and reopen this one.

**Comment by binarykitchen** [comment] 2017-06-21 06:22
hello guys, what's the state of this issue? i raised a similar problem over there https://github.com/camelaissani/rollup-plugin-closure-compiler-js/issues/10

**Comment by bfred-it** [comment] 2017-06-21 19:06
@RyanZim @binarykitchen can you explain to me why you don't use a non-dashed name? What's the resolution you're hoping for?

**Comment by RyanZim** [comment] 2017-06-21 19:29
@bfred-it There isn't a real good reason, just something I stumbled across. IMO, a JS tool shouldn't output invalid code; it should either handle this case or error out if an invalid identifier is passed. 

Also https://github.com/rollup/rollup/issues/584 was similar, and that was fixed.

**Comment by binarykitchen** [comment] 2017-06-21 21:36
well, either we allow or disallow dashes in module names. if we disallow, then have rollup at least print a warning before things get started.

but i bet, the more users you will win, the more often this will happen and you'll get more complaints :)

i really recommend to support dashes in names. furthermore, in other programming languages, dashes in names are very common and it would be poor DX for them when dashes aren't welcome here.

**Comment by bfred-it** [comment] 2017-06-22 04:35
>  it would be poor DX for them when dashes aren't welcome here.

Forward your complaints to https://github.com/tc39 😂

**Comment by binarykitchen** [comment] 2017-06-22 04:41
yeah, an error in that case would be good.

ps: glad you find my comment entertaining ;)

**Comment by binarykitchen** [comment] 2017-06-22 07:13
alright, removing the dash helped. but now we have a new problem @bfred-it 

```
└─( 2 ) ❱❱❱ yarn build                                                                       1 ⏎  +2557 19:11 ❰─┘
yarn build v0.24.6
$ yarn std --silent
$ rollup -c env/prod/rollup.config.js 
100% (750): src/wrappers/optionsWrapper.js⚠️   'default' is not exported by 'node_modules/buffer-es6/index.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/home/michael-heuberger/code/videomail-client/node_modules/buffer-es6/index.js (1:137)
1: import * as index from "/home/michael-heuberger/code/videomail-client/node_modules/buffer-es6/index.js"; export default ( index && index['default'] ) || index;
                                                                                                                                            ^

Input_0:14447 (JSC_PARSE_ERROR)
Parse error. Character 'ಠ' (U+0CA0) is not a valid identifier start char
}

var iOS8or9 = typeof document === 'object' && 'object-fit' in document.head.style && !matchMedia('(-webkit-video-playable-inline)').matches;

var ಠ = 'bfred-it:iphone-inline-video';
    ^
var ಠevent = 'bfred-it:iphone-inline-video:event';
var ಠplay = 'bfred-it:iphone-inline-video:nativeplay';
var ಠpause = 'bfred-it:iphone-inline-video:nativepause';


🚨   (closure-compiler-js plugin) Error transforming bundle with 'closure-compiler-js' plugin: compilation error, 1 error

error Command failed with exit code 1.
```

... and this is an npm package of yours ;)

**Comment by bfred-it** [comment] 2017-06-22 07:22
OT: That's neither rollup's nor strictly IIV's issue since IIV is rolled by rollup (meaning that rollup supports that char) and because ಠ is indeed `a valid identifier start char`, because it works. I'd say it's technically Closure's own parser bug. But I'll accept a PR in IIV replacing`ಠ` with `IIV`

**Comment by guybedford** [comment] 2018-02-09 18:32
From what I can tell this is now being correctly warned as an invalid input option if not a valid identifier.

**Closed by guybedford** 2018-02-09 18:32 UTC
Labels: PR welcome :-), bug
