### ISSUE TITLE
Tree-shaking not work

### ISSUE THREAD

**Issue by nuintun** [rollup/rollup#2807] opened 2019-04-14 04:54 UTC
- Rollup Version: v1.10.0
- Operating System (or Browser): Win10
- Node Version: v11.14.0

### How Do We Reproduce?
1. Clone https://github.com/nuintun/qrcode
2. Run `yarn`
3. Run `yarn build`
4. Run `yarn rollup`
5. Check `example/encoder/bundle.js`

You see `QRKanji` `QRNumber` `QRAlphanumeric` not used in `example/encoder/index.js`, but they have not been removed.

### Expected Behavior
`QRKanji` `QRNumber` `QRAlphanumeric` not include in `example/encoder/bundle.js`

### Actual Behavior
`QRKanji` `QRNumber` `QRAlphanumeric` include in `example/encoder/bundle.js`

**Comment by nuintun** [comment] 2019-04-14 05:02
Another strange bug: [DEMO](https://rollupjs.org/repl?version=1.10.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMFNxdWFyZSUyMCU3RCUyMGZyb20lMjAnLiUyRmluZGV4JyUzQiU1Q24lNUNubmV3JTIwU3F1YXJlKDYpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGNsYXNzJTIwQ3ViZSUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoeCklMjAlN0IlNUNuJTVDdCU1Q3R0aGlzLnglMjAlM0QlMjB4JTNCJTVDbiU1Q3QlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNxdWFyZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBTcXVhcmUlMjAlN0IlNUNuJTVDdGNvbnN0cnVjdG9yKHgpJTIwJTdCJTVDbiU1Q3QlNUN0dGhpcy54JTIwJTNEJTIweCUzQiU1Q24lNUN0JTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJpbmRleC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0IlMjBkZWZhdWx0JTIwYXMlMjBDdWJlJTIwJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMnJTNCJTVDbmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjBhcyUyMFNxdWFyZSUyMCU3RCUyMGZyb20lMjAnLiUyRnNxdWFyZSclM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by GrosSacASac** [comment] 2019-04-16 11:44
[DEMO](https://rollupjs.org/repl?version=1.10.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMFNxdWFyZSUyMCU3RCUyMGZyb20lMjAnLiUyRmluZGV4JyUzQiU1Q24lNUNubmV3JTIwU3F1YXJlKDYpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGNsYXNzJTIwQ3ViZSUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoeCklMjAlN0IlNUNuJTVDdCU1Q3R0aGlzLnglMjAlM0QlMjB4JTNCJTVDbiU1Q3QlN0QlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNxdWFyZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBTcXVhcmUlMjAlN0IlNUNuJTVDdGNvbnN0cnVjdG9yKHgpJTIwJTdCJTVDbiU1Q3QlNUN0dGhpcy54JTIwJTNEJTIweCUzQiU1Q24lNUN0JTdEJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJpbmRleC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAlN0IlMjBkZWZhdWx0JTIwYXMlMjBDdWJlJTIwJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMnJTNCJTVDbmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjBhcyUyMFNxdWFyZSUyMCU3RCUyMGZyb20lMjAnLiUyRnNxdWFyZSclM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=) has no side effect so it is not a bug.

**Comment by GrosSacASac** [comment] 2019-04-16 11:48
You use typescript compiler and then rollup on the output.
Can you try using typescript inside rollup ? not before ?
use https://github.com/rollup/rollup-plugin-typescript or https://github.com/ezolenko/rollup-plugin-typescript2

**Comment by nuintun** [comment] 2019-04-19 07:47
@GrosSacASac 
I publish to npm: [@nuintun/qrcode](https://www.npmjs.com/package/@nuintun/qrcode),
so I can't ask others must to use `rollup-plugin-typescript2`!

**Comment by lukastaegert** [comment] 2019-04-19 07:57
Rollup usually cannot tree-shake TypeScript classes that are transpiled to ES5 as Rollup is not able to determine if the generated code is side-effect free. You might have more luck choosing "ES2015" as a TypeScript target and manually transpiling later using e.g. Babel (or a second TypeScript pass with a different config).

**Comment by kzc** [comment] 2019-04-24 14:32
dup of #1763

Replace the typescript generated `/* @class */` comments with `/*@__PURE__*/` to have the unused es5 class IIFEs dropped either by Rollup itself or by a minifier plugin.

```
$ cat rollup.config.js 
import typescript from 'rollup-plugin-typescript';

export default {
    input: [
        './example.ts',
    ],
    plugins: [
        typescript(),
        {
            transform(code, id) {
                return code.replace(/\/\*\* @class \*\//g, "\/*@__PURE__*\/");
            }
        },
    ],
    output: {
        dir: './dist/',
        format: 'es',
    }
};
```
```
$ cat example.ts 
class Base { }
class Derived extends Base { 
    hi() { console.log("hello Derived"); }
}
class Unused extends Derived { 
    hi() { console.log("hello Unused"); }
}
(new Derived).hi();
```
```
$ node_modules/.bin/rollup -v
rollup v1.10.1
```
```
$ node_modules/.bin/rollup -c rollup.config.js --silent
```
Notice that the class `Unused` does not appear in the generated bundle:
```
$ grep Derived dist/example.js | wc -l
       6
```
```
$ grep Unused dist/example.js | wc -l
       0
```
It probably would be a good idea if `rollup-plugin-typescript` were to default to this behavior by default as it's what most would want.

**Comment by lukastaegert** [comment] 2019-04-25 04:27
@kzc Great idea! Either that or add a pure annotation next to each class annotation in case people already care about the class annotations.

**Comment by nuintun** [comment] 2019-05-08 07:37
For safety, I use ast replace `/** @class */`.

```js
const { parse } = require('@babel/parser');
const { default: traverse } = require('@babel/traverse');
const { default: generate } = require('@babel/generator');

const ast = parse(`var QRByte = /** @class */ (function(){}());`, { sourceType: 'module' });

traverse(ast, {
  CallExpression(path) {
    if (Array.isArray(path.node.leadingComments)) {
      path.node.leadingComments.forEach(node => {
        if (node.value === '* @class ') {
          node.value = '#__PURE__';
        }
      });
    }
  }
});

const { code } = generate(ast, { retainLines: true });
```

**Comment by nuintun** [comment] 2019-05-08 10:12
@lukastaegert 

```js
import typescript from 'rollup-plugin-typescript2';

export default {
  external: ['tslib'],
  input: 'src/index.ts',
  preserveModules: true,
  plugins: [typescript()],
  output: { format: 'esm', dir: 'exnext' },
  onwarn(error, warn) {
    if (error.code !== 'CIRCULAR_DEPENDENCY') {
      warn(error);
    }
  }
};
```

I want to use `rollup preserveModules`, but it ouput `.ts` file. How do I output `.js` file. 3Q~

**Comment by myklt** [comment] 2019-05-08 20:11
@nuintun , I've just raised a feature request for this #2842 . Please add any details there if you find it relevant for you as well.

**Comment by shellscape** [comment] 2019-08-15 13:36
@lukastaegert I'm unsure how to classify this issue. Any thoughts?

**Comment by lukastaegert** [comment] 2019-08-15 17:47
I believe from the original issue it has been discussed enough with solution suggestions to warrant closing this one.

**Closed by lukastaegert** 2019-08-15 17:47 UTC
