### ISSUE TITLE
Exported functions referenced only by a tree-shaken func are not tree-shaken

### ISSUE THREAD

**Issue by IvanSanchez** [rollup/rollup#1077] opened 2016-10-24 13:26 UTC
Consider the following case (see a [demo here](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwVXRpbHMlMjBmcm9tJTIwJy4lMkZ1dGlscyclNUNuJTVDbmNvbnNvbGUubG9nKFV0aWxzLmMpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnV0aWxzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwYShwYXJhbSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwcGFyYW0uZG9Tb21ldGhpbmcoKSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwYihwYXJhbSklMjAlN0IlNUNuJTVDdHJldHVybiUyMGEocGFyYW0pJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBjJTIwJTNEJTIwNDIlM0IlNUNuJTIyJTdEJTVEJTdE)):

``` js
// Utils.js
export function a(param) {return param.method()}
export function b(...) { var foo = a(...); ... }
export const c = 42;
```

``` js
// main.js
import * as Utils from './Utils.js'
console.log( Utils.c );
```

The expected bundle should contain only the definition for `function c()`. However, in the demo, the definition for `function a()` is outputted even though the only place where `a()` is used is inside `b()`, and `b()` is tree-shaken, i.e.:

``` js
// expected bundle
const c = 42;
console.log(c);
```

``` js
// actual bundle
function a(param) {return param.method()}
const c = 42;
console.log(c);
```

Oddly enough, `function a()` is tree-shaken if it does _not_ call some method of some of its arguments ([demo here](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwVXRpbHMlMjBmcm9tJTIwJy4lMkZ1dGlscyclNUNuJTVDbmNvbnNvbGUubG9nKFV0aWxzLmFuc3dlciklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydXRpbHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZnVuY3Rpb24lMjBhKHBhcmFtKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBwYXJhbSUyMCUyQiUyMDElM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGIocGFyYW0pJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMGEocGFyYW0pJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBhbnN3ZXIlMjAlM0QlMjA0MiUzQiU1Q24lMjIlN0QlNUQlN0Q=)), e.g.:

``` js
// This will be tree-shaken properly
export function a(param) {
    return param + 1;
}

export function b(param) {
    return a(param);
}
```

This is reproducible using v0.36.3, the latest available at the date of this writing.

**Comment by kzc** [comment] 2016-10-25 00:43
Dupe of https://github.com/rollup/rollup/issues/977#issuecomment-249613600

Workaround: run the actual rollup output through rollup again to get the expected rollup output.

**Comment by Rich-Harris** [comment] 2016-12-28 19:47
Fixed in recent versions, closing

**Closed by Rich-Harris** 2016-12-28 19:47 UTC
