### ISSUE TITLE
Issue with tree shaking

### ISSUE THREAD

**Issue by chielkunkels** [rollup/rollup#1147] opened 2016-12-14 13:01 UTC
Recently I stumbled on an issue where rollup bundle was including a bunch of modules which were not used in the final bundle.

I have created a small repository here to reproduce the issue: https://github.com/chielkunkels/rollup-issue2. Sadly, I could not distil it to anything smaller than this.

In the repository there are three commits, in all but the first the build works perfectly fine:

1. The first commit simply contains a very small tree, there are 2 components being exposed in `src/ui/index.js`, one of these (`Logo`) is included in `src/index.js` and the final bundle only includes the absolutely essential code to do its thing.
2. In the second commit I have moved the code from `src/ui` to `node_modules/poki-ui/src` and changed the structure slightly. The goal here was to get closer to the issue I'm having by moving it to a separate packages. In this commit the final bundle also included only the essential code do do its thing.
3. In this commit I do include the actual `poki-ui` package. The `es6/index.js` file has the same structure as the `node_modules/poki-ui/jsnext/index.js`, however it seems it is not getting tree-shaken properly since all the modules from `es6/index.js` (amd their dependencies) are included in the final bundle.

I have tried to debug this issue myself a little by digging around in the `dist/rollup.js`, but I didn't get much further than where the tree-shaking occurs. It feels like dependencies are being marked to be included in the bundle even though they shouldn't be.

I'm happy to help out more in fixing this issue, so please let me know if there's anything else I can do.

**Comment by Rich-Harris** [comment] 2016-12-22 02:43
This falls under https://github.com/rollup/rollup/wiki/Troubleshooting#tree-shaking-doesnt-seem-to-be-working – I'll close this issue as it's a duplicate of several others, and without specific examples of code that could be removed but isn't there's not much we can do. Thanks

**Closed by Rich-Harris** 2016-12-22 02:43 UTC
