### ISSUE TITLE
Treeshake and babel 7 template literals plugin

### ISSUE THREAD

**Issue by edoardocavazza** [rollup/rollup#1714] opened 2017-11-09 13:17 UTC
Hi,

I have noticed that treeshake is broken with new babel 7 template literal transform. It seems that rollup cannot recognise unused variables with the transpiled string. Here a sample which throws SyntaxError with already transpiled babel code:
https://rollupjs.org/repl?version=0.51.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGIlMjAlN0QlMjBmcm9tJTIwJy4lMkZsaWInJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhiKSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJsaWIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjBoZWxsbyUyMCUzRCUyMCdoZWxsbyclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAlN0IlNUNuJTVDdGtleSUzQSUyMCcnLmNvbmNhdChoZWxsbyUyQyUyMCclMjB0aGVyZSEnKSUyQyU1Q24lN0QlM0IlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwYiUyMCUzRCUyMCd3b3JsZCclM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by lukastaegert** [comment] 2017-11-09 13:27
Actually, this is not (only?) a problem with babel's transformation but with `.concat()`. For now, no string or array prototype methods are implemented yet. Therefore, rollup assumes the call to `''.concat(...)` can have side-effects and it is retained. This is something I expect to be fixed in the future, though. Similar things will happen when you use `.apply(...)` or `.call(...)` on functions.

**Comment by edoardocavazza** [comment] 2017-11-09 19:56
But in case of default export of an object, this trows a Syntax Error. Maybe [here](https://github.com/rollup/rollup/blob/master/src/ast/nodes/ExportDefaultDeclaration.js#L67) can be added a check for variable assignement (or force it) before removing the export statement?

**Comment by guybedford** [comment] 2018-02-10 21:06
Marking as a duplicate of https://github.com/rollup/rollup/issues/1772.

**Closed by guybedford** 2018-02-10 21:06 UTC
Labels: treeshaking
