### ISSUE TITLE
variable is used before declaration

### ISSUE THREAD

**Issue by szdailei** [rollup/rollup#4187] opened 2021-07-23 05:00 UTC
### Rollup Version

2.52.8

### Operating System (or Browser)

Linux

### Node Version (if applicable)

v14.16.0

### Link To Reproduction

https://github.com/szdailei/www/tree/main/packages/api-server

### Expected Behaviour

Rollup 2.52.7 bundle glob 7.1.6 sync.js.
Bundled code is:

var sync = globSync$1;
globSync$1.GlobSync = GlobSync$1;

var fs$5 = fs__default;
var rp$1 = fs_realpath;
var minimatch$1 = minimatch_1;
var path$5 = path__default;
var assert$2 = require$$6;
var isAbsolute$1 = pathIsAbsolute.exports;
var common$1 = common$2;
common$1.alphasort;
common$1.alphasorti;

### Actual Behaviour

Rollup 2.52.8 bundle glob 7.1.6 sync.js. glob_1 is used before declaration. 
Bundled code is:

var sync = globSync$1;
globSync$1.GlobSync = GlobSync$1;

var fs$5 = fs__default;
var rp$1 = fs_realpath;
var minimatch$1 = minimatch_1;
glob_1.Glob;
var path$5 = path__default;
var assert$2 = require$$6;
var isAbsolute$1 = pathIsAbsolute.exports;
var common$1 = common$2;
common$1.alphasort;
common$1.alphasorti;

**Comment by nborko** [comment] 2021-07-23 13:42
I've got the same issue when bundling glob, on Windows 10 19043.1110, Node v14.17.3.

Bundling fails on rollup 2.52.8 through 2.53.3, 2.52.7 works.

**Comment by kzc** [comment] 2021-07-24 14:59
This issue is likely related to Rollup now respecting ECMAScript rules governing [Temporal Dead Zone (TDZ)](https://exploringjs.com/es6/ch_variables.html#sec_temporal-dead-zone) for const/let variables.

Before rollup would incorrectly process code like the following and mask user created and library errors:

```
$ cat tdz-example.js 
console.log(C && "WRONG BEHAVIOR"); const C = true;
```
expected ECMAScript runtime behavior:
```
$ cat tdz-example.js | node
[stdin]:1
console.log(C && "WRONG BEHAVIOR"); const C = true;
            ^
ReferenceError: Cannot access 'C' before initialization
```
rollup v2.52.7 incorrect output:
```
$ rollup tdz-example.js --silent
console.log("WRONG BEHAVIOR");
```
```
$ rollup tdz-example.js --silent | node
WRONG BEHAVIOR
```

rollup v2.53.3 correct output:
```
$ rollup tdz-example.js --silent
console.log(C && "WRONG BEHAVIOR"); const C = true;
```
```
$ rollup tdz-example.js --silent | node
[stdin]:1
console.log(C && "WRONG BEHAVIOR"); const C = true;
            ^
ReferenceError: Cannot access 'C' before initialization
```

**Comment by kzc** [comment] 2021-07-24 18:26
A simple way to determine whether your code or some imported library has a TDZ error is to run the old (or new) version of rollup with `--no-treeshake` and then test the bundle as you normally would.

**Comment by szdailei** [comment] 2021-07-26 03:55
@kzc You are right. there is a TDZ error.
When I run rollup 2.52.7 with --no-treeshake, I got same error with rollup 2.52.8

**Comment by nborko** [comment] 2021-07-26 21:47
In this case, globSync is a function, and aren't functions hoisted in ECMAScript?

**Comment by lukastaegert** [comment] 2021-07-27 04:30
I wonder if it is an artifact of the commonjs conversion and the issue is not present in the original sources. Maybe we need a flag to disable TDZ detection after all until we can fix the CommonJS plugin, which is definitely harder.

**Comment by lukastaegert** [comment] 2021-07-27 04:38
> In this case, globSync is a function, and aren't functions hoisted in ECMAScript?

The function may be hoisted, but the property access in

```js
var Glob = require('./glob.js').Glob
```

is not hoisted. The commonjs plugin replaces the require call with a variable that is undefined when used due to the imperfectly resolved circular dependency. It probably works in the original sources because here, the require calls are basically run like function calls. Until now, Rollup does not support circular CommonJS dependencies properly, unfortunately.

**Comment by kzc** [comment] 2021-07-27 05:49
> Maybe we need a flag to disable TDZ detection after all until we can fix the CommonJS plugin, which is definitely harder.

I don't think adding a flag to disable TDZ detection (i.e., correct ES operation) could help considering that the problem also occurs when tree shaking is disabled altogether:

> When I run rollup 2.52.7 with `--no-treeshake`, I got same error with rollup 2.52.8

But I'm still missing what's the actual problem. If we can create the smallest possible program demonstrating the issue we can compare it to an unbundled set of source files running directly in NodeJS and see whether it works there.

**Comment by lukastaegert** [comment] 2021-07-27 10:22
The problem is very likely that the commonjs plugin does not wrap commonjs modules into function calls, maintaining a registry to resolve require calls. Instead, it tries to rewrite them to ESM directly. This works surprisingly well except when there are circular require calls in the code. In that case, the "correct" logic would be to
* Execute part of the current file, putting properties on `exports` until the require call
* Then execute the required file, resolving imports of the initial file with the current state of its `exports` object
It is the "half-finished exports object" that is usually missing and breaking things.

**Comment by kzc** [comment] 2021-07-27 16:30
@szdailei Just out of curiosity could you please try running both rollup 2.52.7 and rollup 2.52.8 with `--treeshake --no-treeshake.unknownGlobalSideEffects --no-treeshake.propertyReadSideEffects`? This would eliminate `glob_1.Glob;` from the Actual Behavior output seen in the top post. This might be enough to paper over the real underlying issue (whatever that may be) and allow the code to run. Although these options would still leave `globSync$1.GlobSync = GlobSync$1;` which ought to throw an error as well.

**Comment by kzc** [comment] 2021-07-27 18:33
Confirmed that the workaround suggested [above](https://github.com/rollup/rollup/issues/4187#issuecomment-887658101) works...

Given:
```
$ cat glob-repro.mjs
import glob from "glob";
glob("*/glob/*js",{},(e,f)=>console.log(f.join(" ")));
```
Expected:
```
$ node glob-repro.mjs
node_modules/glob/common.js node_modules/glob/glob.js node_modules/glob/sync.js
```
Reproduction of issue:
```
$ rollup -v
rollup v2.54.0
```
```
$ rollup glob-repro.mjs -p node-resolve,commonjs --silent | node --input-type module
[eval1]:1883
glob_1.Glob;
       ^
TypeError: Cannot read property 'Glob' of undefined
```

Workaround:
```
$ rollup glob-repro.mjs --no-treeshake.unknownGlobalSideEffects --no-treeshake.propertyReadSideEffects -p node-resolve,commonjs --silent | node --input-type module
node_modules/glob/common.js node_modules/glob/glob.js node_modules/glob/sync.js
```

The diff between the output of the two rollup output bundles above:
```diff
--- failing.mjs
+++ working.mjs
@@ -76,4 +76,2 @@
 
-pathModule.normalize;
-
 // Regexp that finds the next partion of a (partial) path
@@ -1882,3 +1880,2 @@
 var minimatch$1 = minimatch_1;
-glob_1.Glob;
 var path$1 = require$$0;
```

Ironically, the problematic line and local variable `Glob` in the `glob` package in `node_modules/glob/sync.js` is not used:
```
var Glob = require('./glob.js').Glob
``` 
and probably can be safely removed from the upstream package.

**Comment by kzc** [comment] 2021-07-27 21:55
Here's a minimal repro of a bug where the previous workaround does not work...

```
$ cat test.mjs 
import foo from "./foo.js";
foo();
```
```
$ cat foo.js 
var foo = () => console.log("FOO");
module.exports = foo;
foo.prop = "PROP";
var bar = require('./bar.js');
console.log(bar);
```
```
$ cat bar.js 
module.exports = "BAR";
var prop = require('./foo.js').prop;
console.log(prop);
```

Expected output with node v14 and v16:
```
$ node test.mjs 
PROP
BAR
FOO
```

Actual:

```
$ rollup -v
rollup v2.54.0
```
```
$ rollup test.mjs -p commonjs --silent
var bar$1 = "BAR";
var prop = foo_1.prop;
console.log(prop);

var foo = () => console.log("FOO");
var foo_1 = foo;
foo.prop = "PROP";
var bar = bar$1;
console.log(bar);

foo_1();
```
```
$ rollup test.mjs -p commonjs --silent | node
[stdin]:2
var prop = foo_1.prop;
                 ^
TypeError: Cannot read property 'prop' of undefined
```
```
$ rollup test.mjs -p commonjs --no-treeshake.unknownGlobalSideEffects --no-treeshake.propertyReadSideEffects --silent | node
[stdin]:2
var prop = foo_1.prop;
                 ^
TypeError: Cannot read property 'prop' of undefined
```

The old version of rollup cited above also doesn't work in this case:

```
$ node_modules/.bin/rollup -v
rollup v2.52.7

$ node_modules/.bin/rollup test.mjs -p commonjs --silent | node
[stdin]:2
var prop = foo_1.prop;
                 ^
TypeError: Cannot read property 'prop' of undefined
```
fwiw, esbuild can handle require cycles:

```
$ esbuild --version
0.12.16

$ esbuild test.mjs --bundle --minify | node
PROP
BAR
FOO
```

**Comment by kzc** [comment] 2021-07-27 22:53
> the commonjs plugin does not wrap commonjs modules into function calls, maintaining a registry to resolve require calls. Instead, it tries to rewrite them to ESM directly. This works surprisingly well except when there are circular require calls in the code.

To your point - but it also occurs without require cycles:

```
$ cat start.mjs 
console.log("start.js begin");
import "./a.js";
console.log("start.js end");
```
```
$ cat a.js
console.log("a.js begin");
require("./b.js");
console.log("a.js end");
```
```
$ cat b.js
console.log("b.js");
```
Expected:
```
$ node start.mjs 
a.js begin
b.js
a.js end
start.js begin
start.js end
```
Actual:
```
$ rollup start.mjs -p node-resolve,commonjs --silent | node
b.js
a.js begin
a.js end
start.js begin
start.js end
```

It's interesting that the rollup commonjs require ordering hasn't been noticed before. It must not be an issue with many projects.

**Comment by szdailei** [comment] 2021-07-28 02:46
@kzc I have added --treeshake --no-treeshake.unknownGlobalSideEffects --no-treeshake.propertyReadSideEffects and upgrade to rollup 2.54.0, it works.

**Comment by kzc** [comment] 2021-07-28 03:18
It's not a general solution for require cycles, but it does work for bundling `glob`.

`--treeshake` is implicit and not needed.  I specified that only to differentiate it from an earlier comment.

It's possible that `--no-treeshake.unknownGlobalSideEffects` is not necessary since `glob_1` was a `var` that was declared later in the bundle:

```
$ rollup -v
rollup v2.54.0

$ rollup glob-repro.mjs --no-treeshake.propertyReadSideEffects -p node-resolve,commonjs --silent | node --input-type module
node_modules/glob/common.js node_modules/glob/glob.js node_modules/glob/sync.js
```

**Comment by szdailei** [comment] 2021-07-28 05:25
@kzc You are right again. Only  --no-treeshake.propertyReadSideEffects is required. --treeshake and --no-treeshake.unknownGlobalSideEffects are not necessary.

**Comment by nicolo-ribaudo** [comment] 2021-07-28 20:42
Probably I found the same problem: Rollup `2.55.0` fails to bundle `semver@7` when using `@rollup/plugin-commonjs@18`, because of a variable used before its declaration caused by a circular dependency. Rollup `2.54.0` works.

I'll not open a new issue since it works with `@rollup/plugin-commonjs@19` (even if "it stops working with v18" is technically a breaking change for `rollup`), but if needed I already created a repo that reproduces the error: https://github.com/nicolo-ribaudo/rollup-2.55-bug-semver-7

**Comment by lukastaegert** [comment] 2021-11-25 06:18
We are finalizing a new version of the commonjs plugin in rollup/plugins#1038. It is pre-published as `@rollup/plugin-commonjs@beta`. Please give it a spin to see if it resolves the issue, ideally without additional config needed.

**Closed** 2022-04-24 05:58 UTC
Labels: t¹ 🐞 bug, t⁸ ⋅ triage
