### ISSUE TITLE
import * handled incorrectly (not at all) in chunking code

### ISSUE THREAD

**Issue by arackaf** [rollup/rollup#2014] opened 2018-02-25 20:50 UTC
Repo: https://github.com/arackaf/booklist/tree/special/rollup-snapshot-feb-25  (that branch in particular)

Switch to the react-redux folder.  `npm i` `npm run ts` then finally `npm run rollup`

In `public/module/books.js` search for `booksActionCreators`

You should find two references, without declarations, which of course causes a ReferenceError at runtime.  This variable is imported here

`import * as booksActionCreators from "../reducers/books/actionCreators";`

in `modules/books/components/booksMenuBar.tsx`.  (the other, adjacent import * statements are similarly orphaned)

**Comment by guybedford** [comment] 2018-03-01 14:08
I can confirm this is a bug, will let you know when I've got a fix here.

**Comment by arackaf** [comment] 2018-03-01 22:23
Thanks as always Guy!

**Comment by guybedford** [comment] 2018-03-04 16:11
@arackaf I just ran this on the latest branch of Rollup I have here and couldn't reproduce the issue anymore.

When the next version goes out this week, please test with that and let me know if you're still seeing the issue.

**Comment by arackaf** [comment] 2018-03-04 16:33
Will do, thanks.

**Comment by lukastaegert** [comment] 2018-03-05 05:48
Just released the first bunch of PRs.

**Comment by arackaf** [comment] 2018-03-10 20:06
Finally got back to this.  Sorry, the `import *` is still getting dropped.  In public/module/books.js I'm still seeing undeclared references to `booksActionCreators`

**Comment by guybedford** [comment] 2018-03-11 17:10
@arackaf thanks for getting back on this. My apologies I should have mentioned that this will likely be resolved by https://github.com/rollup/rollup/pull/2041 now, which should be released soon!

**Comment by arackaf** [comment] 2018-03-11 19:27
Outstanding - thanks much!

**Comment by guybedford** [comment] 2018-03-19 17:14
I'm closing this as fixed, but please do post back if you are still noticing this at all.

**Closed by guybedford** 2018-03-19 17:14 UTC
Labels: bug, scope-hoisting
