### ISSUE TITLE
iife external and globals

### ISSUE THREAD

**Issue by thisconnect** [rollup/rollup#401] opened 2015-12-31 12:30 UTC
Can an external be a relative import or does it have to be a node module with a package.json and main / jsnext:main?

https://github.com/rollup/rollup/wiki/JavaScript-API#external

Same question for globals, can they be relative imports somehow or are only node modules supported as globals?

https://github.com/rollup/rollup/wiki/JavaScript-API#globals

**Comment by thisconnect** [comment] 2015-12-31 12:31
relates to #372

**Comment by Victorystick** [comment] 2015-12-31 16:42
A relative import _can theoretically_ be external, but it's usually not what you want. An iife's externals are always globals.

**Comment by thisconnect** [comment] 2015-12-31 16:44
Actually I want it as global, I'm just not able to exclude it atm. See the setup here https://github.com/rollup/rollup/issues/372#issuecomment-168187985

**Comment by Victorystick** [comment] 2016-01-04 14:56
Closing as duplicate of #410.

**Closed by Victorystick** 2016-01-04 14:56 UTC
Labels: duplicate
