### ISSUE TITLE
[experimentalCodeSplitting] Unused import left in entry file

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#2368] opened 2018-08-02 14:01 UTC
The issue can be observed by checking the build output [here](https://github.com/reakit/reakit/pull/168/commits/cd26e0ebc9ee60ecb6f02a5d2627d300e8f3b4a2). It's not a minimal repro though.

This library is reexporting all public exports from `index.js` but also wants to allow for imports like `import Divider from 'reakit/Divider'`. To avoid code duplication `experimentalCodeSplitting` comes in handy.

```js
// es/Divider.js
import { a as Divider } from './chunk-b07cd038.js';
export { a as default } from './chunk-b07cd038.js';
import 'prop-types';
import 'styled-components';
import 'styled-tools';
import './as-8a1cd76d.js';
import 'lodash-es/uniq';
import 'react-known-props';
import 'react';
import 'lodash-es/omit';
import './chunk-5c6a1db8.js';
import 'lodash-es/kebabCase';
```

As you can see actual contents of this entry file were moved to a separate chunk (which is ok) and "unused" import referencing the chunk is left in it (`import { a as Divider } from './chunk-b07cd038.js'`). It seems to me that it should be enough to output this:
```diff
- import { a as Divider } from './chunk-b07cd038.js';
export { a as default } from './chunk-b07cd038.js';
import 'prop-types';
import 'styled-components';
import 'styled-tools';
import './as-8a1cd76d.js';
import 'lodash-es/uniq';
import 'react-known-props';
import 'react';
import 'lodash-es/omit';
import './chunk-5c6a1db8.js';
import 'lodash-es/kebabCase';
```

I realize this shouldn't cause any problems, but the output could be more "compact" 😉 

Sideways question - shouldnt "optimizing" side-effect imports (such as `import 'react';`) come first? Or are they intentionally last? Would putting them first or last change the behaviour in any way?

**Comment by guybedford** [comment] 2018-08-02 19:55
Glad you're trying out these workflows... feedback is super useful as this is moving towards unflagged release!

I believe the issue you're seeing is https://github.com/rollup/rollup/issues/2231, although that wasn't very clearly worded, I've updated the wording there a bit.

As for your optimization question, execution order is retained as the important thing to keep here, so we don't move things about at all. In theory we could move pure modules around wherever we want in the execution order, but there's no logic along that sort of line currently.

**Comment by guybedford** [comment] 2018-08-03 11:59
Great to hear it's working well for you there.

Closing as a duplicate of #2231, and apologies that one won't get traction for a little while yet.

**Closed by guybedford** 2018-08-03 11:59 UTC
