### ISSUE TITLE
name conflicting

### ISSUE THREAD

**Issue by JounQin** [rollup/rollup#1505] opened 2017-07-28 07:48 UTC
reproduction: https://github.com/JounQin/issues

generated codes:
``` js
var getImages = function () {
};

var index = {
  getImages: function getImages() {
    getImages();
  }
};

export default index;
```

Obviously, there is a conflict of `getImages`.

**Comment by pshrmn** [comment] 2017-07-28 16:07
I believe that this is a duplicate of #1488

**Comment by Rich-Harris** [comment] 2017-08-12 01:41
Thanks, this is fixed in 0.46.3

**Closed by Rich-Harris** 2017-08-12 01:41 UTC
Labels: bug
