### ISSUE TITLE
Tree shaking is broken in React apps

### ISSUE THREAD

**Issue by VladShcherbin** [rollup/rollup#855] opened 2016-08-15 23:37 UTC
**tl;dr** After failing with [webpack tree shaking](https://github.com/webpack/webpack/issues/2867), I gave rollup a shot. Unfortunately, it's not working here too.

The test case is a simple app with React & React Router v3. `Link` component is not used, but the whole router package is bundled.

```js
import React from 'react'
import ReactDOM from 'react-dom'
import { Link } from 'react-router'

ReactDOM.render(
  <p>Hey</p>,
  document.getElementById('app')
)
```

[Webpack & Rollup test repo](https://github.com/VladShcherbin/react-rollup-webpack-test)

**Comment by Rich-Harris** [comment] 2016-08-16 19:41
Are you able to share the repo you're working with?

**Comment by VladShcherbin** [comment] 2016-08-16 20:35
@Rich-Harris sure, here is the [repo](https://github.com/VladShcherbin/react-rollup-webpack-test) with my current Rollup and Webpack configs.

**Comment by GGAlanSmithee** [comment] 2016-08-16 21:37
In not too long I will attempt to migrate a rather large React app from webpack to rollup at work (for production), so I thought it would be nice to see if I could track down this error as preparation.

Unfortunately I was not able to find what was wrong, but maybe what I didn't find can rule something out:

* I tried changing the order of the presets in the `.babelrc` file
* I tried changing the order of the plugins in the `rollup.config.js` file
* I tried various `include` / `exclude` options for the `nodeResolve` and `commonJS` plugin (even though `'node_modules/**'` should work I guess)

So, this did not fix it, however, if I do `import React, { PropTypes } from 'react'` directly in `index.js` it bundles succesfully, so maybe that is indicative that the problem is with the `nodeResolve/commonJs` plugin combo?

**Comment by marvinhagemeister** [comment] 2016-08-17 17:20
For reference: React exports an object. If I recall correctly there have been similar issues before when a package didn't use named exports.

```js
var React = {
  PropTypes: ReactPropTypes,
  ... // more stuff
};

module.exports = React;
```

**Comment by VladShcherbin** [comment] 2016-08-21 17:54
@marvinhagemeister yep, `namedExports` is the current fix.

Still, tree shaking is not working, even with `react-router`'s special `es` version. Surprisingly, rollup with react-router is [still bigger](https://github.com/VladShcherbin/react-rollup-webpack-test#current-status) than webpack.

We have the [tree-shaking issue](https://github.com/webpack/webpack/issues/2867) opened in webpack as well, the suggested idea to try `uglify` with `warnings: true` produced [them](https://github.com/VladShcherbin/react-rollup-webpack-test/tree/master/uglify-warnings).

@Rich-Harris maybe this can somehow help the investigation.

**Comment by nolanlawson** [comment] 2016-08-21 21:00
Besides the fact that many modules are getting pulled in as CommonJS, it seems like another issue is Uglify. Without Uglify, Rollup is actually smaller:

| | Rollup | Webpack |
| --- | --- | --- |
| default | 749401 | 825801 |
| uglify -mc | 199059 | 188910 |
| uglify -mc \| gzip -c9 | 58731 | 55672 |

I checked the code for `eval`, `Function`, and other things that Uglify would de-optimize, but nothing stood out. Apparently there's some other reason that Rollup's output is not being minified very efficiently here.

**Comment by nolanlawson** [comment] 2016-08-21 21:05
It's also quite possible that the number of modules in this project is low enough (and not enough of them are ES6 modules vs CommonJS) that you're not seeing a big gain from Rollup's optimizations. Using `browserify-count-modules` (and `browserify -t babelify` to build), I only count 227 total modules.

**Comment by VladShcherbin** [comment] 2016-08-21 21:15
This is actually one of the reasons, why I took `react-router` for the test. I've seen @taion in many discussions about tree shaking and there are efforts to make it work: [es6 build](https://github.com/reactjs/react-router/blob/v3.0.0-alpha.3/package.json#L21), [module](https://github.com/reactjs/react-router/blob/v3.0.0-alpha.3/package.json#L13), [jsnext:main](https://github.com/reactjs/react-router/blob/v3.0.0-alpha.3/package.json#L14).

But still, even using `import { Link } from 'react-router/es'` and not using it anywhere includes the `react-router` package in the bundle.

I actually thought, it would completely remove it so the bundle size will be similar to just plain react bundle.

**Comment by nolanlawson** [comment] 2016-08-22 00:17
There are issues when modules have side effects; see @calvinmetcalf's comments on this: https://github.com/rollup/rollup/pull/555

**Comment by Rich-Harris** [comment] 2016-08-31 01:14
Alright, I figured out what's going on here. React has a bunch of stuff like this:

```js
if (process.env.NODE_ENV !== 'production') {
  var ReactElementValidator = require('./ReactElementValidator');
  createElement = ReactElementValidator.createElement;
  createFactory = ReactElementValidator.createFactory;
  cloneElement = ReactElementValidator.cloneElement;
}
```

Now, Rollup is smart enough to drop the code once rollup-plugin-replace has turned that into this...

```js
if ('production' !== 'production') {
  /* code disappears in a puff of smoke */
}
```

...but by that point, rollup-plugin-commonjs has already seen `require('./ReactElementValidator')` and turned it into the equivalent `import` statement. In a perfect world that wouldn't matter, because the unused stuff would get tree-shaken out, but [it's not a perfect world](https://github.com/rollup/rollup/wiki/Troubleshooting#tree-shaking-doesnt-seem-to-be-working). A lot of unused code gets included.

So that explains the larger bundle size. I think the solution is to add the same dead branch logic to rollup-plugin-commonjs (i.e. it should disregard any `require` calls inside `if ( false ) ...` and equivalent blocks). Will have a think about the best way to do that. You'd also need to put the replace plugin *before* the commonjs plugin for that to work.

**Comment by tmornini** [comment] 2016-08-31 07:11
@snuggs great stuff!

**Comment by Rich-Harris** [comment] 2016-09-02 02:47
I've just released a new version of rollup-plugin-commonjs which ignores dead branches. Using the test repo (thanks!), I get the following results:

| | Rollup | Webpack |
| --- | --- | --- |
| default | 691436 | 825880 |
| uglify -mc | 180365 | 188832 |
| uglify -mc \| gzip -c9 | 53585 | 55762 |

(If React and friends were using ES modules rather than CommonJS, it would swing more sharply in Rollup's favour. One day!)

**Comment by VladShcherbin** [comment] 2016-09-02 08:43
I've updated the [test repo](https://github.com/VladShcherbin/react-rollup-webpack-test) with the latest version, though it is 186574 for me, not sure why.

@Rich-Harris `react-router` in the repo has a separate build (in `es` folder) with only ES modules, but it is still in the build file when not used. What has to be done in the libraries for rollup to be more effective?

**Comment by lukeapage** [comment] 2016-09-04 18:11
This pr to use rollup in the react repo solved the same issue by refactoring the code : https://github.com/facebook/react/pull/7178

**Comment by bfred-it** [comment] 2016-09-14 06:10
This would be a good use case for [shareable configs](https://github.com/rollup/rollup/issues/736)

Something like `rollup-config-react` could be created and used as a starter configuration.

**Comment by calvinmetcalf** [comment] 2016-09-14 18:17
https://www.npmjs.com/package/rollup-config-cjs

**Comment by kzc** [comment] 2017-01-03 19:00
The problem is one can't know if an unreferenced module has side effects.

https://github.com/rollup/rollup/wiki/Troubleshooting#tree-shaking-doesnt-seem-to-be-working

**Comment by Rich-Harris** [comment] 2017-01-06 00:42
Yeah, I think we should close this issue as there are several other similar ones.

**Closed by Rich-Harris** 2017-01-06 00:42 UTC
