### ISSUE TITLE
Rollup doesn't correctly mangle names

### ISSUE THREAD

**Issue by wereHamster** [rollup/rollup#1411] opened 2017-05-23 12:57 UTC
Example: https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMF9ib3VuZHMlMjBmcm9tJTIwJy4lMkZib3VuZHMuanMnJTNCJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwZihib3VuZHMpJTIwJTdCJTVDbiUyMGJvdW5kcyUyMCU3QyU3QyUyMChib3VuZHMlMjAlM0QlMjBfYm91bmRzLmRlZmF1bHQoKSklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJib3VuZHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBib3VuZHMoKSUyMCU3QiUyMHJldHVybiUyMDElM0IlMjAlN0QlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGJvdW5kcyUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

bounds-the-function and bounds-the-argument are two things. It works correctly when I change the import line to `import mkBounds from './bounds.js';` and then use `(bounds = mkBounds())`.

**Comment by Rich-Harris** [comment] 2017-06-04 18:33
Potential duplicate of https://github.com/rollup/rollup/issues/1338

**Comment by guybedford** [comment] 2018-02-09 18:30
This seems to be working in 0.55.4 now - https://rollupjs.org/repl?version=0.55.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMF9ib3VuZHMlMjBmcm9tJTIwJy4lMkZib3VuZHMuanMnJTNCJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwZihib3VuZHMpJTIwJTdCJTVDbiUyMGJvdW5kcyUyMCU3QyU3QyUyMChib3VuZHMlMjAlM0QlMjBfYm91bmRzLmRlZmF1bHQoKSklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJib3VuZHMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBib3VuZHMoKSUyMCU3QiUyMHJldHVybiUyMDElM0IlMjAlN0QlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGJvdW5kcyUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Closed by guybedford** 2018-02-09 18:30 UTC
Labels: bug, scope-hoisting
