### ISSUE TITLE
Rollup incorrectly exports null when re-exporting another file.

### ISSUE THREAD

**Issue by acollard** [rollup/rollup#605] opened 2016-04-13 18:28 UTC
See the following demo: http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22amd%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22%2F%2F%20Generated%20by%20build%20process%2C%20this%20is%20the%20multi-entry%20point%20file%5Cnexport%20*%20from%20'.%2Fmain.export'%3B%5Cnimport%20'.%2Fwidgets.constants'%3B%5Cnimport%20'.%2Fwidgets.funcs'%3B%5Cnimport%20'.%2Fwidgets.export'%3B%22%7D%2C%7B%22name%22%3A%22widgets.constants.js%22%2C%22code%22%3A%22export%20const%20%CF%80%20%3D%203.14159%3B%22%7D%2C%7B%22name%22%3A%22widgets.export.js%22%2C%22code%22%3A%22export%20*%20from%20'.%2Fwidgets.constants'%3B%5Cnexport%20*%20from%20'.%2Fwidgets.funcs'%3B%22%7D%2C%7B%22name%22%3A%22main.export.js%22%2C%22code%22%3A%22import%20*%20as%20Widgets%20from%20'.%2Fwidgets.export'%3B%5Cnexport%20%7BWidgets%7D%3B%22%7D%2C%7B%22name%22%3A%22widgets.funcs.js%22%2C%22code%22%3A%22export%20function%20abc()%7B%5Cn%20%20%5Cn%7D%3B%22%7D%5D%7D

Specifically:
```javascript
exports.Widgets = null;
```
We have a number of files we want to merge into one bundled output file. I've used the multi-entry point plugin as an example for importing all files in our build.

The application is broken down into multiple logical areas (Widgets, etc). Typically each area re-exports some information. I'd like to export these areas as the appropriate name from the root package. 

From my example above I would expect that I have something like this in my final package.
```javascript
const π = 3.14159;

function abc(){
};

var Widgets = { π: π, abc: abc};
exports.Widgets = Widgets;
```

**Comment by Victorystick** [comment] 2016-04-14 16:18
Rollup doesn't seem to understand that the `Widgets` namespace is used, and omits the declaration. Since the declaration is omitted, there is no identifier name for it to use in the assignment to `exports.Widget`.

**Comment by acollard** [comment] 2016-04-14 16:28
There is a workaround but it is pretty ugly.

This fails.
```javascript
import * as Widgets from './widgets.export';
export {Widgets};
```
This works.
```javascript
import * as w from './widgets.export';
export const Widgets = w;
```

Unfortunately for us our common library export file looks like this (before workaround):
```javascript
import * as Account from './account/account.exports';
import * as Async from './async/async.exports';
import * as Auth from './auth/auth.exports';
import * as ChangeTracking from './changeTracking/changeTracking.exports';
import * as Events from './events/events.exports';
import * as Files from './files/files.exports';
import * as Http from './http/http.exports';
import * as Logging from './logging/logging.exports';
import * as Moment from './moment/moment.exports';
import * as Resources from './resources/resources.exports';
import * as Routing from './routing/routing.exports';
import * as SignalR from './signalR/signalR.exports';
import * as Storage from './storage/storage.exports';
import * as TimeZone from './timeZone/timeZone.exports';
import * as UI from './ui/ui.exports';
import * as Url from './url/url.exports';
import * as Users from './users/users.exports';
import * as Utils from './utils/utils.exports';
import * as Validation from './validation/validation.exports';

export { Account, Auth, Async, ChangeTracking, Events, Files, Http, Logging, Moment, Resources, Routing, SignalR, Storage, TimeZone, UI, Url, Users, Utils, Validation};
```
And each of these areas (UI, Account, etc) could have re-export files. So we would need to replace a lot of entries with consts.

Please let me know if you come up with any better workarounds.

**Comment by Victorystick** [comment] 2016-04-14 16:35
@acollard This is an issue that should definitely be fixed; I don't know of any other workaround.

**Comment by Victorystick** [comment] 2016-04-14 19:03
Closing as duplicate of #430.

**Closed by Victorystick** 2016-04-14 19:03 UTC
Labels: bug
