### ISSUE TITLE
Bootstrapping

### ISSUE THREAD

**Issue by SnarkBoojum** [rollup/rollup#1050] opened 2016-10-13 06:53 UTC
I would like to package rollup in Debian, as it is now a build-dep of es6-promise. Unfortunately, I don't know where to start from, as rollup depends on itself!

Could you hint me at how I should proceed?

Thanks,

Snark on #debian-js

**Comment by lucascastro** [comment] 2016-11-23 03:38
A lot of packages have rollup as dependence, i'd be good  some hint about that. 

Thanks, 
Lucas Castro

**Comment by SnarkBoojum** [comment] 2016-11-23 06:05
I have been able to "compile" vlq, magic-string and sourcemap-codec using [es6-module-transpiler](http://esnext.github.io/es6-module-transpiler) which made it possible to get packages.

I'm still fighting with acorn, and no clear idea if that will really get rollup down.

I'm glad I'm not the only one finding that hard -- let's share our ideas!

**Comment by eventualbuddha** [comment] 2016-11-23 19:17
Perhaps you could explain what "packaging rollup for debian" entails? Why not use the usual method of using it via node and npm?

**Comment by SnarkBoojum** [comment] 2016-11-23 19:26
Debian is a system distribution : the usual method is to install Debian packages, which have been built from sources, hence the problem of bootstrapping.

**Comment by lucascastro** [comment] 2016-11-23 22:23
@eventualbuddha like babel team releases package on npm repository, the Debian Package folks provides packages for debian users to easy install by an package management software. But we need to enforce Debian Police and provide all dependence for that software. When we  try get rollup software prepare to get in Debian we run in problem because rollup depends on itself, then who to solve that dependence how will the package management install rollup before install rollup?

Why  provides software by an GNU/Linux distribution as Debian GNU/Linux?
Some software need big deployment,  it's needed to be tested for end users,
so it's needed to be sure the package will be installed with all the workable dependences. 
 when a bug comes up we can easy reproduce the bug and trace, 
work in a solution and contact the uptream for fix.

**Comment by Victorystick** [comment] 2016-12-09 17:59
@SnarkBoojum Why not just clone the repo, run `npm install && npm run build` and grab what's in the `dist/` folder? That's basically how we develop and publish new versions.

Not sure _why_ you'd want to package Rollup in Debian though... You can just `npm i -g rollup`.

**Comment by SnarkBoojum** [comment] 2016-12-09 19:27
Because npm is a distribution, and Debian is another.

And Debian wants to ship the sources of what it contains, not pre-built things, so I need to bootstrap from the sources.

**Comment by Rich-Harris** [comment] 2017-01-07 21:08
Not sure I can see a clean way out of this. Could you create a separate rollup-debian package that included a prebuilt Rollup, then git cloned this repo and built it using the existing build?

How do self-hosting packages normally work in Debian? I can't believe this problem hasn't already been solved somewhere. Is it a technical limitation or an ideological one?

**Closed** 2017-06-21 16:12 UTC
Labels: closed for inactivity, support
