### ISSUE TITLE
RFC: Adopt TypeScript and Prettier

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#1427] opened 2017-06-03 20:23 UTC
The thing that this project needs more than anything is more contributors, because my own schedule basically only permits the odd few hours here and there to work on it. But this is quite an intimidating codebase — even I forget what a lot of the internal APIs look like.

TypeScript could help a lot with that. It could also deter contributors, if they're unfamiliar with it, but when I've asked this question in other contexts people overwhelmingly seem to favour TypeScript.

And now that Prettier supports TypeScript and has a `--use-tabs` option, I'd vote for using that so that we never have to think about code style (since my own preference for jQuery style seems to put me in an ever-dwindling minority).

Any thoughts?

**Comment by bfred-it** [comment] 2017-06-08 03:53
TypeScript could improve code quality but:

1. I feel it's a big undertaking to add it now
2. Contribution count

I'm not sure the switch would accomplish your goal (more contributors, less work for you)

I'm not a fan of Prettier's wrapping, but I agree on using a shared style instead of building your own `eslintrc`. I chose [`xo`](https://github.com/sindresorhus/xo) and it's mostly been good.

**Comment by kzc** [comment] 2017-06-08 12:25
I think Rollup should be written in the same language it operates on - ECMAScript. Changing the implementation language sends the wrong message in my opinion.

Switching to Typescript or any other language wouldn't help increase the number of contributors. It's not a technical barrier, but a willingness barrier. Case in point: https://github.com/rollup/rollup/issues/1275. It was an experiment to see if someone would put together a PR after a patch was created - no one bit. Most people regard software like Babel, Rollup and Uglify as utilities the Internet magically provides - they'll report issues but would never consider creating a pull request. Corporate users of such software complain the loudest in my experience. Ironic that those in the software business value software the least.

The OSS Fridays initiative is a step in the right direction. The companies who benefit from this software ought to contribute.

**Comment by marvinhagemeister** [comment] 2017-06-12 09:08
Agree with @kzc. I don't think moving to TS would make any difference in contributions. The issue is more a culture one and there is not much we can do about it. Of the 80+ developers at work I only know of 3 devs that have contributed in some way to OSS. The way OSS is often treated in companies culturally is that it often is someone else's responsibility to put in the work. Like you described nicely: "...as utilities the Internet magically provides" :S

My personal vote would go to TS nonetheless, because it forces one to think more about the underlying data structure. That's what I found the most difficult when briefly helping with the TS port of svelte. There are a few cases where contradicting data structures are passed to the same function.

**Comment by Kequc** [comment] 2017-07-10 10:07
My experience when bringing existing projects over to TypeScript has been that immediately you see about 50 different problems in the code you didn't know about before. It forces you to write some of it again.

I'm not sure about the implementation timeframe as I am unfamiliar with this code base. But to get the most out of TypeScript you want to the `noImplicitAny` compiler option, which is the biggest time sink, defining everything.

Separately, isn't using tabs in programming illegal?

**Comment by guybedford** [comment] 2017-12-19 16:21
I'd be happy to work on this if there is still interest.

**Comment by guybedford** [comment] 2018-02-10 20:23
TypeScript support has been added and Prettier work is happening in https://github.com/rollup/rollup/pull/1896 😀

**Closed by guybedford** 2018-02-10 20:23 UTC
Labels: discussion
