### ISSUE TITLE
import unused package when input has array inputs

### ISSUE THREAD

**Issue by aelbore** [rollup/rollup#4512] opened 2022-05-27 16:20 UTC
### Rollup Version

2.75.0

### Operating System (or Browser)

MacOSX

### Node Version (if applicable)

16

### Link To Reproduction

https://replit.com/@aelbore/Rollup

### Expected Behaviour

should not add `import "fs"` which is unused on the file
since `fs` was used in `abc.js` it only import on that file

Please see screenshot below

### Actual Behaviour

![Screenshot 2022-05-28 at 12 18 13 AM](https://user-images.githubusercontent.com/18069807/170739103-24e230b7-2c9d-4cc8-8cbb-1db629b252e0.png)

**Comment by Tanimodori** [comment] 2023-03-16 06:45
Duplicate of #4622

**Closed** 2023-03-16 10:51 UTC
Labels: t¹ 🐞 bug, t⁸ ⋅ triage
