### ISSUE TITLE
Rollup ignoring external dependencies with format 'system'

### ISSUE THREAD

**Issue by harimambura** [rollup/rollup#2857] opened 2019-05-14 07:51 UTC
- Rollup Version:1.11.3
- Operating System (or Browser): Win10 Chrome 74
- Node Version: 10.15.1

### How Do We Reproduce?

I have 'Inferno' library as global variable on window, use babel for transpile JSX syntax and set to rollup.config external and global variables for this case.

```
const rollupBabel = require('rollup-plugin-babel');
const babelConfig = require('./babel.config');

module.exports = {
	input: ['main.js'],
	external: ['inferno'],
	plugins: [
		rollupBabel(babelConfig)
	],
	output: [
		{
			dir: './bundles/',
			format: 'system',
			globals: {
				'inferno': 'Inferno'
			},
			sourcemap: true
		},
	],
};
```

In 'iife' format everything works fine, rollup skips Inferno and don't try to resolve this dependency, but with format 'system' compiled bundle contains inferno as module that needs to be resolved and cuts 'Inferno.' from code.

```
// example with 'system' format
System.register(['inferno'], function (exports, module) { // here inferno is like module
	'use strict';
	var createVNode;
	return {
		setters: [function (module) {
			createVNode = module.createVNode;
		}],`

```
```
// example with 'iife' format
var bundle = (function (inferno) {
	'use strict';

	function span() {
	  return inferno.createVNode(1, "span", null, "text", 16);
	}

	return span;

}(Inferno)); // inferno using as external dependency

```
I provided link with working example below.

https://github.com/harimambura/rollup_systemjs_bug
### Expected Behavior
External dependencies described in rollup config are not ignored, bundle generates with no external modules

### Actual Behavior
External dependencies are ignoring, bundle has globals as modules

**Comment by lukastaegert** [comment] 2019-05-27 05:57
So if I understand you correctly you expect there to be no imports in the SystemJS file because you used the `globals` option. The `globals` option, however, is only observed by IIFE and UMD bundles (and by UMD bundles only if they are not used in a Node or AMD context). All other formats ignore the `globals` option because in those formats, `external` means exactly what you see here, i.e. the module is imported by the wrapper.

In a way, this is a duplicate of #2374. @eight04 wrote a plugin to address this, check out [rollup-plugin-external-globals](https://github.com/eight04/rollup-plugin-external-globals)

**Comment by shellscape** [comment] 2019-08-15 14:39
Closing citing duplicate issue. Please see previous reply.

**Closed by shellscape** 2019-08-15 14:39 UTC
Labels: x³ ⋅ duplicate
