### ISSUE TITLE
TypeError: Cannot read property 'DomHandler' of undefined

### ISSUE THREAD

**Issue by tmos** [rollup/rollup#1674] opened 2017-10-12 19:49 UTC
Hi,

My repo is here : https://github.com/tmos/cowtest
On the "rollup" branch, install dependencies and run rollup with the config.

At bundle execution, I get :

```
[...]/dist/index.js:8405
var DomHandler$1 = lib.DomHandler;
                      ^

TypeError: Cannot read property 'DomHandler' of undefined
    at Object.<anonymous> ([...]/dist/index.js:8405:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

I don't have any idea where it can come from, I'm totaly new to rollup.
Do someone have any idea were it may come from ?

Thanks,
Tom

**Comment by TrySound** [comment] 2017-10-12 20:20
@tmos There's no rollup brunch in your repo.

**Comment by tmos** [comment] 2017-10-12 21:05
meh... my bad. Here it is!

**Comment by tmos** [comment] 2017-10-20 14:08
Is there any way I can help on this issue ? I'm not sure I have the knowledge to dig into rollup, but would be glad to help!

I'm kinda stuck because of the impossibility to bundle my project I have to admit...

**Comment by nickmanning214** [comment] 2017-11-06 23:48
I'm having the same issue, trying to include cheerio in my rollup project.

**Comment by lukastaegert** [comment] 2017-11-07 06:22
Hi @tmos, @nickmanning214,

sorry to keep you waiting. It seems the core of the issue is a circular dependency in one of cheerio's dependencies, htmlparser2 (cheerio is also a dependency of dandy-crawl). Basically, `htmlparser2/lib/index.js` requires `htmlparser2/lib/FeedHandlerjs` and vice versa. This conflicts with rollup's scope hoisting as it does not know which module to run first.

I do not think we will be able to provide a good solution for this soon. A similar issue is e.g. #1507. Maybe it is possible to make cheerio or dandy-crawl an external dependency? Sorry I have no better news for now.

**Comment by tmos** [comment] 2017-11-23 16:32
Thanks, I created an issue on the repo of htmlparser2, and I will on cheerio if they don't answer !
I guess we can close the issue here as it's not directly on rollup ?

**Comment by guybedford** [comment] 2018-02-10 20:34
Marking as a duplicate of https://github.com/rollup/rollup/issues/1507.

**Closed by guybedford** 2018-02-10 20:34 UTC
Labels: bug, scope-hoisting
