### ISSUE TITLE
Compilation hangs

### ISSUE THREAD

**Issue by jacarma** [rollup/rollup#2729] opened 2019-02-28 09:00 UTC
- Rollup Version: 1.3.2
- Operating System (or Browser): macOS Sierra 
- Node Version: 8.10.0, 9.11.2 and 10.15.1

### How Do We Reproduce?

```
git clone https://github.com/jacarma/with-recharts.git
cd with-recharts
yarn
```

This project has been generated with `npx create-react-library` with default options. Then added a dependency to [recharts](https://github.com/recharts/recharts). Then updated all dependencies to latest versions.

### Expected Behavior

Build process completes successfully.
Alternatively: build fails and an error message point to what is wrong.

### Actual Behavior

Build never ends, no error messages appear 
```
> yarn build
yarn run v1.12.1
$ rollup -c

src/index.tsx → dist/index.js, dist/index.es.js...
```

**Comment by TrySound** [comment] 2019-02-28 09:17
This problem is fixed in the latest rollup version.
/cc @transitive-bullshit

**Comment by jacarma** [comment] 2019-02-28 15:09
I'm testing with the 1.3.2 and still doesn't work. Is there a newer version?

Thanks a lot

**Comment by lukastaegert** [comment] 2019-02-28 15:19
I can confirm your repro is hanging during its third tree-shaking run. Probably something we missed. Will see if I can figure it out.

**Comment by lukastaegert** [comment] 2019-02-28 16:33
I actually identified the issue. So it is not an infinite loop but rather an exponential performance degradation when handling nested property calls. You can check it out for yourself by increasing/decreasing the number of .concat() here: https://rollupjs.org/repl?version=1.3.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMHRyeSUyMGNoYW5naW5nJTIwdGhlJTIwbnVtYmVyJTIwb2YlMjAuY29uY2F0KCd4JyklNUNudmFyJTIweCUyMCUzRCUyMCd1JyU1Q24lNUN0LmNvbmNhdCgneCcpJTVDbiU1Q3QuY29uY2F0KCd4JyklNUNuJTVDdC5jb25jYXQoJ3gnKSU1Q24lNUN0LmNvbmNhdCgneCcpJTVDbiU1Q3QuY29uY2F0KCd4JyklNUNuJTVDdC5jb25jYXQoJ3gnKSU1Q24lNUN0LmNvbmNhdCgneCcpJTVDbiU1Q3QuY29uY2F0KCd4JyklNUNuJTVDdC5jb25jYXQoJ3gnKSU1Q24lNUN0LmNvbmNhdCgneCcpJTVDbiU1Q3QuY29uY2F0KCd4JyklNUNuJTVDdC5jb25jYXQoJ3gnKSU1Q24lNUN0LmNvbmNhdCgneCcpJTVDbiU1Q3QuY29uY2F0KCd4JyklNUNuJTVDdC5jb25jYXQoJ3gnKSU1Q24lNUN0LmNvbmNhdCgneCcpJTVDbiU1Q3QuY29uY2F0KCd4JyklNUNuJTVDdC5jb25jYXQoJ3gnKSU1Q24lNUN0LmNvbmNhdCgneCcpJTVDbiU1Q3QuY29uY2F0KCd4JyklNUNuJTVDdC5jb25jYXQoJ3gnKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

I will check if there is some possibility to address this via caching or similar.

**Comment by lukastaegert** [comment] 2019-02-28 17:15
Thanks so much for this issue! As it turned out the fix was rather simple and a small oversight in one place of the code. Please check out if #2732 works for you (i.e. `npm install rollup/rollup#gh-2729-fix-call-performance-regression`).

**Comment by lukastaegert** [comment] 2019-02-28 17:16
Should be a nice performance improvement for everyone.

**Comment by lukastaegert** [comment] 2019-02-28 17:17
Thanks especially for the nice repro, that was key to finding the cause!

**Closed** 2019-03-01 05:24 UTC
Labels: bug, has PR

**Comment by jacarma** [comment] 2019-03-01 08:02
Thanks a lot for such a quick fix! I'll try it out in a few minutes.

**Comment by jacarma** [comment] 2019-03-01 08:54
It works nicely in v1.3.3 thanks again.
