### ISSUE TITLE
methods not treeshaken

### ISSUE THREAD

**Issue by hbrls** [rollup/rollup#588] opened 2016-04-04 08:45 UTC
I'm trying to make a subset of the Modernizr. And the output is:

```javascript
(function () {
  'use strict';

  ...

  var ModernizrProto = {
    
    on: function(test, cb) {
      ...
    },

    addTest: function(name, fn, options) {
      tests.push({name: name, fn: fn, options: options});
    },

    addAsyncTest: function(fn) {
      tests.push({name: null, fn: fn});
    }
  };

  var Modernizr = function() {};
  Modernizr.prototype = ModernizrProto;

  Modernizr = new Modernizr();

  var Modernizr$1 = Modernizr;

  Modernizr$1.addTest('promises', function() {
    ...
  });

}());
```

The `addAsyncTest` is never used but not removed. Am I misunderstanding what you mean by treeshaking?

How can I manually flag it to be removed?

**Comment by Victorystick** [comment] 2016-04-04 08:49
Closing as duplicate of #349.

**Closed by Victorystick** 2016-04-04 08:49 UTC

**Comment by hbrls** [comment] 2016-04-04 08:57
@Victorystick Thanks for that ref.

> Unfortunately, traditional modules – CommonJS and AMD – result in code more like the second example than the first, making them next-to-impossible to optimise. Rather than excluding dead code, we should be including live code (aka 'tree-shaking'). That's only possible with ES6 modules.

The document led me wrong. I was imaging that Rollup has some dark magic than Webpack.

**Comment by Victorystick** [comment] 2016-04-04 09:11
The emphasis here is _ES6 modules_ and the statically analysable imports and exports, not ES6 classes unfortunately. I would say that Rollup currently has more magic than Webpack in regards to tree-shaking, but none of it is black. :stuck_out_tongue_winking_eye:
