### ISSUE TITLE
Rollup 0.35.4 - tree shaking too agressive

### ISSUE THREAD

**Issue by ghost** [rollup/rollup#921] opened 2016-09-10 23:42 UTC
Hi! Rollup now removes code I actually use, or have added to improve performance.

Original code (_simplified_)

``` js
function isType(x) {
    // loads of if else down here to quickly check for some types
 if (x === null) {
        return 'null';
    }

     if(x === 'string') {
            ....
     }
    var typeofObj = typeof x;
    if (typeofObj !== 'object') {
        return ....
};
```

After bundling with latest Rollup, I sit back with this

``` js
var isType = function (x) {
    var typeofObj = typeof x;
    if (typeofObj !== 'object') {
        return typeofObj;
@@ -274,7 +368,7 @@ function isType (x) {
        .call(x)
        .slice(8, -1)
        .toLowerCase();
}
```

In the main function I have at leat 8 different if -else and they are all gone now. Maybe not a big issue, but I also in the same code try to validate if a feature exist, but the validation code is gone too!!!

**Comment by Kflash** [comment] 2016-09-10 23:50
Here is one feature detection check that got removed with latest Rollup:

```js
 if (typeof WeakMap !== 'undefined' && objPrototype === WeakMap.prototype) {
        return 'weakmap';
    }
```

**Comment by Rich-Harris** [comment] 2016-09-11 00:19
Argh! Whoops, sorry. Can you reproduce it on http://rollupjs.org/ ? It *might* have been fixed since, but probably not...

**Comment by Kflash** [comment] 2016-09-11 00:24
I just tried it with 0.35.6 and it's working now as expected.  Except my bundle jumped from 717 lines to now 900 lines.  Probably not Rollup's fault, but I noticed functions now are turned into variabels?

**Comment by Rich-Harris** [comment] 2016-09-11 00:27
Previously `var foo = function () {...}` would be turned into `function foo () {...}`, which is *technically* incorrect (different hoisting behaviour etc) – probably harmless, but I didn't think it was worth reinstating that behaviour after the rewrite. Open to persuasion if anyone feels strongly about it.

Curious about the increase in LOC – if it does turn out to be Rollup's fault (entirely possible, the tree-shaking logic was basically rewritten from scratch) then please let us know

**Comment by Kflash** [comment] 2016-09-11 00:35
Compared between 0.34.13 and 0.35.6 and seems to be partly Rollup's fault regarding LOC increasement (*32 lines in difference*), but I suspect Acorn 4.x to be the one to blame here.

**Comment by Rich-Harris** [comment] 2016-12-27 22:46
I'll close this as there have been a number of improvements to the treeshaking since 0.35, but please reopen with a repro if there are still things that aren't behaving correctly

**Closed by Rich-Harris** 2016-12-27 22:46 UTC
