### ISSUE TITLE
Webpack / Browserify integration

### ISSUE THREAD

**Issue by franleplant** [rollup/rollup#338] opened 2015-12-02 01:01 UTC
Hi!
    First of all let me tell you that is module is **awesome** thanks a lot for your work!
The second thing I thought after reading about it was:

> Can I integrate this to my existing Webpack build?

So, can this be integrated to Webpack or Browserify existing builds? It'll be amazing!

Thanks!

**Comment by mstade** [comment] 2015-12-03 01:24
Seems a bit odd to integrate a linker with another linker, no? :o)

Anyway, what I do is to use rollup as a pre-compile step, something like so:

```sh
rollup in.js | babel --presets 2015 > out.js
```

Substitute `babel --presets 2015` in that flow with `browserify -t babelify` and you might achieve the same. Certainly, you could probably write a webpack plugin or browserify transform to achieve the same, if there isn't one already.

**Comment by franleplant** [comment] 2015-12-03 01:34
Thanks! I'd like to set some time apart to dig into this, webpack and browserify could benefit greatly from this library, any pointers where to start?

**Comment by mstade** [comment] 2015-12-03 01:47
I'm not sure what the benefit would be – rollup bundle files together, and browserify and webpack... bundle files together. Sorry, I'm too stupid to get it :o)

Anyway, [the wiki](/rollup/rollup/wiki) is a pretty good place to get started.

**Comment by franleplant** [comment] 2015-12-03 03:10
The main benefit will be optimizing the way those bundlers bundle the files
in the same way rollup does it :)

What is the difference between rollup and the rest of the module bundlers?
It's optimization!

**Comment by Victorystick** [comment] 2015-12-04 11:17
If you cannot bundle all your dependencies using Rollup, we recommend bundling as much as possible into a CommonJS module and let Browserify/Webpack/something-else take it from there. If CommonJS modules are what you need, I suggest taking a look at [rollup/rollup-plugin-commonjs](/rollup/rollup-plugin-commonjs).

Closing as a duplicate of #219.

**Closed by Victorystick** 2015-12-04 11:17 UTC
Labels: duplicate

**Comment by Victorystick** [comment] 2015-12-04 11:22
If you cannot bundle all your dependencies using Rollup (if you depend on some special transform/loader), we recommend bundling what you can and then let Webpack/Browserify finish the job. If all you need is support for CommonJS, may I suggest that you take a look at [rollup-plugin-commonjs](/rollup/rollup-plugin-commonjs). If it's something else, why not [create your own plugin](https://github.com/rollup/rollup/wiki/Plugins)?

Closing as a duplicate of #219

**Comment by franleplant** [comment] 2015-12-04 13:29
Thanks a lot Ill take a look and see what I can do
