### ISSUE TITLE
Too much setup friction

### ISSUE THREAD

**Issue by axefrog** [rollup/rollup#905] opened 2016-09-08 09:15 UTC
When I decided to give Rollup a go, I assumed it was going to be simple and straightforward to get working. On the contrary, trying to get it to work with a few standard npm-installed modules has proved to be a constant stream of seemingly-unresolvable errors. I tried to include the required plugins as per examples I found for loading npm modules and such, but to no avail.

First I floundered around trying to get internal modules to load. "import Foo from '../foo'" kept failing, complaining that it couldn't resolve it, or something like that. I guess it didn't know how to add the "index.js" bit to the path, so then I looked around and discovered that I should be using the node.js plugin, which didn't seem to relate to this particular error, but it seemed to let me move on...

"[snip]node_modules\@cycle\most-run\lib\index.js does not export default"

In fact it does, and other loaders have no problem with it. I looked inside the installed package and there was the last line: `exports.default = "......."`. I couldn't find any configuration options in the commonjs or node plugins that indicated what I might be doing wrong.

"Could not resolve 'most' from [snip]\node_modules\most-subject\lib\index.js"

And yet there it was in the node_modules folder, and working fine with other bundlers.

I'm using TypeScript 2.0, and I was wanting to compile it to pure ES6 with imports, then have rollup do the rest. The TypeScript side of things works fine and gives me a bunch of js files with clean import statements, ready for compiling by Rollup. However, given that I can't seem to get Rollup to "just work", I next thought of trying the Rollup TypeScript plugin, but it looks like that one wants to install TypeScript 1.8 internally and then have me install another version of TypeScript after the fact.... ugh... I give up, that's enough.

I don't know if Rollup is supposed to be easy to get going, but maybe my frustration can be taken as feedback as to the user experience that I'm sure at least some other people must be experiencing right now as well. Maybe it's just me. I'm going to go back to using Webpack for now though.

**Comment by jonataswalker** [comment] 2016-09-08 09:58
Maybe you this [example-project](https://github.com/jonataswalker/es6-sample-project) can help you with the initial setup.

**Comment by snuggs** [comment] 2016-09-08 20:39
@axefrog Working that out in a simple convention wrapper. Writing a couple blog posts about the matter as well.

Until then happy to help with any setup issues you may have.

**Comment by bfred-it** [comment] 2016-09-14 06:08
This would be a good use case for [shareable configs](https://github.com/rollup/rollup/issues/736)

Something like `rollup-config-typescript` could be created and used as a starter configuration.

**Comment by bitjson** [comment] 2017-02-18 17:01
@axefrog (and anyone else landing here looking for Typescript -> ES6 & Rollup) – please check out:

### [typescript-starter](https://github.com/bitjson/typescript-starter)

That repo includes a demo of how to use async/await downleveling, compile to ES6, and [bundling with Rollup](https://github.com/bitjson/typescript-starter/blob/master/examples/browser/rollup.config.js).

**Comment by jhabdas** [comment] 2017-03-20 18:33
Stale. Also, there are other open issues covering the doc needs. This should be closed.

**Comment by bfred-it** [comment] 2017-06-21 15:54
Closing as duplicate of #385

**Closed by bfred-it** 2017-06-21 15:54 UTC
Labels: dev-x
