### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#372] opened 2015-12-22 17:28 UTC
Previously: #120.

Probably not going to happen any time soon, but at some point it would be nice to add support for code-splitting, i.e. finding the common dependencies of `a.js` and `b.js` so that you can do this sort of thing...

``` html
<!-- a.html -->
<script src='shared.js'></script>
<script src='a.js'></script>

<!-- b.html -->
<script src='shared.js'></script>
<script src='b.js'></script>
```

...and let visitors to `b.html` who have already been to `a.html` use a cached copy of `shared.js` (_mutatis mutandis_ for client-side routing situations with an asynchronous module loader).

First hard question is what the API looks like – my initial thought is that if you specify _x_ entry points you should get _x+1_ bundles back, where the _+1_ is the shared code. Very easy to grok and probably meets most use cases, but not as flexible as some other approaches.

Anyway I'll just leave this here for now.

**Comment by thisconnect** [comment] 2015-12-22 20:39
I'd love to have control over what is shared. I.e `b.html` and `c.html` may share a large part, that I don't want to have in. I belive that people usually like to decide what should be shared and whatnot.

**Comment by thisconnect** [comment] 2015-12-31 12:45
Related to automatic finding common dependencies, I am currently trying to setup 2 configs to manually control what goes in the shared common lib and what goes into app.

- app1.js
- common/
  - index.js
  - moduleA.js
  - moduleB.js

Trying to keep it as simple as possible, my approach is currently to build 2 iife one as a lib and the app importing from the lib (common/index.js).

common/index.js
```javascript
export * from './moduleA.js';
export * from './moduleB.js';
```
Is there a better way to export all shared modules, than listing all modules and `export * from`? 

app1.js
```javascript
import Lib from './common/index.js';
```

The lib build works fine (entry `common/index.js`, moduleName `Lib`),
but I can't find a way to exclude the Lib from app.

I am not sure if this approach should be working at all or if it would make sence to put all common code into its own node module, see #401

**Comment by Victorystick** [comment] 2015-12-31 17:14
`common/index.js` should probably export it's submodules' namespaces,
```js
import * as moduleA from './moduleA.js';
import * as moduleB from './moduleB.js';

export { moduleA, moduleB };
```

And then in `app1.js` import,
```js
import { moduleA, moduleB } from './common/index.js';
```

And hack together a plugin that will ensure that `./common/index.js` isn't included in the bundle. I think that should be possible.

**Comment by thisconnect** [comment] 2015-12-31 17:52
Hey, great. But do you recon that this approach is good? One disadvantage would be that index.js would just contain everything and would not have any knowledge of what is actually needed.

I introducted index.js just for the need of an entry entry point. Actually I'd rather like to use the app entry point and filter afterwards everything ouside the modules/ AST tree. Do you think this approach would be better?

**Comment by thisconnect** [comment] 2016-01-01 11:50
I am going to try a separate common node module, which should keep things simpler. Since I want it as simple as possible anyway :)

**Comment by Victorystick** [comment] 2016-01-01 14:29
That might be a good idea, until we figure out how best to do this. :+1:

**Comment by therealklanni** [comment] 2016-01-16 23:30
Possibly related, I was just trying to figure out if Rollup supports multiple outputs. I figured to do this I would have to configure multiple separate builds (:frowning:) and use `excludes` to enforce not bundling my internal lib into the main bundle file (to be required/imported). But in my experimenting it seems that the `exclude` option doesn't prevent my internal lib from being rolled into the main bundle file.

**Comment by thisconnect** [comment] 2016-01-17 09:55
hi, I'd like to share my current setup for manually splitting code into a shared library and app.

https://gist.github.com/thisconnect/c5b3cb626953dd3b0001

At this point I am still not 100% about the correct order of the npm, commonjs and babel plugins :)
but nevertheless this seems to work, using an lib entry point.

**Comment by therealklanni** [comment] 2016-01-17 23:49
Thanks @thisconnect, I think this will be helpful for me :+1:

**Comment by thisconnect** [comment] 2016-01-21 09:03
This issue by @Rich-Harris was more about automatic code splitting and got a bit hijacked to manual code splitting. Maybe rename this issue to manual code splitting and open a new one for auto code splitting?

**Comment by shannonmoeller** [comment] 2016-04-13 16:24
This is the only feature keeping me from adopting rollup. Manual splitting isn't an option as it forces all of my modules (and dev team members) to be aware of the code splitting.

Has work been started? I'd love to contribute. Super looking forward to this feature so I can drop browserify and factor-bundle.

**Comment by AndrewIngram** [comment] 2016-08-15 23:06
I'm wondering if there's a way to define rollup "boundaries" (for lack of a better term) as config. So that rollup doesn't do anything to imports at the boundaries, leaving them for something like webpack to handle as a second pass.

**Comment by tivac** [comment] 2016-08-18 06:43
I started looking at this a bit, it's not possible to achieve via plugin w/ existing hooks but a naive implementation seems almost doable.

I started futzing with this as a plugin: https://github.com/tivac/rollup-plugin-bundles

The first sticking point I've found is that the [`ongenerate` hook runs after output is generated](https://github.com/tivac/rollup-plugin-bundles/blob/master/index.js#L39-L41). It makes sense given the name but means that `ongenerate` doesn't work for the purpose I was hoping to use it for. Based on looking at `Bundle.js` it looks like the `transformBundle` hook would also be too late, hrmph 😒 

I'm sure that even if I hack up rollup to add an `onbeforegenerate` hook (ugh that name) I'll find some issues w/ my first-pass plan, which is just to yank the modules w/ multiple deps out of the `Bundle` instance.

**Comment by tivac** [comment] 2016-08-18 07:00
Well, I did what I promised and hacked up `rollup.js` to add an `onbeforegenerate` hook. If I splice the shared module out of the `bundle.orderedModules` it seems to generate mostly-correct code. Haven't checked the map yet.

Still a ways to go on how to turn the array of removed `Module` instances into actual usable code.

https://github.com/tivac/rollup-plugin-bundles/commit/7544cd84d2c51a976c16b7d29b6047d2d128c840

**Comment by tivac** [comment] 2016-08-18 07:12
Urge, spoke too soon. Late now but tomorrow I'll detail all the ways this plan won't work :sad:

**Comment by tivac** [comment] 2016-08-18 17:11
#### Issues

1. I'm currently using `rollup-plugin-multi-entry` to get multiple files into `rollup`, but that only supports multiple inputs -> one output.
2. The hooks aren't available to plugins to modify the `Bundle` instance before the bundle is generated (https://github.com/rollup/rollup/issues/372#issuecomment-240640453)

So it seems like for this to be possible `rollup` would need to natively support multiple inputs that map to multiple outputs, otherwise there's going to need to be some serious `Bundle` editing going on to extract shared modules or modules that are part of a specific input and then generating new `Bundle` instances for them to take advantage of code generation.

Or maybe I just don't know `rollup` well enough yet and I'm missing something obvious. I'll take another look at this in a bit.

**Comment by tivac** [comment] 2016-08-19 23:53
Decided to tackle Issue 1 first, because after looking at `rollup.js` it seems simple. I'll know for sure once I write some tests, but here's my first crack at it.

https://github.com/tivac/rollup/commit/f489050901d1117e2ebf5dc1cc4538414efddafc?w=1

**Comment by snuggs** [comment] 2016-08-20 01:58
The `rollem` project currently supports this feature @tivac. Possibly leaves us only with #2?

https://github.com/bahmutov/rollem

A tad slow but we'll fix that and delegate the watcher to rollup (if possible).

Then we get into the manual/automatic discussion (again). However have to start somewhere. Or we'll be talking about this for another 9 months. VERY interested in this and look forward to helping.

**Comment by tivac** [comment] 2016-08-20 05:24
@snuggs `rollem` could work, I'd rather it was integrated into `rollup` proper though so code splitting didn't depend on a brittle dance of getting multiple plugins installed in *just* the right order.

**Comment by shannonmoeller** [comment] 2016-08-20 13:53
I agree that this would be best at the rollup level. It seems like there are a couple ideas happening here:

1. N to 1
2. N to N
3. N to N+1

My understanding was that the OP is about 3, but the rollem functionality is 2. Am I correct that this issue is about 3?

**Comment by snuggs** [comment] 2016-08-20 17:08
@shannonmoeller  correct!
1. is satisfied by `rollup-plugin-multi-entry` https://github.com/rollup/rollup-plugin-multi-entry
2. is satisfied by `rollem`

I'm kinda with @TrySound on this one. I feel we are already at the tipping point of SRP (Single Responsibility Principle) for `rollup`. If anything it's in a space where internal features can be exposed via the public API. (i.e. `FileWatcher` https://github.com/rollup/rollup-watch/blob/master/src/index.js#L10-L39)

That "needing an additional API" pain is a great pain to have for a project that's growing. Should always push back until YAPA (Yet Another Public Api) is a last resort. This will encourage the plugin ecosystem.

**Comment by bfred-it** [comment] 2016-08-21 04:06
Config-based splitting is a pain though. I like webpack's approach with `require.ensure`, which not only automatically creates new bundles, but also doesn't burden you with naming and loading each one (i.e. it embeds require.js-like functionality for async loading)

Essentially to create multiple bundles you just need this:

```js
import _ from 'lodash';
var its = my(main, 'bundle');

require.ensure([], () => {
  import 'jquery';
  $('.this').is('bundle.1.js');
});

**Comment by snuggs** [comment] 2016-08-21 16:01
Correct me if i'm wrong @bfred-it but wouldn't custom syntax be outside the scope of rollup?

**Comment by tivac** [comment] 2016-08-21 18:25
I don't want rollup to provide async module loading, certainly. Plenty of solutions for that already.

**Comment by bfred-it** [comment] 2016-08-22 02:50
@snuggs maybe it is expensive to maintain (linters and such), but it'd be a nice option.

@tivac yes, but are those solutions as efficient as rollup? The difference between loading "shared.js" and "a.js" via `script` tag and loading the latter dynamically is literally a few lines of code (or a nano module)

**Comment by Swatinem** [comment] 2016-08-31 08:49
Hm, I tried doing something like this by defining one of my internal source files inside `externals`, or creating a custom plugin that returns `false` inside `resolveId`.

Both result in a `Could not resolve` Error, so no luck there :-(

**Comment by Rich-Harris** [comment] 2016-09-02 14:15
@Swatinem external paths need to either be a package ID or a fully resolved path:

```js
// NOT this
external: [
  'src/some/file.js'
]

// this
external: [
  path.resolve( 'src/some/file.js' )
]
```

That might work?

@bfred-it there is an equivalent of `require.ensure` for ES modules, though I'm not entirely sure what it is – for a long time it was `System.import(...).then(...)` but I think that might have changed? (As ever, @guybedford probably knows best 😀 ) I think there's something to be said for marking large shared dependencies as such though, so that you can import `React` or whatever from multiple places without having to do the async dance. Definitely don't want to get into custom syntax, that way madness lies.

@tivac 

> I don't want rollup to provide async module loading

Me neither. I wonder if it could be done via a (officially supported) plugin somehow though.

**Comment by bfred-it** [comment] 2016-09-02 14:47
Agree on it being a plugin, I wouldn't mind doing that if it takes care of itself (i.e. as little config as possible)

Sure, `System.import` would be great, as long as you're ok with the semantic being different. 

`require.ensure` doesn't actually necessarily import anything. You can use it like an AMD loader and get the resulting imports as parameters, or say `require.ensure([/*nothing*/], callback)` and webpack will automatically find whatever requires are in the callback and its dependents.

Essentially this should be possible:

```js
System.import('').then(() => {
    import _ from 'lodash';
    // more code
    // this whole block and lodash should be in its own file
    // (unless lodash is shared. I'm not sure how webpack handles that)
})
```

**Comment by mindeavor** [comment] 2016-10-15 22:44
What's the current status of this issue?

**Comment by corysimmons** [comment] 2016-10-22 16:54
Yeah, could someone please give us a TL;DR of the thread above and mention if anyone is currently working on this?

**Comment by DonGissel** [comment] 2016-11-24 08:48
I don't have the need for multiple payloads yet, but that day will come soon. My problem is that I'm using `rollup-stream` (yeah yeah, I know that wrappers are both frowned upon and discouraged) in order to fit rollup into a stream-based pipeline – otherwise known as Gulp – and I don't know how it would handle Rollup itself (or a plugin) suddenly adding a separate output stream to the fray. Of course that'd be up to the author of `rollup-stream` to fix, but still. I know I'm going off on a tangent, but use cases like mine do exist. And I'm betting smarter people than I can think of a solution.

**Comment by lukeed** [comment] 2016-11-30 18:26
I'd consider this a high priority, considering that it's really the only feature that lacks when comparing to Webpack.

**Comment by tivac** [comment] 2016-11-30 18:27
My work on this stalled out, fighting w/ the `Bundle` object wore me down. I'd still like to do it but I'm not actively hacking on it any longer. 😞

**Comment by lukeed** [comment] 2016-11-30 18:31
@tivac No worries. Thank you for giving it a good try!

**Comment by snuggs** [comment] 2016-12-08 13:14
@Rich-Harris @Victorystick #ping #restlessNatives 👆

**Comment by thisconnect** [comment] 2017-02-18 08:52
`import()` is coming, would that be the way to go?

stuff being imported by `import()` could be rolled up separatelly with it's own entry/dest path what do you think about that?

**Comment by Pauan** [comment] 2017-02-18 17:10
To clarify for anybody who is confused, @thisconnect is referring to [this](https://github.com/tc39/proposal-dynamic-import).

It is at stage 3 (candidate), which means that it's accepted, but not implemented yet.

Babel [has some preliminary support for it](http://babeljs.io/docs/plugins/syntax-dynamic-import/), but I don't think Acorn supports it at all (yet).

**Comment by PaulBGD** [comment] 2017-02-24 08:13
I'm currently working on this, but I'm curious what types of code splitting people need.
Is it just splitting code into multiple pages then a common chunk, like webpack does [with this plugin](https://webpack.js.org/plugins/commons-chunk-plugin/)?

**Comment by lukeed** [comment] 2017-02-24 08:23
@PaulBGD Yes, imo. And I personally would forgo a "runtime" that loads/imports the chunks because there are already so many options for this. If worried, injecting a runtime would make for a great plugin.

**Comment by tv-brendan-jefferis** [comment] 2017-03-02 00:34
The use case I was interested in was multi-page apps such as .NET MVC where each page makes a call to the server and has its own JS bundle - so a rollup config that supports multi-in multi-out would be necessary for this.

I'd like to be able to structure the JS in my app something like this:


    dist/
      ├─ app.js          // shared code
      ├─ products.js     // code for the Products page
      ├─ account.js      // code for the Account page
      └─ settings.js     // code for the Settings page

    src/
      ├─ app/
      │    ├─ appModules/
      │    │    ├─ logger.js
      │    │    ├─ polyfill.js
      │    │    └─ ... etc
      │    └─ app.js    // entry point for shared, app-level code
      │
      ├─ components/
      │    ├─ modal.js
      │    ├─ grid.js
      │    ├─ product-card.js
      │    └─ ...etc
      │
      └─ pages/
           ├─ products.js    // entry point for Product page - imports from components
           ├─ account.js     // ... etc
           └─ settings.js

**Comment by PFight** [comment] 2017-03-02 20:17
Background and use case for this comment can be found there: [1170](https://github.com/rollup/rollup/issues/1170)
@tivac, looks like main problem is multi-out. How about temporary solution like this:

1.  Run roollup to make common bundle
2.  Run rollup once for every application part bundle

The second step is already can be performed with "external" option. We just exclude common parts. The first step can be implemented as special option "include", that contains list of modules or fucntion (like "external"). If this option specified, we simple remove from the result bundle code from modules, that do not math any of included modules (i.e. code of entry point can be also elliminated, if it has not included).

Later, when multi-output will be added, we can add to config something like this, and do not run rollup many times:

    out: [
        { name: "vendor", include: [ ... ], external: [...] },
        { name: "common", include: [ ... ], external: [...] },
        { name: "account", include: [ ... ], external: [... ] }
    ]

**Comment by wagerfield** [comment] 2017-03-12 15:10
@PFight I was thinking the same thing, but with a slightly different API. 

Rather than deferring the splitting configuration to the _out_ stage when generating/writing bundles, make it apart of the config passed to `rollup()`. 

Now, in order for this to work Rollup would need to adopt a couple of things that are familiar to those who have used webpack. Firstly, each bundle would need a `name`. Secondly when generating/writing bundles, special placeholder strings would be used in the `dest` value. These placeholders would then be replaced when generating/writing bundles: `bundle.dest.replace('$name', bundle.name)`.

A revised version of the API might look like this:

```js
var rollup = require( 'rollup' );

rollup.rollup({
  name: 'app', // new required field per bundle (when code splitting)
  format: 'umd',
  entry: 'src/index.js',
  dest: 'dist/$name', // $name would be 'app' and 'vendor' here. File ext should be inferred IMO
  split: [{ // an array of 'chunks' to split the entry into
    name: 'vendor',
    include: /node_modules/, // anything in node_modules would be consumed by the vendor chunk
    exclude: 'react', // exclude would negate matches
    format: 'commonjs' // any inherited config values could be overridden in chunks
  }]
}).then((bundle) => {
  // bundle would have a 'name' property that could be used here 
  if (bundle.name === 'vendor') {
    // options passed here are optional and would override config
    bundle.write({
      dest: 'dist/vendor.js'
    })
  } else {
    bundle.write() // ...but no need to specify an object if you don't want to :)
  }
})
```

**Comment by PRR24** [comment] 2017-03-28 13:54
I would like to propose another way to manually define components -- by defining  component dependency tree.. Smth like that:
{
  modules: [
    {
      id: "main", // module name (for future reference)
      entry: 'src/main.js',
      dest: 'dist/app.bundle.js', // will contain all the needed stuff from main.js point of view
      dontStrip: ["node_modules/@angular/http/*"] // will keep and export http for "lazy" even though it is not needed for "main"
    },
    {
      id: "lazy",
      entry: 'src/components/lazy.js',
      dest: 'dist/lazy.bundle.js', // will contain all the needed stuff from lazy.js point of viev except what is already available in app.bundle.js
       dependencies: ["main"] // this declares, that the module will use available components from "main" and repeated ones can be discarded from "lazy"
    },
    ...
  ]
}

I think such definition tree would give Rollup all the means to build up the optimal dependency graph for shaking.

Later on, lazy.bundle.js can be directly includer in the index.html or lazyloaded by (not yet existing) Rollup plugin or by some other means.

**Comment by shannonmoeller** [comment] 2017-03-29 13:22
This thread has once again diverged into manual configuration when the original topic was automatic code splitting. See:

https://github.com/rollup/rollup/issues/372#issuecomment-173505606
https://github.com/rollup/rollup/issues/372#issuecomment-241201390
https://github.com/rollup/rollup/issues/372#issuecomment-241211861

@Rich-Harris Can we shut down this issue and open two others? One for manual and one for automatic?

**Comment by PaulBGD** [comment] 2017-03-29 14:48
@shannonmoeller Well actually I think the first course of action is implementing an API that even allows for multiple bundles to be outputted.

**Comment by PFight** [comment] 2017-03-29 18:48
@shannonmoeller how do you imagine automatic splitting? Splitting has any meaning only if you know, what parts of the application will be in every part, so you can lazy load it as they needed. How this work can be done without specifying what every part should contain?

**Comment by DonGissel** [comment] 2017-03-29 18:55
@PFight: for me, the big advantage of code splitting would be to specify which imports should be moved into a separate payload. So, say I have a site that relies on GSAP TweenMax and a handful of other plugins and frameworks, I could specify that in the configuration. Each time Rollup encountered one of these imports in any of my files, it would automatically defer them, but "bake in" everything else like normal. So automatic splitting isn't a bad idea for my use case. :)

**Comment by andyearnshaw** [comment] 2017-03-30 08:45
Webpack 2.x supports code splitting based on `import()`.  

> webpack treats import() as a split-point and puts the requested module in a separate chunk. import() takes the module name as argument and returns a Promise

https://webpack.js.org/guides/code-splitting-import

This is how I imagined Rollup could work when I was thinking about this over the past week.  We're due to ramp up on a project soon that needs this feature, so it looks like we may have to go with webpack for now.

**Comment by PaulBGD** [comment] 2017-03-30 12:43
@andyearnshaw The issue is that `import()` is still in stage 3, there's no guarantee that it'll be in the standard.

**Comment by andyearnshaw** [comment] 2017-03-30 14:27
@PaulBGD of course, but that's not a major issue for several reasons:

 * `import()` is new and its semantics were accepted in the run up to stage 3, barring very unlikely implementation difficulties, it's unlikely to change.
 * Rollup is a build tool that uses semver, no production code will be affected by shipping a breaking change.
 * Rollup is not an implementation of Ecma-262. It could keep `import()` even if it never reached stage 4 (assuming it was easy enough to keep it in the parser, which it is for Babel).
 * Acceptance into Stage 4/the spec doesn't guarantee that there will be no issues that arise later (see `Array.prototype.values`).

Either way, there's a clear demand for code splitting and `import()` is well on its way to satisfying that demand.  Waiting for full sign off just means that people can't use Rollup if they want code splitting and implementing something different means writing something that *will* inevitably change instead of something that *may* one day change.

**Comment by Pauan** [comment] 2017-03-31 23:41
I think it would be super cool if Rollup supported `import()`, however Acorn only supports Stage 4 features, so Rollup would either have to switch parsers or use an Acorn plugin like [`acorn-dynamic-import`](https://www.npmjs.com/package/acorn-dynamic-import)

**Comment by pspeter3** [comment] 2017-04-10 22:39
I think there is value in allowing multiple entry points that split out common chunks.

**Comment by cowwoc** [comment] 2017-04-17 20:59
Sorry for throwing a wrench into this discussion, but here is an interesting benchmark I just ran across: https://medium.com/outreach-engineering/tree-shaking-vs-code-splitting-a-real-world-benchmark-bbbf36245db3

Code-splitting will increase the complexity of the tool/configuration, so there has to be a pretty compelling benefit to warrant it. If I understand correctly, the results of this benchmark seem to imply that the performance difference between code splitting (async multiple) and not bundling at all (async individual) is so minimal that you might want to reconsider implementing this feature altogether.

**Comment by andyearnshaw** [comment] 2017-04-17 22:31
I disagree. One of the main use cases for code splitting is to defer
downloading of nonessential parts to keep the initial page load smaller.
Overall performance isn't the only use case. The "not bundling at all"
approach increases complexity of the application, as it requires a loader,
increasing initial download and/or requiring that the code be written in
another way (es-module-loader and friends are large).

Increased complexity of tools to reduce complexity of code is the reason
tools like rollup exist. One of the benefits of rollup is that it's focus
is small enough that it doesn't have nearly the complexity of similar tools
like webpack, jspm and others.

**Comment by shannonmoeller** [comment] 2017-04-17 22:50
@cowwoc The desire here is for both optimizations, not one vs another. My use cases involve minimizing the data over the wire for low-end devices and service plans.

**Comment by ghempton** [comment] 2017-04-18 00:25
@shannonmoeller is right: dynamic loading and rollup-style optimizations are not mutually exclusive. One ideal world would be to have multiple bundles, each with internal rollup-style optimizations, that export only the dependencies needed by other bundles.

**Comment by cowwoc** [comment] 2017-04-18 02:19
@andyearnshaw I'm actually not against code splitting. Ironically, I ran across this issue while researching how to add code-splitting to my rollup configuration.

The thing that caught my attention about the benchmarking article is their point that with HTTP2 around the corner download latency will be decreasing. This trend is true for mobile as well, even if it might not be the case today.

> The "not bundling at all" approach increases complexity of the application, as it requires a loader,

Not necessarily. Eventually browsers will support ES6 modules, in which case loaders won't be necessary (but parsing time will remain a problem). In the meantime, I was planning to manually specify all JS dependencies in the HTML `<head>`.

I agree with the rest of you, though, that dynamic loading (you mean async loading right?) and rollup-style optimizations are not mutually-exclusive. This is precisely why I filed this issue: https://github.com/rollup/rollup/issues/1369

**Comment by lastmjs** [comment] 2017-04-18 03:34
I would like to emphasize that not bundling at all most definitely decreases the complexity of an application, if all browser standards are fully in play and optimized. We're in the middle of launching a production application and we've decided to do no bundling whatsoever. Our setup is very minimal and allows us to emulate the behavior the browser has always had. Just load the scripts you need through script tags. That model is very easy to grok for component-based architectures.

I guess what I'm trying to say is that we should be looking towards no bundling as our end goal because it reduces the development complexity of our applications. I'll be working on this much more over the summer, but this project is how we're doing it if anyone is interested: https://github.com/lastmjs/zwitterion/blob/master/README.md

That's actually the slightly outdated project, but I will be combining it with the project that we actually use for production soon: https://github.com/lastmjs/zwitterion-production

I think these projects are promising. The idea is to transpile all requested files on the server and then serve them to the user. There are a number of optimizations available to explore for optimization.

I wonder if we could somehow use Rollup server-side to transpile and tree-shake requested files, with no build-process necessary.

**Comment by bfred-it** [comment] 2017-04-18 04:38
@lastmjs HTTP compression doesn't work across files. By unbundling your scripts you're increasing your payload's size. I think this is off topic too.

**Comment by andyearnshaw** [comment] 2017-04-18 10:01
@cowwoc 

>> The "not bundling at all" approach increases complexity of the application, as it requires a loader

> Not necessarily. Eventually browsers will support ES6 modules, in which case loaders won't be necessary (but parsing time will remain a problem).

Browsers supporting modules in any useful manner is still a ways off.  Simple script importing is useful for small applications with very few dependencies but it doesn't scale well as dependencies and code size increase.  I've experienced this first-hand using SystemJS to load ES modules in the browser.  As you add dependencies that use different module formats or directory structures, you go deeper down the rabbit hole trying to tie everything together nicely.  This is the increase in application complexity I was talking about.

> In the meantime, I was planning to manually specify all JS dependencies in the HTML `<head>`.

Good luck with that 😝.  Seriously, though, I don't think this is a good approach at all. Code-splitting allows you to specify dependencies at the point they are used in the code.  By specifying scripts in the `<head>`, you have to ensure that dependencies are available before referencing them.  Again, this works ok for small, 1-page apps but becomes a nightmare as you scale up. +Complexity.

As for HTTP/2, it doesn't address the requirement to defer loading of components until they're required.  Eventually, yes, `HTTP/2` and `import()` will eventually give us a workable solution.  But as long as people need to support older operating system/browser combinations that don't implement both of these features, bundling and code splitting will be required.

**Comment by shannonmoeller** [comment] 2017-04-18 13:14
For those that would like the code-splitting feature, I think we all agree on two things:

1. It's not the future yet.
2. Current solutions are less-than-desirable.

The original issue envisions this usage of the final (preferably automated) solution:

```html
<!-- a.html -->
<script src="shared.js"></script>
<script src="a.js"></script>

<!-- b.html -->
<script src="shared.js"></script>
<script src="b.js"></script>
```

I believe module loading and alternate patterns are off topic. I'd like to see more discussion around what the internals of `shared.js`, `a.js`, and `b.js` look like. I think the simplest solution is to use UMD and some sort of object reference or destructuring.

Thus, given input similar to this:
https://gist.github.com/shannonmoeller/f7f80a4da3e034518cb5524d3ec0e056

I might expect output similar to this:
https://gist.github.com/shannonmoeller/280dda1f47e222c1ee88e5613bd01897

**Comment by jessehattabaugh** [comment] 2017-07-03 17:51
My two cents: code-splitting is more useful for lazy-loading chunks, than generating common chunks like the OP wants. This would require a runtime to determine which chunks have been loaded. Am I correct in assuming that this is something Roll-up's maintainers are loathe to do? If that's the case, could a plugin, or complimentary tool perform this job, and what would that look like?

**Comment by MikeMatusz** [comment] 2017-10-10 14:57
Lazy loading is my use case as well.  There are already ways of manually generating common chunks with rollup.  I'm currently using webpack to bundle a large Angular application with lazy-loaded routes.  What I'm using rollup for currently is bundling several Angular libraries shared by multiple teams.  I was hoping to try bundling our application with it as well, but that won't be practical without a feature like this.

**Comment by ctavan** [comment] 2017-11-23 11:11
[Chrome 63](https://developers.google.com/web/updates/2017/11/dynamic-import#dynamic) and [Safari Technology Preview 24](https://webkit.org/blog/7423/release-notes-for-safari-technology-preview-24/) will both support dynamic `import()`.

Me too, I'd love to be able to chunk my rollup bundles and use dynamic `import()` for lazy loading of these chunks.

**Comment by guybedford** [comment] 2018-01-24 14:03
Closing as the feature is now live, will also be iterating on enhancements as we get feedback, but these can track in new issues.

**Closed by guybedford** 2018-01-24 14:03 UTC
Labels: enhancement
