### ISSUE TITLE
Watch build stops at "bundling..."

### ISSUE THREAD

**Issue by rista404** [rollup/rollup#887] opened 2016-08-31 11:07 UTC
When running rollup with `--watch` param on version `0.34.11` the task get stuck at `bundling...`. 
```
checking rollup-watch version...
bundling...
```
But with version `0.34.10` everything works fine 😺 

You can just clone https://github.com/rista404/next-project-kickstart if you want to reproduce the problem (watch out the rollup versions),  and run `npm run start:js`.

Cheers!

**Comment by samccone** [comment] 2016-09-01 01:28
Just ran into this as well seems to be a regression btw:

`0.34.9 && 0.34.10`

these three commits seem to be the root issue:

https://github.com/rollup/rollup/commit/ebbb5bec62a9dd42b478d3fbbf12b8f72ac4de45
https://github.com/rollup/rollup/commit/98b4da0f355c4abf6fa71f1ae835ac71b65eb58f
https://github.com/rollup/rollup/commit/3ed945c8e1cd40d65f9092b72be7127c69ba8676

**Comment by Rich-Harris** [comment] 2016-09-01 03:15
😬 sorry! my bad, that was careless of me. The offending commit was https://github.com/rollup/rollup/pull/886/commits/3817b74002b66f901bdf3cce64eff9bafc7dc1c7. Fixed in 0.34.12

**Closed by Rich-Harris** 2016-09-01 03:15 UTC

**Comment by samccone** [comment] 2016-09-01 04:23
Ha my GitHub bisect failed me 😂 thanks @Rich-Harris !

**Comment by rista404** [comment] 2016-09-01 13:40
Thanks @samccone @Rich-Harris !
:shipit:
