### ISSUE TITLE
Add rollup-all command line?

### ISSUE THREAD

**Issue by futurist** [rollup/rollup#750] opened 2016-06-24 13:47 UTC
I have to add below in `package.json` to generate all version from command line:

```
    "iife": "mkdir -p iife && rollup -f iife -n extend_exclude src/extend_exclude.js | uglifyjs -c -m -o iife/extend_exclude.js",
    "amd": "mkdir -p amd && rollup -f amd -u extend_exclude src/extend_exclude.js -o amd/extend_exclude.js",
    "cjs": "mkdir -p cjs && rollup -f cjs src/extend_exclude.js -o cjs/extend_exclude.js",
    "es": "mkdir -p es && rollup -f es src/extend_exclude.js -o es/extend_exclude.js",
    "make": "npm run iife && npm run cjs && npm run amd && npm run es",
```

Is it possible to add a new command line / command line option to generate all the version in one line?

**Comment by bfred-it** [comment] 2016-06-24 13:58
You might want to look into:

* https://github.com/frostney/rollup-babel-lib-bundler
* https://github.com/bfred-it/npm-bundler/blob/master/readme.md

Or just create a config. There's likely not going to be a way to configure all of that in one command

**Comment by Rich-Harris** [comment] 2016-06-24 15:08
You could do the whole lot in one go with a config file, like so:

```js
// rollup.config.js
export default {
  entry: 'src/extend_exclude.js',
  moduleName: 'extend_exclude',
  moduleId: 'extend_exclude',
  targets: [
    { format: 'iife', dest: 'iife/extend_exclude.js' },
    { format: 'amd',  dest: 'amd/extend_exclude.js'  },
    { format: 'cjs',  dest: 'cjs/extend_exclude.js'  },
    { format: 'es',   dest: 'es/extend_exclude.js'   }
  ]
};
```

Then, you could add a single task in your package.json, with a post-task to uglify the IIFE:

```bash
"build": "rollup -c && uglify iife/extend_exclude.js -cm > iife/extend_exclude.js"
```

Bonus: it should be quicker, because it only needs to create the bundle once even though there are four output targets.

**Comment by futurist** [comment] 2016-06-24 21:56
@bfred-it A good plugin, wll try it. But it's babel thing, which not always be used.

@Rich-Harris  Can add a little command line questionnaire similar to `npm init` to generate the config file? I think that make sense

**Comment by TrySound** [comment] 2016-06-25 05:29
@futurist It was already discussed. This doesn't have a lot of sense, because config can be very-very different. The only regular thing is something like
```js
export default {
  entry: 'src/index.js',
  plugins: [],
  dest: 'dist/index.js',
  format: 'iife'
};
```
Can't you remember and reproduce this? And still this stuff is very opinionated. By the way you can now use config from `node_modules`,
https://github.com/rollup/rollup/wiki/Command-Line-Interface#using-a-config-file

**Comment by Rich-Harris** [comment] 2016-12-31 17:46
Will close this as there's a separate issue regarding `rollup init`: https://github.com/rollup/rollup/issues/495

**Closed by Rich-Harris** 2016-12-31 17:46 UTC
