### ISSUE TITLE
[iife] Multiple named exports from entry

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#1397] opened 2017-05-04 10:57 UTC
**Feature request:**
Allow multiple named exports for IIFE variable

**Input:**
```javascript
export const foo = 'foo'
export const bar = 'bar'
```

**Output:**
```javascript
var myBundle = (function (exports) {
'use strict';

const foo = 'foo';
const bar = 'bar';

exports.foo = foo;
exports.bar = bar;

}({});
```

**Webpack** supports it with:
```javascript
libraryTarget: 'var',
library: 'myBundle',
```

Would like to contribute to this, if we establish that we want to support this + establish semantics (names for options etc). The only thing I aint sure - how tests are written here, implementation alone should be trivial.

**Comment by olsonpm** [comment] 2017-05-14 06:01
Not sure I agree with this approach.  Currently rollup requires `moduleName` for bundles with `format: 'iife'`.  What your code suggests is to not require `moduleName` and to instead allow the export to write properties to the returned object directly.

So, I only don't agree because it deviates from current convention.  Just an opinion though.

**Comment by Andarist** [comment] 2017-05-14 06:48
`moduleName` would still be very much needed - we need to know to what variable the returned object should be assigned to.

**Comment by olsonpm** [comment] 2017-05-14 06:56
Then your output doesn't match your description, because an iife bundle will never pass an empty object without `this.<module name>` prefixed.  For example

```js
(function (exports) {
'use strict';

const namedExport = 'a named export';

exports.namedExport = namedExport;

}((this.myModule = this.myModule || {})));
```

**Comment by thisconnect** [comment] 2017-05-14 07:43
`moduleName` for IIFE should be optional IMO! It should assign your exports to the global this self.

There are 2 "hacky" ways, related to that
- The moduleName Window hack:  `moduleName: 'window'` see https://github.com/rollup/rollup/issues/494#issuecomment-268243574
- The footer ways `footer: 'window.Mn = window.Marionette;'` https://github.com/rollup/rollup/issues/553#issuecomment-202166713

**Comment by olsonpm** [comment] 2017-05-14 07:49
Also - I was wrong when I said 'an iife bundle will never pass an empty object...'.  I was playing around with it and the behavior depends on rollup.config.js' `exports` option.  By setting it to 'default', the output is as OP mentions.  By setting it to 'named', the output is as I showed.

@Andarist - is your issue related to the `exports` option?  Because rollup already allows for multiple named exports.

**Comment by Andarist** [comment] 2017-05-14 08:03
@olsonpm kinda, main problem is that with `named` its geting assigned to `this.myModule` and `this` might be `window` - dont want to pollute the global space with my bundle, so its not a viable option for me

**Comment by olsonpm** [comment] 2017-05-14 08:07
Gotcha.  I think the default vs named implementation is odd (one assigning to a variable, the other assigning to `this`).  But I don't care to look into the git history to find out whether that design was intentional or just a quick hack.

**Comment by Rich-Harris** [comment] 2017-06-03 20:33
Seems to me the best option here is to use `moduleName: 'window'`, as @thisconnect notes. Is there any reason not to do that?

**Comment by Andarist** [comment] 2017-06-03 20:44
I guess this would make it global, attached to window. My use case is to assign it to a local variable, which i later embed in a bigger script within a closure.

Attaching to a window is super leaky

**Comment by Rich-Harris** [comment] 2017-06-03 20:55
In that case maybe you could do this...

```diff
-export const foo = 'foo'
-export const bar = 'bar'
+const foo = 'foo'
+const bar = 'bar'
+export default { foo: foo, bar: bar }
```

...so that it uses the `var` form, and then use `options.footer` to create the additional local variables you need.

The 'attach to `exports`' behaviour is pretty baked in, I'm afraid — it's the only realistic way to support AMD and CommonJS.

**Comment by Andarist** [comment] 2017-06-04 10:31
Yeah, I have figured that workaround in my project. 

> The 'attach to exports' behaviour is pretty baked in

That's not the problem at all in the case of named exports either, problem is that whats geting passed in as `exports` is attached to the outer `this`. What could be produced with an option is what I have described in the original request, pass in an empty object as `exports` and return it so it gets assigned to a local `var`. 

I guess the problem is that in the solution u have described the `default` export is not assigned as `default` property, but just returned as is - and thats conflicting for default + named exports scenario. That differs from what webpack does (which ofc it can).

I just had to bundle the same thing once by rollup and once by webpack in my build process (dont ask why ;) ) and because of that workaround I had to write in the code in which this got embedded in smth like this - `(myBundle.default || myBundle).init()`

Anyway - if u think that there is nothing we can do to support this, please close the issue and I'll file in a PR to the docs with explanation on how to achieve this.

**Comment by Rich-Harris** [comment] 2017-06-04 14:06
Ah, I see. I guess there's nothing in principle that would stop us from doing this:

```js
var myBundle = this.myBundle || {};
(function (exports) {
exports.a = 1;
}((myBundle)));
```

Slightly less compact, but avoids assignments to the global object. Would that solve your problem? Can't *think* of any downside, though there might be something I haven't thought of

**Comment by Andarist** [comment] 2017-06-05 09:18
This would still require from the consumer to provide something as `this` in `strict mode;`, ofc doable but quite cumbersome. Cannot we just skip `this` with some setting?

**Comment by bfred-it** [comment] 2017-06-21 16:37
I think I'm missing the point of your request. You mention you want multiple exports in `iife` format, but what does that mean?

Currently `iife` exports one object, which translates to "one global".

If you ask for "multiple exports" you're asking for "multiple globals".

To make what you're asking extra clear, please show the expected output for this code:

```js
export const foo = 'foo'
export const bar = 'bar'
```

**Comment by Andarist** [comment] 2017-06-22 18:46
@bfred-it exactly what is marked as *output* in the original post

**Comment by bfred-it** [comment] 2017-06-23 01:31
Gotcha! So it's a duplicate of this other issue: https://github.com/rollup/rollup/issues/827

I've been asking for the same thing :D

**Closed by bfred-it** 2017-06-23 01:31 UTC
Labels: duplicate, enhancement

**Comment by Andarist** [comment] 2017-06-23 09:13
@bfred-it exactly that! sorry that it might have not be that clear from my request, its super easy to implement this, I think I could do that, just wanted to establish in the issue what configuration should be used to achieve it (names of options etc)
