### ISSUE TITLE
Tree shaking removing valid code

### ISSUE THREAD

**Issue by arackaf** [rollup/rollup#3093] opened 2019-09-04 13:44 UTC
- Rollup Version: 1.20.3
- Operating System (or Browser): Mac
- Node Version: 8

### How Do We Reproduce?

https://rollupjs.org/repl/?version=1.20.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHglMjBmcm9tJTIwJy4lMkZ4LmpzJyUzQiU1Q24lNUNueC5iKCklM0IlNUNuJTVDbmlmJTIwKHguYSklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdobW0nKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ4LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAlN0IlNUNuJTVDdGElM0ElMjBudWxsJTJDJTVDbiU1Q3RiKCklMjAlN0IlNUNuJTVDdCU1Q3R0aGlzLmElMjAlM0QlMjAnYiclM0IlNUNuJTVDdCU3RCU1Q24lN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

### Expected Behavior

`if (x.a) {` should not be removed

### Actual Behavior

it is

**Comment by dnalborczyk** [comment] 2019-09-04 14:13
not sure if rollup is bundling as intended in this case, but the outcome is correct . the condition will never be true.

compare:

https://rollupjs.org/repl/?version=1.20.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHglMjBmcm9tJTIwJy4lMkZ4LmpzJyUzQiU1Q24lNUNueC5iKCklM0IlNUNuJTVDbnguYSUyMCUzRCUyMCdmb28nJTVDbiU1Q25pZiUyMCh4LmEpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygnaG1tJyklM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyeC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwJTdCJTVDbiU1Q3RhJTNBJTIwbnVsbCUyQyU1Q24lNUN0YigpJTIwJTdCJTVDbiU1Q3QlNUN0dGhpcy5hJTIwJTNEJTIwJ2InJTNCJTVDbiU1Q3QlN0QlNUNuJTdEJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by dnalborczyk** [comment] 2019-09-04 14:16
although this leaves the condition in place as well:

https://rollupjs.org/repl/?version=1.20.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHglMjBmcm9tJTIwJy4lMkZ4LmpzJyUzQiU1Q24lNUNueC5iKCklM0IlNUNuJTVDbnguYSUyMCUzRCUyMG51bGwlMjAlMkYlMkYlMjBhbmQlMjB1bmRlZmluZWQlNUNuJTVDbmlmJTIwKHguYSklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKCdobW0nKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ4LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjAlN0IlNUNuJTVDdGElM0ElMjBudWxsJTJDJTVDbiU1Q3RiKCklMjAlN0IlNUNuJTVDdCU1Q3R0aGlzLmElMjAlM0QlMjAnYiclM0IlNUNuJTVDdCU3RCU1Q24lN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by arackaf** [comment] 2019-09-04 14:23
How do you think the outcome is correct? `x.b();` is plainly, clearly called, which sets `a` to something, which would trigger the `if` statement, and cause the log to display. But the log is suppressed.

**Comment by dnalborczyk** [comment] 2019-09-04 14:32
😄 ha, you're right! looked too quick, didn't see that ...

**Comment by lukastaegert** [comment] 2019-09-04 15:06
Yes, this is a known issue. Modifications through `this` are still not tracked properly. I REALLY to get to this soon... There are already other issues for this, though.

**Comment by lukastaegert** [comment] 2019-09-04 15:08
Duplicate of #2345, #2473, #3027

**Comment by arackaf** [comment] 2019-09-05 00:03
Is it possible to just turn all tree shaking off for local modules? (But leave it on for npm stuff)

**Comment by lukastaegert** [comment] 2019-09-06 15:48
Also not yet done, unfortunately... By this point, I think I am actually open for a PR that plugs this hole e.g. in one of the ways described in #2345 even at the cost of some tree-shaking quality. This would give me more time to prepare a proper solution that supports context tracking without breaking people's code. cc @robpalme

**Closed** 2019-12-02 06:13 UTC

**Comment by arackaf** [comment] 2020-10-14 13:41
This appears to be fixed now - woo hoo! Thanks! 

![image](https://user-images.githubusercontent.com/11261266/95997061-fea1d000-0df8-11eb-8173-1e8478616891.png)

**Comment by lukastaegert** [comment] 2020-10-15 04:52
Actually, it was fixed last December. This PR was closed by the fixing commit.
