### ISSUE TITLE
Interop failed if export object contains 'default' key

### ISSUE THREAD

**Issue by ghost** [rollup/rollup#2667] opened 2019-01-27 14:00 UTC
- Rollup Version: 1.1.2
- Operating System (or Browser): Windows 10
- Node Version: 10.13.0

### How Do We Reproduce?

Currently working with `joi` and found this bug when executing the bundled file.
It turned out that `joi` exports object containing `default` key. Rollup interop system only checks for `default` key, but not `__esModule` key.

**main.js**
```javascript
import joi from 'joi';

const schema = joi.object();

schema.validate({});
```

**rollup.config.js**
```javascript
export default [
  input: './main.js',
  output: {
    file: './bundle.js',
    format: 'cjs'
  },
  external: [
    'joi'
  ]
}
```

### Expected Behavior

**bundle.js**
```javascript
'use strict';

// `__esModule` key is checked, instead of `default`
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && '__esModule' in ex) ? ex['default'] : ex; }

var joi = _interopDefault(require('joi'));

// We are accessing `joi.object()` correctly
const schema = joi.object();

schema.validate({});
```

### Actual Behavior
**bundle.js**
```javascript
'use strict';

// `__esModule` key is not checked
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var joi = _interopDefault(require('joi'));

// We are accessing `joi.default.object()`, which is `undefined` and will throw error
const schema = joi.object();

schema.validate({});
```

**Comment by shellscape** [comment] 2019-12-23 16:12
Thanks for opening an issue, and apologies that it took so long for a reply. It must be because of the age of the issue, but neither the deprecated `joi` nor it's replacement `@hapi/joi` export `default` nor `__esModule`. So it looks like there's been some churn in that project and they've eliminated that export. 

It does seem that the issue is still valid, as discussed on #2554. We're going to close this in favor of that issue to continue discussion.

**Closed by shellscape** 2019-12-23 16:12 UTC
Labels: s² 🔥🔥 important, t¹ 🐞 bug
