### ISSUE TITLE
TS emitted namespace-functions are not tree-shaken

### ISSUE THREAD

**Issue by zenmumbler** [rollup/rollup#2226] opened 2018-05-28 10:23 UTC
As a follow-up to #2225, I tried to change my code to export a TypeScript namespace instead of using `export * as X from Y`, however this runs into another problem that exhibits strange behaviour.

I have made a testcase in the repl with 8 variations of the same theme that you can try by (un)commenting various blocks but it boils down to:

```js
var obj;
obj = obj || {}; // Rollup does not seem to like this
obj.prop = 1; // removing this makes things work
```

Rollup will not tree-shake `obj` if it has been assigned to after declaration and it is not empty.

REPL here:
https://rollupjs.org/repl?version=0.59.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHRlc3QlMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRnZlYzIlNUMlMjIlM0IlNUNudGVzdCgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnZlYzIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGKiU1Q252YXIlMjB2ZWMyJTIwJTNEJTIwJTdCJTdEJTNCJTIwJTJGJTJGJTIwQ2FzZSUyMDElM0ElMjByZW1vdmVkJTIwcHJvcGVybHklNUNudmVjMi5YJTIwJTNEJTIwMSUzQiU1Q24qJTJGJTVDbiU1Q24lMkYqJTVDbnZhciUyMHZlYzIlM0IlMjAlMkYlMkYlMjBDYXNlJTIwMiUzQSUyMGludmFsaWQlMjAodW5pbml0aWFsaXplZCklMkMlMjBub3QlMjByZW1vdmVkJTVDbnZlYzIuWCUyMCUzRCUyMDElM0IlNUNuKiUyRiU1Q24lNUNuJTJGKiU1Q252YXIlMjB2ZWMyJTNCJTIwJTJGJTJGJTIwQ2FzZSUyMDMlM0ElMjB2YWxpZCUyMGFuZCUyMG5vdCUyMHJlbW92ZWQlNUNudmVjMiUyMCUzRCUyMHZlYzIlMjAlN0MlN0MlMjAlN0IlN0QlM0IlNUNudmVjMi5YJTIwJTNEJTIwMSUzQiU1Q24qJTJGJTVDbiU1Q24lMkYqJTVDbnZhciUyMHZlYzIlMjAlM0QlMjAlN0IlN0QlM0IlMjAlMkYlMkYlMjBDYXNlJTIwNCUzQSUyMHZhbGlkJTJDJTIwaW5pdGlhbGl6ZWQlMkMlMjBub3QlMjByZW1vdmVkJTVDbnZlYzIlMjAlM0QlMjB2ZWMyJTIwJTdDJTdDJTIwJTdCJTdEJTNCJTVDbnZlYzIuWCUyMCUzRCUyMDElM0IlNUNuKiUyRiU1Q24lNUNuJTJGKiU1Q252YXIlMjB2ZWMyJTNCJTIwJTJGJTJGJTIwQ2FzZSUyMDUlM0ElMjBkaWZmZXJlbnQlMjB0ZXN0JTJDJTIwbWFraW5nJTIwYXNzaWdubWVudCUyMGNvbmRpdGlvbmFsJTJDJTIwbm90JTIwcmVtb3ZlZCU1Q25pZiUyMCh2ZWMyJTIwJTNEJTNEJTNEJTIwdW5kZWZpbmVkKSUyMHZlYzIlMjAlM0QlMjAlN0IlN0QlM0IlMjAlMkYlMkYlMjB0aGlzJTIwdGVzdCUyMHNob3VsZCUyMGFsc28lMjBiZSUyMHJlbW92ZWQlMjBhcyUyMHZlYzIlMjBpcyUyMGd1YXJhbnRlZWQlMjB0byUyMGJlJTIwdW5kZWZpbmVkJTIwaGVyZSU1Q252ZWMyLlglMjAlM0QlMjAxJTNCJTVDbiolMkYlNUNuJTVDbiUyRiolNUNudmFyJTIwdmVjMiUzQiUyMCUyRiUyRiUyMENhc2UlMjA2JTNBJTIwdmFsaWQlMjBhbmQlMjByZW1vdmVkJTIwKGJlY2F1c2UlMjBpdCUyMGlzJTIwZW1wdHklMjBJJTIwYXNzdW1lKSU1Q252ZWMyJTIwJTNEJTIwdmVjMiUyMCU3QyU3QyUyMCU3QiU3RCUzQiU1Q24qJTJGJTVDbiU1Q24lMkYqJTVDbnZhciUyMHZlYzIlM0IlMjAlMkYlMkYlMjBDYXNlJTIwNyUzQSUyMFR5cGVzY3JpcHQlMjBlbWl0JTIwZm9yJTIwJTYwbmFtZXNwYWNlJTIwdmVjMiUyMCU3QiUyMCUyMCU3RCU2MCUyQyUyMHJlbW92ZWQlMjAoZW1wdHkpJTVDbihmdW5jdGlvbiUyMCh2ZWMyKSUyMCU3QiU1Q24lN0QpKHZlYzIlMjAlN0MlN0MlMjAodmVjMiUyMCUzRCUyMCU3QiU3RCkpJTNCJTIwJTJGJTJGJTIwdmVjMiU1Q24qJTJGJTVDbiU1Q24lNUNudmFyJTIwdmVjMiUzQiUyMCUyRiUyRiUyMENhc2UlMjA4JTNBJTIwVHlwZXNjcmlwdCUyMGVtaXQlMjBmb3IlMjBuYW1lc3BhY2UlMjB3aXRoJTIwY29udGVudHMlMkMlMjBub3QlMjByZW1vdmVkJTVDbihmdW5jdGlvbiUyMCh2ZWMyKSUyMCU3QiU1Q24lNUN0ZnVuY3Rpb24lMjBzdHIoYSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTYwdmVjMiglMjQlN0JhJTVCMCU1RCU3RCUyQyUyMCUyNCU3QmElNUIxJTVEJTdEKSU2MCUzQiU1Q24lMjAlMjAlN0QlNUNuJTIwJTIwdmVjMi5zdHIlMjAlM0QlMjBzdHIlM0IlNUNuJTdEKSh2ZWMyJTIwJTdDJTdDJTIwKHZlYzIlMjAlM0QlMjAlN0IlN0QpKSUzQiUyMCUyRiUyRiUyMHZlYzIlNUNuJTVDbiU1Q25mdW5jdGlvbiUyMHRlc3QoKSUyMCU3QiU1Q24lNUN0Y29uc29sZS5pbmZvKCU1QyUyMnRlc3QlNUMlMjIpJTNCJTVDbiU3RCU1Q24lNUNuZXhwb3J0JTIwJTdCJTIwdmVjMiUyQyUyMHRlc3QlMjAlN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

**Comment by lukastaegert** [comment] 2018-05-28 11:59
> Rollup will not tree-shake obj if it has been assigned to after declaration and it is not empty

Yes, this is exactly how rollup works at the moment. The current logic is that if there is an assignment to a variable other than its initial declaration, this variable is treated as "unknown". The same logic applies to reassigning properties of objects.

The reason is that we cannot track values through reassignments yet. In fact, changing this behaviour is one of the biggest mid-term goals we have in this area at the moment. Until then, rollup very much favours an "immutable variable" approach i.e. if each variable is only ever assigned a value during its declaration, tree-shaking will work best.

**Comment by zenmumbler** [comment] 2018-05-28 12:10
Thanks again @lukastaegert, for the explanation. Fun to see I'm slowly reverse engineering Rollup's mechanics just from its output :) Sadly, certain TS emits run into this problem directly. In my specific case, I can switch from a grouped re-export or explicit namespace to a class with all static functions. The emit for a class in ES5 is a direct, single assignment and in ES6+ of course, just a class.

**Comment by zenmumbler** [comment] 2018-05-28 12:27
Just as a follow-up Q for @lukastaegert before I post another issue that is the same as this one:

I assume that the same "use single assignments" rule also causes this?
Consider the following module:
```js
export function create() {
	const out = []; // or: new Float32Array(ELEMENT_COUNT);
	out[0] = 0; // removing this fixes the problem
	return out;
}

const tempQ1_ = create(); // this is not removed by tree-shake
```
The tempQ1_ var is not removed when I use this module in any way. By initialising the array in the assignment, the var is removed. I guess even though it is assigned, by assigning to subindexes I still invalidate the knowledge of `out`? This case is actually simple to fix, mostly curious.

**Comment by lukastaegert** [comment] 2018-05-28 13:07
Not necessarily. In case you use an array, this is actually something we could improve with only moderate effort. Just look at this example: [REPL](https://rollupjs.org/repl?version=0.59.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwb3V0MSUyMCUzRCUyMCU1QiU1RCUzQiU1Q25vdXQxJTVCMCU1RCUyMCUzRCUyMDAlM0IlNUNuJTVDbmNvbnN0JTIwb3V0MiUyMCUzRCUyMCU3QiU3RCUzQiU1Q25vdXQyJTVCMCU1RCUyMCUzRCUyMDAlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

As you can see in case the value is an object, the assignment is not a side-effect. Might be worth looking into why this is not the case for array literals. As for `Float32Array`s, this will probably take a little longer as it ties into the global handling.

**Comment by shellscape** [comment] 2019-08-09 18:51
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Closed by shellscape** 2019-08-09 18:51 UTC
Labels: b³ 🐞 tree-shaking, t³ ✨ enhancement

**Comment by shrinktofit** [comment] 2020-08-20 04:53
Encountered the same question.

We have a function and it behaves like a namespace too:
```js
function f () {}
f.g = () => {};
```

We expect there is a way we can tell rollup that `g` is a freezed,const property of `f` so that occurances of `f.g` can be tree-shaked :)

**Comment by dgreensp** [comment] 2025-02-21 09:50
Since there has been some recent work on tree-shaking, I wonder if this could be revisited?

Here's some code where an API consists of some functions in a namespace that's merged with a function (the desired syntax is `Foo.inc(Foo.inc(Foo(1)))`, where `Foo(1)` is a `Foo`):

```ts
export interface Foo {
  x: number;
}

export function Foo(x: number): Foo {
  return { x };
}

export namespace Foo {
  export function inc(f: Foo): Foo {
    return Foo(f.x + 1);
  }
  export function dec(f: Foo): Foo {
    return Foo(f.x - 1);
  }
}
```

This looks very tree-shakable, if you look at the TypeScript.

At the JavaScript level, though:

```js
export function Foo(x) {
    return { x };
}
(function (Foo) {
    function inc(f) {
        return Foo(f.x + 1);
    }
    Foo.inc = inc;
    function dec(f) {
        return Foo(f.x - 1);
    }
    Foo.dec = dec;
})(Foo || (Foo = {}));
```

It would be pretty amazing if this could be tree-shaken somehow.

**Comment by dgreensp** [comment] 2025-02-21 09:58
Related to #5706.

The issue is namespaces in general.  It seems Rollup can't tree-shake anything in a namespace.

**Comment by dgreensp** [comment] 2025-02-21 10:21
esbuild has decided not to tree-shake TypeScript namespaces: https://github.com/evanw/esbuild/issues/3077
