### ISSUE TITLE
Wrong order of dependencies that are included in the output bundle

### ISSUE THREAD

**Issue by emilos** [rollup/rollup#1767] opened 2017-11-30 13:37 UTC
#### Description

I'm trying to use rollup to bundle `jimp` which depends on `xmlbuilder`. The `xmlbuilder` dependency is not being included properly in the output bundle as its code becomes out of order:

```js
var XMLNode$11 = XMLNode
// do something with XMLNode$11 in between, errors here
var XMLNode = 'foo'
```

#### How to reproduce the issue?

```bash
git clone https://github.com/emilos/rollup-bug-xmlbuilder
npm install
npm test --silent
```

#### Contribution

I don't know rollup / rollup-plugin-commonjs internals very well but I'd be happy to help fixing this if you can help me / guide a little bit to narrow down the issue further.

**Comment by lukastaegert** [comment] 2017-12-01 05:57
Hi @emilos, actually I can tell you exactly what the issue is.
`xmlbuilder` has LOTS of circular dependencies, for instance `XMLElement` requires `XMLNode` and `XMLNode` requires `XMLElement`. Rollup has had problems properly sorting circular dependencies for quite some time (this is actually not at all trivially to solve). Matters are not helped by the fact that this is all dynamic `require` statements which somehow need to be approximated by static `import` statements by `rollup-plugin-commonjs`.

I hope we are able to at some time in the future implement a heuristic that can identify synchronous usages to decide how to sort the dependencies but it will be a HUGE refactoring. If you want to have a shot, I will not stop you :)
Otherwise, you will need to wait. Solving this has been bugging me for quite some time now.

**Comment by guybedford** [comment] 2017-12-08 09:54
@lukastaegert I would be weary here of altering the specified ordering of ES modules to fix CommonJS circular dependency issues.

I have a solution for making CommonJS circular dependency issues work fully with Rollup and will be sharing this work very soon.

**Comment by lukastaegert** [comment] 2017-12-08 09:56
I'm looking forward!

**Comment by farwayer** [comment] 2017-12-18 00:18
I have a similar problem with `core-js`:
```js
_export(_export.S + _export.F * !_descriptors, 'Object', {
  defineProperty: _objectDp.f
});

var $export = function $export(type, name, source) {...}
var _export = $export;
```

**Comment by guybedford** [comment] 2018-02-10 20:34
Marking as a duplicate of https://github.com/rollup/rollup/issues/1507.

**Closed by guybedford** 2018-02-10 20:34 UTC
Labels: bug, scope-hoisting
