### ISSUE TITLE
Support IIFE format for --experimentalCodeSplitting

### ISSUE THREAD

**Issue by theseanl** [rollup/rollup#2323] opened 2018-07-07 08:18 UTC
Currently UMD and IIFE formats are not supported for `--experimentalCodeSplitting`.

#### Proposal

 - Allow `iife` option for `--experimentalCodeSplitting`.
 - Each chunk is finalized as an iife, as if it was a bundle having a name `{ namespace provided by option.name } + "." + Chunk.name`
 - Generated bundles can be included as separate `script` tags manually to provide an intended combined functionality.

Potential issues if it is implemented as such:
 - End users will need to load chunks manually, and it may not be ergonomic for end users to figure out what chunks were actually created.
   - Currently, consumers can use `(await (await rollup.rollup(options)).generate()).output` to get chunk names.
   - It may even be better if rollup could provide a way to control chunk names.
 - Semantics of `option.name` changes when code splitting is enabled.

For me, this behavior seems to be natural for `iife` formats, and seems to require small changes to iife finalizer only. Not having to include a separate systemjs loader or amd loader would enable users to create bundles with minimal size that can readily be used.

**Comment by guybedford** [comment] 2018-07-12 08:59
Marking as a duplicate of https://github.com/rollup/rollup/issues/2072.

**Closed by guybedford** 2018-07-12 08:59 UTC
