### ISSUE TITLE
Tree shaking not quite working when importing dependencies.

### ISSUE THREAD

**Issue by r3oath** [rollup/rollup#1119] opened 2016-11-23 07:21 UTC
```bash
./node_modules/.bin/rollup -v
rollup version 0.36.3
```

Library in question (used for demonstration purposes) https://github.com/enzyme/qoob

For some reason when I import something like this

```
import { documentReady } from '../../node_modules/qoob/src/packs/events.js'
```

I get a bunch of extra functions included in the output that aren't actually used anywhere. These seem to be related to the files that are `import`ed from the `events.js` file in question. It's not every function in each import either, seems to be rather random.

Quick example, I seem to be getting the `function html(selector)...` function, which isn't used by `documentReady`.

**Comment by vprasanth** [comment] 2016-11-23 18:30
Not sure if this [article](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80#.nmb0d6lvz) can illuminate some of the reasons why this might be happening.. ?

**Comment by Rich-Harris** [comment] 2016-12-18 21:22
Please see https://github.com/rollup/rollup/wiki/Troubleshooting#tree-shaking-doesnt-seem-to-be-working

Will close this as a duplicate of similar issues, but if you have a specific test case that doesn't seem to fall under the caveats outlined in that section of the wiki then let us know.

**Closed by Rich-Harris** 2016-12-18 21:22 UTC
