### ISSUE TITLE
CommonJS circular dependency execution order could be handled better

### ISSUE THREAD

**Issue by au-phiware** [rollup/rollup#1507] opened 2017-07-29 17:32 UTC
(Wasn't quite sure how to summarise this one...)

## Problem

Attempting a new project that creates a bundle for a node app but I have encountered the following error. I have created a repro repo: [au-phiware/rollup-readable-stream](https://github.com/au-phiware/rollup-readable-stream).

<details>
  <summary>TypeError: The super constructor to "inherits" must not be null or undefined</summary>

    at Object.exports.inherits (util.js:961:11)
    at Object.<anonymous> (/home/corin/Projects/GitHub/rollup/rollup-readable-stream/bundle.js:1105:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
</details>

## Cause

The problem seems to stem from `readable-stream`'s fast-and-loose use of require, whereby Duplex (defined in `_stream_duplex.js`) inherits Readable (defined in ` _stream_readable.js`) and therefore requires ` _stream_readable.js`, however ReadableState (also defined in ` _stream_readable.js`) does some type checking of Duplex types, therefore ` _stream_readable.js` requires `_stream_duplex.js`. Now, `readable-stream` could be written a lot better, but if rollup simply ensures that the declaration of `_stream_readable` (and, admittedly the assignment, which in this case is between two globals, but I could see how this could be problematic) occurs before its use, then there wouldn't be a problem.

## What I have tried

One work-around to my problem is just don't create a bundle, I'm targeting node so it's really not all that critical to create a bundle. But the crazy thing is that `eslint` and `remap-istanbul` are the only packages that explicitly depend on `readable-stream`. I have one other package that optionally depends on it, and there doesn't seem to be a way to have optional modules (let alone tell rollup about them).

Considering that `readable-stream` appears to be a fillin for the builtin `stream`, another workaround is to alias the package. This worked for me using `rollup-plugin-node-resolve-and-alias`.

**Comment by Rich-Harris** [comment] 2017-08-11 18:40
Is it practical to just exclude `readable-stream` from the bundle?

```js
// rollup.config.js
export default {
  // ...
  external: ['readable-stream']
};
```

**Comment by timdp** [comment] 2017-10-30 19:02
This just bit me as well.

I didn't want to hack it into the node-resolve plugin as suggested by @au-phiware. Instead, I came up with a different solution that extends @Rich-Harris's suggestion of adding `readable-stream` to `external` with rewriting some imports in the source using `rollup-plugin-replace`, which is super ugly as well, unfortunately:

```js
const bundle = await rollup({
  input: PKG_ENTRY,
  external: ['readable-stream', 'readable-stream/transform'],
  plugins: [
    plugins.nodeResolve({
      preferBuiltins: true
    }),
    plugins.replace({
      delimiters: ['', ''],
      values: {
        'require(\'readable-stream/transform\')': 'require(\'stream\').Transform',
        'require("readable-stream/transform")': 'require("stream").Transform',
        'readable-stream': 'stream'
      }
    }),
    plugins.commonjs()
  ]
})
```

As you can see, I'm additionally making it rewrite an import of `readable-stream/transform` to one of the named export `Transform` from `stream`. This fixed it for `through2` in my case, but I'm sure there are tons of other packages that will require special treatment.

It feels to me like this should be fixed in both `readable-stream` and in Rollup itself. On the one hand, Rollup's imports should behave exactly like the original `require`, and on the other hand, "just" aliasing these imports shouldn't be such a pain. But it's probably more easily said than done.

Also, the `delimiters` for `rollup-plugin-replace` are necessary to make the plugin refrain from adding a `\b` to its regexp, making the match fail for the brackets because they aren't always at a word boundary. That took me a while to figure out too.

**Comment by jdub** [comment] 2017-12-20 06:30
I've just hit this too.

I tried replacing `readable-stream` with `stream` as suggested above, but it looks like `mysql` relies strongly on the behaviour of `readable-stream` -- it hits a "Received packet in the wrong sequence" error with `stream`. 😄

Haven't come up with a solution yet, but will post if I do.

**Comment by CMCDragonkai** [comment] 2018-05-14 13:09
I just hit this issue as well. https://github.com/MatrixAI/js-virtualfs/issues/4 There's no solution right now?

**Comment by guybedford** [comment] 2018-05-14 13:11
I'm working on a new CommonJS plugin here, but it will be a month or so yet before it is released.

**Comment by CMCDragonkai** [comment] 2018-05-14 13:13
@guybedford What do you mean? Is your new plugin addressing this issue?

**Comment by guybedford** [comment] 2018-05-14 13:14
Yes, it's designed to exactly fix this issue.

**Comment by DianaSuvorova** [comment] 2018-07-15 20:50
I am hitting the issue #1674 which is closed by this one.  The CommonJS plugin that would be able to resolve it sounds like magic. 
I wonder why this never been an issue for libs with circular dependencies before? Does webpack know how to resolve these scenarios?

**Comment by lukastaegert** [comment] 2018-07-16 06:55
I think Webpack is not resolving this at all. By that I mean CommonJS modules are never inlined but kept in a module map handled by Webpack's runtime code to resolve imports dynamically at runtime. This allows them to handle dynamic and circular CommonJS modules at the cost of some performance. But yes, @guybedford has some ideas how we could wrap CJS modules in a way that those scenarios could be handled by rollup as well without adding a full-blown runtime and with only a minor performance hit.

**Comment by ldub** [comment] 2018-12-23 22:12
@guybedford any updates on your effort to fix this with a new CommonJS plugin?

**Comment by RedHatter** [comment] 2019-03-04 22:32
@guybedford I would also be intrested in your new CommonJS plugin

**Comment by szahnfender** [comment] 2019-03-29 17:45
Having the same problem, please fix to support circular dependencies for importing aws sdk

```
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/json.js -> node_modules/aws-sdk/lib/protocol/helpers.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/json.js -> node_modules/aws-sdk/lib/protocol/helpers.js -> commonjs-proxy:node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/query.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/protocol/rest_xml.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/sequential_executor.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/config.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/config.js -> node_modules/aws-sdk/lib/credentials.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/config.js -> node_modules/aws-sdk/lib/credentials/credential_provider_chain.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/http.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/event_listeners.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/response.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/resource_waiter.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v2.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v3.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v3https.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v4.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/v4.js -> node_modules/aws-sdk/lib/signers/v4_credentials.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/s3.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/signers/request_signer.js -> node_modules/aws-sdk/lib/signers/presign.js -> node_modules/aws-sdk/lib/core.js
(!) Circular dependency: node_modules/aws-sdk/lib/core.js -> node_modules/aws-sdk/lib/param_validator.js -> node_modules/aws-sdk/lib/core.js
```

**Comment by BryanCrotaz** [comment] 2019-05-11 01:41
@guybedford wrote ( a year ago)

> I'm working on a new CommonJS plugin here, but it will be a month or so yet before it is released.

I'm hitting this problem - where can I find your new plugin?

**Comment by guybedford** [comment] 2019-05-12 00:55
The Babel transform is available here - https://github.com/jspm/babel-plugin-transform-cjs-dew/, used by this plugin - https://github.com/jspm/rollup-plugin-jspm.

**Comment by GreenGremlin** [comment] 2019-05-26 23:28
Is rollup-plugin-jspm a replacement for rollup-plugin-node-resolve?

**Comment by nightwolfz** [comment] 2019-06-16 22:29
This is how I solved my problem:

```js
import replace from 'rollup-plugin-replace'

plugins: [
  replace({
    delimiters: ['', ''],
    values: {
      "require('readable-stream').Writable": "require('stream').Writable",
      "require('readable-stream').Readable": "require('stream').Readable",
    }
  }),
 //...the rest
]
```

**Comment by dhruvarora93** [comment] 2019-07-25 18:24
I am running into this issue right now, how did you guys resolve it ? Thanks.

**Comment by shellscape** [comment] 2019-08-08 14:02
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Closed by shellscape** 2019-08-08 14:02 UTC
Labels: b² 🐞 scope-hoisting, t¹ 🐞 bug

**Comment by jonathanmarvens** [comment] 2019-08-19 21:40
Hi there. Any updates on this?

**Comment by BryanCrotaz** [comment] 2019-08-19 21:50
> I am running into this issue right now, how did you guys resolve it ? Thanks.

I switched to webpack - had it working in a couple of hours after weeks struggling with issues like this one

**Comment by jonathanmarvens** [comment] 2019-08-19 21:51
I’ve been debugging some *really nasty* issues with values being `undefined` in a critical business application, and I *finally* (unfortunately, after *hours* of debugging) discovered that some of the issues are being caused by this same problem. I’ve read through this thread (and other relevant issues), and I’ve also attempted a few ideas that came to mind, but it doesn’t seem that there’s currently a resolution to this issue barring either (1) excluding important dependencies from the bundle or (2) dropping __Rollup__ altogether; is this a correct conclusion?

Thank you.

__CC:__ @Rich-Harris, @jtnelson

**Comment by jonathanmarvens** [comment] 2019-08-19 21:52
@BryanCrotaz That’s grossly disappointing.

**Comment by BryanCrotaz** [comment] 2019-08-19 22:04
> @BryanCrotaz That’s grossly disappointing.

Unfortunately it is, but this was only one of several issues I had trying to include npm libraries. It was either throw away weeks of work on rollup config, get a new job, find a good therapist, apologise to my neighbours for all the swearing, or find a good tall bridge to throw my laptop off.

**Comment by mmomtchev** [comment] 2020-02-05 12:10
The solution to replace readable-stream with stream actually works very well even with MySQL
readable-stream and stream are supposed to be 100% compatible
The "Received packet in the wrong sequence" is another problem which is related to the MySQL module being minified because of the way it calls functions
If you need to make MySQL work with stream you have to disable terser()

**Comment by lukastaegert** [comment] 2021-11-25 06:15
We are finalizing a new version of the commonjs plugin in rollup/plugins#1038. It is pre-published as `@rollup/plugin-commonjs@beta`. Please give it a spin to see if it resolves the issue, ideally without additional config needed.
