### ISSUE TITLE
Tree shaking include unused methods

### ISSUE THREAD

**Issue by futurist** [rollup/rollup#1107] opened 2016-11-12 00:46 UTC
Please see below module:

https://github.com/cssobj/cssobj-helper/blob/master/lib/cssobj-helper.js

When import this module, the `own` and `arrayKV` always included (not tree shaked)

```javascript
import { random } from './cssobj-helper'
console.log( random() )
```

The result code now is:

```js

function own(o, k) {
  return {}.hasOwnProperty.call(o, k)
}


var random = (function () {
  var count = 0;
  return function () {
    count++;
    return '_' + Math.floor(Math.random() * Math.pow(2, 32)).toString(36) + count + '_'
  }
})();

function arrayKV (obj, k, v, reverse, unique) {
  obj[k] = k in obj ? [].concat(obj[k]) : [];
  if(unique && obj[k].indexOf(v)>-1) { return }
  reverse ? obj[k].unshift(v) : obj[k].push(v);
}

console.log(random())
```

**Expected result:**

Should not include `own` and `arrayKV` in the output code.

**Comment by kzc** [comment] 2016-11-12 14:58
dupe of https://github.com/rollup/rollup/issues/977#issuecomment-249613600

Workaround: run rollup output through rollup again.

**Closed** 2016-11-20 12:24 UTC
Labels: duplicate
