### ISSUE TITLE
Tree-shaking and side-effects

### ISSUE THREAD

**Issue by vanruesc** [rollup/rollup#551] opened 2016-03-10 19:53 UTC
Hi,

I've been working with Rollup for a while and I'm loving it. However, right now I'm faced with a problem that has to do with side-effect detection and is most likely related to #305 and #179 so feel free to close this one if it doesn't tell you something new.

I've accustomed myself to using Object.defineProperty() to define some fancy getters and setters. Unfortunately, this practice leads to the inclusion of a lot of unused code.

Here is an [example](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%2C%22moduleId%22%3A%22%22%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20cube%20%7D%20from%20'.%2Fmaths.js'%3B%5Cnconsole.log%28%20cube%28%205%20%29%20%29%3B%20%2F%2F%20125%22%7D%2C%7B%22name%22%3A%22maths.js%22%2C%22code%22%3A%22%2F%2F%20This%20function%20isn't%20used%20anywhere%2C%20so%5Cn%2F%2F%20Rollup%20should%20exclude%20it%20from%20the%20bundle%2C%20but...%5Cnexport%20function%20square%20%28%20x%20%29%20%7B%5Cn%5Ctreturn%20x%20*%20x%3B%5Cn%7D%5Cn%5Cn%2F%2F%20...this%20is%20considered%20a%20side-effect%20and%20the%20code%20and%20%5Cn%2F%2F%20everything%20that%20it%20entails%20will%20be%20included.%5CnObject.defineProperty%28square.prototype%2C%20%5C%22test%5C%22%2C%20%7B%5Cn%20%20get%3A%20function%28%29%20%7B%20return%20%5C%22hi%5C%22%3B%20%7D%2C%5Cn%20%20set%3A%20function%28%20arg%20%29%20%7B%7D%5Cn%7D%29%3B%5Cn%5Cn%2F%2F%20This%20function%20gets%20included.%5Cnexport%20function%20cube%20%28%20x%20%29%20%7B%5Cn%5Ctreturn%20x%20*%20x%20*%20x%3B%5Cn%7D%22%7D%5D%7D) of the problem using the Rollup website. (Note, that the output on the right is broken until you update it by clicking on another bundle format or randomly modify the code on the left side.)

It took me a while to find out why a lot of unused code was included in my bundles. At first, this behaviour appeared to be random because many, but not all unrelated parts of external dependencies were included. So I created two mock modules:
- [This](https://github.com/vanruesc/external-module/blob/master/src/index.js) is the entry file of the module that acts as a external dependency.
- And [this](https://github.com/vanruesc/external-module/blob/master/src/main/b.js) is the problematic file in that module.
- Furthermore, we have [this](https://github.com/vanruesc/rollup-module/blob/master/src/index.js)  entry file in the other module.
- And [here](https://github.com/vanruesc/rollup-module/blob/master/src/sub/z.js), a part of the external module is used.
- The [result](https://github.com/vanruesc/rollup-module/blob/master/build/bundle.js) contains not only C, Z and the external X, but also the completely unrelated external components Y and B.

This might sound ignorant but why are side-effects even supported to such an extent? At least to me it seems unnecessary to even look at the unrelated files :confused:

**Comment by eventualbuddha** [comment] 2016-03-10 23:15
Thanks for the issue! This does seem to fall into the same category as the issues you referenced, though I would defend rollup's decision to include a module based on what it sees as side-effects even if none of its exports are referenced directly. It's possible the side-effects could be changing global state that is needed by the code that actually is used.

**Comment by vanruesc** [comment] 2016-03-11 17:45
> It's possible the side-effects could be changing global state that is needed by the code that actually is used.

I see, but aren't patterns that actually do this really bad? This appears to be the opposite of explicit and predictable dependencies.

According to [MDN](https://developer.mozilla.org/en/docs/web/javascript/reference/statements/import), you can use the ES6 module syntax to "import an entire module for side effects only, without importing any bindings" like so:
```javascript
import "my-module";
```

I think of Rollup as a tool that does what web browsers would do if they supported ES6 modules. Only that Rollup does it first so that the browsers just have to load one bundle.

Would browsers load modules that aren't directly referenced in an entry module? 

I think the current behaviour feels unintuitive or rather non-transparent to me; I can't really predict how Rollup processes my code.

**Comment by paf31** [comment] 2016-03-11 19:46
Would it be possible to enable more aggressive tree-shaking using a flag? The PureScript community is particularly interested in this, since our generated code generally doesn't have these problems with side-effects. Our current tree-shaking code is specific to our compiler, but we'd like to move to something like Rollup instead if possible (i.e. if we can get a similar level of code reduction).

**Comment by calvinmetcalf** [comment] 2016-03-15 17:43
I made a [more clear cut example](http://rollupjs.org/#{%22options%22%3A{%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A{}%2C%22moduleId%22%3A%22%22}%2C%22modules%22%3A[{%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20{%20cube%20}%20from%20%27.%2Fmaths.js%27%3B\nconsole.log%28%20cube%28%205%20%29%20%29%3B%20%2F%2F%20125%22}%2C{%22name%22%3A%22maths.js%22%2C%22code%22%3A%22export%20{square}%20from%20%27.%2Fsquare.js%27%3B\n\n%2F%2F%20This%20function%20gets%20included.\nexport%20function%20cube%20%28%20x%20%29%20{\n\treturn%20x%20*%20x%20*%20x%3B\n}%22}%2C{%22name%22%3A%22square.js%22%2C%22code%22%3A%22export%20default%20square%3B\n%2F%2F%20This%20function%20isn%27t%20used%20anywhere%2C%20so\n%2F%2F%20Rollup%20should%20exclude%20it%20from%20the%20bundle%2C%20but...\nexport%20function%20square%20%28%20x%20%29%20{\n\treturn%20x%20*%20x%3B\n}\n\n%2F%2F%20...this%20is%20considered%20a%20side-effect%20and%20the%20code%20and%20\n%2F%2F%20everything%20that%20it%20entails%20will%20be%20included.\nObject.defineProperty%28square.prototype%2C%20\%22test\%22%2C%20{\n%20%20get%3A%20function%28%29%20{%20return%20\%22hi\%22%3B%20}%2C\n%20%20set%3A%20function%28%20arg%20%29%20{}\n}%29%3B%22}]}) of the issue.

removing side effect causing code from modules that are never imported seems like a less dangerous option compared to side effect causing code referencing variables that are never imported.

**Comment by jltrv** [comment] 2016-03-22 16:49
The problem here is that `Object.defineProperty` may have been overloaded, so considering it does not cause side effects is an unsafe optimisation.

**Comment by dtinth** [comment] 2016-05-05 05:51
Would it be possible to explicitly declare a certain Statement as side-effect free?

**Comment by bergus** [comment] 2016-07-04 12:52
@jltrv I believe that rollup can (and should) assume built-in functions not to be overloaded. Any author that uses them expects them not to be overloaded (with deviant behaviour) as well, as that would be just a bad practice.
If @calvinmetcalf's example would have read `square.test = "hi";` instead, then that assignment *could* have been overloaded as well, but rollup already assumes it's not and optimises it away.
I wholeheartedly agree with @dtinth's suggestion to allow a purity annotation for statements that rollup should ignore as global side effects.

However I would like to propose an even more aggressive optimisation behaviour. Side effects of whatever kind (i.e. basically any top-level statement that is not a declaration) should be assumed to be local to the module. If the module is not imported (due to tree-shaking), its potential side effects should be ignored. In the above example, `maths.js` does not use any of the imports from `square.js`, so the latter should be dropped completely regardless of its contents.
I think that when a module relies on the side effects of an imported module, that is only a) when it uses functionality of the import that needs this side-effect or b) when it does explicitly import the module for side effects only (`import from …;`). Everything else should be discouraged, and I wouldn't expect anything to break if rollup did use this approach.

**Comment by devinrhode2** [comment] 2016-09-25 06:13
I agree with @bergus's suggestion, however, I think it'd be best to instead tell a developer to remove the apparently dead import so rollup doesn't have to make a decision about including code with potential side effects. If a developer chooses to keep the code, then the side-effect code must be desired (Maybe it extends String.prototype with some convenience methods).

**Comment by epiloque** [comment] 2016-11-20 13:17
There is an extreme case of this issue in #1109 

### How to reproduce ?

On [rollupjs.org](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBjdWJlJTIwJTdEJTIwZnJvbSUyMCdzb21lLWJpZy1tb2R1bGUnJTNCJTVDbiU1Q25pZiUyMChmYWxzZSklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKGN1YmUoMSkpJTVDbiU3RCU1Q24lMjIlN0QlNUQlN0Q=) try 

```js
import { cube } from 'some-big-module';

if (false) {
  console.log(cube(1))
}
```

Which would result in the following:

```js
import 'some-big-module';
```

Most minifiers won't remove the above like, assuming that it has side-effects.

**Comment by epiloque** [comment] 2016-11-20 13:18
+1 for some way to declare a statement as side-effect free

**Comment by nathancahill** [comment] 2017-01-26 23:53
Using Rollup with React and setting propTypes, contextTypes or defaultProps ends up including the components. See React docs [here](https://facebook.github.io/react/docs/react-without-es6.html#declaring-prop-types-and-default-props) and [minimal example](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwT2slMjAlN0QlMjBmcm9tJTIwJy4lMkZtb2R1bGVfMSclNUNuJTVDbk9rKCklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlXzEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBPayUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwJTdCJTIwY29uc29sZS5sb2coJ0J1bmRsZSUyMHNob3VsZCUyMG5vdCUyMGluY2x1ZGUlMjBHcmVldGluZycpJTIwJTdEJTVDbmV4cG9ydCUyMGNvbnN0JTIwR3JlZXRpbmclMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU3RCU1Q24lNUNuR3JlZXRpbmcuZGVmYXVsdFByb3BzJTIwJTNEJTIwJTdCJTVDbiUyMCUyMG5hbWUlM0ElMjAnTWFyeSclNUNuJTdEJTNCJTVDbiUyMiU3RCU1RCU3RA==)

**Comment by GordonSmith** [comment] 2017-11-19 09:26
I see webpack 4 will support a ```"side-effects": false``` property in package.json, does that help this issue?

**Comment by lukastaegert** [comment] 2017-12-04 06:16
This flag is certainly interesting but looking at [this example](https://github.com/webpack/webpack/tree/next/examples/side-effects), these are issues that rollup can handle quite well without such a flag already. Nevertheless this is something we should keep an eye on. However, since this is done via `package.json` files, it would be the responsibility of `rollup-plugin-node-resolve` + some improvements to rollup to actually be able to implement this via a plugin.

For now, rollup already has an option `pureExternalModules` that can help with some of the issues described above, albeit in a "blanket" non-module-specific way.

**Comment by vanruesc** [comment] 2017-12-04 14:01
As far as I am concerned, this issue may be closed. Although I can't speak for everyone involved in this discussion, most of the tree-shaking issues that I faced have been resolved thanks to @lukastaegert 's efforts.

If there's still a need to discuss other specific problems related to tree-shaking, it might be better to do so in separate, concise issue reports ✌️

**Comment by lukastaegert** [comment] 2017-12-06 06:45
I agree. As it seems, this discussion has moved in a direction that is already covered by other issues, e.g. #1130 and #1293 . I will close this now, please open a new issue if you think there are points not covered by existing issues. BTW many (though not all) of these issues now carry the [treeshaking](https://github.com/rollup/rollup/labels/treeshaking) label.

**Closed** 2017-12-06 06:46 UTC
Labels: discussion, treeshaking
