### ISSUE TITLE
Output property is missing in options callback

### ISSUE THREAD

**Issue by AgronKabashi** [rollup/rollup#1575] opened 2017-08-23 09:29 UTC
I've noticed that the options object passed into the options callback no longer contains the output information. This sort of breaks the plugin rollup-plugin-jspicl since it needs to know the destination of the build. Tested with v0.48+

Here's a repro of the problem:

```js
// File: rollup.config.js
export default {
  input: "rollup.config.js",
  output: {
    file: "build.js",
    format: "es"
  },
  plugins: [
    {
      options: function (options) {
        console.log(options.input, options.output); // Prints "rollup.config.js undefined"
      }
    }
  ]
}
```

```
npx rollup -c
```

Am I missing something from the documentation or is this a bug? Is there a different way to access output?

**Comment by jharris4** [comment] 2017-08-23 15:59
This looks like a duplicate of what I reported in #1573

**Comment by guybedford** [comment] 2018-02-10 20:42
From what I can tell this was resolved by https://github.com/rollup/rollup/pull/1606.

**Closed by guybedford** 2018-02-10 20:42 UTC
