### ISSUE TITLE
Cannot use import statement outside a module rollup.config.js:1

### ISSUE THREAD

**Issue by jeremybradbury** [rollup/rollup#4446] opened 2022-03-18 23:20 UTC
### Rollup Version

2.3.4 & later

### Operating System (or Browser)

Windows 10

### Node Version (if applicable)

14.19 & 14.17 & 16.3

### Link To Reproduction

close me if you like, it's your issue, i can simply avoid updates

### Expected Behaviour

the build should work.

### Actual Behaviour

I was switching from node 14.17 to 14.19, then wiped modules and lock file.

```
> yarn build
yarn run v1.22.5
$ rollup -c
[!] SyntaxError: Cannot use import statement outside a module
svelte-project-folder\rollup.config.js:1
import svelte from "rollup-plugin-svelte";
```

restoring my lockfile fixed the issue. 

Pretty sure some recent changes have broken things for not just me.

feel free to ignore this and pretend like it's not a problem if you like.

**Comment by PwrSrg** [comment] 2022-03-22 14:26
**SAME issue** while testing Svelte for the very first time.

```
npx degit sveltejs/template my-svelte-project
cd my-svelte-project
npm install
npm run dev
```
![image](https://user-images.githubusercontent.com/711603/159504343-c2945a64-4f57-4a7b-87a7-05288e37b84e.png)

Windows 11
Node 17.7.2

**Comment by treebok** [comment] 2022-03-22 18:22
It's already solved. It solved itself..  I had the problem for 4 days.

**Comment by PwrSrg** [comment] 2022-03-22 20:01
> It's already solved. It solved itself.. I had the problem for 4 days.

I wish that were the case for me.  But after further debugging, the issue is somehow related to running from an SMB drive.

I will update this post as I discover more.

**Comment by treebok** [comment] 2022-03-22 22:24
![image](https://user-images.githubusercontent.com/20598648/159586237-5a332df8-7b77-4bf7-af24-1bb9709e0dec.png)

**Comment by kylescudder** [comment] 2022-03-29 12:52
> > It's already solved. It solved itself.. I had the problem for 4 days.
> 
> I wish that were the case for me. But after further debugging, the issue is somehow related to running from an SMB drive.
> 
> I will update this post as I discover more.

Thank you for this, I just moved my project to a brand new TrueNAS SMB this morning. Oh well, back we go until this is fixed I guess.

**Comment by waitingsong** [comment] 2022-04-02 06:11
I solved it with:

- upgrade node to v17 
- change file name `rollup.config.js` to `rollup.config.mjs`

OR

- keep node with v16 and file name ``rollup.config.js`
- npm install rollup@~2.66

**Comment by treebok** [comment] 2022-04-02 18:56
> 

thanks the second option worked for me:

![image](https://user-images.githubusercontent.com/20598648/161397310-ddac92b6-95cc-485c-834d-c97d57f86a79.png)

**It was solved simply running npm install rollup@~2.66** 

I had "rollup": "^2.56.2", and node 14.17.1

**Comment by Samuel-Martineau** [comment] 2022-04-18 15:22
I'm having the same issue. I'm the creator of [generator-svelte](https://github.com/Samuel-Martineau/generator-svelte) and my automatic tests, which used to pass, suddenly started to always fail, but only on Windows. The only fix I found was to convert my `rollup.config.js` to a `rollup.config.mjs` and to convert all `import` statements to `require()`.

I can only imagine that that is a bug, as the behavior should be the same on Linux, MacOS and Windows.

**Comment by lukastaegert** [comment] 2022-05-19 07:10
Can you check if this issue still persists in rollup@2.74.0?

**Comment by gooddaytoday** [comment] 2022-05-19 10:53
> Can you check if this issue still persists in rollup@2.74.0?

I have the same Issue. rollup@2.74.0 is working well and solves this for me.

**Comment by lukastaegert** [comment] 2022-05-19 12:18
Closing this for now, feel free to reopen if there are still issues

**Closed by lukastaegert** 2022-05-19 12:18 UTC
Labels: t¹ 🐞 bug, t⁸ ⋅ triage

**Comment by ghostcode** [comment] 2022-12-03 01:31
two way fix this:
1. change rollup.config.js to rollup.config.mjs
2. add "type":"module" to package.json

**Comment by a-m-dev** [comment] 2023-07-27 09:13
I have "type": "module" in my pkg.json, 
converted my config file to .mjs

Still seeing this issue!
rollup version -> "rollup": "^3.26.2"
