### ISSUE TITLE
problem of function parameter destructuring

### ISSUE THREAD

**Issue by xiechao06** [rollup/rollup#1332] opened 2017-03-13 07:43 UTC
source file:
```javascript
// main.js
const f = function ({ 你, 是, 哪, 个 }) {};
const g = function ({ a, b, c, d }) {};
let { 你, 是, 哪, 个 } = {};

console.log({ 你, 是, 哪, 个 });
console.log(f());
console.log(g());
```

output file:
```javascript
// bundle.js, generated by 'rollup main.js --format cjs -o bundle.js'
'use strict';

const f = function ({ 你: _, 是: _, 哪: _, 个: _ }) {}; // ERROR! DUPLICATE PARAMETER
const g = function ({ a, b, c, d }) {};
let { 你: _, 是: _$1, 哪: _$2, 个: _$3 } = {};

console.log({ 你: _, 是: _$1, 哪: _$2, 个: _$3 });

console.log(f());
console.log(g());
```

when executing bundle.js, error "Duplicate parameter name not allowed in this context" will be thrown.

**Comment by olsonpm** [comment] 2017-05-14 05:32
I believe rollup uses [buble](https://gitlab.com/Rich-Harris/buble) to transpile cjs bundles.  Your issue is a side-effect of that transpilation, and should be reported there.

**Comment by Rich-Harris** [comment] 2017-06-04 18:47
> I believe rollup uses buble to transpile cjs bundles

That's not correct, Bublé is only used if you use the Bublé plugin. Rollup by itself doesn't appear to introduce the duplicate parameters ([REPL](https://rollupjs.org/repl?version=0.42.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZiUyMCUzRCUyMGZ1bmN0aW9uJTIwKCU3QiUyMCVFNCVCRCVBMCUyQyUyMCVFNiU5OCVBRiUyQyUyMCVFNSU5MyVBQSUyQyUyMCVFNCVCOCVBQSUyMCU3RCklMjAlN0IlN0QlM0IlNUNuY29uc3QlMjBnJTIwJTNEJTIwZnVuY3Rpb24lMjAoJTdCJTIwYSUyQyUyMGIlMkMlMjBjJTJDJTIwZCUyMCU3RCklMjAlN0IlN0QlM0IlNUNubGV0JTIwJTdCJTIwJUU0JUJEJUEwJTJDJTIwJUU2JTk4JUFGJTJDJTIwJUU1JTkzJUFBJTJDJTIwJUU0JUI4JUFBJTIwJTdEJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglN0IlMjAlRTQlQkQlQTAlMkMlMjAlRTYlOTglQUYlMkMlMjAlRTUlOTMlQUElMkMlMjAlRTQlQjglQUElMjAlN0QpJTNCJTVDbmNvbnNvbGUubG9nKGYoKSklM0IlNUNuY29uc29sZS5sb2coZygpKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)), and for what it's worth [neither does Bublé](http://buble.surge.sh/#const%20f%20%3D%20function%20(%7B%20%E4%BD%A0%2C%20%E6%98%AF%2C%20%E5%93%AA%2C%20%E4%B8%AA%20%7D)%20%7B%7D%3B%0Aconst%20g%20%3D%20function%20(%7B%20a%2C%20b%2C%20c%2C%20d%20%7D)%20%7B%7D%3B%0Alet%20%7B%20%E4%BD%A0%2C%20%E6%98%AF%2C%20%E5%93%AA%2C%20%E4%B8%AA%20%7D%20%3D%20%7B%7D%3B%0A%0Aconsole.log(%7B%20%E4%BD%A0%2C%20%E6%98%AF%2C%20%E5%93%AA%2C%20%E4%B8%AA%20%7D)%3B%0Aconsole.log(f(%7B%7D))%3B%0Aconsole.log(g(%7B%7D))%3B), so it's not at all clear what's going on here — can you post a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) please?

**Comment by olsonpm** [comment] 2017-06-04 19:36
Ah sorry about that.  I don't remember why I thought cjs was transpiling.

The issue is a version number.  I can reproduce OP's example at [0.34.13](https://rollupjs.org/repl?version=0.34.13&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZiUyMCUzRCUyMGZ1bmN0aW9uJTIwKCU3QiUyMCVFNCVCRCVBMCUyQyUyMCVFNiU5OCVBRiUyQyUyMCVFNSU5MyVBQSUyQyUyMCVFNCVCOCVBQSUyMCU3RCklMjAlN0IlN0QlM0IlNUNuY29uc3QlMjBnJTIwJTNEJTIwZnVuY3Rpb24lMjAoJTdCJTIwYSUyQyUyMGIlMkMlMjBjJTJDJTIwZCUyMCU3RCklMjAlN0IlN0QlM0IlNUNubGV0JTIwJTdCJTIwJUU0JUJEJUEwJTJDJTIwJUU2JTk4JUFGJTJDJTIwJUU1JTkzJUFBJTJDJTIwJUU0JUI4JUFBJTIwJTdEJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglN0IlMjAlRTQlQkQlQTAlMkMlMjAlRTYlOTglQUYlMkMlMjAlRTUlOTMlQUElMkMlMjAlRTQlQjglQUElMjAlN0QpJTNCJTVDbmNvbnNvbGUubG9nKGYoKSklM0IlNUNuY29uc29sZS5sb2coZygpKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==), but not [0.35.0](https://rollupjs.org/repl?version=0.35.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIwZiUyMCUzRCUyMGZ1bmN0aW9uJTIwKCU3QiUyMCVFNCVCRCVBMCUyQyUyMCVFNiU5OCVBRiUyQyUyMCVFNSU5MyVBQSUyQyUyMCVFNCVCOCVBQSUyMCU3RCklMjAlN0IlN0QlM0IlNUNuY29uc3QlMjBnJTIwJTNEJTIwZnVuY3Rpb24lMjAoJTdCJTIwYSUyQyUyMGIlMkMlMjBjJTJDJTIwZCUyMCU3RCklMjAlN0IlN0QlM0IlNUNubGV0JTIwJTdCJTIwJUU0JUJEJUEwJTJDJTIwJUU2JTk4JUFGJTJDJTIwJUU1JTkzJUFBJTJDJTIwJUU0JUI4JUFBJTIwJTdEJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiU1Q25jb25zb2xlLmxvZyglN0IlMjAlRTQlQkQlQTAlMkMlMjAlRTYlOTglQUYlMkMlMjAlRTUlOTMlQUElMkMlMjAlRTQlQjglQUElMjAlN0QpJTNCJTVDbmNvbnNvbGUubG9nKGYoKSklM0IlNUNuY29uc29sZS5sb2coZygpKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

So the solution is to update rollup.

**Comment by Rich-Harris** [comment] 2017-06-04 19:39
Ah, great, we can close this then. Thanks

**Closed by Rich-Harris** 2017-06-04 19:39 UTC
Labels: needs repro
