### ISSUE TITLE
Exports without side effects removed from emitted chunk with implicitlyLoadedAfterOneOf

### ISSUE THREAD

**Issue by LarsDenBakker** [rollup/rollup#3683] opened 2020-07-20 12:48 UTC
- Rollup Version: 2.22.1
- Operating System (or Browser): Chrome
- Node Version (if applicable): Not sure...
- Link to reproduction (IMPORTANT, read below): https://repl.it/repls/HelplessUnwrittenConfiguration

### Expected Behavior
An emitted chunk which uses `implicitlyLoadedAfterOneOf` preserves exports.

### Actual Behavior
When using the `implicitlyLoadedAfterOneOf`, the exports of the chunk are removed if they did not contain any side effects.

I'm guessing this is a side effect of making the chunk act like a dynamically imported chunk, and I could see where this would be a useful for some projects. However I'm emitting chunks manually which only reexport from other modules. These exports need to be available at runtime, as they're going to be used by separately deployed modules.

**Comment by lukastaegert** [comment] 2020-07-20 12:58
Interestingly I think you might happen to have found a bug here. At least for me, if you directly write an export `export const foo = 'bar';` it works. It is reexports that seem to be swallowed.

**Comment by LarsDenBakker** [comment] 2020-07-20 13:01
Ah yes indeed, that seems to work fine. 

Introducing a side effect on the exported variables also preserves the export:

```js
      load(id) {
        if (id === 'manual') {
          return `import { foo } from "${path.resolve("src/shared.js")}"; console.log(foo); export { foo }`;
        }
      }
```

**Comment by LarsDenBakker** [comment] 2020-07-20 13:13
When there are two emitted chunks which share a common dependency, it throws an error:

https://repl.it/@LarsDenBakker/rollup-repro

It seems related because when I add a side effect the error goes away:

https://repl.it/@LarsDenBakker/rollup-repro-1

**Comment by lukastaegert** [comment] 2020-07-22 04:36
Thanks for spotting this one, fix at #3688. The problem was that even though all exports of implicit dependencies were properly included, there was a bug in the module dependency wiring logic that is running as a pre-processing step before the chunk generation: If a variable was reexported from another module, that module was not automatically designated as a necessary static dependency of the implicit entry point. This is fixed now.

**Closed** 2020-07-22 04:38 UTC
Labels: t¹ 🐞 bug

**Comment by LarsDenBakker** [comment] 2020-07-23 14:55
@lukastaegert thanks a lot!

**Comment by dasa** [comment] 2020-07-30 00:27
I think I'm still running into a similar issue, but with namespaces, where if the import is not used, it's missing, and then the namespace has an invalid reference. It's fixed if I add a `console.log` like above, but so far I haven't been able to create a repro test case, but I was hoping maybe either of you would have an idea 🙏🏻

**Comment by lukastaegert** [comment] 2020-07-30 05:13
I would say a proper reproduction on recent Rollup would help
