### ISSUE TITLE
export * cause variable collision

### ISSUE THREAD

**Issue by hightopo** [rollup/rollup#1580] opened 2017-08-25 11:48 UTC
I'm running into a variable not getting renamed and colliding with an import, look like the same issue as https://github.com/rollup/rollup/issues/1550, but in that thread it said this issue is fixed in 0.47.3, but when i try version 0.48.2, the problem is still there. 

You can reproduce the bug by the following link:

https://rollupjs.org/repl?version=0.48.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGIlMjBmcm9tJTIwJy4lMkZiLmpzJyUzQiU1Q24lNUNuZnVuY3Rpb24lMjB0ZXN0KCklMjAlN0IlNUNuJTVDdCUyMGxldCUyMHRlc3QlMjAlM0QlMjBiLnRlc3QoKSUzQiU1Q24lNUN0JTIwbGV0JTIwdGVzdHMlMjAlM0QlMjBiLnRlc3RzKCklM0IlNUNuJTVDdHJldHVybiUyMHRlc3QlMjAtJTIwdGVzdHMlM0IlNUNuJTdEJTVDbmNvbnNvbGUubG9nKHRlc3QoKSklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMHRlc3QoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwMSUzQiU1Q24lN0QlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjB0ZXN0cygpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjAyJTNCJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJy4lMkZhLmpzJyUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJ1bWQlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

main.js:  
```js
    import * as b from './b.js';  

    function test() {
         let test = b.test();
         let tests = b.tests();
        return test - tests;
    }
    console.log(test());`  
```

a.js:
```js
    export function test() {
        return 1;
    }
    export function tests() {
        return 2;
    }
```
 
output:
```js
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    (factory());
}(this, (function () { 'use strict';

function test$1() {
    return 1;
}
function tests() {
    return 2;
}
function test() {
     let test = test$1();
     let tests = tests(); // collide here!!!
    return test - tests;
}
console.log(test());
})));
})));

```
Thanks for your help!

**Comment by guybedford** [comment] 2018-02-10 14:23
This is a duplicate of #1338.

**Closed by guybedford** 2018-02-10 14:23 UTC
Labels: bug, scope-hoisting
