### ISSUE TITLE
Broken `ansi-styles` produced by latest `@rollup/plugin-commonjs`

### ISSUE THREAD

**Issue by coderaiser** [rollup/rollup#4882] opened 2023-02-27 09:55 UTC
### Rollup Version

3.17.3

### Operating System (or Browser)

darwin

### Node Version (if applicable)

18

### Link To Reproduction

To reproduce you can clone the repository: https://github.com/putoutjs/bundle, update `@rollup/plugin-common` to latest version, then `npm install && npm run build && node bundle/putout.js` will produce an error (there is no error in `@rollup/plugin-common` v22)

### Expected Behaviour

I'm using `chalk`, and it has dependency [`ansi-styles`](
https://github.com/chalk/ansi-styles/blob/v4.3.0/index.js), it works good with `@rollup/plugin-commonjs@22`, but I have issues using `@rollup/plugin-commonjs@23` (same with v24) it converts the code to something like this (simplified a bit):

```js
function requireAnsiStyles () {
	if (hasRequiredAnsiStyles) return ansiStylesExports;
	hasRequiredAnsiStyles = 1;
	(function (module) {
		function assembleStyles() {
			const styles = {
			};

			return styles;
		}

		// Make the export immutable
		Object.defineProperty(module, 'exports', {
			enumerable: true,
			get: assembleStyles
		});
} (ansiStyles));
	return ansiStylesExports;
}
```

So `ansiStylesExports` never assigned so it is an empty object.

In opposite `@rollup/plugin-commonjs@22` produces next code (simplified):

```js
function requireAnsiStyles () {
	if (hasRequiredAnsiStyles) return ansiStyles.exports;
	hasRequiredAnsiStyles = 1;
	(function (module) {
		function assembleStyles() {
			const codes = new Map();
			const styles = {

			return styles;
		}

		// Make the export immutable
		Object.defineProperty(module, 'exports', {
			enumerable: true,
			get: assembleStyles
		});
} (ansiStyles));
	return ansiStyles.exports;
}
```

Maybe I missing something in configuration, could you please help me with this?

I use `chalk@4` because I need a [Yarn Berry](https://github.com/yarnpkg/berry/issues/3879#issuecomment-1061274668) support and deduplication.

### Actual Behaviour

`ansy-styles` produces in `@rollup/plugin-commonjs@24` in the same way as it was in `@rollup/plugin-commonjs@22`.

Related to https://github.com/rollup/plugins/issues/1446

**Comment by Versirity** [comment] 2023-03-07 03:25
I have the same problem. Is there a temporary solution?

**Comment by coderaiser** [comment] 2023-03-07 09:12
I created a file `lib/chalk.js`:

```js
export default () => {};
```

And used `alias`:

```js
alias({
    entries: [
        {find: 'chalk', replacement: './lib/chalk.js'},
    ]
});
```

Here is how it looks like: [@putout/bundle](https://github.com/putoutjs/bundle/blob/v1.7.1/rollup.config.js#L22).

**Comment by Versirity** [comment] 2023-03-08 02:53
> I created a file `lib/chalk.js`:
> 
> ```js
> export default () => {};
> ```
> 
> And used `alias`:
> 
> ```js
> alias({
>     entries: [
>         {find: 'chalk', replacement: './lib/chalk.js'},
>     ]
> });
> ```
> 
> Here is how it looks like: [@putout/bundle](https://github.com/putoutjs/bundle/blob/v1.7.1/rollup.config.js#L22).

It works for me,thanks.

**Comment by maecapozzi** [comment] 2023-03-09 16:20
Does this workaround only work if `chalk` isn't used when `jsondiffpatch` is invoked?

**Comment by lukastaegert** [comment] 2023-03-15 05:43
I tried the reproduction but it did not seem to be broken for me. In any case from the described problems, rollup/plugins#1455 should fix this. I released a beta version for easier testing, could you please verify that the issue is resolved with @rollup/plugin-commonjs@24.1.0-0 ?

**Comment by lukastaegert** [comment] 2023-03-15 05:48
Ah, the last commits in your reproduction add the fix discussed above. If I go back to before that commit, I can see the error and can confirm that the new plugin version would fix it.

**Closed** 2023-04-11 19:27 UTC
Labels: t¹ 🐞 bug, t⁸ ⋅ triage
