### ISSUE TITLE
Using cache parameters will cause the next compilation to freeze

### ISSUE THREAD

**Issue by sbfkcel** [rollup/rollup#2371] opened 2018-08-03 06:23 UTC
rollup Ver：0.63.5

Normal when the cache is null. When the cache has a value, it will die.

---

```javascript
global.rollupCache = global.rollupCache || {};
let src = './main.jsx',
    rollup = require('rollup'),
    cache = global.rollupCache[src] ? global.rollupCache[src] : null ;

rollup.rollup({
  input:src,
  cache:cache,
  plugins:[]
}).then(result => {
  global.rollupCache[src] = result.cache;
});
```

---

- `npm run dev`
- Try again to modify `index.tsx` and it will not compile again.

[rollupTest.zip](https://github.com/rollup/rollup/files/2257087/rollupTest.zip)

**Comment by guybedford** [comment] 2018-08-03 12:50
I had a look at this and it seems like the issue is that the rollup-typescript2 plugin is never resolving the `transform` promise when run a second time.

I'd suggest confirming this, by testing the same workflow without the rollup-typescript2 plugin and demonstrating that it works fine. Then posting an issue to that project.

**Comment by sbfkcel** [comment] 2018-08-04 01:55
Even if `rollup-plugin-typescript` is removed, the problem still exists.

**Test example:**

[rollupTest.zip](https://github.com/rollup/rollup/files/2259141/rollupTest.zip)

But in rollup 0.56.3 everything works fine. However, the compilation speed has not improved significantly.

**Comment by sbfkcel** [comment] 2018-08-04 03:32
It seems that there are some exceptions in `rollup-plugin-commonjs 9.1.4`.

will
`rollup-plugin-typescript2` is replaced with `rollup-plugin-typescript`
`rollup-plugin-commonjs 9.1.4` is replaced with `rollup-plugin-commonjs 8.3.0`. Normal


Unfortunately, `rollup-plugin-typescript` also has many problems.

**Comment by guybedford** [comment] 2018-08-06 08:33
@sbfkcel are you staying the stalling behaviour is from rollup-plugin-commonjs then? If so, let's set an issue there to track further.

**Comment by guybedford** [comment] 2018-08-06 08:34
(but please lets be sure of the isolation first, and try to get the absolute minimal replication - I already spent 20 minutes just ruling out Rollup core :) !)

**Comment by porsager** [comment] 2018-08-09 07:54
I just experienced the same with a project, and it appears to be a regression in `rollup-plugin-commonjs` v 9.1.1

I'll create an issue there to track this instead ;)

**Comment by guybedford** [comment] 2018-08-09 17:35
Ok great to know which plugin it is. Let's track on the plugin page as this is clearly a plugin bug.

**Closed by guybedford** 2018-08-09 17:35 UTC

**Comment by joeyhub** [comment] 2019-12-03 22:46
I'm still getting this problem.
