### ISSUE TITLE
namespaced imports with same name as local identifier causes runtime error when namespace is removed by rollup

### ISSUE THREAD

**Issue by tomkel** [rollup/rollup#1783] opened 2017-12-08 18:01 UTC
~~I was unable to create a minimal repro, but [here](https://rollupjs.org/repl?version=0.52.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHV0aWwlMjBmcm9tJTIwJy4lMkZ1dGlsJyU1Q24lNUNuZnVuY3Rpb24lMjBtYWluKCklMjAlN0IlNUNuJTIwJTIwY29uc3QlMjBoZWFkJTIwJTNEJTIwdXRpbC5oZWFkKCU1QjElMkMyJTJDMyUyQzQlMkM1JTVEKSU1Q24lNUN0Y29uc29sZS5sb2coaGVhZCklNUNuJTdEJTVDbiU1Q25tYWluKCklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIydXRpbC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBmdW5jdGlvbiUyMGhlYWQobGlzdCklMjAlN0IlNUNuJTVDdHJldHVybiUyMGxpc3QlNUIwJTVEJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJpaWZlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=) is an example of what my code does.~~(see below)

My rolled up main() looks like 
```
function main() {
  const head = head([1,2,3,4,5]);
  console.log(head);
}
```
where the `const head` identifier isn't changed, so it throws an error that head is undefined.

**Comment by kzc** [comment] 2017-12-08 18:25
Your example link appears to work in version 0.52.1.

**Comment by tomkel** [comment] 2017-12-08 18:25
Here is an actual repro:
https://github.com/tomkel/rollup-bug-1783

**Comment by deckar01** [comment] 2018-01-03 18:39
I was able to reproduce the bug on 0.53.3 using @tomkel's repro repo. The issue is difficult to reproduce. I tried to boil my use case down, but it magically started working. That is frustrating.

**Comment by guybedford** [comment] 2018-02-10 12:22
Here's the reproduction in the repl - https://rollupjs.org/repl?version=0.55.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMFIlMjBmcm9tJTIwJ3JhbWRhJyUzQiU1Q24lNUNuZnVuY3Rpb24lMjBtYWluKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjBoZWFkJTIwJTNEJTIwUi5oZWFkKCU1QjElMkMyJTJDMyUyQzQlMkM1JTVEKSU1Q24lMjAlMjAlMjAlMjBjb25zb2xlLmxvZyhoZWFkKSU1Q24lN0QlNUNuJTVDbm1haW4oKSUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJuYW1lJTIyJTNBJTIybWFpbiUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=

Which seems to be working. Closing, but let me know if this is not the case.

**Closed by guybedford** 2018-02-10 12:22 UTC

**Comment by tomkel** [comment] 2018-02-10 19:03
@guybedford Please reopen this, you can still repro this in latest rollup using this repo: https://github.com/tomkel/rollup-bug-1783

**Comment by guybedford** [comment] 2018-02-10 19:13
@tomkel thanks for the update. You're right in that it's not working in the current release, although looking again it just so happens the actual bug is a duplicate of #1338 which I fixed earlier today in https://github.com/rollup/rollup/pull/1960 for the next release (just tested it now and the fix does work too).

**Comment by tomkel** [comment] 2018-02-10 19:42
Thank you!!
