### ISSUE TITLE
Using `preserveModules` unexpectedly removes some exports

### ISSUE THREAD

**Issue by daleyjem** [rollup/rollup#3113] opened 2019-09-12 14:52 UTC
### Summary

Certain exports come up missing when using the `preserveModules: true` option, but are present as expected when bundling to one single file.

### Specs

- Rollup Version: 1.21.2
- Operating System (or Browser): Mac OSX
- Node Version: 11.12.0

### How Do We Reproduce?

Please see the following example repo: https://github.com/daleyjem/rollup-preserve-modules

I've included 2 generated `dist-bundled` and `dist-preserved` folders in the repo for quick review, but you can certainly pull the repo down and test bundling for yourself what actually gets generated.

### Expected Behavior

Bundled files should include correct imports/exports. 

For both single-file bundle and `preservedModules`, `foo` and `baz` should both be exported from entry file.

### Actual Behavior

Bundled entry file is missing some exports.

**For single-file bundle:** `foo` and `baz` are both exported
**For preserved:** `foo` has been removed from being exported

**Comment by lukastaegert** [comment] 2019-09-13 15:41
Looks like a bug to me, thanks for reporting!

**Comment by daleyjem** [comment] 2019-09-13 16:00
Thank you for confirming, @lukastaegert

**Comment by myklt** [comment] 2019-10-01 08:26
I had very similar issue. A quick workaround was to import the module assign to a variable and then export.

**Comment by cacheflow** [comment] 2019-12-03 08:35
I was looking into this issue as well and noticed that it only occurs when you try to export the same imported modules with the same name as @myklt said. However, if you store the imported modules as variables and export those, then everything works. 

At first I thought it had something to do with the `generateIdPreserveModules` in `Chunk.ts`, but I'm not too sure. I noticed that in `assignChunksToBundle` the exported modules remain and it isn't dropped until `chunk.render` is called that the module gets dropped for some reason. 🤷‍♂ 

https://github.com/cacheflow/rollup-preserve-modules-with-vars

**Comment by lukastaegert** [comment] 2019-12-05 14:43
I have identified the issue and have a possible fix, but I want to think a little more about if there are additional implications or alternative solutions.

At its core, the problem is this:
- We assume you have modules A, B, C, where C exports `foo`, B reexports it, and A imports it from B
- Further assume that A, B, C end up in different chunks. This is always the case when we are preserving modules.
- Then Rollup would short-circuit the import so that A imports `foo` directly from C.
- For that to be rendered correctly, the chunk of C needs to become a direct dependency of the chunk of A. This is taken care of if B uses a direct reexport, i.e.
  ```js
  export {foo}  from 'C';
  ```
  However it is not taken care of if you do it in two steps
    ```js
  import {foo}  from 'C';
  export {foo};
  ```
  This was an oversight in the original implementation.
- Why did this never turn up until now? Because for non-preserveModules situations, we "fix" this situation, at least for entry chunks, by inlining all transitive dependencies into the chunk. For A this would of course include C.

I have a fix prepared which will also check the exports of a module for reexports from different modules, but as I have little time today, it may take a few more days to merge.

**Closed** 2019-12-07 20:16 UTC
Labels: s² 🔥🔥 important, t¹ 🐞 bug
