### ISSUE TITLE
Make module ordering adhere to spec

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup#435] opened 2016-01-07 14:42 UTC
The [spec](https://tc39.github.io/ecma262/#sec-moduleevaluation) is clear on the order in which modules should be evaluated:

```js
// main.js
import a from './a.js';
import b from './b.js';

// a.js
import c from './c.js';
export default 'a';

// b.js
import d from './d.js';
export default 'b';

// c.js
export default 'c';

// d.js
export default 'd';
```

In the example above, starting at `main.js`, the order is `[c, a, d, b, main]`, because a module's imports are evaluated before the module itself. 

Because Rollup is a bundler and not a loader, it doesn't evaluate modules – instead, we sort the modules in such a way that they are eventually executed in the correct order.

Right now, we're not adhering to the spec. [While we usually end up with the correct order](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20'.%2Fa.js'%3B%5Cnimport%20'.%2Fb.js'%3B%5Cn%5Cnconsole.log('evaluating%20main')%3B%22%7D%2C%7B%22name%22%3A%22a.js%22%2C%22code%22%3A%22import%20'.%2Fc.js'%3B%5Cnconsole.log('evaluating%20a')%3B%22%7D%2C%7B%22name%22%3A%22b.js%22%2C%22code%22%3A%22import%20'.%2Fd.js'%3B%5Cnconsole.log('evaluating%20b')%3B%22%7D%2C%7B%22name%22%3A%22c.js%22%2C%22code%22%3A%22console.log('evaluating%20c')%3B%22%7D%2C%7B%22name%22%3A%22d.js%22%2C%22code%22%3A%22console.log('evaluating%20d')%3B%22%7D%5D%7D), when we have situations like this...

```js
// A.js
import B from './B.js';
export class A extends B {}

// B.js
import A from './A.js';
export class B {
  a () {
    return new A();
  }
}
```

...we ensure that B appears before A, regardless of the order in which they're imported, because while they both depend on each other, A *strongly* depends on B – it can't execute until B has executed.

Ultimately, this isn't helpful insofar as it allows people to write code that will fail when used with a real module loader, so we should be less clever and use the more straightforward ordering (which will also fix #335). We can, however, detect these situations and maybe print some helpful information at bundling time:

```
[ROLLUP]: Module /path/to/a.js depends on /path/to/b.js, but will be evaluated first due
to the order of imports. This may cause a runtime error – consider swapping lines 3 and
6 in /path/to/main.js. See https://github.com/rollup/rollup/wiki/Troubleshooting#cycles
for more information.
```

**Comment by eventualbuddha** [comment] 2016-01-07 15:26
👍🏻, especially the error message.

**Comment by Victorystick** [comment] 2016-01-07 20:06
It's a shame that we can't "fix" those parts of the module execution order; but good if we could inform the users of the issue if they encounter it.

I suppose that makes the execution order of imports _very_ similar to CommonJS `require` calls? Transpiling `import`s to `require`s should map pretty well.

**Comment by rosskevin** [comment] 2016-01-08 15:45
In the babelHelpers_inherits, I'm getting `Uncaught TypeError: Super expression must either be null or a function, not undefined`.  The superclass for `Switch` is not yet defined (3 deep hierarchy), even though my `index.js` imports the superclasses in order.  Regardless of my index.js order, rollup sticks Switch's definition (using `iife`) right after the base classes.

Here's my index.js

```
import '../../node_modules/babel-polyfill/dist/polyfill'

import Base from './base'
import BaseInput from './baseInput'
import BaseFormControl from './baseFormControl'
import BaseSelection from './baseSelection'
import Util from './util'

import Checkbox from './checkbox'
import CheckboxInline from './checkboxInline'
import CollapseInline from './collapseInline'
import File from './file'
import Radio from './radio'
import RadioInline from './radioInline'
import Select from './select'
import Switch from './switch'
import Text from './text'
import Textarea from './textarea'

import Ripples from './ripples'
import Autofill from './autofill'
import BootstrapMaterialDesign from './bootstrapMaterialDesign'
```
Hierarchy of Switch is:
```
Switch -> Checkbox -> BaseSelection -> BaseInput -> Base
```

This popped up on me after adding what seems to be an unrelated class (it was working prior).  Is there a way to force the ordering?  I'm up a river without a paddle now...

**Comment by N1kto** [comment] 2016-07-22 12:33
Hello. Faced an issue with modules ordering in generated bundle. 

Not sure if this is a problem of rollup ordering logic or of the weird cyclical dependency of the [package](https://github.com/fb55/htmlparser2) I try to consume. Anyways will be thankful if anybody could give a hint to what could be the possible root cause of the problem and ways to tackle it.

More details of below short summary can be found in [this](https://gist.github.com/N1kto/0646a9a06e2ddf1dec4ff54519cfbf30) gist.

#### Short summary
I am trying to prepare a bundle of [slate](https://github.com/ianstormtaylor/slate) editor. One of its dependencies is [cheerio](https://github.com/cheeriojs/cheerio), which in return depends on [htmlparser2](https://github.com/fb55/htmlparser2).

So, main file of *htmlparser2*, `index.js`, makes following export:
```
module.exports = {
    .......
	get FeedHandler(){
		return defineProp("FeedHandler", require("./FeedHandler.js"));
	},
	.......
}
```
`FeedHandler.js` in its turn starts with the following lines:
```
var index = require("./index.js"),

    DomHandler = index.DomHandler,
	DomUtils = index.DomUtils;
```
It looks like cyclical dependency. 

When I try to consume generated bundle, I get an error `Uncaught TypeError: Cannot read property 'DomHandler' of undefined` which comes from this place:
```
var FeedHandler$1 = createCommonjsModule(function (module) {
    var index = interopDefault(require$$0$69),
        DomHandler = index.DomHandler,
    	DomUtils = index.DomUtils;
```
It comes because `require$$0$69` is `undefined`. And it is `undefined` because `require$$0$69` is actually defined  2k lines below this place:
```
var require$$0$69 = Object.freeze({
    	...
    	FeedHandler: FeedHandler,
    	...
    });
```

**Comment by Victorystick** [comment] 2016-07-23 19:17
@N1kto This appears to be related to the CommonJS plugin rather than Rollup itself.

**Comment by N1kto** [comment] 2016-07-24 16:17
@Victorystick could you give more details? I will open issue there (in commonjs repo) in that case

**Comment by Victorystick** [comment] 2016-07-25 16:05
@N1kto _htmlparser2_'s index file attempts to lazily load `FeedHandler` through a nested `require` call. The "import" is highly dynamic and the exection order is only knowable at runtime. Rollup's CommonJS plugin will transform the dynamic, nested `require` into a static, top-level `import` which likely is what caused the errors you're describing.

**Comment by DVLP** [comment] 2016-09-30 10:09
`// A.js
import B from './B.js';
export class A extends B {}

// B.js
import A from './A.js';
export class B {
  a () {
    return new A();
  }
}`

This doesn't work like that in my project. For some reason with similar structure B definition is still after A and I'm getting reference error: B is undefined. Temporarily I removed dependency of A inside B (it was only used to check something using `obj instanceof A`) and replaced with `obj.constructor.name === 'A'`

**Comment by Victorystick** [comment] 2016-10-03 17:37
See [this reproduction](http://rollupjs.org/?version=0.36.1&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBleHBvcnQlMjAlN0JBJTdEJTIwZnJvbSUyMCcuJTJGQS5qcyclM0IlNUNuZXhwb3J0JTIwJTdCQiU3RCUyMGZyb20lMjAnLiUyRkIuanMnJTNCJTVDbmV4cG9ydCUyMCU3QkElN0QlMjBmcm9tJTIwJy4lMkZBLmpzJyUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJCLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QkElN0QlMjBmcm9tJTIwJy4lMkZBLmpzJyUzQiU1Q25leHBvcnQlMjBjbGFzcyUyMEIlMjAlN0IlNUNuJTIwJTIwYSgpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMG5ldyUyMEEoKSUzQiU1Q24lMjAlMjAlN0QlNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMkEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCQiU3RCUyMGZyb20lMjAnLiUyRkIuanMnJTNCJTVDbmV4cG9ydCUyMGNsYXNzJTIwQSUyMGV4dGVuZHMlMjBCJTIwJTdCJTdEJTIyJTdEJTVEJTdE) of the issue. Successful execution of the resulting bundle depends on the order in which the modules are imported. Closing this in favor of #995.

**Closed by Victorystick** 2016-10-03 17:37 UTC
Labels: bug
