### ISSUE TITLE
Weird sourcemaps

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#745] opened 2016-06-23 10:01 UTC
Threw out thousands lines of my project code and got this minimal structure which logs in wrong line and file.
[rollup-sourcemaps.zip](https://github.com/rollup/rollup/files/329644/rollup-sourcemaps.zip)

**Comment by Rich-Harris** [comment] 2016-06-23 15:00
Looks like a dupe of #668 – looking into it now

**Closed by Rich-Harris** 2016-06-23 15:00 UTC

**Comment by Rich-Harris** [comment] 2016-06-23 15:34
fixed in 0.32.3

**Comment by TrySound** [comment] 2016-06-23 15:34
Thanks!

**Comment by TrySound** [comment] 2016-06-23 15:36
Yay! It works!:)
