### ISSUE TITLE
Self module reference is undefined

### ISSUE THREAD

**Issue by alexi2014** [rollup/rollup#1935] opened 2018-02-01 19:32 UTC
The issue with the impossibility to bundle modules with self module references represented by PR [https://github.com/rollup/rollup/pull/1777](https://github.com/rollup/rollup/pull/1777) has been fixed in build 0.52.2. Nevertheless, the obtained self reference is **undefined**. The following code
```
// script.js
import * as mSelf from './script.js';
console.log(`mSelf is ${mSelf ? 'Defined' : 'Undefined'}`);
```
will produce the following output:
> mSelf is Undefined

, which is wrong because it should be a reference to this module.
To compare, if to run this natively in **Chrome**, the output will be
> mSelf is Defined

, and mSelf will contain the module reference. This is demonstrated in the following plunker:
[https://plnkr.co/edit/WN7qTXdAdnAxZaDgaJaS?p=preview](https://plnkr.co/edit/WN7qTXdAdnAxZaDgaJaS?p=preview)
The same correct result will be produced by an app bundled by Webpack.

I attached the sample demonstrating the problem (modules are in CommonJS format there).
The code for script.js is as follows:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var mSelf = require('./script.js');
console.log(`mSelf is ${mSelf ? 'Defined' : 'Undefined'}`);
var MyClass = (function () {
    function MyClass() {
    }
    return MyClass;
}());
exports.MyClass = MyClass;
```
, and the relevant part of this code in the generated bundle looks like
```
var script$$1 = createCommonjsModule(function (module, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });

    console.log(`mSelf is ${script$$1 ? 'Defined' : 'Undefined'}`);
    var MyClass = (function () {
        function MyClass() {
        }
        return MyClass;
    }());
    exports.MyClass = MyClass;
});
```
As you see, the var script$$1 will not be initialized until the exit from the createCommonjsModule function, so inside the callback function it's undefined.
The simplest (not sure if the best) fix for this is to add the following line of code to the callback function:
```
var script$$1 = createCommonjsModule(function (module, exports) {
    script$$1 = module; // <-- ADD THIS LINE
```

**Comment by alexi2014** [comment] 2018-02-01 19:35
Forgot the attachement:
[Rollup_SelfModule.zip](https://github.com/rollup/rollup/files/1686915/Rollup_SelfModule.zip)

**Comment by alexi2014** [comment] 2018-02-02 13:36
Sorry, it was a typo here:
```
var script$$1 = createCommonjsModule(function (module, exports) {
    script$$1 = module; // <-- ADD THIS LINE
```
It should look like:
```
var script$$1 = createCommonjsModule(function (module, exports) {
    script$$1 = exports; // <-- ADD THIS LINE
```

**Comment by guybedford** [comment] 2018-02-03 12:12
I can confirm this with repl replication - https://rollupjs.org/repl?version=0.55.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHNlbGYlMjBmcm9tJTIwJy4lMkZtYWluLmpzJyUzQiU1Q24lNUNuZXhwb3J0JTIwdmFyJTIwcCUyMCUzRCUyMDUlM0IlNUNuJTVDbmNvbnNvbGUubG9nKHNlbGYpJTNCJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

The issue is that the self variable is created at the end of the module to have all the export references, but the usages may come before that.

This may require altering the way a namespace is output, with a frozen empty object created at the top of the module with blank export names, then having exports defined into the namespace module as they are made. It may be easier in the process to just remove the `object.freeze` and have the module.exports match the namespace object exactly.

This isn't a trivial fix to make unfortunately, so will leave this open to track.

**Comment by alexi2014** [comment] 2018-02-06 13:51
Thanks for checking this!
I think that as an immediate quick workaround returning the module reference (in any way) is way better that returning an undefined value. This is a responsibility of the module that uses self reference to be aware of and correctly process its incompleteness. 

Regarding the "true" implementation of this stuff that you described - I'm sorry, I'm not sure that I correctly understood all the details of your suggestion. So I would like to emphasize one point, to make sure that we are on the same plate - the self module reference and the reference to this module obtained by an external module should be equal. I.e. with this piece of code
```
// script.js
import * as mSelf from './script.js';
export var selfRef = mSelf;

// app.js
import * as extRef from './script.js';
// 'extRef === extRef.selfRef' resolves to true here in Chrome
console.log(`extRef and selfRef are ${extRef === extRef.selfRef ? 'EQUAL': 'DIFFERENT'}`);
```
, if you load app.js, the output in the console should be:

> extRef and selfRef are EQUAL

I'm just not sure whether this is supposed by your proposal or not, so I want to make an accent on this nuance.

The live example of the code above is in this plunk (should be run in Chrome):
[https://plnkr.co/edit/sJNp84FSSfciQSNqvnzz](https://plnkr.co/edit/sJNp84FSSfciQSNqvnzz)

**Comment by alexi2014** [comment] 2018-02-06 14:12
Just to clarify a bit my anxieties. From your explanation I made a conclusion that you want to first create a temporary object that will be returned as a result of a self import, and then return another object that will represent a completely initialized module. If this is the case then it will not work, it should be the same object. But probably I just misunderstood you.

**Comment by guybedford** [comment] 2018-02-06 14:29
@alexi2014 yes I'm referring to it exactly becoming the same object.

**Comment by alexi2014** [comment] 2018-02-06 14:31
@guybedford Nice, thanks for the clarification.

**Comment by guybedford** [comment] 2018-03-27 22:47
This was resolved in https://github.com/rollup/rollup/pull/2041.

**Closed by guybedford** 2018-03-27 22:47 UTC
Labels: bug, scope-hoisting
