### ISSUE TITLE
Rollup watch only one config in exported array

### ISSUE THREAD

**Issue by luwol03** [rollup/rollup#3607] opened 2020-05-29 08:51 UTC
### Feature Use Case
If you have e.g. four diffrent configs in an array to build by typing ```rollup -c``` and if you add the ```-w``` parameter to watch these configs, I find no way to build only one version.

### Feature Proposal
My first idea was to set 
```js
watch: false,
```
but it doesen't worked, I think this is a good idea to handle these case.

**Comment by lukastaegert** [comment] 2020-05-29 19:32
Adding `watch: false` as a way to exclude certain configs from watch mode is actually a good idea and should be easy to implement. I would say PR welcome, the changes should be mostly filtering here https://github.com/rollup/rollup/blob/2040f82cea21f615a10ba47264ade9237918a847/src/watch/watch.ts#L31, adjusting the types here https://github.com/rollup/rollup/blob/master/src/rollup/types.d.ts and adjusting the docs here https://rollupjs.org/guide/en/#watchoptions

**Comment by lukastaegert** [comment] 2020-05-29 19:36
Most work will probably setting up a test, for this one, adding one in this file would probably fit best: https://github.com/rollup/rollup/blob/master/test/watch/index.js

There are already tests for multi-config scenarios here.

**Comment by luwol03** [comment] 2020-05-30 22:32
Ok, I will try this on Monday. But I have no idea, how I can insert it into the docs. My first idea, was to add two | after the } like this: 
![IMG_20200530_235655](https://user-images.githubusercontent.com/60048565/83339813-5c61cf80-a2d1-11ea-9a70-5ebc56877d79.png) and in the big list of all opinions file: 
![IMG_20200531_002611](https://user-images.githubusercontent.com/60048565/83340189-79989d00-a2d5-11ea-95c5-e34bbd419e7a.png) I admit, documentation is not mine. what would you say is that ok?

And one last question for now: How long does it take after a pull request is merged until I can get the changes via `npm update`?

**Comment by lukastaegert** [comment] 2020-05-31 03:58
In the types, I would use

```ts
watch: {
  buildDelay,
  ...
  include
} | boolean
```

with a single `|`. This is following how TypeScript writes these kind of types and though we do not follow TypeScript strictly here, this is more in line with how we specify types in the last section.

For the second part, I would take a look at the documentation `--treeshake` option that is very similar in its structure. Basically it does not use `object` but explicitly specifies the type. This might not be easily readable, though, so we could also leave it like this.

More importantly, I would insert a sentence to summarize what the option does before going into when to use it, maybe like this:

```
Default: true

Specify options for watch mode or prevent this configuration from being watched. Specifying `false` is only really useful when an array of configurations is used. In that case, this configuration will not be built or rebuilt on change in watch mode, but it will be built when running Rollup regularly.
```

The example Rollup config should also ideally contain an array, how about something like this

```js
// rollup.config.js
export default [
  {
    input: 'main.js',
    output: { file: 'bundle.js', format: 'es' }
  },
  {
    input: 'other.js',
    watch: false,
    output: { file: 'other-bundle.js', format: 'es' }
  }
]
```

One last thing I noticed: At the moment, the logic here https://github.com/rollup/rollup/blob/2040f82cea21f615a10ba47264ade9237918a847/src/utils/options/mergeOptions.ts#L118 will override a value of `watch: false` with an empty object if `--watch` is specified on the command line. The reason is that CLI options usually take precedence, but this would be an exception. This needs to be changed, but without modifying `getObjectOption` as `treeshake` also relies on this. How about a special handler `getWatch` that returns `false` if the config option is `false` and only otherwise calls `getObjectOption`?

**Comment by lukastaegert** [comment] 2020-05-31 03:59
> And one last question for now: How long does it take after a pull request is merged until I can get the changes via npm update?

In this repo I usually try to release non-breaking changes within a day.

**Comment by luwol03** [comment] 2020-06-01 09:38
i am currently working on this change, and have a question, is it normal that when i build it, it always updates the license file this way?
![image](https://user-images.githubusercontent.com/60048565/83396528-68967b80-a3fc-11ea-9fe6-dbf0371259fb.png)

**Comment by lukastaegert** [comment] 2020-06-01 13:35
That depends how you installed your dependencies. For some reason, the license file looks slightly differently with regard to repositories if you used `npm install` vs. `npm ci` to install the dependencies. I prefer using `npm ci`. Also it is faster and will never modify the lock file.

**Comment by luwol03** [comment] 2020-06-01 16:51
Okay, thanks I didn't know. I'll test it tomorrow.

**Comment by luwol03** [comment] 2020-06-02 12:49
I am in the process of implementing this function and have two small questions.
1. are the types for the config defined somewhere?
2. i want that if in every config watch is false, there should be only a message that there is nothing to watch. What do you say to that? And where would you implement it? I would do it there. https://github.com/rollup/rollup/blob/aa33e4b9250ba9f2cfb216e58f31638147ce34b5/src/watch/watch.ts#L40 But there are two more questions, how do I log that there is no watch config? So with which function? is there anything from rollup already? and how do I stop it? i have seen there is 'watcher.close' but that does not end the process. Do you have any idea what I can do? This is my fork: https://github.com/luwol03/rollup/tree/issue/3607-Rollup-watch-only-one-config-in-exported-array

**Comment by luwol03** [comment] 2020-06-02 16:11
i have just discovered that `npm run test:typescript` throws two type errors. So this is wrong what I did, right? https://github.com/luwol03/rollup/blob/9fa6fa560bc4882bd019ab2b37658977182263e5/src/rollup/types.d.ts#L498 I just don't know much about typescript. and a second question, when i run `npm run test:quick` but only test, i always get an error is that normal? 
![image](https://user-images.githubusercontent.com/60048565/83543261-73383a00-a4fc-11ea-9eca-5fb5446fa6cd.png)

**Comment by lukastaegert** [comment] 2020-06-02 19:03
> So this is wrong what I did, right?

The two errors are not only TypeScript problem but TypeScript is showing you two very real JS problems that stem from the fact that you also allow `true` as a value. E.g. in `watch.ts`

```ts
const watchOptions: WatcherOptions = this.options.watch || {};
```

could now also have the value `true`, which is incompatible with the expectation that `watchOptions` here is always an object. The simplest fix could be to not allow `boolean` but only `false`. Then the implicit default value would not `true` but an empty object, which is equivalent here. This fixed the type errors for me and also looks about right in the two places that were affected.

>  i always get an error is that normal?

No it should not be. Do you also get the error for a full `npm run test`? And did you update your dependencies, e.g. `npm ci`, after merging/rebasing onto latest master?

> which file do you mean with the default config?

Ah, sorry, what was the context here?

> i want that if in every config watch is false, there should be only a message that there is nothing to watch. What do you say to that?

That makes sense. However, ending the watch process is a big problem: It is just not expected to end. The problem is that traditionally, `rollup.watch` synchronously returns an event emitter. So for that reason alone, ending with an error is probably the safest choice to not cause breaking changes in other tools. However for improved code-splitting, the actual `Watcher` class is only created asynchronously here: https://github.com/rollup/rollup/blob/5bcb3d56056ba7223344f87c3758c36103ae11a3/src/watch/watch-proxy.ts#L17-L23 which means that there is no easy way to pass an error to the outside.

However what you can do is moving this validation into `watch-proxy.ts` and throw an error synchronously. If you also move the `ensureArray`, the `Watcher` constructor can also be simplified to only accept an array of configs.

Now of course for this error to actually end the process when using the CLI, you will need to handle it in `watch-cli.ts`. My recommendation would be to modify the `start` function to start with

```ts
try {
  watcher = rollup.watch(configs as any);
} catch (err) {
  handleError(err);
}
```

The `handleError` will take care of proper logging and ending the process

**Comment by luwol03** [comment] 2020-06-02 20:53
> No it should not be. Do you also get the error for a full npm run test? 

yes, as I just said. I get this error: https://bin.the-morpheus.de/?d5c32e49d6e2329e#3oCtyEDY2SQmX99ecYufWXifa7EyfokobKXzDRd5tZi2

> And did you update your dependencies, e.g. npm ci, after merging/rebasing onto latest master?

yes, I tested it in the current master branch and in my fork after installing the dependencies via `npm ci`.

> Ah, sorry, what was the context here?

https://github.com/rollup/rollup/issues/3607#issuecomment-636417128
> The example Rollup config should also ideally contain an array, how about something like this

> My recommendation would be to modify the start function to start with

That means, I have to reject the rollup.watch function, if there is in every config watch = false?

**Comment by lukastaegert** [comment] 2020-06-03 04:07
With regard to the error, I think I know what is going on. You are on Windows, which means that by default, your system would use different line breaks (`\r\n` instead of `\n`). This by itself is not a problem, but it is likely that Git is configured to "fix" things for your by converting `\n` to `\r\n` on the fly on checkout, which will break snapshot tests. To fix this, you will need to tweak this setting https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf

I would guess `core.autocrlf input` is the correct value to use, even though it is not the "recommended" value for Windows. I think you should also be able to configure this per repo without the `--global` flag.

With regard to the default, it is `mergeOptions` in `mergeOptions.ts` that will likely not preserve your value of `false` at the moment. If this was about the documentation, I was referring to the mini-example in the big list of options: I find that one mis-leading as it only contains a single config while this option only makes sense for an array.

> That means, I have to reject the rollup.watch function

"reject" is probably not the word I would use as that function does not return a Promise, but if you mean throwing an error in that function, yes. By the way, the "recommended" way to throw errors is to use the `error` helper like this and also add a `code` to the error:
https://github.com/rollup/rollup/blob/5bcb3d56056ba7223344f87c3758c36103ae11a3/src/ModuleLoader.ts#L209

For the error code, `INVALID_OPTION` is probably a good choice. The idea here is that by using a shared helper, we can do some custom post-processing in a central place if we need to. The `code` on the other hand can be picked up by downstream systems to discern error types without relying on the message.

**Comment by luwol03** [comment] 2020-06-03 07:14
ok, thanks I read this article but so far I have only set it to true.  but what do you think, why am I getting this error on `npm run test`?  the complete output can be viewed at https://bin.the-morpheus.de/?d5c32e49d6e2329e#3oCtyEDY2SQmX99ecYufWXifa7EyfokobKXzDRd5tZi2

**Comment by lukastaegert** [comment] 2020-06-03 09:10
Because `true` is BAD, at least for Rollup. Rollup output will always use `\n`, but if you use true, the expected output will be converted and no longer match the actual output.

**Comment by luwol03** [comment] 2020-06-03 09:34
I have just tested it under arch linux. and i also get a bug. I have used this commit: 5bcb3d56056ba7223344f87c3758c36103ae11a3 first i have cloned it via `git clone https://github.com/rollup/rollup.git` then i have installed the dependencies via `npm ci` and then i have run `npm run test:quick` this is my output on arch linux for the quick test: https://bin.the-morpheus.de/?5cf71817b9afed47#2MHsri3xaUyp9hBCrffGvh1uvjPd87PwrSmLVniWm7rL and this for `npm run test` :  https://bin.the-morpheus.de/?285f9d2b54a8254b#65GmM1T87q2rKmiHMmyyrn5wNUu2wXoHQx7CXuoDUYFM what do you say? is it the same with you?

**Comment by lukastaegert** [comment] 2020-06-03 10:49
This is a single time-out and for this particular test it can be ignored. The global test timeout is set for a rather fast system or our CI, the core-ja test is rather demanding. But no, I do not get this error.

**Comment by luwol03** [comment] 2020-06-03 20:37
I tested provisionally all the time, something like what you mean, right?  Do not be surprised that there are still a few warnings, because I have only tested it provisionally and I have also a few imports too many, which I will of course remove before committing.  Now I have two questions: 
1. Is that how you mean it?  
2. Why do I get these type errors when I move the ensure array function into the watch-proxy function?  I am not very familiar with type script.  Do you have any idea how i can fix this?

watch.ts
![watch ts](https://user-images.githubusercontent.com/60048565/83684905-1023d180-a5e8-11ea-85c6-0f1ecab17e16.JPG)

watch-proxy.ts
![watchproxy ts](https://user-images.githubusercontent.com/60048565/83685077-56793080-a5e8-11ea-8d58-af10fdffc764.JPG)

watch-cli.ts
![watch cli ts](https://user-images.githubusercontent.com/60048565/83685123-6db81e00-a5e8-11ea-867c-59adb5742cbe.JPG)

now I have two other questions
1. 

>  find that one mis-leading as it only contains a single config while this option only makes sense for an array

where and how should I do it then?

2. is there a community discord server for rollup?

At this point I want to thank you again for your support and hope that it is not annoying for you to always answer here.

**Comment by lukastaegert** [comment] 2020-06-04 04:22
At the moment, `configs` is still typed as `GenericConfigObject[] | GenericConfigObject`, but you can only map over it if it is an array (the type with the `[]` at the end). As you moved `ensureArray` to `watch-proxy`, `configs` will now always be an array, so to fix this you need to simplify the type in the constructor argument to `GenericConfigObject[]`.

Also to throw the error, do not throw `errInvalidOption(...)`. That function just returns an object but not a proper Error instance. You also need to pass it to the `error` function you import from `error.ts`. That one also takes care of throwing the error. And last the watch options have not been normalized in any way in `watch-proxy` so most people will not have a `watch` property at all, which is ok and you should not throw an error in that case. So what I would do is

```js
if (configArray.every(config => config.watch === false)) return error(errInvalidOption('watch', 'there must be at least one config where "watch" is not set to "false"'));
```

> where and how should I do it then?

The place is correct, the example should contain multiple configs, however, e.g.

```js
// rollup.config.js
export default [
  {
    input: 'main.js',
    output: { file: 'bundle.js', format: 'es' }
  },
  {
    input: 'other.js',
    watch: false,
    output: { file: 'other-bundle.js', format: 'es' }
  }
]
```

> is there a community discord server for rollup?

There is a Gitter, but no discord as far as I know. https://gitter.im/rollup/rollup

**Comment by luwol03** [comment] 2020-06-04 09:30
Thanks a lot! I am sometimes really stupid. I could have seen that you can't just put an array in there.

> And last the watch options have not been normalized in any way in watch-proxy so most people will not have a watch property at all, which is ok and you should not throw an error in that case. So what I would do is <...>

But it's already normalized. See type `MergedRollupOptions[]`. That means it would have worked with `configArray.some()`.
https://github.com/rollup/rollup/blob/e2618c8916416ce4a63f06c996a509d4c21ddc7c/cli/run/watch-cli.ts#L83

But I just got a better idea, I filter the configs in the `watch-proxy.ts' and pass only the configs where the watcher have to watch. What do you say to this? Is this a better idea? Like this:
![image](https://user-images.githubusercontent.com/60048565/83738153-367f5680-a654-11ea-98a2-396443a6f34c.png)

> The place is correct, the example should contain multiple configs, however, e.g.

what place? you mean there?
![image](https://user-images.githubusercontent.com/60048565/83738477-a55caf80-a654-11ea-976b-5f5a2665f276.png)
this is in the `docs/999-big-list-of-options.md` file.

and there's one last thing I would have noted. When I throw
```js
throw error(errInvalidOption('watch', 'there must be at least one config where "watch" is not set to "false"'));
```
I get a double output like that:
![image](https://user-images.githubusercontent.com/60048565/83739357-c07bef00-a655-11ea-9d80-7122e73fc025.png) 
is this wanted? because one comes from line 22 and the second from 39, because `err.stack` is defined. And if I omit the error then logically I only get the first one because it is not an error object and therefore err.stack is not defined. What should I do there?

**Comment by lukastaegert** [comment] 2020-06-05 04:16
> But it's already normalized.

Only if you use the CLI. But the `watch` function in `watch-proxy.ts` is also directly expose in the pure JavaScript API via `node-entry.ts`, and here, no normalization happens. This is why the type of the parameter is `GenericConfigObject[] | GenericConfigObject` and not e.g. `MergedRollupOptions[]` and why you need the `ensureArray`.

> But I just got a better idea, I filter the configs in the watch-proxy.ts and pass only the configs where the watcher have to watch

That sounds like a very good idea!

> you mean there?

yes

> I get a double output like that:

Yes, that is how errors should be reported. In any case, I would never throw anything but a proper `Error` instance for consistency.

**Comment by luwol03** [comment] 2020-06-05 13:05
is the code and docs okay now? Now I only have to start with the unit tests. Is there a test enough? and what the test is just a config array where once watch is false? and then i compare the dirs? or how? and if i understand it correctly, it goes there?
https://github.com/rollup/rollup/blob/e2618c8916416ce4a63f06c996a509d4c21ddc7c/test/watch/index.js#L1152 ? and since my corejs test always fails, could you test it on yourself? so my fork with the issue / .. branch

**Comment by lukastaegert** [comment] 2020-06-07 04:09
If you actually create a pull request from your branch, it will make things a lot easier as I can easily add comments directly to your code and even push small changes to your branch. We will also see how CI runs your tests. There is no reason for a human to do that.

With regard to tests, the goal is to have each branch in the logic covered by tests. As I see it, there are at least two cases: First the case where some configs are disabled and second the case where all configs are disabled. Putting them in `rollup/test/watch` makes sense. When CI successfully runs your tests, it will generate a coverage report that will tell you if there are any conditions in the code left that are not covered by tests.

**Comment by lukastaegert** [comment] 2020-06-07 04:25
Actually it would be nice to test the error case via the CLI tests as some changes to `watch-cli.ts` were necessary to handle it properly. This one should be placed in `test/cli/samples/watch`, but as the error is directly stopping execution, the test config can be quite simple, similar to e.g. `test/cli/samples/duplicate-import-options`

**Closed** 2020-06-08 05:02 UTC
Labels: c³ ⋅ 😀 PR welcome, t³ ✨ enhancement
