### ISSUE TITLE
Request: Output multiple dependent files (only Tree Shaking mode)

### ISSUE THREAD

**Issue by petamoriken** [rollup/rollup#1565] opened 2017-08-19 19:58 UTC
This is a feature request for outputting multiple dependent files.

Some browsers are starting to support ES6 Module (`<script type="module">` http://caniuse.com/#feat=es6-module), so it is not necessary to put JavaScript files in one file in the future.

```html
<!-- a.html -->
<script type="module" src='a.js'></script>

<!-- b.html -->
<script type="module" src='b.js'></script>
```

I want rollup to have the following Implementation.

`src/`
└ `a.js`
└ `b.js`
└ `lib/`
　　└ `print.js`: `a.js`, `b.js` use this code
　　└ `dummy.js`: nobody uses this

`src/lib/print.js`:
```js
export function print(...args) { // a.js, b.js use this function
  console.log(...args);
}

export function noop() {} // nobody uses this
```

↓ execute: `rollup src/a.js src/b.js --format es --output-dir dist`

`dist/`
└ `a.js`
└ `b.js`
└ `lib/`
　　└ `print.js`: `a.js`, `b.js` use this code

`dist/lib/print.js`:
```js
export function print(...args) { // a.js, b.js use this function
  console.log(...args);
}
```

Thanks!

related: #372

**Comment by Rich-Harris** [comment] 2017-08-20 21:53
Closing as this is basically a dupe of #372. We'll get to it, eventually...

**Closed by Rich-Harris** 2017-08-20 21:53 UTC
