### ISSUE TITLE
Make each dest target accept its own set of plugins

### ISSUE THREAD

**Issue by raphaelokon** [rollup/rollup#799] opened 2016-07-28 11:14 UTC
Hi there. I tried to pass in a custom plugin config to one of my dest targets https://github.com/rollup/rollup/wiki/Command-Line-Interface#targets but it is not picking up the plugins …

``` js
let plugins = […];
let minify = plugins.concat({…});

export default {
        //→ other opts
    targets: [{
        moduleName: name,
        dest: `${destPath}.js`,
        format: "umd",
        plugins: plugins //→ Normal set of plugins
    }, {
        moduleName: name,
        dest: `${destPath}.min.js`,
        format: "umd",
        plugins: minify //→ Normal set of plugins + uglify plugin
    }]
};
```

This would allow for very slim one file configs (when adding additional formats like `es`). 
Is this already supposed to be working? Or a missing feature? If the latter: Would like to implement this if it is worth in your eyes @Rich-Harris

**Comment by raphaelokon** [comment] 2016-07-28 11:24
From inspecting the code it seems like the plugins are applied before `rollup` process the `options.target`.

**Comment by eventualbuddha** [comment] 2016-07-28 13:01
The `targets` option mainly exists to allow writing multiple formats of the same bundle. Using different sets of plugins means you have to build the bundle multiple times. I suppose that could be supported, but has the disadvantage I mentioned.

**Comment by raphaelokon** [comment] 2016-07-28 14:12
Yes … I know that with this as it currently stands you have to bundle per target … which is obviously not ideal. I was thinking of a `bundleCache` where the transformation state of a bundle is memoized and can be efficiently retrieved for reuse across targets.

```js
let plugins = […];
let minify = plugins.concat({…});

export default {
        //→ other opts
	targets: [{
		moduleName: name,
		dest: `${destPath}.js`,
		format: "umd",
		plugins: plugins //→ Normal set of plugins. Cache this transformation.
	}, {
		dest: `${destPath}.es.js`,
		format: "es",
		plugins: plugins //→ Normal set of plugins. Reuse cached transform.
	}, {
		moduleName: name,
		dest: `${destPath}.min.js`,
		format: "umd",
		plugins: minify //→ Reuse cached transform. Apply uglify plugin on top. Cache it.
	}, {
		dest: `${destPath}.es.min.js`,
		format: "es",
		plugins: minify //→ Reuse cached transform.
	}]
};
```

Because every transformation state is cached … the order of targets doesn't really matter.

**Comment by skeggse** [comment] 2016-07-29 20:33
@raphaelokon if you don't mind being a little hacky, you can do something like this:

```js
var cache = {modules: {}};

pluginSets.forEach((plugins) => {
rollup.rollup({
```

**Comment by skeggse** [comment] 2016-07-29 20:38
Fixed previous comment.

**Comment by raphaelokon** [comment] 2016-07-29 20:45
Cheers. Looks good :-) This goes in the same direction I described above. Would like have the thoughts of the maintainer(s) if the cache would be something viable.

**Comment by Victorystick** [comment] 2016-07-29 21:24
@raphaelokon If all you want to do is also generate minified builds, why not just do that as a postprocessing step?

**Comment by raphaelokon** [comment] 2016-07-30 06:56
@Victorystick Fair point. The minify example was just an obvious one. In theory you could use different plugin permutations (node resolve, commonjs et al) to achieve different outputs based on targets and format/target platform needs.

**Comment by braco** [comment] 2016-10-02 03:20
Was finding that it's hard to use babel and rollup together without messing with the other builds:

```
export default {
  plugins: [
    babel(babelrc()),
  ],
  targets: [
    // babel, yes
    {
       dest: es5File,
       format: 'umd',
       sourceMap: true,
    },
   // please, no babel
    {
      dest: esnextFile,
      format: 'es',
      sourceMap: true,
    },
  ],
};
```

and it looks like this is a common problem where config bloats out pretty rapidly:

https://gist.github.com/koistya/1abc156c61814fc307210f33e127f124#file-build-js

**Comment by Victorystick** [comment] 2016-10-03 17:45
@braco Why not do what Rollup does for its [browser build](https://github.com/rollup/rollup/blob/master/rollup.config.browser.js)?

```js
// rollup.umd-config.js
import config from './rollup.es-config-without-babel.js';
import babel from 'rollup-plugin-babel';

Object.assign(config, {
  // Change the destination and the format.
  dest: 'out.js',
  format: 'umd'
});

// Add the Babel plugin.
config.plugins.push(babel());

export default config;
```

**Comment by raphaelokon** [comment] 2016-10-03 18:42
@Victorystick That is how I finally utilised it.

**Comment by joaovieira** [comment] 2016-12-05 17:56
If I want to have a normal and a minified versions of the same bundle I need to have two different plugin pipelines, or have standalone uglify run after the build. I also want an ES6 + ES modules future ready version and a ES5 + UMD modern day versions. I.e.:

* ES6 + ES modules
* ES6 + ES modules + uglify
* ES5 + UMD
* ES5 + UMD + uglify

Having all of this in a single config file would be great.

**Comment by Grigory90** [comment] 2016-12-18 14:09
Yeah, it would be great.
My way 😑 

```javascript
gulp.task('scripts', () => {
    let bundleCode;

    let options = {
        base: {
            entry: `${cfg.dirs.src}/js/main.js`,
            plugins: [...]
        },
        write: {
            format: 'iife',
            dest: `${cfg.dirs.build}/js/main.js`
        }
    };

    return rollup(options.base).then(bundle => {
        bundleCode = bundle.generate(options.write).code;
        return bundle.write(options.write);
    }).then(() => {
        let result = uglify.minify(bundleCode, {fromString: true});
        fs.writeFileSync(`${cfg.dirs.build}/js/main.min.js`, result.code);
    });
});
```

**Comment by Rich-Harris** [comment] 2017-01-07 19:47
I'm going to close this issue as there really isn't a good way to implement it — when you have different sets of plugins, you're essentially talking about entirely different bundles as far as Rollup is concerned. It *could* detect that it needed to bundle everything multiple times, but at that point it's just sugar over having separate configs, so in essence this is a duplicate of #863.

**Closed by Rich-Harris** 2017-01-07 19:47 UTC
Labels: suggestion
