### ISSUE TITLE
Tree-shaking rxjs 6 produces left-over non-exported functions

### ISSUE THREAD

**Issue by 43081j** [rollup/rollup#2415] opened 2018-08-21 18:15 UTC
Given the following:

```js
import { Subject } from 'rxjs';
import { take } from 'rxjs/operators';
export function foo() {
    const s = new Subject();
    s.next('foo');
    return s.pipe(take(1));
}

```

And config:

```js
import resolve from 'rollup-plugin-node-resolve';

export default {
  input: 'lib/index.js',
  output: {
    file: 'bundle.js',
    format: 'iife',
    name: 'foo'
  },
  plugins: [
    resolve()
  ]
};
```

The `rxjs/operators` import resolves to `rxjs/_esm5/operators/index.js` which looks something like:

```js
export { audit } from './audit';
export { auditTime } from './auditTime';
export { buffer } from './buffer';
// all operators...
```

We end up with a `214K` bundle, for 9 lines of code and two imports.

---

Looking at the bundle, it seems unexported functions/classes are somehow kept.

Take [this operator](https://github.com/ReactiveX/rxjs/blob/a95441bce3f012abaf7d8958239d4f4d2909f9d4/src/internal/operators/distinctUntilChanged.ts) for example.

In our bundle:

* The exported functions from this operator are indeed shaken (as we don't use them and our imports don't seem to)
* The classes which are _not exported_ from this operator are in the resulting bundle (such as [this class](https://github.com/ReactiveX/rxjs/blob/a95441bce3f012abaf7d8958239d4f4d2909f9d4/src/internal/operators/distinctUntilChanged.ts#L64))

---

What is going on here? Is this rx's fault or rollup's or mine?

How do we possibly end up with classes in our bundle which were never even exported?

---

## Edit

**rxjs depends on `tslib` which seems to be the culprit for marking everything as having side effects**

I stepped through rollup's traversal for a while to see which node returned true for `hasEffects`. It turns out to be [this helper from TypeScript's tslib helpers](https://github.com/Microsoft/tslib/blob/9dd9aa322c893e5e0b3f1609b1126314ccf37bbb/tslib.es6.js#L25).

The `CallExpression` here goes through the usual checks (`hasEffects`):

`CallExpression -> callee (Identifier) -> variable (LocalVariable)`

Where the `LocalVariable` is [this](https://github.com/Microsoft/tslib/blob/9dd9aa322c893e5e0b3f1609b1126314ccf37bbb/tslib.es6.js#L17). Because `isReassigned` is true on that, _everything_ which uses this helper ends up being included.

Any idea how to combat this? This is depended on by rx, not my code. Is there a way maybe to let rollup know we don't care about it?

**Comment by 43081j** [comment] 2018-08-22 08:25
Try [this example](https://rollupjs.org/repl?version=0.63.5&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGlzVXNlZCUyMCU3RCUyMGZyb20lMjAnLiUyRm1vZHVsZSclM0IlNUNuJTVDbmlzVXNlZCgpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmhlbHBlcnMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIydmFyJTIwZXh0ZW5kU3RhdGljcyUyMCUzRCUyMGZ1bmN0aW9uKGMpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGV4dGVuZFN0YXRpY3MlMjAlM0QlMjBPYmplY3Qua2V5cyUyMCU3QyU3QyUyMGZ1bmN0aW9uKCklMjAlN0IlN0QlM0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwZXh0ZW5kU3RhdGljcyhjKSUzQiU1Q24lN0QlM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwdGhpc0hhc1NpZGVFZmZlY3RzKGNscyklMjAlN0IlNUNuJTVDdGV4dGVuZFN0YXRpY3MoY2xzKSUzQiU1Q24lN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybW9kdWxlLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHRoaXNIYXNTaWRlRWZmZWN0cyUyMCU3RCUyMGZyb20lMjAnLiUyRmhlbHBlcnMnJTNCJTVDbiU1Q252YXIlMjBmb28lMjAlM0QlMjBjbGFzcyUyMEZvbyUyMCU3QiU3RCUzQiU1Q250aGlzSGFzU2lkZUVmZmVjdHMoZm9vKSUzQiU1Q24lNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBuZXZlclVzZWQoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwbmV3JTIwZm9vKCklM0IlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGlzVXNlZCgpJTIwJTdCJTVDbiU1Q3Rjb25zb2xlLmxvZygxMjMpJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJpaWZlJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

Out of interest, what kind of "new logic" would solve this problem?

Something like traversing further into the variable declarator and checking what it _really_ modifies?

**Comment by lukastaegert** [comment] 2018-08-22 08:55
Thanks a lot!

The rough issue is that if a variable has been marked as "reassigned", the current logic becomes very conservative about further modifications. The new approach would be akin to calculating a ["single static assignment form"](https://en.wikipedia.org/wiki/Static_single_assignment_form) which means modifications are treated as definitions of new variables with different values and run the tree-shaking on the new form to determine which modifications do not have effects because the resulting variables are not used.

However with your example, we can figure out if there are ways to extend the existing logic as well, which could provide a solution in a shorter frame of time.

**Comment by Draccoz** [comment] 2018-10-29 15:02
I've noticed something similar when importing `import { Observable } from './node_modules/@reactivex/rxjs/dist/esm2015/index.js';
`. The bundle contains not just Observable and its dependencies, but seems to also include everything that uses `Observable` or `Subscriber` (dependency of `Observable`). This results in around twice as big bundle (in my very minimal case).
Could it be the same issue, or is it something different? I can create a repro GH if needed.

**Comment by kzc** [comment] 2018-12-12 23:14
@lukastaegert Does Rollup support the Webpack `package.json` convention for module `sideEffects`? This coarse grained hint would be pertinent to this issue. I couldn't find any reference to it in the source or documentation for Rollup, `rollup-plugin-node-resolve` or `rollup-plugin-commonjs`.

* https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
* https://github.com/webpack/webpack/tree/master/examples/side-effects
* https://github.com/ReactiveX/rxjs/commit/47351d6547b770dad54d9b81f5db39bb3f2fb58a
* https://github.com/openlayers/openlayers/blob/a73e9607a8f379d8d9383c060705111f5f6c81e8/package.json#L101-L103

**Comment by lukastaegert** [comment] 2018-12-13 05:07
As rollup does not read package.json files, this would be needed to be implemented somehow in rollup-plugin-node-resolve but there is no API for this in rollup yet.

As for the algorithmic rewrite, 2-3 months will probably not be enough but adding support for `sideEffects` should be doable in that time-frame.

**Comment by kzc** [comment] 2019-05-15 23:54
@lukastaegert There's a marked improvement in rollup bundling now that it supports `package.json` `sideEffects`.

Building https://github.com/mischnic/tree-shaking-example with:

```
  rollup@1.12.0
  rollup-plugin-babel@4.3.2
  rollup-plugin-commonjs@10.0.0
  rollup-plugin-node-resolve@5.0.0
  rollup-plugin-terser@3.0.0
  rollup-pluginutils@2.7.0
  parcel-bundler@1.10.3
  webpack@4.31.0
```

produces:

```
file                size    
------------------  --------
parcel/lodash-es    19.28 KB
rollup/lodash-es    18.22 KB
webpack/lodash-es   20.74 KB

parcel/lodash       91.13 KB
rollup/lodash       69 KB   
webpack/lodash      70.57 KB

parcel/remeda       1.9 KB  
rollup/remeda       1.82 KB 
webpack/remeda      2.74 KB 

parcel/ramda        6.36 KB 
rollup/ramda        6.25 KB 
webpack/ramda       7.16 KB 

parcel/ramdaBabel   6.72 KB 
rollup/ramdaBabel   6.35 KB 
webpack/ramdaBabel  8.39 KB 

parcel/rambda       9.81 KB 
rollup/rambda       589 B   
webpack/rambda      2 KB    

parcel/rambdax      25.57 KB
rollup/rambdax      3.53 KB 
webpack/rambdax     5.09 KB 
```

@43081j The tree shakability of rxjs is being improved in https://github.com/ReactiveX/rxjs/pull/4769 thanks to @filipesilva.

/cc @mischnic

**Comment by Draccoz** [comment] 2019-05-16 09:38
That is fantastic! Hope the rxjs fix lands there fast and that it will all work correctly now, that would mean much simpler build step for production.

**Comment by kzc** [comment] 2019-05-16 15:10
@filipesilva Will the tree shaking fix in PR ReactiveX/rxjs#4769 introduce pure annotations into `rxjs/_esm2015` as well?

```
$ git clone https://github.com/filipesilva/rxjs-6.4.0-without-toplevel-prop-assignment.git

$ grep __PURE__ `find rxjs-6.4.0-without-toplevel-prop-assignment/_esm5 -name '*.js'` | wc -l
     224

$ grep __PURE__ `find rxjs-6.4.0-without-toplevel-prop-assignment/_esm2015 -name '*.js'` | wc -l
       0
```

Comparison of `_esm5` and `_esm2015` bundle sizes using `rollup@1.12.1` and `terser@3.17.0`:

```
$ cat main5.js 
import {Observable} from './rxjs-6.4.0-without-toplevel-prop-assignment/_esm5/index.js';

$ rollup main5.js -f es --silent | terser --toplevel -mc passes=3 | wc -c
      15
```

```
$ cat main2015.js 
import {Observable} from './rxjs-6.4.0-without-toplevel-prop-assignment/_esm2015/index.js';

$ rollup main2015.js -f es --silent | terser --toplevel -mc passes=3 | wc -c
   12096
```

**Comment by filipesilva** [comment] 2019-05-16 15:22
Hmmm I imagine that's actually a bug in the build setup for RxJs. I should have a look at that.

**Comment by mischnic** [comment] 2019-05-16 16:37
I've updated https://github.com/mischnic/tree-shaking-example to include rxjs (waiting for that rxjs PR...) and react-icons (which parcel has/had issues bundling). I've also added coverage reports for all these cases (though 100% is not always achievable).
Does someone have suggestions for popular packages which (could) really benefit from treeshaking?

**Comment by filipesilva** [comment] 2019-05-16 16:47
@mischnic Angular relies a LOT of tree shaking to reduce our bundle size. You can try `@angular/core`. 

If you also want to just check if libraries have side effects without importing anything specific I recommend https://github.com/filipesilva/check-side-effects. This is what I used to detect them in the RxJS and the equivalent Angular PR (https://github.com/angular/angular/pull/29329).

**Comment by kzc** [comment] 2019-05-16 19:35
@mischnic Regarding the newly added https://github.com/mischnic/tree-shaking-example result:

```
rollup/react-icons   29.08 KB  Stmts: 18%, Functions:  6%
webpack/react-icons  10.42 KB  Stmts: 25%, Functions: 15%
```

Webpack sets `process.env.NODE_ENV="production"` when `mode: "production"` is used. Rollup does not, so it's getting the development version of the react library.

To compare apples with apples apply this patch:

```patch
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -15,7 +15,15 @@ export default [
         exclude: "node_modules/**"
       }),
       commonjs(),
-      terser({ sourcemap: false, toplevel: true })
+      terser({
+        compress: {
+          global_defs: {
+            "process.env.NODE_ENV": "production",
+          },
+        },
+        sourcemap: false,
+        toplevel: true,
+      })
     ],
     output: [{ file: `rollup/${libName}.js`, format: "cjs" }]
   }
```

to get this result:

```
rollup/react-icons   9.18 KB   Stmts: 24%, Functions: 10%
webpack/react-icons  10.42 KB  Stmts: 25%, Functions: 15%
```

Webpack v4 bundles are generally 1.5 KB larger than the rollup equivalent because of its fixed bootstrapping code.

**Comment by mischnic** [comment] 2019-05-16 19:49
Thanks, updated.
> Webpack v4 bundles are generally 1.5 KB larger than the rollup equivalent because of its fixed bootstrapping code.

This comparison can't perfectly compare apples to apples of course...

**Comment by kzc** [comment] 2019-05-17 16:27
@filipesilva afaict `rxjs` only runs `@angular-devkit/build-optimizer` on `_esm5` to produce the pure annotations, not `_es2015`:

https://github.com/ReactiveX/rxjs/blob/01a09789a0a9484c368b7bd6ed37f94d25490a00/.make-packages.js#L56-L76

But since the generated `rxjs/package.json` specifies `_esm5` for `"module"`, I think most ES bundlers will pick that up by default:

```
module: './_esm5/index.js',
es2015: './_esm2015/index.js'
```

https://github.com/ReactiveX/rxjs/blob/01a09789a0a9484c368b7bd6ed37f94d25490a00/.make-packages.js#L52-L53

I'm not familiar with the use of the `"es2015"` tag in `package.json`. Unless I'm mistaken, `_es2015` will only used if someone overrides the bundler config default, or if `rxjs/_esm2015` is explicitly imported in source code.

**Comment by filipesilva** [comment] 2019-05-18 09:18
Yes, we use it a lot on Angular packages but it's not a standard. It's part of what we call Angular Package Format (APF, [doc here](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#heading=h.k0mh3o8u5hx)). It's mostly just guidelines on how Angular libs that distribute multiple formats, and different entry points, and should support different consumers should be packaged.

**Comment by kzc** [comment] 2019-05-18 18:03
@filipesilva I see. So if Angular is the only consumer of the not-pure-annotated `rxjs/_esm2015` presumably when the user builds their app with `angular-cli` it will run `@angular-devkit/build-optimizer` on the bundle prior to minification?

**Comment by filipesilva** [comment] 2019-05-19 11:24
Right now, yes. We'd like it to be more ergonomic to use the es2015 bundles though...

**Comment by shellscape** [comment] 2019-08-10 12:42
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Closed by shellscape** 2019-08-10 12:42 UTC
Labels: b³ 🐞 tree-shaking, t³ ✨ enhancement

**Comment by Draccoz** [comment] 2019-08-13 22:13
@shellscape Please reopen this issue as the bug still persists. To replicate the issue, do the following:
1. create a new directory and cd into it
2. `npm init`
3. `npm install @reactivex/rxjs rollup`
4. create file `index.js` with the following content:
```
import { Observable } from './node_modules/@reactivex/rxjs/dist/esm2015/index.js';
console.log(Observable);
```
5. `rollup index.js --format iife >> index.bundle.js`

**Expected behavior:**
Bundle should only contain Observable with dependencies
**Actual behavior:**
Bundle contains multiple functions and variables that are not used

**Comment by shellscape** [comment] 2019-08-13 22:19
@lukastaegert when you have a moment please evaluate that. I can confirm the behavior, but I don't know enough to know if that's intended, or if that's the cause of something else outside of rollup going sideways.

**Comment by Draccoz** [comment] 2019-08-13 22:23
I don't believe this is intended, as even my WebStorm hints the unused items. Also, other bundlers with tree shaking omit unused code.

**Comment by kzc** [comment] 2019-08-13 23:47
Rollup can only tree shake code that is [conducive to it](https://github.com/angular/angular-cli/issues/14316#issuecomment-488438312). AFAICT the tree shaking fix in the `@reactivex/rxjs` library was only merged to the 6.x branch a few days ago and has yet to be released. 

See: https://github.com/ReactiveX/rxjs/pull/4953 https://github.com/ReactiveX/rxjs/pull/4769.

As a workaround in the meantime you could probably use the rollup flag `--no-treeshake.propertyReadSideEffects`.

@filipesilva Correct me if I'm wrong.

**Comment by lukastaegert** [comment] 2019-08-14 06:35
The unused variables are part of the code because Rollup cannot determine conclusively that the functions that are called to generate them are side-effect free. I do not expect in a short time frame for Rollup to properly understand the mutating way TS helper wrappers work unless we hard code them into Rollup, which would be brittle. 

@kzc is right and his suggestion will help. For more dramatic results, you can add `--no-treeshake.moduleSideEffects`.

But you do not need any of this if you use `rollup-plugin-node-resolve` which adds support for side-effects hints. This is how all other bundlers do it, but of course this means that you need to write a config file or use the JS API. This also fixes your example.

**Comment by Draccoz** [comment] 2019-08-14 07:13
Interesting, will give it a shot later, thanks for a workaround tip @kzc @lukastaegert.
