### ISSUE TITLE
input names cannot contain dashes

### ISSUE THREAD

**Issue by runspired** [rollup/rollup#3253] opened 2019-11-22 18:57 UTC
In either of the following input option formats rollup will quietly fail to produce output

```
{
  input: {
     'example-one': 'example-one.js', // won't ouput
     'example-two': 'example-two.js', // won't output
     three: 'example-three.js' // will output three.js
  } 
}
```

```
{
  input: [
    'example-one.js', // won't output
    'example-two.js', // won't output
    'three.js',  // will output
 ]
}
```

**Comment by shellscape** [comment] 2019-11-22 22:19
Come on. Issue template already.

**Comment by runspired** [comment] 2019-11-23 01:19
There goes all respect for you all. 👋

**Comment by shellscape** [comment] 2019-11-23 02:51
Completely ignoring an issue template and the information requested within demonstrates a total lack of respect for the time and effort of maintainers and those who freely give their time to the project. Someone of your experience should know better.

**Comment by lukastaegert** [comment] 2019-11-23 08:58
Sorry this has gotten a little out of hand, I have unlocked and reopened the issue. Andrew’s comment about the template was correct, but I believe we should all work to keep the conversation civil. I hope we can keep this conversation to the actual issue from now on, though. Please add the issue template!

**Comment by lukastaegert** [comment] 2019-11-24 06:59
After discussion with @runspired it turned out that there may be more to the issue than it originally appeared. He will open a new issue once he finds a good reproduction. I am sorry this discussion has gotten out of hand so quickly and hope we can for the future resolve to act a little more modest in our responses and actions. After all, we as maintainers are here because we like creating a great product that you love working with and you as users love to have a great product that works for you, so your issues are important to us. I will close the issue now.

**Closed by lukastaegert** 2019-11-24 06:59 UTC
