### ISSUE TITLE
Input syntax appears to confuse the parser

### ISSUE THREAD

**Issue by chandlerprall** [rollup/rollup#1396] opened 2017-05-03 15:52 UTC
Trying to import the `shaka-player` module but Rollup's output has invalid syntax; the output has no `;` before the `return` in `apply(null,d)return b`. Stripped down to an example case that reproduces the issue.

[Rollup repl with issue](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCcuJTJGc2hha2EuanMnJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNoYWthLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwdGVzdChhKSU3QmZvcih2YXIlMjBiJTNEJTVDJTIyJTVDJTIyJTJDYyUzRDAlM0JjJTNDYS5sZW5ndGglM0JjJTJCJTNEMTZFMyl2YXIlMjBkJTNEYS5zdWJhcnJheShjJTJDYyUyQjE2RTMpJTJDYiUzRGIlMkJTdHJpbmcuZnJvbUNoYXJDb2RlLmFwcGx5KG51bGwlMkNkKSUzQnJldHVybiUyMGIlN0QlM0IlNUNuJTVDbnRlc3QoKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJpaWZlJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

Since the shaka-player code is already minified, I tried reformatting it with WebStorm and that made Rollup happy.
[Rollup repl with formatted code, no issue]()

**Comment by kzc** [comment] 2017-05-03 20:33
Duplicate of issue #1275

See fix: https://github.com/rollup/rollup/issues/1275#issuecomment-273881657

**Closed** 2017-06-21 19:53 UTC
Labels: bug, duplicate
