### ISSUE TITLE
Tree-shaken imports resulting in "unused warnings"

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup#2112] opened 2018-04-04 22:31 UTC
**Repro**
https://github.com/Andarist/rollup-warnings-issue

**Behaviour**
```sh
src/index.js → dist/index.js...
(!) Unused external imports
map imported from external module 'lodash-es' but never used
created dist/index.js in 19ms
```

**Expected**
No warning - this import is used, its consumer got tree-shaken though.

**Comment by guybedford** [comment] 2018-04-05 11:15
I've been meaning to work on this, just struggling a little for time these days.

Note this is a duplicate of #1381.

**Comment by lukastaegert** [comment] 2018-04-05 11:53
I had a look at this warning this morning and my impression is that it is actually "working as intended". Assuming that people do not usually write imports they do not actually use, the only benefit I can see for this message is a "hint" that you may no longer need an external dependency.

I have no idea what the original intention of this warning was but if it is the above, then it should probably only appear if *none* of the imports are used any more. In this case, the wording should probably be changed as well.

Otherwise I agree that this warning is rather useless.

**Comment by lukastaegert** [comment] 2018-04-05 11:55
Looking through #1381 though gives me the feeling that removing might actually be the best solution.

**Comment by Andarist** [comment] 2018-04-05 13:25
> Note this is a duplicate of #1381.

Woops, didnt find it, sorry 😅 

> I had a look at this warning this morning and my impression is that it is actually "working as intended". Assuming that people do not usually write imports they do not actually use, the only benefit I can see for this message is a "hint" that you may no longer need an external dependency.

I think this still might be useful IF one actually doesn't use external dependency, problem here is that actually I use them all - but some of them are tree-shaken.

The warning comes from a shared file which is requested by different bundles and because of that it can report different "unused imports" depending which bundle I create at that moment.

**Comment by guybedford** [comment] 2018-04-13 13:47
I've created a PR at https://github.com/rollup/rollup/pull/2124.

**Comment by guybedford** [comment] 2018-04-18 21:57
This has been merged and released.

**Closed by guybedford** 2018-04-18 21:57 UTC
