### ISSUE TITLE
iife: Missing semicolon in unnamed (default) exports

### ISSUE THREAD

**Issue by bob-v-t** [rollup/rollup#1005] opened 2016-09-30 13:20 UTC
Hi guys,

First I'd like to thank everybody for their input on this project. I really like the simplicity it brings our projects.

We noticed a small 'issue' when using default exports that are unnamed. The function declaration turns into a var declaration, but rollup doesn't add a trailing semicolon to this function. Our JSHint gives us a warning on this and breaks our build process.

What is your take on this? Issue or not?

Use the following setup to reproduce this on rollupjs.org:

_main.js (entry module)_
``` js
import customName from './no-name-default-export.js';
customName( 'Hello moon!' );
```

_no-name-default-export.js_
``` js
export default function(msg) {
  console.log(msg);
}

```

**Comment by Victorystick** [comment] 2016-10-03 17:39
Duplicate of #1004.

**Closed by Victorystick** 2016-10-03 17:39 UTC
Labels: duplicate
