### ISSUE TITLE
Getting Error: A module cannot import itself 

### ISSUE THREAD

**Issue by adampotocki** [rollup/rollup#1630] opened 2017-09-13 13:46 UTC
Getting this error with rollup, any suggestions on fixing this? 

Error: A module cannot import itself
node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/connect/tls.js (1:0)

**Comment by guybedford** [comment] 2017-12-05 16:02
Duplicate of #1055.

**Comment by lukastaegert** [comment] 2017-12-06 05:58
Thanks for checking this @guybedford, closing this in favour of the original issue.

**Closed by lukastaegert** 2017-12-06 05:58 UTC
