### ISSUE TITLE
Fire & Forget calls to promises are removed with tree-shaking as of v0.49.0

### ISSUE THREAD

**Issue by btakita** [rollup/rollup#1601] opened 2017-08-30 19:58 UTC
https://rollupjs.org/repl?version=0.49.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnAyKCklNUNuJTVDbmZ1bmN0aW9uJTIwcDIoKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwbmV3JTIwUHJvbWlzZSgoKSUyMCUzRCUzRSUyMCU3QiU1Q24lNUN0JTVDdGNvbnNvbGUuaW5mbygnZmlyZSUyMCUyNiUyMGZvcmdldCcpJTVDbiU1Q3QlN0QpJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

**Comment by btakita** [comment] 2017-08-30 19:59
It seems like having `.then` adds the function.

https://rollupjs.org/repl?version=0.49.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnAyKCkudGhlbiU1Q24lNUNuZnVuY3Rpb24lMjBwMigpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjBuZXclMjBQcm9taXNlKCgpJTIwJTNEJTNFJTIwJTdCJTVDbiU1Q3QlNUN0Y29uc29sZS5pbmZvKCdmaXJlJTIwJTI2JTIwZm9yZ2V0JyklNUNuJTVDdCU3RCklNUNuJTdEJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

**Comment by btakita** [comment] 2017-08-30 20:00
https://github.com/rollup/rollup/pull/1582

**Comment by kzc** [comment] 2017-08-30 21:05
Duplicate of #786

Fix: https://github.com/rollup/rollup/issues/786#issuecomment-271934420

**Comment by lukastaegert** [comment] 2017-08-31 07:08
I will fix this for now by making `Promise(callback)` impure which in my opinion it certainly is. I have plans for how to handle this properly in the future in cases where the argument to `Promise()` does not have side-effects but for now we should take the cautious road unless we want to keep having more of these issues.

**Closed** 2017-09-08 00:20 UTC
