### ISSUE TITLE
Symbol renaming for classes changes name.

### ISSUE THREAD

**Issue by NaridaL** [rollup/rollup#1914] opened 2018-01-26 00:57 UTC
Rollup is renaming one of my classes from `MyClass` to `MyClass$1`. This is causing problems because the name of the class changes too.

Repro, because I couldn't get the link to work:
```ts
// main.js
export class MyClass {
	constructor() {
		a = "main"
	}
}
assert(MyClass.name == "MyClass") // oops
export {MyClass as MyClass2} from "./MyClass"

// MyClass.js
export class MyClass {
	constructor() {
		a = "external"
	}
}

// Output:
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

class MyClass {
	constructor() {
		a = "external";
	}
}

class MyClass$1 {
	constructor() {
		a = "main";
	}
}
assert(MyClass$1.name == "MyClass"); // oops

exports.MyClass = MyClass$1;
exports.MyClass2 = MyClass;

```

 [repro](https://rollupjs.org/repl?version=0.55.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNsYXNzJTIwTXlDbGFzcyUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoKSUyMCU3QiU1Q24lNUN0JTVDdGElMjAlM0QlMjAlNUMlMjJtYWluJTVDJTIyJTVDbiU1Q3QlN0QlNUNuJTdEJTVDbmFzc2VydChNeUNsYXNzLm5hbWUlMjAlM0QlM0QlMjAlNUMlMjJNeUNsYXNzJTVDJTIyKSU1Q25leHBvcnQlMjAlN0JNeUNsYXNzJTIwYXMlMjBNeUNsYXNzMiU3RCUyMGZyb20lMjAlNUMlMjIuJTJGTXlDbGFzcyU1QyUyMiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJNeUNsYXNzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNsYXNzJTIwTXlDbGFzcyUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoKSUyMCU3QiU1Q24lNUN0JTVDdGElMjAlM0QlMjAlNUMlMjJleHRlcm5hbCU1QyUyMiU1Q24lNUN0JTdEJTVDbiU3RCUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

I would suggest transforming the class as follows to prevent this:

```ts
const MyClass$1 = (class MyClass {
     ...
})
```

(In my particular case, I'm not sure at all why the symbol is being renamed, because there aren't any other variables with the same name and all the other classes which are being exported in exactly the same fashion aren't being renamed. Any hints? PlaneSurface$1 in https://gist.github.com/NaridaL/82126b0a72258dcec0cbfbddacc12532, but that isn't really the main issue)

**Comment by aristov** [comment] 2018-02-27 16:18
This bug is currently preventing me from using rollup to build my library.

**Comment by lukastaegert** [comment] 2018-02-28 14:10
As classes, in contrast to functions, are not hoisted, I guess this should be doable but will require some work. But I think the correct replacement is `let MyClass$1 = class MyClass {}` since classes can be reassigned (though not redeclared like `var` declarations).

**Comment by lukastaegert** [comment] 2018-02-28 14:11
Not sure how we could solve the same problem for functions, though. But, one issue at a time!

**Comment by guybedford** [comment] 2018-02-28 19:23
```js
let MyFunction$1 = (() => {
  function x () {
  }
  return x;
})()
```

perhaps!?

**Comment by guybedford** [comment] 2018-02-28 19:28
Actually that will mess with both the `this` binding and the hoisting of course....

Perhaps a function could be converted from a function declaration into a function expression that is manually hoisted without other loss but I'm not sure how much function declarations get exceptions otherwise in the spec.

**Comment by NaridaL** [comment] 2018-02-28 19:44
What exactly is the issue with functions?

**Comment by guybedford** [comment] 2018-02-28 19:45
`function.name` exists just like classes have names.

**Comment by NaridaL** [comment] 2018-02-28 19:54
@guybedford Right, I mean, is there a reason function declarations aren't replaceable with

```ts
var foo$1 = function foo() {}
```

**Comment by NaridaL** [comment] 2018-03-01 08:03
Would a PR for this be merged? (At least for the classes) If so, I'd be willing to take a crack at it.

**Comment by guybedford** [comment] 2018-03-01 12:19
@NaridaL you're welcome to give it a go, we'll gladly provide review for any PR work.

**Comment by lukastaegert** [comment] 2018-03-01 19:26
I do not like this. `function` declaration work really very different from anything else in that **the whole declaration is hoisted**. Compare the following:
```javascript
console.log(typeof foo); // logs "function"
foo(); // logs "works"
function foo(){
  console.log('works');
};
```

```javascript
console.log(typeof foo); // logs "undefined"
foo(); // throws an error
var foo = function foo(){
  console.log('works');
};
```

This is a very important feature that libraries actually rely on that we **must not destroy**  just in order to fix a feature that is only used in edge cases (at least that would be my suspicion).

Note that at the moment, we do not even have an open issue for functions but only for classes for which a `let` declaration should be a safe substitute. If this really becomes an issue for some, maybe we should implement a way to control the order in which variables are destructured or something along these lines.

**Comment by lukastaegert** [comment] 2018-03-01 19:28
Oh, sorry, you were actually only talking about classes in the last comment, my bad. Sure, that would be awesome!

**Comment by NaridaL** [comment] 2018-03-02 20:46
See PR https://github.com/rollup/rollup/pull/2025.

For function, one option might be to manually hoist the declaration, but from what I've seen of rollup's source, it doesn't lend itself to major AST modifications.

A simpler solution: While `f$1.name = "f"` doesn't work, `Object.defineProperty(f, "name", { value: "f" })` *does*, and it is easily appended to function declarations.

The only question is whether to attempt to protect against redefinitions of `Object` or the `defineProperty` prop. (If you don't replace it with something functionally equivalent, I'd expect many libs to break anyways=

**Comment by Narretz** [comment] 2018-03-02 20:49
I just stumbled over a similar problem - in this case, the parameter of a function that is the same as some class gets renamed. I'm not sure if this has the same root cause: [REPRO](https://rollupjs.org/repl?version=0.55.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyME15Q2xhc3MlMjAlN0QlMjBmcm9tJTIwJy4lMkZNeUNsYXNzLmpzJyUzQiU1Q24lNUNuJTVDbiU1Q25mdW5jdGlvbiUyMG5hbWUoTXlDbGFzcyklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKE15Q2xhc3MuYSklNUNuJTdEJTVDbiU1Q25jb25zb2xlLmxvZyhNeUNsYXNzLmEpJTNCJTVDbmNvbnNvbGUubG9nKG5hbWUoKSklNUNuJTVDdCU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyTXlDbGFzcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjbGFzcyUyME15Q2xhc3MlMjAlN0IlNUNuJTVDdGNvbnN0cnVjdG9yKCklMjAlN0IlNUNuJTVDdCU1Q3RhJTIwJTNEJTIwJTVDJTIyZXh0ZXJuYWwlNUMlMjIlNUNuJTVDdCU3RCU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

In this example, I would not expect that the MyClass parameter gets overwritten. I know it's a bit weird that the parameter is uppercase, but they it's legit JS :)

**Comment by guybedford** [comment] 2018-03-02 21:46
@Narretz thanks for the test case, that does look like a bug to me but unrelated to this issue. If you'd like to repost that as a new issue I can mark it as a bug.

**Comment by NaridaL** [comment] 2018-03-02 22:55
@Narretz as far as I can tell, that happens so [this](https://rollupjs.org/repl?version=0.55.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyME15Q2xhc3MlMjBhcyUyMGZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRk15Q2xhc3MuanMnJTVDbiU1Q25mdW5jdGlvbiUyMG5hbWUoTXlDbGFzcyklMjAlN0IlNUNuJTVDdGNvbnNvbGUubG9nKE15Q2xhc3MuYSUyQyUyMGZvby5hKSU1Q24lN0QlNUNuJTVDbmNvbnNvbGUubG9nKGZvby5hKSUzQiU1Q25jb25zb2xlLmxvZyhuYW1lKCU3QmElM0End2hhdGV2ZXInJTdEKSklNUNuJTVDdCU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyTXlDbGFzcy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjbGFzcyUyME15Q2xhc3MlMjAlN0IlNUNuJTVDdGNvbnN0cnVjdG9yKCklMjAlN0IlNUNuJTVDdCU1Q3RhJTIwJTNEJTIwJTVDJTIyZXh0ZXJuYWwlNUMlMjIlNUNuJTVDdCU3RCU1Q24lN0QlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)  without having to check which imports are actually being used in the function.
```
import { MyClass as foo } from './MyClass.js';
function name(MyClass) {
	console.log(MyClass.a, foo.a)
}
console.log(foo.a);
console.log(name({a:'whatever'}))
```

**Comment by Narretz** [comment] 2018-03-03 11:55
@NaridaL yeah, that makes sense. @guybedford  I'll have opened a new issue so this can be discussed independently: https://github.com/rollup/rollup/issues/2030

**Comment by guybedford** [comment] 2018-04-18 14:03
I tend to think since we don't have any possible approaches for dealing with this that it should be marked as wontfix. But if anyone has some bright ideas do share.

**Comment by shellscape** [comment] 2018-08-10 02:34
@guybedford shall we put this one to rest?

**Comment by guybedford** [comment] 2018-08-10 09:48
Sure.

**Closed by guybedford** 2018-08-10 09:48 UTC
Labels: scope-hoisting, wontfix
