### ISSUE TITLE
How can I extract the common bundle?

### ISSUE THREAD

**Issue by lsycxyj** [rollup/rollup#1115] opened 2016-11-17 23:42 UTC
There is such a plugin called factor-bundle for browserify. But how can I achieve this by rollup? And how can I output multiple bundles (eg. asynchronous loaded Components of React)?

**Comment by tivac** [comment] 2016-11-18 00:52
The short answer is you can't right now.

The longer answer is contained within #372

**Comment by lsycxyj** [comment] 2016-11-18 02:06
#372 It has been a long time. :(

**Comment by Victorystick** [comment] 2016-11-20 12:01
Closing as duplicate of #372.

**Closed by Victorystick** 2016-11-20 12:01 UTC
