### ISSUE TITLE
default exports are deleted if only used locally (within exporting module file)

### ISSUE THREAD

**Issue by lohfu** [rollup/rollup#984] opened 2016-09-25 15:44 UTC
default exports are aggressively removed if requiring module does not use it even if it used locally (inside the same file that exports it).

So for example, give the file `foo.js` with the following code:

``` js
export default function foo() {
  console.log('foo');
}

foo();
```

If our entry `app.js` only imports the module like so:

``` js
import './foo';
```

The following, obviously not functioning code is output:

``` js
(function () {
'use strict';

foo();

}());
```

If we store and use foo our entry file, like so

```
import foo from './foo';

foo();
```

the output looks like this and works as expected:

``` js
(function () {
'use strict';

function foo() {
  console.log('foo');
}

foo();

foo();

}());
```

**Comment by Victorystick** [comment] 2016-09-25 22:00
Reproduced [here](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJy4lMkZmb28nJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBmb28oKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZygnZm9vJyklM0IlNUNuJTdEJTVDbiU1Q25mb28oKSUzQiUyMiU3RCU1RCU3RA==).

**Comment by lohfu** [comment] 2016-09-26 13:22
This breaks both core d3 libraries [d3-transition](https://github.com/d3/d3-transition) and [d3-scale](https://github.com/d3/d3-scale).

For example, a simple

```js
import { scaleLinear } from 'd3-scale';
```

will generate a

```
Uncaught ReferenceError: defaultLocale is not defined
```

on line 7 in [d3-format/src/defaultLocale.js](https://github.com/d3/d3-format/blob/master/src/defaultLocale.js):

```js
import formatLocale from "./locale";

var locale;
export var format;
export var formatPrefix;

defaultLocale({
  decimal: ".",
  thousands: ",",
  grouping: [3],
  currency: ["$", ""]
});

export default function defaultLocale(definition) {
  locale = formatLocale(definition);
  format = locale.format;
  formatPrefix = locale.formatPrefix;
  return locale;
}
```

**Comment by TheBosZ** [comment] 2016-09-30 23:03
Anyone know a hacky workaround?

**Comment by bhousel** [comment] 2016-10-01 03:06
@TheBosZ Yes, you can actually call `transition()` or `defaultLocale()` in your code, then rollup is forced to include it.

[Here's an example](https://github.com/openstreetmap/iD/blob/259792cb3faa2068a0aa6cbc3fb1318900d707fc/modules/behavior/breathe.js#L17-L21) in my code that works around the issue.

**Comment by bytenik** [comment] 2016-10-12 00:15
@bhousel Unfortunately `defaultLocale` is not an exported function like `transition`. Any other hacky workarounds?

**Comment by bytenik** [comment] 2016-10-13 12:43
Can someone give me a pointer for how to fix this in Rollup? I'll take a crack at it.

Otherwise, I guess I'll switch back to Webpack until someone can address this. 😢

**Comment by Rich-Harris** [comment] 2016-12-22 00:39
Looks like this was fixed already – have added a regression test (88195198f8551d851de565d60ae6459f79367e1d), will close this

**Closed by Rich-Harris** 2016-12-22 00:39 UTC
Labels: bug
