### ISSUE TITLE
Unused function in the output

### ISSUE THREAD

**Issue by droooney** [rollup/rollup#1021] opened 2016-10-05 12:04 UTC
Since updating to `rollup@0.36` I've noticed that rollup has started to leave (or started to produce) asyncGenerator function almost in the start of the output file. My rollup config is:

``` javascript
const path = require('path');
const npm = require('rollup-plugin-node-resolve');
const eslint = require('rollup-plugin-eslint');
const babel = require('rollup-plugin-babel');

module.exports = {
  entry: './entry.js',
  dest: './dist/build.js',
  format: 'iife',
  moduleName: 'module',
  sourceMap: true,
  plugins: [
    npm(),
    eslint({
      throwError: true
    }),
    babel({
      presets: ['es2015-rollup', 'stage-0'],
      include: './**/*.js',
      plugins: ['transform-class-properties'],
      babelrc: false
    })
  ]
};
```

Moving to babel-plugin-external-helpers instead of es-2015-rollup doesn't help. Possibly it happens because it is self-executable but still it's clear that not using async functions and even generators no one needs that in their output. Probably we still do need es-2015-rollup because of this kind of stuff.

UPD: Hm, it's not possibly related to updating rollup, but rather to babel stuff but that doesn't change anything and the problem still exists.

**Comment by bclinkinbeard** [comment] 2016-10-05 15:16
Probably a dupe of #977

**Comment by Rich-Harris** [comment] 2016-12-27 22:59
Possibly fixed by more recent versions, but if not then we'd need a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) to investigate

**Closed** 2017-06-21 17:08 UTC
Labels: closed for inactivity, needs repro
