### ISSUE TITLE
[Rollup2.7+] vite build is slow ,vite transform 10000+ file( 2000+[vue] file),  It takes 2 hours to build a mac os air

### ISSUE THREAD

**Issue by cayweb778** [rollup/rollup#4732] opened 2022-12-01 00:01 UTC
### Rollup Version

2.79.1

### Operating System (or Browser)

macos

### Node Version (if applicable)

16.9

### Link To Reproduction

https://github.com/cayweb778/vite2rolluptest.git

### Expected Behaviour
中文: 
我需要帮助!!

问题描述: vite build,开发了 2000+ "vue file", 构建需要transform 10000+文件

问题节点: ”assignEntryToStaticDependencies 构建缓慢“

问题描述: macos air需要构建2小时, 低性能服务器需要6小时左右

rollup新版本有所改进么?

调试过程( 正在进行 )
1. 调试到assignEntryToStaticDependencies 函数,开始卡住,正在进一步调试
2. 看到里面判断 areEntryPointsContainedOrDynamicallyDependent 卡住,这里面有两层for
3. 有可能是这步get,add影响的,先排掉看看速度
```
// areEntryPointsContainedOrDynamicallyDependent 函数
    const dynamicallyDependentEntryPoints = dynamicallyDependentEntryPointsByDynamicEntry.get(entry);
                for (const dependentEntry of dynamicallyDependentEntryPoints) {
                    // entriesToCheck.add(dependentEntry);
                }


```
4. for 无内容,速度是非常快的,测试去掉add
5.去掉add,速度还ok,定位到add引起的缓慢,看看add的变量到底存了什么
6. 查到了一次add的巨大量操作
     -  assignEntryToStaticDependencies 一次 add了5亿次,
     - 我们的项目需要1000次,那就是5000亿add,这相当恐怖
7. 查一下为什么需要巨大量add
8. 尝试了 另一个小项目 transform4000+ file,发现只需要35次,add次数7629次,而这个问题项目1000次,add次数达到了5000亿次add
9, 
dynamicallyDependentEntryPointsByDynamicEntry :
entryPoints
containedIn
10.
每次modulesToHandle才1000左右,但areEntryPointsContainedOrDynamicallyDependent中的add进行了5亿次,
继续排查

11. 理解了下areEntryPointsContainedOrDynamicallyDependent,似乎只有index.html时才会returnfalse,
- 那么为什么,大部分动态导入的模块中,都有index.html这个子依赖呢?
- 如果仅判断index.html,那么在上层一次性查完.效率应该会更高吧

dependentEntryPointsByModule :

modulesToHandle 是 1000个入口模块中的一个

英文: 
I need help!!

Problem description: vite build, developed 2000+"vue file", and build requires transform 10000+files

Problem node: "assignEntryToStaticDependencies are slowly constructed“

Problem description: It takes 2 hours to build a mac os air, and about 6 hours for a low performance server

Is there any improvement in the new version of rollup?

Debugging process (in progress)

1. Debug to the assignEntryToStaticDependencies function. It starts to get stuck and is being debugged further

2. It is judged that areEntryPointsContainedOrDynamically Dependent is stuck when you see it. There are two layers of for

3. This step of get and add may affect the speed

```

//AreEntryPointsContainedOrDynamically Dependent function

const dynamicallyDependentEntryPoints = dynamicallyDependentEntryPointsByDynamicEntry.get(entry);

for (const dependentEntry of dynamicallyDependentEntryPoints) {

// entriesToCheck.add(dependentEntry);

}




```

4. For has no content and is very fast. Test to remove add

5. Remove add, and the speed is OK. Locate the slow speed caused by add, and see what the add variable has

6. A massive add operation is found

-AssignEntryToStaticDependencies were added 500 million times at a time,

-Our project needs 1000 times, that is 500 billion add, which is quite terrible

7. Check why a large amount of add is needed

8. I tried another small project, transform4000+file, and found that only 35 times were needed, 7629 times were added, while this problem project had 1000 times, and the number of add times reached 500 billion times

9,

dynamicallyDependentEntryPointsByDynamicEntry :

entryPoints

containedIn

ten

Each time the modulesToHandle is only about 1000, but the add in areEntryPointsContainedOrDynamically Dependent has been performed 500 million times,

Continue troubleshooting

11. After understanding the following areEntryPointsContainedOrDynamically Dependent, it seems that only index.html returns false,

-So why do most dynamically imported modules have the subdependency index.html?

-If you only judge index.html, it will be more efficient to check it in the upper layer at one time

dependentEntryPointsByModule :

ModulesToHandle is one of 1000 entry modules

### Actual Behaviour

我正在调试过程,
调试到assignEntryToStaticDependencies 函数,开始卡住,正在进一步调试

**Comment by lukastaegert** [comment] 2022-12-02 05:48
From the other thread

> What is areEntryPointsContainedOrDynamically Dependent used for? I removed it, reduced the construction time from 5 hours to less than 5 minutes, and simply tested the running status. It is good.

It is an optimization to reduce the emitted number of chunks in the following scenario

```js
// main.js
import { a } from './a.js';
import('./b.js');
console.log('main', a);

// a.js
export const a = 'a';

// b.js
import { a } from './a.js';
console.log('b', a);
```

Output without this optimization: Three separate chunks
However when the dynamic import `b.js` is loaded, `a.js` has already been loaded and is in memory, so it can be merged into `main.js` [to have two instead of three chunks](https://rollupjs.org/repl/?version=3.5.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZhLmpzJyUzQiU1Q25pbXBvcnQoJy4lMkZiLmpzJyklM0IlNUNuY29uc29sZS5sb2coJ21haW4nJTJDJTIwYSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYSUyMCUzRCUyMCdhJyUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBhJTIwJTdEJTIwZnJvbSUyMCcuJTJGYS5qcyclM0IlNUNuY29uc29sZS5sb2coJ2InJTJDJTIwYSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

But this optimization indeed could be potentially costly. I however did not have a large enough code-base yet to see the effect. One could potentially improve performance here by reducing the situations in which this optimization is applied, or other things.

I would like to work on this soon to improve the situation, and your reproduction could help a lot to try out some things.

Unfortunately I do not speak Chinese. Can you give me instructions in English how to "run" your reproduction to see the issue? What do I need to do after checking out the repository?

**Comment by cayweb778** [comment] 2022-12-02 07:48
> From the other thread
> 
> > What is areEntryPointsContainedOrDynamically Dependent used for? I removed it, reduced the construction time from 5 hours to less than 5 minutes, and simply tested the running status. It is good.
> 
> It is an optimization to reduce the emitted number of chunks in the following scenario
> 
> ```js
> // main.js
> import { a } from './a.js';
> import('./b.js');
> console.log('main', a);
> 
> // a.js
> export const a = 'a';
> 
> // b.js
> import { a } from './a.js';
> console.log('b', a);
> ```
> 
> Output without this optimization: Three separate chunks However when the dynamic import `b.js` is loaded, `a.js` has already been loaded and is in memory, so it can be merged into `main.js` [to have two instead of three chunks](https://rollupjs.org/repl/?version=3.5.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZhLmpzJyUzQiU1Q25pbXBvcnQoJy4lMkZiLmpzJyklM0IlNUNuY29uc29sZS5sb2coJ21haW4nJTJDJTIwYSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYSUyMCUzRCUyMCdhJyUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBhJTIwJTdEJTIwZnJvbSUyMCcuJTJGYS5qcyclM0IlNUNuY29uc29sZS5sb2coJ2InJTJDJTIwYSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).
> 
> But this optimization indeed could be potentially costly. I however did not have a large enough code-base yet to see the effect. One could potentially improve performance here by reducing the situations in which this optimization is applied, or other things.
> 
> I would like to work on this soon to improve the situation, and your reproduction could help a lot to try out some things.
> 
> Unfortunately I do not speak Chinese. Can you give me instructions in English how to "run" your reproduction to see the issue? What do I need to do after checking out the repository?
export NODE_OPTIONS=--max-old-space-size=30000
pnpm install
pnpm build

**Comment by cayweb778** [comment] 2022-12-02 07:51
```
git clone https://github.com/cayweb778/hello.git

cd hello

npm install pnpm -g
export NODE_OPTIONS=--max-old-space-size=30000
pnpm install
pnpm build
```

**Comment by cayweb778** [comment] 2022-12-02 08:13
> From the other thread
> 
> > What is areEntryPointsContainedOrDynamically Dependent used for? I removed it, reduced the construction time from 5 hours to less than 5 minutes, and simply tested the running status. It is good.
> 
> It is an optimization to reduce the emitted number of chunks in the following scenario
> 
> ```js
> // main.js
> import { a } from './a.js';
> import('./b.js');
> console.log('main', a);
> 
> // a.js
> export const a = 'a';
> 
> // b.js
> import { a } from './a.js';
> console.log('b', a);
> ```
> 
> Output without this optimization: Three separate chunks However when the dynamic import `b.js` is loaded, `a.js` has already been loaded and is in memory, so it can be merged into `main.js` [to have two instead of three chunks](https://rollupjs.org/repl/?version=3.5.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZhLmpzJyUzQiU1Q25pbXBvcnQoJy4lMkZiLmpzJyklM0IlNUNuY29uc29sZS5sb2coJ21haW4nJTJDJTIwYSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYSUyMCUzRCUyMCdhJyUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBhJTIwJTdEJTIwZnJvbSUyMCcuJTJGYS5qcyclM0IlNUNuY29uc29sZS5sb2coJ2InJTJDJTIwYSklM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).
> 
> But this optimization indeed could be potentially costly. I however did not have a large enough code-base yet to see the effect. One could potentially improve performance here by reducing the situations in which this optimization is applied, or other things.
> 
> I would like to work on this soon to improve the situation, and your reproduction could help a lot to try out some things.
> 
> Unfortunately I do not speak Chinese. Can you give me instructions in English how to "run" your reproduction to see the issue? What do I need to do after checking out the repository?

Thanks , As above

**Comment by lukastaegert** [comment] 2022-12-04 18:46
Unfortunately, I did not manage to reproduce the problem because for me, the build always failed much earlier due to unrelated issues. Still, I took some time to rewrite the critical part of the chunking algorithm in a way that hopefully performs better in #4736.

As your reproduction still uses Vite 2 and an older version of Rollup, I created a beta version of the patch based on rollup@2.77.

Can you please try it out and give me feedback by installing `rollup@2.77.4-0`?

**Comment by cayweb778** [comment] 2022-12-05 23:24
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/40415260/205764902-470f8344-3781-4346-b4f6-c4925c3a40e6.png">
`getAlreadyLoadedModulesByDynamicEntry`
Sorry, it is still very slow here. It seems that there is not much change ,getAlreadyLoadedModulesByDynamicEntry

**Comment by cayweb778** [comment] 2022-12-05 23:28
This is new single vite2 repo:  `https://github.com/cayweb778/vite2rolluptest.git`

**Comment by cayweb778** [comment] 2022-12-05 23:34
At present, I am using this this for testing. Everything is normal

**Comment by cayweb778** [comment] 2022-12-06 00:07
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/40415260/205773290-23d321f5-f316-4eea-994e-13847e1c833e.png">

Capture in debugging: 

allModules 7200+ times
dependentEntryPoints 1041 times
dynamicEntriesToHandle 1400+ times

**Comment by cayweb778** [comment] 2022-12-06 00:17
This is new single vite2 repo: https://github.com/cayweb778/vite2rolluptest.git

npm install pnpm -g
export NODE_OPTIONS=--max-old-space-size=3000000000
pnpm install
pnpm build

**Comment by cayweb778** [comment] 2022-12-06 00:17
At present, I am using this this for testing. Everything is normal

**Comment by cayweb778** [comment] 2022-12-06 03:45
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/40415260/205807814-7b46c5c6-102a-49a4-99ea-2f95ca4d647e.png">

<img width="417" alt="image" src="https://user-images.githubusercontent.com/40415260/205807719-e5db4226-0926-437a-9996-b6a033c5b668.png">

**Comment by cayweb778** [comment] 2022-12-06 03:46
Seems to be slower, 4s * 7000/60/60=9hours+

**Comment by lukastaegert** [comment] 2022-12-07 12:38
Thanks for the new reproduction, I was actually able to work with this. Based on this, I decided to finally make the algorithm slightly simpler. Now it will not always create ideal chunks, but it still will in most case. For me, it now generates the chunks in around 30s.

You can try it out via rollup@2.77.4-1

**Comment by cayweb778** [comment] 2022-12-07 19:26
> Thanks for the new reproduction, I was actually able to work with this. Based on this, I decided to finally make the algorithm slightly simpler. Now it will not always create ideal chunks, but it still will in most case. For me, it now generates the chunks in around 30s.
> 
> You can try it out via rollup@2.77.4-1

<img width="909" alt="image" src="https://user-images.githubusercontent.com/40415260/206276780-b6a5f5b2-bfa5-4962-b889-95d005755bcf.png">

**Comment by lukastaegert** [comment] 2022-12-07 19:42
If you want to say you still have performance issues there, I fear you will need to update to Rollup 3/Vite 4. This part has been completely reworked here and also a performance issue has been fixed. But I do not have the bandwidth to port a fix to Rollup 2.

**Comment by cayweb778** [comment] 2022-12-07 19:45
> If you want to say you still have performance issues there, I fear you will need to update to Rollup 3/Vite 4. This part has been completely reworked here and also a performance issue has been fixed. But I do not have the bandwidth to port a fix to Rollup 2.

thank you very much,this solves my question,base on this.i will update vite3 +,this may tak some time,hope on rollup 3.xx may use this improve,

Can you tell me the specific version of 3.xx or 4.xx

**Comment by cayweb778** [comment] 2022-12-07 19:48
funciton `assignChunkIds` need about 30min+,What can I do to improve the performance

**Comment by cayweb778** [comment] 2022-12-07 19:49
If possible, I will report to vite.

**Comment by cayweb778** [comment] 2022-12-07 20:49
<img width="854" alt="image" src="https://user-images.githubusercontent.com/40415260/206292352-06a54b87-d82c-47cb-b79f-92e4ad38a980.png">
A lot of processing has been done here,may be 5000 billions

**Comment by cayweb778** [comment] 2022-12-07 21:08
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/40415260/206295685-46f0defc-95e8-40bb-980f-97758417a343.png">
<img width="375" alt="image" src="https://user-images.githubusercontent.com/40415260/206295746-70f370eb-2bbb-4056-ac00-90ce83bb578e.png">

**Comment by cayweb778** [comment] 2022-12-07 21:09
Please move this task to Rollup 3+, vite 4+. I have updated the warehouse dependency to expect future support,

repo: https://github.com/cayweb778/hello.git

**Comment by cayweb778** [comment] 2022-12-08 00:30
rollup2 + vite2 issue : https://github.com/rollup/rollup/issues/4732

**Closed** 2022-12-10 06:14 UTC
Labels: t¹ 🐞 bug, t⁸ ⋅ triage
