### ISSUE TITLE
False positive constant (tree shaking)

### ISSUE THREAD

**Issue by ThomasBrierley** [rollup/rollup#3027] opened 2019-08-05 12:46 UTC
- Rollup Version: v1.18.0
- Operating System (or Browser): Linux 4.19.0-5-amd64
- Node Version: v10.15.2

### How Do We Reproduce?

```js
const local = {
	prop: false,
	meth (x) {
		this.prop = x;
	}
};

export const meth = (x) => {
	local.meth(x);
};

export const test = () => {
	if (local.prop === true) { // this is not constant
		console.log('true'); // this should remain
	}
};
```

### Expected Behaviour

The condition should remain since the value of `prop` can be modified from outside of the module.

### Actual Behaviour

The condition is removed.

### Notes

Some things that avoid this behaviour:

- Setting `prop` value using the object name `local` instead of `this`.
- Exporting the whole `local` object instead of wrapping the method.
- Using a variable in the module context for the condition.

Seems to depend on two things: determining object property mutability through more than one layer of function calls combined with the use of the `this` keyword and non-equivalence with any named references to the object.

**Comment by ThomasBrierley** [comment] 2019-08-05 14:29
I think the source of the issue is here:
https://github.com/rollup/rollup/blob/2443783d0b1214ab742373414ed03d4f0f75964f/src/ast/nodes/IfStatement.ts#L25
My understanding of what's going on bellow that is nil due to being heavily typescript.

**Comment by lukastaegert** [comment] 2019-08-05 16:26
The root of the problem is that modifications via `this` do not yet correctly invalidate object paths. This is a known problem but unfortunately not that easy to fix. I hope to get to this eventually.

**Comment by lukastaegert** [comment] 2019-08-05 16:27
The code line you identified would return UNKNOWN_VALUE if the invalidation would kick in properly.

**Comment by kzc** [comment] 2019-08-05 16:35
Duplicate of #2345 and #2473.

Fixed by either patch in https://github.com/rollup/rollup/issues/2345#issuecomment-466451823. These patches disable an optimization that is not valid in all cases.

I'm kind of surprised that this bug is not encountered by most rollup users. It's a fairly common code pattern.

**Comment by ThomasBrierley** [comment] 2019-08-06 09:37
Thanks, is the patch by @kzc likely to be merged?

I'm also surprised _this_ hasn't hit me before... or maybe it has :worried:

**Closed** 2019-12-02 06:13 UTC
