### ISSUE TITLE
Silent processing - Dynamic Import not transpiled when filepath not exist

### ISSUE THREAD

**Issue by tunnckoCore** [rollup/rollup#1957] opened 2018-02-09 00:23 UTC
We already have support for parsing Dynamic Import through `experimentalDynamicImport` option, which in turn compiles it to something like `Promise.resolve().then(function () { return bar$1; });`.

But it seems that if `./bar.js` not exists it remains as is.

```
rollup -i foo.mjs -o qux.mjs --experimentalDynamicImport -f cjs
```

example

```js
async function run() {
  const { default: bark } = await import('./bar.mjs')
  const res = bark(1, 2)
  console.log(res)
}

run()
```

output when `./bar.mjs` exists

```js
'use strict';

async function run() {
  const { default: bark } = await Promise.resolve().then(function () { return bar$1; });
  const res = bark(1, 2);
  console.log(res);
}

run();

var bar = (a, b) => Promise.resolve(a + 1 + 2 + b)


var bar$1 = Object.freeze({
	default: bar
});
```

But when we change the path to something that not exists it returns

```js
'use strict';

async function run() {
  const { default: bark } = await import('./barasasas');
  const res = bark(1, 2);
  console.log(res);
}

run();

```

I know Rollup is not meant for transpiling, but it does this currently and does not informs you with error that the path not exists.

**Comment by lukastaegert** [comment] 2018-02-09 05:33
Yes, that is by design. If you have dynamic imports enabled without code-splitting, locally resolvable dynamic imports are inlined (that is what you observed with `Promise.resolve().then...`). If you additionally have code-splitting enabled, new chunks are created instead.

Unfortunately for non-resolvable imports, it is impossible to inline them (because–what would you inline?), and it may not even be desired as one feature of dynamic imports is of course that you could e.g. import something from outside your bundle or even a web server at run-time. For that matter, non-resolvable dynamic imports are not unlike traditional external imports.

This is documented here: https://rollupjs.org/guide/en#experimental-options

Let us know if you have suggestions for how to improve this behaviour or its documentation.

**Comment by guybedford** [comment] 2018-02-09 08:03
We could potentially provide a warning for untraceable dynamic imports, and I think that might at least be useful here, unless the dynamic import module is explicitly marked as an external.

**Comment by lukastaegert** [comment] 2018-02-09 08:14
I agree, this issues shows that it makes sense to hook at least statically resolvable dynamic imports into the external dependency warning mechanism.

**Comment by olstenlarck** [comment] 2018-02-09 15:41
Yea. Exactly, warn or error would be enough.

I even think that Rollup best would be to exit with non-zero code when `id` is local module (e.g. `./` and `../`) **and** when not exists.

Not make sense to just warn, cuz you'll go and check that it is a typo and fix it, cuz you don't want to have dynamic imports in the final output.

**Comment by alundiak** [comment] 2018-10-12 10:02
Considerig, that `experimentalDynamicImport` removed from Rollup, how this issue is relevant? 
cc/ @guybedford ; @tunnckoCore ; @lukastaegert

**Comment by tunnckoCore** [comment] 2018-10-12 13:31
I'm not sure. Is the behavior still the same?
I shared my thoughts and still am behind my words.

**Comment by shellscape** [comment] 2019-08-09 13:27
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Closed by shellscape** 2019-08-09 13:27 UTC
