### ISSUE TITLE
Tree shaking not applied for node modules

### ISSUE THREAD

**Issue by blacksonic** [rollup/rollup#663] opened 2016-05-24 21:04 UTC
I dont know if it is a problem of the node resolve plugin or something in connection with rollup itself or my config, so i open this ticket also here as in node resolver https://github.com/rollup/rollup-plugin-node-resolve/issues/39

When i use rollup with node_modules unused exports also appear in the bundled file.
Shouldnt it apply tree shaking also for node_modules?
Of course these unused exports disappear when uglified, but according to the official Rollup examples these should not be there before uglify.

I made an example repo to show my problem.
https://github.com/blacksonic/es2015-tree-shaking

I use RxJS, and it always applies operators for example, which makes the size bigger. Even if i uglify.

**Comment by Victorystick** [comment] 2016-05-26 20:09
@blacksonic Rollup can tree-shake code so long as it's written using ES modules whose exports are free of side-effects. Code in `node_modules` should be tree-shakeable so long as it satisfies those requirements.

CommonJS modules or side-effectful module aren't shakable. Last time I looked, RxJS does not appear to be easy for Rollup to optimize.

**Comment by blacksonic** [comment] 2016-05-26 20:11
I'm using this package ```rxjs-es```, it uses ES6 modules.

**Comment by Victorystick** [comment] 2016-05-27 20:32
[This part](https://github.com/ReactiveX/rxjs/blob/master/src/Rx.ts#L11-L140) of the main Rx definition are all side-effectful imports, which aren't tree-shaken. According to [the rxjs-es docs](https://www.npmjs.com/package/rxjs-es#es6-via-npm) it should be better to:

```js
import { Observable } from 'rxjs-es/Observable';

const source = Observable.create( observer => {
  observer.next(42);
  observer.complete();
});

console.log(source.map); // => undefined
source.subscribe( value => {
  console.log(value);
});
```

**Comment by blacksonic** [comment] 2016-05-28 07:00
I know it, but for example ```BehaviorSubject``` also appears there which can be shaken.

**Comment by blacksonic** [comment] 2016-05-28 07:01
If it finds a side-effectful import automatically skips tree-shaking?

**Comment by Victorystick** [comment] 2016-06-01 18:31
@blacksonic Well, no it doesn't _skip_ tree-shaking. But Rollup has to make sure that any code that is _used_ is included in the bundle. So if there are statements that have side-effects, we'll need to include anything used by those statements.

**Comment by Rich-Harris** [comment] 2016-06-24 02:15
This falls under the general heading of 'things that might improve with smarter static analysis' – it's not a bug per se – so I'll close this as there are several other similar issues. Thanks

**Closed by Rich-Harris** 2016-06-24 02:15 UTC
