### ISSUE TITLE
Error after rollup upgrade from 0.50.0 to 0.51.1

### ISSUE THREAD

**Issue by edoardocavazza** [rollup/rollup#1710] opened 2017-11-08 21:18 UTC
Hi! I have tried to update to rollup 0.51.1 in order to benefit of threeshake improvements but when I run the build task, now it fails with:
```
RangeError: Maximum call stack size exceeded
    at ParameterVariable.bindAssignmentAtPath (rollup/dist/rollup.js:11351:23)
    at Node.bindAssignmentAtPath (rollup/dist/rollup.js:12620:20)
    at path$$1.length._forEachRelevantBranch.node (rollup/dist/rollup.js:12862:48)
    at Node._forEachRelevantBranch (rollup/dist/rollup.js:12913:4)
    at Node.bindAssignmentAtPath (rollup/dist/rollup.js:12862:11)
    at boundExpressions.forEachAtPath (rollup/dist/rollup.js:11360:10)
    at _assignments.get.forEach.assignment (rollup/dist/rollup.js:11255:59)
    at Set.forEach (<anonymous>)
    at VariableShapeTracker.forEachAtPath (rollup/dist/rollup.js:11255:36)
    at ParameterVariable.bindAssignmentAtPath (rollup/dist/rollup.js:11359:26)
```

At the moment, I can't share my repository, and I have no idea about which part of the code throws the error, but if someone could help me to to spot where to put a log in order to find out the indicted file, I would be pleased to report a more detailed issue.

**Comment by lukastaegert** [comment] 2017-11-09 05:45
Hi @edoardocavazza,
this is unfortunate and I really want to help here. This kind of errors is usually caused by recursive calls or assignments or combinations thereof. I have spent a lot of time finding and preventing every last one of them but apparently there is still at least one situation left.
It would be VERY helpful if you could provide code that causes this issue, or a repository that has this issue, but you already mentioned this is not easily possible.

If you want to help with debugging: You could put a log statement into node_modules/rollup/dist/rollup.js around line 11351 like this:
```javascript
bindAssignmentAtPath ( path$$1, expression, options ) {
	console.log('bind', this.name, path$$1, expression.toString()); // new log statement
	if ( path$$1.length > MAX_PATH_LENGTH || this.boundExpressions.hasAtPath( path$$1, expression ) ) { return; }
...
```
Now before the stack trace, you will probably get many repeating lines of logs. These will give you the names of variables which are assigned values, what object path they are assigned to (when I assign to `foo.bar.baz` the name is `foo` and the path is `["bar",  "baz"]`), and what expression is assigned to them. This will give us an indication of which of your code might cause this. Maybe then it is possible to isolate this problem running only this code.

**Comment by edoardocavazza** [comment] 2017-11-09 20:28
Ok, thanks to the log I found out that the problem occurs when importing PouchDB distribution file. I have managed to reduce the case to just the issue and, finally, I got this:

https://rollupjs.org/repl?version=0.51.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwVGVzdCUyMCU3QiU1Q24lMjAlMjAlMjAlMjBjb25zdHJ1Y3RvcihuYW1lJTJDJTIwb3B0cyklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwb3B0cyUyMCUzRCUyMG9wdHMlMjAlN0MlN0MlMjAlN0IlN0QlM0IlNUNuJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGlmJTIwKG5hbWUlMjAlMjYlMjYlMjB0eXBlb2YlMjBuYW1lJTIwJTNEJTNEJTNEJTIwJ29iamVjdCcpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG9wdHMlMjAlM0QlMjBuYW1lJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG5hbWUlMjAlM0QlMjBvcHRzLm5hbWUlM0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwZGVsZXRlJTIwb3B0cy5uYW1lJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdGhpcy5uYW1lJTIwJTNEJTIwbmFtZSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjB0aGlzLm9wdHMlMjAlM0QlMjBvcHRzJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lN0QlNUNuJTVDbm5ldyUyMFRlc3QoJ2EnJTJDJTIwJTdCJTdEKSUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

It seems that the `delete opts.name` statement is the cause for `Maximum call stack size exceeded`

**Comment by lukastaegert** [comment] 2017-11-10 05:36
You are a hero, this is REALLY valuable, thanks! I will take a look soon.

**Closed** 2017-11-11 22:16 UTC
