### ISSUE TITLE
custom bundle including d3-hierarchy breaks in 0.36.1

### ISSUE THREAD

**Issue by davelandry** [rollup/rollup#1009] opened 2016-09-30 20:09 UTC
First off, thanks for all the hard work that's been put into this library.

Updating to 0.36.1 has broken my build, which uses [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) to include the [d3-hierarchy](https://github.com/d3/d3-hierarchy#treemap) treemap generator. Here is a stripped down example repository that reproduces the error: https://github.com/davelandry/rollup-d3

**Comment by mbostock** [comment] 2016-09-30 22:38
This is interesting. It looks like it’s due to Rollup forgetting the trailing semicolon when it rewrites functions. The generated code looks like this, abridged:

```js
var treemap = function() {
  // treemap constructor
}

(function custom(ratio) {
  // resquarify constructor
})(phi);
```

Restoring the semicolon fixes the issue:

```js
var treemap = function() {
  // treemap constructor
};

(function custom(ratio) {
  // resquarify constructor
})(phi);
```

**Comment by Victorystick** [comment] 2016-10-03 18:00
Closing as duplicate of #1004.

**Closed by Victorystick** 2016-10-03 18:00 UTC
Labels: duplicate
