### ISSUE TITLE
Rollup 0.49 includes unused babel-helpers

### ISSUE THREAD

**Issue by mjeanroy** [rollup/rollup#1595] opened 2017-08-29 13:41 UTC
Hi,

Since rollup 0.49, some babel helpers are included even when it is not used. As documented, I'm using `rollup-plugin-babel` with `babel-external-helpers` plugin.

You can look at [this repository](https://github.com/mjeanroy/rollup-bug-0.49) to reproduce the issue: I only use a class so I expect to get only the `classCallCheck` helper, but the `AsyncGenerator` helper is also included (see the [generated bundle](https://github.com/mjeanroy/rollup-bug-0.49/blob/master/index.bundle.js)).

It worked fine with rollup 0.48, so my intuition is that it's probably due to the new tree-shaking algorithm (great job by the way!), or it may be due to a bad configuration that appear now with the new version of rollup.

I tried to debug and I would be happy to help, but honestly, I don't know where to start :/

**Comment by vlad-zhukov** [comment] 2017-08-30 13:17
It also adds unused [`var babelHelpers = {};`](https://github.com/mjeanroy/rollup-bug-0.49/blob/4761379290c738069f96abedfbd82adaa7f65f3c/index.bundle.js#L1) at the top and [`babelHelpers;`](https://github.com/mjeanroy/rollup-bug-0.49/blob/4761379290c738069f96abedfbd82adaa7f65f3c/index.bundle.js#L173) at the bottom.

**Comment by lukastaegert** [comment] 2017-08-31 11:13
I have taken a look at it and unfortunately it will take some time. @vlad-zhukov This one is a result of a safety measure we added in case where variables are executed as statements for side-effect. This one is easily remedied since babelHelpers is a local variable and accessing it has certainly no side-effects. I will make a small pull request for this.

Unfortunately, the bigger problem is removing the unused helpers. The core of the problem is code like this:

```javascript
AsyncGenerator.prototype.next = function (arg) {
  return this._invoke("next", arg);
};
```

For now, rollup is unable to determine if AsyncGenerator.prototype has been assigned elsewhere and therefore is forced to assume that mutating it can have side-effects. I plan on resolving this eventually but it will take some time until we get there. Sorry for this. At least, besides AsyncGenerator, all other helpers are removed. But I think solving this will benefit a lot of libraries.

Thanks for the issue, especially with the repo for reproduction, this is really helpful to see where we stand!

**Comment by mjeanroy** [comment] 2017-08-31 12:04
@lukastaegert Thanks for these details, I understand the problem.

> For now, rollup is unable to determine if AsyncGenerator.prototype has been assigned elsewhere and therefore is forced to assume that mutating it can have side-effects.

For this specific example, it may be possible (I'm not saying "easy" 😉) to detect that `AsyncGenerator` is only local to the anonymous function, so it cannot have been assigned elsewhere, what do you think?

**Comment by lukastaegert** [comment] 2017-08-31 12:10
Still quite difficult because you could have reassigned it locally 😮. I am sorry but I do not feel comfortable with a quick fix here, there have already been quite a few regressions with my PR 🙄. Fear, there will be a generic solution soon, but it may take a few weeks.

**Comment by kentcdodds** [comment] 2017-09-07 22:22
Thanks for all the work on this so far. I went through the trouble of creating [my own reproduction repo](https://github.com/kentcdodds/rollup-async-babel-issue) before finding this issue 😅 

Would love this to get fixed. If I can find some cycles I'll look into it myself, but I probably wont be able to :-( I'll just stick with 0.48 for now.

**Comment by Andarist** [comment] 2017-09-11 12:47
> Still quite difficult because you could have reassigned it locally

As its created in function's local scope it should be doable to track reassignments, right?

**Comment by lukastaegert** [comment] 2017-09-11 13:02
Now that I have submitted #1624 , I plan to work on this for my next PR. The problem is that we need to track reassignments of member expressions, not variables. The difficult part is then to associate variables with the assignments to their member expressions in a meaningful way. Basically, we will be tracking potential object shapes.

My current plan is to handle this via the newly created `Variable` (or, more precisely, its descendant `LocalVariable`) class I introduced in #1624. Still, experience tells me that there will be more refactorings necessary to make this work. Nevertheless, 2-3 weeks might be a realistic time frame.

**Comment by kzc** [comment] 2017-09-11 13:28
> Nevertheless, 2-3 weeks might be a realistic time frame.

@lukastaegert If you hope to implement something like [SSA](https://en.wikipedia.org/wiki/Static_single_assignment_form) that would be impressive. In any case no one will hold you to that time frame. ;-)

**Comment by lukastaegert** [comment] 2017-09-11 13:42
That would indeed be quite a feat (and I see I should definitely read up on my theoretic background - only time will tell where we will go at some point) 🙄

No, I have set my sights a little lower: My goal (for now…) is purely static analysis, no dynamic analysis. I.e. the results will not be as optimal as they could be, but our code should become noticeably simpler.

1. During .bind(), I want to collect all member assignments in data structures I attach to the individual variables.
2. Each time we check if calling/mutating a member has an effect, I want to call some method on the variable that receives something like the path we are interested in and forwards the request to all potential nodes.
3. Handling of object literals is something I will surely figure out on the way
4. If something unforeseen has been done, we can always return UNKNOWN_ASSIGNMENT which always has an effect.

The hardest part will probably be to figure out a what can be unforeseen 😋. And mind you, this is all ideas in my head, it's quite possible I will abandon this approach once I start to actually implement things.

**Comment by kzc** [comment] 2017-09-12 12:54
related: 

Marking babel helpers with pure annotation if they are a CallExpressions
https://github.com/babel/babel/pull/6231

**Comment by Andarist** [comment] 2017-10-01 10:51
Just for anyone interested, this can be 'fixed' for now in the userland with:
```js
import babel from 'rollup-plugin-babel'
import { list as babelHelpersList } from 'babel-helpers'

// ...

  babel({
    plugins: [
      'external-helpers',
    ],
    // fixing temporary rollup's regression, remove when rollup/rollup#1595 gets solved
    externalHelpersWhitelist: babelHelpersList.filter(helperName => helperName !== 'asyncGenerator'),
  }),
```

**Comment by lzxb** [comment] 2017-11-04 17:20
I also have the same problem

**Closed** 2017-11-08 06:56 UTC
