### ISSUE TITLE
rollup --watch clears screen even though it's configured not to

### ISSUE THREAD

**Issue by JimPanic** [rollup/rollup#1804] opened 2017-12-21 07:09 UTC
Following up on the comment in the PR #1688 . I have the same issue as @futuris88. I run rollup on fish using the stock Terminal app on macOS High Sierra.

I tried to turn off the `clearScreen` feature by configuration, but was not successful. The output on my screen still gets reset.

I tried to update the source to not do this, but had to destructively change a *lot* to make this work. This is also why I haven't provided a PR yet.

My `rollup.config.js` looks roughly like this:
```js
export default {
  name: '...',
  input: './built/src/app/client.js',
  output: {
    file:   './public/client.js',
    exports: 'named',
    format: 'iife'
  },
  watch: {
    clearScreen: false
  },
  plugins
}
```

I'd appreciate any pointers towards a possible PR or a different solution.

**Comment by PaulBGD** [comment] 2017-12-22 00:36
I can confirm it happens in Gnome Terminal running Bash.

**Comment by evocateur** [comment] 2017-12-26 23:03
Unfortunately #1688 didn't completely solve the issue, as it still allows the alternate screen to be opened, which causes what _appears_ to be a screen reset (but is actually just the alternate buffer being super-imposed) regardless of `clearScreen` config.

To properly address this, you'd need to configure the alternate screen [here](https://github.com/rollup/rollup/blob/d94db0f2ee23cc4a036c645b517b9dcb94659eb6/bin/src/run/watch.ts#L33), perhaps by adding a boolean parameter `clearScreen` and modifying [screen.reset](https://github.com/rollup/rollup/blob/d94db0f2ee23cc4a036c645b517b9dcb94659eb6/bin/src/run/alternateScreen.ts#L32) to omit the special characters appropriately. The problem is, right now, the config isn't evaluated until after `start()` is called, which is wayyyyy after the `alternateScreen()` factory has been initialized (and `screen.open()` has been called).

I think it's safe to require restarting the whole watcher process if you change those options in a config file that you'd normally expect to hot-reload. It's maddening otherwise, since several TTY-related options have already been essentially hard-coded during the initialization of the watcher parent process.

**Comment by evocateur** [comment] 2017-12-26 23:21
I started sketching out a fix, but I haven't had time to test it properly (still getting my TypeScript legs, too). I suspect I need to guard the alternate screen open & close, too, but I'm not sure if the alternate screen buffer is really the issue, here.
```diff
diff --git a/bin/src/run/alternateScreen.ts b/bin/src/run/alternateScreen.ts
index 0065ad5f..628bd5d1 100644
--- a/bin/src/run/alternateScreen.ts
+++ b/bin/src/run/alternateScreen.ts
@@ -25,10 +25,10 @@ export default function alternateScreen (enabled: boolean, clearScreen: boolean)
 
 	return {
 		open () {
-			process.stderr.write(SHOW_ALTERNATE_SCREEN);
+			clearScreen && process.stderr.write(SHOW_ALTERNATE_SCREEN);
 		},
 		close () {
-			process.stderr.write(HIDE_ALTERNATE_SCREEN);
+			clearScreen && process.stderr.write(HIDE_ALTERNATE_SCREEN);
 		},
 		reset (heading: string) {
 			stderr(`${resetPrefix}${heading}`);
```
The patch above (onto my linked commit) would completely avoid the alternate screen buffer when `{ clearScreen: false }` was passed via config.

**Comment by JimPanic** [comment] 2017-12-28 09:36
I just tried out a few things and got it to work, but it is far from ideal. Turns out a ``rollup.config.js`` can return an array of configurations, each having their own `watch` configuration. Ignoring that, having a variable `clearScreen` inside `watch->start` function and some rearrangement in the order of execution, the `alternateScreen` can be already be disabled by passing `false`. Or more precisely: `screen = alternateScreen(isTTY && clearScreen)`.

*I do have a hard time understanding whether these changes have unintended effects due to the interwoven nature of the `I/O`, configuration and event handling in this file.*

This is my naïve patch:

```diff
diff --git a/bin/src/run/watch.ts b/bin/src/run/watch.ts
index 39cea2ed..ff7dd8b0 100644
--- a/bin/src/run/watch.ts
+++ b/bin/src/run/watch.ts
@@ -29,19 +29,14 @@ interface Watcher {
 
 export default function watch (configFile: string, configs: RollupWatchOptions[], command: any, silent = false) {
 	const isTTY = Boolean(process.stderr.isTTY);
-
-	const screen = alternateScreen(isTTY);
-	screen.open();
-
 	const warnings = batchWarnings();
-
+	let screen:  any;
 	let watcher: Watcher;
 	let configWatcher: Watcher;
 
 	function start (configs: RollupWatchOptions[]) {
-		screen.reset(chalk.underline(`rollup v${rollup.VERSION}`));
+		let clearScreen: boolean = true;
 
-		let screenWriter = screen.reset;
 		configs = configs.map(options => {
 			const merged = mergeOptions({ config: options, command, defaultOnWarnHandler: warnings.add });
 
@@ -58,12 +53,19 @@ export default function watch (configFile: string, configs: RollupWatchOptions[]
 				(<RollupWatchOptions>merged.inputOptions).watch &&
 				(<RollupWatchOptions>merged.inputOptions).watch.clearScreen === false
 			) {
-				screenWriter = stderr;
+				clearScreen = false;
 			}
 
+
 			return result;
 		});
 
+		screen = alternateScreen(isTTY && clearScreen);
+		screen.open();
+		screen.reset(chalk.underline(`rollup v${rollup.VERSION}`));
+
+		let screenWriter = clearScreen ? stderr : screen.reset;
+
 		watcher = rollup.watch(configs);
 
 		watcher.on('event', (event: WatchEvent) => {
@@ -114,6 +116,8 @@ export default function watch (configFile: string, configs: RollupWatchOptions[]
 		});
 	}
 
+	start(configs);
+
 	// catch ctrl+c, kill, and uncaught errors
 	const removeOnExit = onExit(close);
 	process.on('uncaughtException', close);
@@ -136,7 +140,6 @@ export default function watch (configFile: string, configs: RollupWatchOptions[]
 		if (configWatcher) configWatcher.close();
 	}
 
-	start(configs);
 
 	if (configFile && !configFile.startsWith('node:')) {
 		let restarting = false;
```

**Comment by evocateur** [comment] 2017-12-28 15:01
That patch won’t work, you can’t start before the exit handlers are setup, and you should only setup the screen once.

The watch configuration option isn’t generally passed from rollup.config.js, it’s merged from CLI options. Finding it in any config is sufficient.

**Comment by evocateur** [comment] 2017-12-28 19:29
https://github.com/evocateur/rollup/commit/d74e4492fd5c39f94d8ef6819c074b634508d130 avoids clearing the screen when `{ watch: { clearScreen: false } }` is passed from a `rollup.config.js` in _any_ provided config block.

**Comment by JimPanic** [comment] 2017-12-29 08:31
This looks good and splitting `start` and the configuration processing makes a lot of sense.

But with the `SHOW_ALTERNATE_SCREEN` and `HIDE_ALTERNATE_SCREEN` still being printed, the screen is still cleared. When rearranging `alternateScreen` to only show those two control strings when `clearScreen` and `enabled` are true, the whole function can become simpler and there is actually no need to have the `clearScreen` parameter separately. The responsibility can be shifted to the caller (`isTTY && clearScreen` enables or disables the alternating screen):

```diff
diff --git a/bin/src/run/alternateScreen.ts b/bin/src/run/alternateScreen.ts
index 0065ad5f..96937dda 100644
--- a/bin/src/run/alternateScreen.ts
+++ b/bin/src/run/alternateScreen.ts
@@ -6,32 +6,23 @@ import { stderr } from '../logging.js';
 const SHOW_ALTERNATE_SCREEN = '\u001B[?1049h';
 const HIDE_ALTERNATE_SCREEN = '\u001B[?1049l';
 
-export default function alternateScreen (enabled: boolean, clearScreen: boolean) {
-	if (!enabled) {
-		let needAnnounce = true;
-		return {
-			open () { },
-			close () { },
-			reset (heading: string) {
-				if (needAnnounce) {
-					stderr(heading);
-					needAnnounce = false;
-				}
-			}
-		};
-	}
+const showAlternateScreen = process.stderr.write.bind(process.stderr, SHOW_ALTERNATE_SCREEN);
+const hideAlternateScreen = process.stderr.write.bind(process.stderr, HIDE_ALTERNATE_SCREEN);
+const noOp = () => {};
 
-	const resetPrefix = clearScreen ? `${ansiEscape.eraseScreen}${ansiEscape.cursorTo(0, 0)}` : '';
+export default function alternateScreen (enabled: boolean) {
+	const resetPrefix = enabled ? `${ansiEscape.eraseScreen}${ansiEscape.cursorTo(0, 0)}` : '';
+	const open = enabled ? showAlternateScreen : noOp;
+	const close = enabled ? hideAlternateScreen: noOp;
 
-	return {
-		open () {
-			process.stderr.write(SHOW_ALTERNATE_SCREEN);
-		},
-		close () {
-			process.stderr.write(HIDE_ALTERNATE_SCREEN);
-		},
-		reset (heading: string) {
+	let needAnnounce = true;
+
+	const reset = (heading: string) => {
+		if (needAnnounce) {
 			stderr(`${resetPrefix}${heading}`);
+			needAnnounce = false;
 		}
 	};
+
+	return { open, close, reset };
 }
diff --git a/bin/src/run/watch.ts b/bin/src/run/watch.ts
index b8ac04b9..68ae20ed 100644
--- a/bin/src/run/watch.ts
+++ b/bin/src/run/watch.ts
@@ -34,7 +34,7 @@ export default function watch (configFile: string, configs: RollupWatchOptions[]
 	const initialConfigs = processConfigs(configs);
 	const clearScreen: boolean = initialConfigs.every(cfg => cfg.watch.clearScreen !== false);
 
-	const screen = alternateScreen(isTTY, clearScreen);
+	const screen = alternateScreen(isTTY && clearScreen);
 	screen.open();
 
 	let watcher: Watcher;

```

**Comment by evocateur** [comment] 2017-12-29 15:52
Okay, so this really is about the alternate buffer being opened, not just the cursor stuff. I would just leave `alternateScreen.ts` alone and pass the `isTTY && clearScreen` bool as you described. Solves all the problems, as far as I can tell.

**Comment by jhildenbiddle** [comment] 2018-02-01 23:07
Curious if any progress has been made on this. Would be great to not have the screen clear each time rollup does its thing...

Thanks in advance for the effort. Much appreciated!

**Comment by lukastaegert** [comment] 2018-02-02 09:22
No yet I am afraid. PR welcome :)

**Comment by jhildenbiddle** [comment] 2018-02-02 16:42
Thanks @lukastaegert. Appreciate the quick reply. :)

I can only offer a "would if I could" on the PR. This is a bit out of my comfort zone.

**Closed** 2018-05-25 06:49 UTC
Labels: PR welcome :-), good first issue

**Comment by koo5** [comment] 2021-01-07 21:21
two years later, human civilization still hasn't found a way to prevent rollup from clearing the screen.
