### ISSUE TITLE
Chunking appears to separate variable definition from usage

### ISSUE THREAD

**Issue by arackaf** [rollup/rollup#1989] opened 2018-02-19 17:52 UTC
Repo: https://github.com/arackaf/booklist/tree/special/rollup-chunking-bug-emptyFunction1  (that branch in particular)

Clone, drop into the react-redux folder.  Run `npm i` then `npm run ts`, then finally `npm run rollup`

In `public/module/chunk2.js` you should see this line

`  ReactPropTypes.checkPropTypes = emptyFunction_1;`

which is a ReferenceError at runtime, since emptyFunction_1 is not defined in that same file.  It seems to be defined in a *lot* of other places though, so I'm assuming the chunking code has accidentally orphaned that particular usage.

**Comment by guybedford** [comment] 2018-02-20 15:26
It seems like this is a duplicate of #1996.

**Comment by arackaf** [comment] 2018-02-20 15:29
Sorry for the duplicate -- even though GitHub says mine was opened first, but yet has a *lower* issue number.  Weird - wonder if there's some time bug in GitHub.

**Comment by guybedford** [comment] 2018-02-20 15:31
Nope yours was opened first, just marking this as the duplicate as #1996 the simpler replication :)

**Comment by arackaf** [comment] 2018-02-20 15:34
Yeah I was going to say - he's got a WAY nicer repro story for you.  Sorry about that - I'm not quite smart enough in Rollup to be able to see through to what the root cause is, else I would have done likewise.

**Comment by guybedford** [comment] 2018-02-20 15:39
Binary isolations on the dependency tree can get surprisingly far - removing half the imports, adding back half, etc as the issue arises narrowing it down to a small tree case. Was actually halfway through the process of doing just that when the other issue was posted!

**Comment by guybedford** [comment] 2018-02-21 21:09
@arackaf I've just tested your case and can confirm it is fixed in https://github.com/rollup/rollup/pull/2001!

**Comment by arackaf** [comment] 2018-02-21 23:37
@guybedford Thank you SO much!!!  Amazing work as always.

**Comment by guybedford** [comment] 2018-02-25 19:26
This should be fixed in 0.56.3.

**Closed by guybedford** 2018-02-25 19:26 UTC
