### ISSUE TITLE
Support Dual CommonJS/ES Module Packages with isolated state

### ISSUE THREAD

**Issue by ctavan** [rollup/rollup#3514] opened 2020-04-24 08:27 UTC
### Feature Use Case

I'm a maintainer of the [uuid npm module](https://github.com/uuidjs/uuid/) and I'm currently trying to add ESM support for node, see https://github.com/uuidjs/uuid/pull/402.

Since the uuid module needs to store internal state I'm running into [the dual package hazard](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_dual_package_hazard) and I want to prevent it using [the "isolate state" approach](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_approach_2_isolate_state).

In practice this means that I have the following line in the ESM source:

```js
import state from './v1state.cjs';
```

Unfortunately I can now no longer bundle code that depends on the uuid module unless I add the `commonjs()` plugin to treat `*.cjs` files as shown here https://github.com/uuidjs/uuid/pull/402/files#diff-ff6e5f22a9c7e66987b19c0199636480R16-R18

If I leave the commonjs plugin out I get

```
[!] Error: 'default' is not exported by ../../dist/esm-browser/v1state.cjs, imported by ../../dist/esm-browser/v1.js
```

Now I don't want to ship a library, that requires users of the library to set up extra rollup config but I also don't want to ship it exposing the dual package hazard.

This problem doesn't exist in webpack since webpack seems to have auto-detection of CommonJS files and supports parsing them out-of-the-box.

I understand that rollup explicitly is an "ES Module" bundler. However I can imagine that other library authors will want to ship dual CommonJS/ES Module packages and they will run into the same issue if they choose the "isolate state" approach.

The Node.js docs also mention the ESM-Wrapper approach, where you ship a CommonJS module and only add an ESM wrapper around it for use with Node.js. This would effectively allow me to ship a different true ESM build for bundling with rollup with the downside of Node.js still executing the CommonJS source. That's probably fine for a small library like `uuid()` but maybe something that bigger libraries would want to avoid.

It should be noted that, as far as I understand, bundles created with rollup are not affected by the dual package hazard. This is due to the fact that rollup will always resolve to the _same_ (ES Module) source files as specified by the `"module":` property in `package.json` for the `uuid` module, irrespective of whether it is `require()`d as a transitive dependency inside a CommonJS module or `import`ed in an ES Module.

So the issue here really is that, as far as I understand, library authors have to ship different code for direct execution as ES Module in Node.js and for consumption by rollup.

### Feature Proposal

I am not sure what the proposal should be, I would mainly like to clarify with the rollup maintainers how you think about the dual package hazard and whether you think that library authors should ship different code for direct execution with Node.js and for bundler consumption.

**Comment by frank-dspeed** [comment] 2020-04-27 11:33
@ctavan i did msg you on gitter and also did respond to your 402 issue we need to do a bit more clean up

**Comment by ctavan** [comment] 2020-04-27 15:57
After some discussion on gitter with @frank-dspeed my current understanding is that rollup considers itself as a pure ESM bundler and is therefore not likely to support CommonJS imports out-of-the box.

I would still be happy about an official clarification from the rollup maintainers.

For my specific use case I have found a viable alternative (https://github.com/uuidjs/uuid/pull/423) so I can perfectly live with rollup not supporting this.

**Comment by frank-dspeed** [comment] 2020-04-28 05:15
@lukastaegert can you please look into that and close this?

**Comment by lukastaegert** [comment] 2020-04-28 09:20
Hi, sorry for not getting back earlier. I am aware of this issue and the recommendation by Node to wrap a CJS module in an ESM wrapper.

As you already found out, yes, native CJS support is very unlikely to arrive in Rollup. Moreover, directly bundling such a pattern is probably not in the user’s best interest as due to its nature, CJS modules negate many of the benefits that ES modules provide for bundling. Namely, tree-shaking will likely not work across module boundaries and scope-hoisting may not work either due to necessary code wrappers, resulting in unnecessary property accesses.

There are no established best practices yet but as you already noticed, bundlers will not have this issue anyway. As I see it, the `module` property seems like the best way forward at the moment. It is ignored by Node and only observed by bundlers so it might provide a special entry point for optimal bundling. Does this help?

**Comment by ctavan** [comment] 2020-04-28 09:35
@lukastaegert this perfectly summarizes the conclusion that we arrived at as well (see https://github.com/uuidjs/uuid/pull/423#issuecomment-620271832), thanks!

We just have to be very careful when dealing with https://github.com/rollup/plugins/issues/208 in order not to break the current solution (or provide a viable alternative).

If you agree with that feel free to close this issue.

**Comment by lukastaegert** [comment] 2020-04-28 11:28
Yes, I am aware. This issue will be quite a tricky one, and backwards compatibility is one very important aspect, besides avoiding duplication. My feeling is that by default, Rollup should check `module`, them ESM `exports`, then other alternatives.

**Closed by lukastaegert** 2020-04-28 11:28 UTC

**Comment by jaydenseric** [comment] 2020-04-28 12:05
`exports` field should be the source of truth, not `module`. Firstly, `module` is no help for deep imports. Secondly, `module` can break things when the user is expecting CJS as a result of `require()`, here is something I ran into in the last half hour:

```js
// The full path is required because mitt has a package.json `module` field.
// When graphql-react is used in a webpack project (e.g. via Next.js), webpack
// swaps out the mitt `main` CJS file for the `module` ESM file, represented as
// an object with a `default` key because the ESM only has a default export.
// This would result in `mitt` being undefined instead of a function.
const mitt = require('mitt/dist/mitt.js');
```

**Comment by lukastaegert** [comment] 2020-04-28 13:59
If the user expects CJS, then the user should probably not be using Rollup where all CJS is transpiled to ESM first anyway. Note that this is not a Webpack issue board. Second it does not seem you read the issue I linked, nor did you provide a better alternative solution.

**Comment by jaydenseric** [comment] 2020-04-28 14:40
@lukastaegert 

> Note that this is not a Webpack issue board.

Unnecessarily passive aggressive; I'm here to help. I was referring to webpack in an example of a class of bugs to be avoided - the lesson will presumably apply for any tool that automatically prefers `module` over Node.js standard resolution via package `exports`.

Package authors should not have both `module` and `exports` fields at the same time, but in the real world many people won't realise that (I didn't at first) so tools should prefer `exports`.

> Second it does not seem you read the issue I linked

What link are your referring too? None of your comments in this issue have a link to an issue in them. If you're referring to https://github.com/rollup/plugins/issues/208 , I read it weeks ago and again recently, I even thumbed it.

You can't avoid properly supporting the package `exports` field; it's shipped in Node.js and people are relying on it. The `main` fallback won't help for deep imports, and neither will `module`.

> nor did you provide a better alternative solution.

Use package `exports` field to resolve `require` and `import` specifiers, the Node.js way. Be aware of ESM/CJS interop problems regarding `default` - I can't offer an implementation suggestion because I'm not too familiar with how Rollup works.

I don't actually use Rollup myself. For the ecosystem's sake I have an interest in Rollup playing nicely with the packages I publish, and when I saw a confusing comment like [this](https://github.com/rollup/rollup/issues/3514#issuecomment-620548059):

> My feeling is that by default, Rollup should check `module`, then ESM `exports`, then other alternatives.

…and  [this](https://github.com/rollup/plugins/issues/208#issuecomment-620549486):

> `module` will need to remain a very important field and should by default take precedence over `exports`

I had to say something.

**Comment by guybedford** [comment] 2020-06-06 08:47
@lukastaegert can you share some more justification here on why you feel "module" should take precedence over "exports" in RollupJS?

**Comment by lukastaegert** [comment] 2020-06-06 09:29
Yes I will. The main reason is that `exports` was designed to satisfy the needs of Node, not that of browser users or an ESM bundler, and therefore
- Even something flagged es `import` will not guarantee a pure ESM tree as you can freely import CJS modules from ES modules in Node. And to make things worse, this is even encouraged by Node: https://nodejs.org/api/esm.html#esm_approach_1_use_an_es_module_wrapper

  The approach described here might make sense for Node, but it will produce very sub-optimal output when used for bundling, i.e. hardly any tree-shaking or scope-hoisting is possible. And that is sad because the problem that is solved here is usually not a problem that bundlers experience as they are designed to resolve any package only one way.
- Node allows to use `createRequire` https://nodejs.org/api/modules.html#modules_module_createrequire_filename to support CJS imports from Node. Admittedly, we might eventually support this in `@rollup/plugin-commonjs` but it still produces sub-optimal wrappers.
- It is really difficult for Rollup to actually support proper semantics as handling package.json files is handled by `@rollup/plugin-node-resolve` while importing CJS will be handled by the commonjs plugin. So we will need to establish some form of communications between plugins.

But really, my main motivation is that `module` was specified from the beginning for the need of ESM bundlers, and I do not find this with `exports` at all.

What I could get behind is if we can align on a new specification, e.g. for `package.exports.browser`, that has similar implications as `package.module`. I see there is a growing need from tools like Vite, Snowpack or es-dev-server to make libraries work without bundling in a browser. Those needs are very similar to what we currently want to achieve with the `module` field except `module` has no implication that this code is designed for the browser.

Here are my suggestions what we could put into such a spec. If there are too many libraries that already use `package.exports.browser` to do something else then we might align on a different name. And possible a second field like `package.exports.browserDev` for a dev build if it is available:

The entry point exposed via `package.exports.browser` should
- import only ES modules via relative imports using proper file extensions, or other packages (possibly with sub-paths, there is room for discussion what we could allow here)
- if another package is imported, then this package either satisfies these requirements again or has a `package.exports.browser` field with an entry point that satisfies these requirements
- only use Stage 4 JS features at the time of publishing. This should make everything run in a modern browser. Bundlers can take care of transpiling and adding polyfills for older browsers.
- not import Node builtins (obviously)
- not use Node globals, i.e. no `process.env`. This is also why we would need an optional `package.exports.browserDev` entry for the most common use of `process.env`.

**Comment by guybedford** [comment] 2020-06-06 22:28
With `"module"` it is not necessarily clear how to do browser branching though.

**Comment by lukastaegert** [comment] 2020-06-07 04:56
That is definitely true and the only problem with `module` at the moment, hence the idea to push additional semantics to `exports.browser`. Following the suggestions here https://github.com/uuidjs/uuid/pull/462#issuecomment-640013466 and in the following comments, we could actually go for `exports.module` and use nested conditions.

```json
{
  "main": "./main.js",
  "exports": {
    "module": {
      "browser": "./main-browser.js",
      "node": "./main-node.mjs"
    }
  }
}
```

You could even play around using `"default": ` here so that you only have "node"  and a catch-all for all other environments like "deno".

**Comment by sokra** [comment] 2020-06-07 18:27
Browser branching is also possible with "browser" and "module":

``` json
"main": "./node-cjs.js",
"module": "./node-esm.js",
"browser": {
  "./node-cjs.js": "./web-cjs.js"
  "./node-esm.js": "./web-esm.js"
}
```

But not sure if this is required in practice since it's pretty sure that every tool that chooses the `browser` field supports ESM, so you can just provide only ESM at the browser field.

**Comment by ctavan** [comment] 2020-06-07 21:29
> Browser branching is also possible with "browser" and "module":
> 
> ```json
> "main": "./node-cjs.js",
> "module": "./node-esm.js",
> "browser": {
>   "./node-cjs.js": "./web-cjs.js",
>   "./node-esm.js": "./web-esm.js"
> }
> ```
> 
> But not sure if this is required in practice since it's pretty sure that every tool that chooses the `browser` field supports ESM, so you can just provide only ESM at the browser field.

We do have exactly [this pattern in `uuid`](https://github.com/uuidjs/uuid/blob/0f6c4365275e1f7ef9ee875e01415cd466ae977a/package.json#L29-L33) at the moment but now that you mention it I believe that this is indeed just a legacy from the times where we were not yet shipping an ESM build but _only_ CJS sources.

So I'm sure that this is dead code for recent versions of `webpack` and `rollup`. However I'm not sure about things like `browserify`, I find it pretty hard to foresee what brickage removal of such definitions will cause 🤷‍♂️ .

**Comment by eemeli** [comment] 2020-07-19 08:52
> But not sure if this is required in practice since it's pretty sure that every tool that chooses the `browser` field supports ESM, so you can just provide only ESM at the browser field.

@sokra, this is unfortunately only _almost_ true, as at least Browserify [supports](https://github.com/browserify/browserify#browser-field) `"browser"` but does not support ESM.

**Comment by CxRes** [comment] 2020-07-29 16:40
A naive suggestion perhaps: Since es modules with node (when used repository wide) requires `type: modules` to be set, can't that be used as a test to determine if `exports` should be preferred over `browser`/`module` fields.

**Comment by guybedford** [comment] 2020-07-29 16:47
@CxRes "exports" applies to both CommonJS and ES Modules and is fully independent of the "type": "module" field so that wouldn't be consistent unfortunately.

**Comment by frank-dspeed** [comment] 2020-07-30 15:54
I Think the future is to warn on CJS Imports and create tooling to analyze that at last this is what i am doing at present i try to create tools that will find out which dependencies do return a ESM and which are CJS only so that you can replace them at last.

**Comment by trusktr** [comment] 2021-05-26 03:51
@frank-dspeed Sounds useful. Got a link to such tool?

**Comment by jessethomson** [comment] 2021-06-06 01:07
For me, the power of the `exports` field isn't for commonjs support, but rather, the encapsulation and and subpath exports.

For example, even if you aren't supporting commonjs, the following is quite powerful.

```
{
  "exports": {
    ".": "./dist/index.js",
    "./utils": "./dist/utils/index.js",
    "./features/*": "./dist/features/*.js"
  }
}
```

As such, I would argue that the `exports` field should take precedence over the `module` field, as the `exports` field is more extensible and supports more use cases than the `module` field.

Imo, as a library author, this would be the ideal set up:
```
{
  "name": "pkg",
  "main": "index.cjs.js",
  "module": "index.es.js",
  "exports": {
    ".": {
      "import": "./dist/index.es.js",
      "require": "./dist/index.cjs.js",
    },
    "./utils": {
      "import": "./dist/utils/index.es.js",
      "require": "./dist/utils/index.cjs.js",
    }
  }
}
```
For bundlers that support the `exports` field:
```
import pkg from 'pkg';
import utils from 'pkg/utils';
```
For bundlers that do _not_ support the `exports` field:
```
import pkg from 'pkg'; // <-- still works, falls back to "module" field
import utils from 'pkg/dist/utils'; // <-- no fallback for subpaths, but still works
```
