### ISSUE TITLE
Immediate exports

### ISSUE THREAD

**Issue by leonovalex** [rollup/rollup#2876] opened 2019-05-27 06:57 UTC
### Feature Use Case

Rollup makes exports as:
```js
const something = true;
export { something };
```

### Feature Proposal

It would be useful for some cases if there would be flag (or even default behaviour) for immediate exports:
```js
export const something = true;
```
This will remove intermediate object in declaration of export. This in its turn will allow some minifiers (i.e. webpack) to compress bundles even better by renaming exports.

**Comment by lukastaegert** [comment] 2019-05-27 13:35
Basically a duplicate of #826. Unfortunately at the moment this is a "wontfix". The reasons are:
- According to the spec, there is no semantic difference between the two export styles
- It would be a HUGE refactoring to render the exports inline. Basically we would need to take the complete chunking information into account when rendering modules in order to render the correct exports and there are a lot of edge-cases that need to be considered. Rollup would become A LOT more complicated if we do inline rendering which means increased maintenance cost. And such a cost would need to be outweighed by the benefits. Also, this would probably make future improvements such as sub-module-chunking more difficult.
- There are probably no significant improvements size-wise, bundles might even get larger (e.g. we trade `const x = 1; const y = 2; export {x, y}` for `export const x = 1; export const y = 2`).
- If Webpack is not able to optimize this export style the same way as the other export style, I think everyone would benefit more if Webpack were to improve their algorithms.

**Comment by bdwain** [comment] 2019-06-11 22:08
@lukastaegert can you explain more what webpack has to do with this? Are you saying they should minify both versions the same so rollup shouldn't need to switch from one to the other?

**Comment by lukastaegert** [comment] 2019-06-12 05:46
Exactly.

**Comment by bdwain** [comment] 2019-06-12 15:36
Hmmm it's possible they don't make a distinction anymore. It's hard for me to tell. I know they used to treat them differently in webpack 3, but webpack 4 broke all of our spies so we had to add a hacky plugin that changed the compiled code a little. I just tried running that without my rollup plugin that changed the exports to `export function foo(){}` for the first time and things still passed, so maybe it's no longer necessary for webpack.

**Comment by shellscape** [comment] 2019-08-15 13:27
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Closed by shellscape** 2019-08-15 13:27 UTC
Labels: x⁷ ⋅ wontfix
