### ISSUE TITLE
Issue when using rollup in combination with react

### ISSUE THREAD

**Issue by chiel** [rollup/rollup#1000] opened 2016-09-29 14:06 UTC
I've been experimenting with rollup for the first time today and I must say I'm very impressed so far. However, I'm running into an issue when trying to use react in combination with Rollup.

The building itself goes perfectly fine but when I try to open the actual page, I get the following error in my console:

```
Warning: Exception thrown by hook while handling onBeforeMountComponent: ReferenceError: validateProperty is not defined
ReferenceError: validateProperty is not defined
    at warnUnknownProperties (http://localhost:8080/js/app.js:18688:19)
    at handleElement$1 (http://localhost:8080/js/app.js:18712:3)
    at Object.onBeforeMountComponent (http://localhost:8080/js/app.js:18717:5)
    at callHook (http://localhost:8080/js/app.js:6461:8)
    at emitEvent (http://localhost:8080/js/app.js:6473:7)
    at Object.onBeforeMountComponent (http://localhost:8080/js/app.js:6695:5)
    at Object.mountComponent (http://localhost:8080/js/app.js:6775:42)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8080/js/app.js:11878:36)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8080/js/app.js:11765:21)
    at Object.mountComponent (http://localhost:8080/js/app.js:6778:35)
```

`validateProperty` is missing entirely from the final bundle and I'm not sure what's causing this. I've been playing around with the `babel` and `commonjs` plugins to see if that would change anything, but so far - to no avail.

I have created a repository that reproduces the issue here: https://github.com/chielkunkels/rollup-issue

Basic steps to get it working are:

``` bash
git clone https://github.com/chielkunkels/rollup-issue.git
cd rollup-issue
npm i
npm run build
npm run start
```

Which will serve a page on http://localhost:8080.

Sorry if this issue is just a matter of me using rollup wrong - I tried getting help on the reactiflux community and in the reactjs channel on irc before coming here, but no luck so far.

Cheers

**Comment by chielkunkels** [comment] 2016-09-29 15:12
I've further condensed the example repository. I think that it might be the `commonjs` plugin that causes this issue

**Comment by thisconnect** [comment] 2016-09-30 07:41
hi, your `dist/public/js/app.js` file contains `if (undefined !== 'production') {` so you are running react in dev mode. 

Unfortunately I am not sure what react is trying to tell you.
If you set NODE_ENV to 'production' or change this, the warning should go away and your bundle is a little smaller (still 544kb unminified with all comments):
```js
'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production')
```

btw I personally would not use es modules (import / export) for your server.

**Comment by thisconnect** [comment] 2016-09-30 07:41
congrats issue 1000 !

**Comment by chielkunkels** [comment] 2016-09-30 08:25
@thisconnect aye, I saw that solved it, but the thing is, in dev mode you want those warnings. `if (undefined !== 'production') {}` should resolve to true, and therefore the code should be kept - no?

`validateProperty` I think is something it only does in development mode to ensure that you pass the correct prop types to your components, so it's definitely handy to have in development.

**Comment by chielkunkels** [comment] 2016-09-30 08:30
Alright, so if I explicitly set

```
'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
```

It works, and the code is kept intact... So while my issue is fixed, it still feels to me like an error, since `undefined !== 'production'` should be `true`, and thus the code should be included, no?

**Comment by Victorystick** [comment] 2016-09-30 08:41
Rollup can compare literals in the test expressions of if statements. The reason why it doesn't work at this time is that `undefined` in the `undefined !== 'production'` expression is an identifier, and not a literal. Rollup currently doesn't track the values of Identifiers, although one could argue we could make an exception for `undefined` which would make your example work.

**Comment by chielkunkels** [comment] 2016-09-30 08:52
Alright fair enough, that explains it. So long as it's expected behaviour, that's perfectly fine, but perhaps it should be documented somewhere? Don't know if you want to keep this issue open, but on my end things work a charm now.

Either way - thanks for a  great tool!

**Comment by Victorystick** [comment] 2016-09-30 10:11
@chielkunkels I'll keep it open. :wink:

**Comment by piuccio** [comment] 2016-12-28 15:37
I believe this is a duplicate of rollup/rollup-plugin-commonjs#118

**Comment by guybedford** [comment] 2018-02-11 10:15
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.

**Closed by guybedford** 2018-02-11 10:15 UTC
Labels: closing for inactivity, enhancement
