### ISSUE TITLE
RollUp Logs breaks TFS Build - Silent Mode for RollUp

### ISSUE THREAD

**Issue by NightkingCH** [rollup/rollup#1313] opened 2017-02-23 09:28 UTC
Hi there

I was wondering if it is possible to implement a log level or at least a "silent" option to prevent that non errors (warnings, infos, debug prints) are printed to the error stream / console log. 

I face a problem with this  Message:

> 'default' is imported from external module 'rollup' but never used

This is nothing that breaks the process / the code, but using rollup in the build pipeline with TFS breaks the build cause the warning is written to the StandardError-stream.

I already did suppress the warnings with:

```
options.onwarn = function() {
};
```
But this only affects messages like this:

> The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined

But what I need are only real errors, like when a name is not exported or something else went terrible wrong:

> 'SelectModule' is not exported by node_modules\ng2-select\ng2-select.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

Or is already a solution out there to this (my) problem?

Thanks in advance

**Comment by bfred-it** [comment] 2017-06-21 18:59
Duplicate of https://github.com/rollup/rollup/issues/651

**Closed by bfred-it** 2017-06-21 18:59 UTC
Labels: duplicate
