### ISSUE TITLE
outro position with iife and default export

### ISSUE THREAD

**Issue by timbell** [rollup/rollup#1121] opened 2016-11-23 16:32 UTC
Given test.js:
```
var foo = "bar";
export default foo;
```
and rollup-config.js:
```
import rollup from 'rollup';

export default {
    entry: 'test/test.js',
    dest: 'test/bundle.js',
    moduleName: 'testModule',
    outro: '// outro appears after return',
    format: 'iife',
}
```
I'm getting this bundle.js (rollup 0.36.4):
```
var testModule = (function () {
'use strict';

var foo = "bar";

return foo;
// outro appears after return

}());
```
Is this the expected behaviour? I was hoping to add some code before the `return foo;` statement.

**Comment by nkoterba** [comment] 2016-11-23 22:38
Same exact issue I'm facing.  I'm desperately trying to add some code before the `IIFE` returns the "module_name" and like OP, it adds it *AFTER* the return statement which doesn't do us much good.

**Comment by Rich-Harris** [comment] 2016-12-18 21:20
This is expected behaviour, yes. Can you elaborate on what you're trying to do?

**Comment by tivac** [comment] 2016-12-19 07:04
`outro` blocks are never run & thus useless, because they're after the `return`?

**Comment by timbell** [comment] 2016-12-19 09:52
@Rich-Harris I was battling with bundling `moment` locales. In the end I accepted defeat and set `moment` on the global object and gave up on intro/outro. This notwithstanding, I don't understand the purpose of the outro blocks emitted after the return statement, unless they're not meant for code?

**Comment by timbell** [comment] 2016-12-19 10:04
(I should have said, a `moment` locale self defines on load by calling `moment.defineLocale`. I was trying to shim `moment.defineLocale` using intro/outro blocks to avoid having to have moment set globally.)

**Comment by Rich-Harris** [comment] 2016-12-20 20:46
> `outro` blocks are never run & thus useless, because they're after the `return`?

Ah, I see. That makes sense. I've only used `outro` to hack around the `exports` object in bundles with named exports. I forget the specifics (the only clue is this cryptic issue – https://github.com/rollup/rollup/issues/852), but I do seem to recall that it only worked if the outro happened after `exports` had been assigned to...

Not entirely sure what the correct course is here. Perhaps if it's a default export situation (i.e. there's a `return`, instead of a series of assignments to `exports`) the outro goes first? I guess the alternative would be to introduce a new option. Both seem less than ideal!

**Comment by shellscape** [comment] 2019-08-07 15:05
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.

**Closed by shellscape** 2019-08-07 15:05 UTC
Labels: discussion
