### ISSUE TITLE
Making a testing for project with many dependencies

### ISSUE THREAD

**Issue by YuryStrozhevsky** [rollup/rollup#873] opened 2016-08-24 10:15 UTC
I am working on a **set** of projects, all using ES6. These are really native ES6 projects, completelly without any transformations to ES5 code. Plus from some of these projects I have dependencies to other my projects (directly to ES6 code).

When I am working with a "simple" environment I am using just "rollup-node-resolve" and then use Babel (if needed). But seems I have a problem using Mocha with such projects.

I saw the [rollup-starter-project](https://github.com/rollup/rollup-starter-project), thank you for it. But it works fine until I have ES6 dependencies inside ES6 dependencies. In other words when I am writing ES6 test for mocha and using "import * as proj1 from proj1" all works fine if code for "proj1" does not use any other ES6 code from other ES6 projects. But all crashes in opposite case - when "proj1" has import from "proj2", which is ES6 project. Yes, I had been using "rollup-node-resolve" and riefy - problem exists.

I had been trying to create a special "rollup-register" (special JS compiler) for Mocha, but seems it is not possible - the Mocha expect code to return result synchroniously, but Rollup works with Promises only.

So, please give me an advice what to do in my case. The projects I am working on are really interesting and I would like to use Rollup only + ES6 code only, without making intermediate ES5 code.

**Comment by marvinhagemeister** [comment] 2016-08-24 13:37
You should only need babel to test es6 code with mocha:

```js
// .babelrc
{
  "env": {
    "test": {
      "presets": ["es2015"],
      "plugins": ["transform-runtime"]
    }
  }
}
```

```bash
BABEL_ENV=test mocha --compilers js:babel-register test/**/*.js
```

**Comment by YuryStrozhevsky** [comment] 2016-08-24 19:21
Will it works with ES6 modules as NPM packages? I have dependencies as "import * from npm_package_name".

**Comment by marvinhagemeister** [comment] 2016-08-24 22:18
Yes.

**Comment by YuryStrozhevsky** [comment] 2016-08-25 06:15
No, your suggestion is not working. You can easily test it easily (more or less easily) by doing this:
1) Download and install [rollup-starter-project](https://github.com/rollup/rollup-starter-project);
2) **Before** running "npm install" modify package.json by adding ASN1js ES6 package
```
"asn1js": "git+https://github.com/PeculiarVentures/asn1js-es6.git"
```
3) Change "test/index_test.js" with this code:
```javascript
import { multiply } from '../';
import { strictEqual } from 'assert';
import * as asn1js from "asn1js";

describe('multiply', () => {
  const bitString = new asn1js.BitString();
  bitString.valueBlock.valueHex = new ArrayBuffer(10);

  it('returns 0 when either argument is 0', () => {
    strictEqual(multiply(0, 2), 0);
    strictEqual(multiply(4, 0), 0);
  });

  it('returns the value of one number if the other is 1', () => {
    strictEqual(multiply(1, 8), 8);
    strictEqual(multiply(5, 1), 5);
  });

  it('is commutative', () => {
    strictEqual(multiply(2, 4), multiply(4, 2));
  });

  it('returns the product of the two numbers', () => {
    strictEqual(multiply(11, 9), 99);
  });

  it('handles negative numbers', () => {
    strictEqual(multiply(-2, 2), -4);
    strictEqual(multiply(2, -2), -4);
    strictEqual(multiply(-2, -2), 4);
  });
});
```
4) Modify .babelrc with your changes;
4) Run "npm test".

You will see error "SyntaxError: unexpected token import" on "import { multiply }...". If you will change back .babelrc to initial then after "npm test" you will see the same error but on import from asn1js package (import some symbols from "pvutils" package).

So I have an ugly (IMO) option: make a "pretest" with making special ES6 bundles for files under "test" dir. But probably there a more elegant solution. Please point me to the right direction.

**Comment by GGAlanSmithee** [comment] 2016-08-25 06:51
I don't see how this is related to rollup since you should probably test against the original files (and not a bundle).

Here is how I do it:

`mocha test/* --recursive --compilers js:babel-register --require babel-polyfill`

This requires the packages:

`mocha`
`babel-polyfill`
`babel-register`

Also, just as an aside note, it might be smart to mock external modules from your tests.

**Comment by YuryStrozhevsky** [comment] 2016-08-25 07:26
Yes, my problem is not directly related to rollup itself, more its related to "rollup-starter-project", I think so. But I decided to put in here just because probably more experienced than me which is using rollup will give me a right direction.

And again: @GGAlanSmithee you suggestion **is not working** in case if inside code in "test" would be using NPM ES6 packages which are using other NPM ES6 packages. You can check yourself by going "step-by-step" actions I described above.

Guys, please-please do not think this is a simple question - it is not. I am not a newbie (18+ years of software development) and I spent few days looking on appropriate solution for my problem. Now I need an answer from a real expect in Rollup. Or I need an answer from expect in Babel if the tool supports imports from NPM packages (from my knowledge it is not support it at all).

**Comment by marvinhagemeister** [comment] 2016-08-25 08:50
@YuryStrozhevsky Please reread the replies again. The `test` script of the rollup-starter-project calls mocha directly without any further arguments:

```js
// package.json
{
  ...
  "scripts": {
    "test": "mocha" // <- won't transpile anything at all
  }
}
```

Change this to:

```js
"test": "mocha --compilers js:babel-register test/**/*.js" // or something similar
```

This really is not a rollup issue. For questions regarding `babel` you should file a report there.

**Comment by YuryStrozhevsky** [comment] 2016-08-25 09:11
Probably you did not inspect the project I was refering to - the [rollup-starter-project](https://github.com/rollup/rollup-starter-project). There in the "test" dir there is a file "mocha.opts" with content:
```
--reporter test/istanbul.reporter.js --recursive --compilers js:babel-register
```
So, in fact when I run "npm test" I will get almost the same command arguments for Mocha as you said.

As for "not a rollup issue": I am looking for an answer/advice from experienced Rollup users or developers. I think my problem could be solved by Rollup, but if anyone knows any way how to solve it using only Babel I would appreciate it.

**Comment by marvinhagemeister** [comment] 2016-08-25 11:21
@YuryStrozhevsky you're right, I missed the `mocha.opts` file. I just cloned the project and everything including es6 modules work right out of the gate.

NPM-Modules work fine:

```js
import * as t from 'assert';
import _ from 'lodash';

describe('test', () => {
  it('test2', () => {
    const a = { 'a': 1 };
    const b = { 'a': 1 };

    t.ok(_.isEqual(a, b));
  });
});
```

```bash
npm t

  test
    ✓ test2

  multiply
    ✓ returns 0 when either argument is 0
    ✓ returns the value of one number if the other is 1
    ✓ is commutative
    ✓ returns the product of the two numbers
    ✓ handles negative numbers


  6 passing (98ms)
```

Can you point to a test repository where the problem you're experiencing is easily reproducible?

**Comment by YuryStrozhevsky** [comment] 2016-08-25 11:23
Please follow the steps I described earlier. NPM modules work just fine until you do not have a NPM module on native ES6 which is using other NPM module on native ES6.

**Comment by YuryStrozhevsky** [comment] 2016-08-25 11:43
But in fact the "problem condition" could be simplified down to "NPM modules work until you do not have any imports from NPM modules on native ES6".

So, again back to my initial message: in a "simple" environment I am using rollup + rollup-node-resolve plugin. Rollup then produces me a "bundle" where I do not have any references to external files - all classes and external NPM packages are combined into just one file. But in the case of Mocha testing I do not have a way how to produce the "bundle" before Mocha testing. I have an opition to create "pretest" and create the bundle there, but in fact it would be an ugly solution. I would like to have something simular to "babel-register" compiler for Mocha, but seems Rollup can not compile file syncroniously, as Mocha needed.

**Comment by marvinhagemeister** [comment] 2016-08-25 11:47
Please provide a sample repository. That way you have a better chance of people helping you.

**Comment by YuryStrozhevsky** [comment] 2016-08-25 11:49
If people can not process with simple 6 steps then they could not help me, sorry.

**Comment by GGAlanSmithee** [comment] 2016-08-25 11:57
> But in the case of Mocha testing I do not have a way how to produce the "bundle" before Mocha testing. I have an opition to create "pretest" and create the bundle there, but in fact it would be an ugly solution

This is not your problem. Your problem is that you cannot get mocha+babel to transpile ES6 node_modules on the fly. IMO, you are trying to force the wrong solution to your problem.

As I already ansered, you should not test against the bundle, but against the origianl files. If there is a problem with that, address it where you can get help (mocha and/or babel). This has litterally nothing to do with Rollup. If you _must_  use rollup, then I see nothing wrong with `npm run bundle && npm run test`

**Comment by YuryStrozhevsky** [comment] 2016-08-25 12:09
@GGAlanSmithee OK, then a small course for you also. Just a one question: does Babel supports NPM modules? Myself I found the answer as "no". Thus I came to Rollup. Does Rollup support NPM modules? Yes! So, I **already** found a solution for my problem, as you described it - using Rollup for making bundle which is then could be processed by Babel. But then we come to a real problem - I can not get the bundle "on the fly" before Mocha testing. So, my real problem is what I had been describing. If you do not see any possible solutions (expect the "compiled test" option) please do not write in the thread.

**Comment by GGAlanSmithee** [comment] 2016-08-25 12:11
@YuryStrozhevsky Looking [here](https://babeljs.io/docs/usage/cli/) it says that the deafult option for `ignore` is 'node_modules', so if you set that as an empty array instead, it might work:

´.babelrc´
´´´javascript
{
  "plugins": [...],
  "presets": [...],
  "ignore": []
}
´´´

Unfortunatley, babel has an [open issue](https://phabricator.babeljs.io/T6726) that this option is ignore (it is a bug). But it was fixed Aug. 23 and will be merged soon.

**Comment by YuryStrozhevsky** [comment] 2016-08-25 12:12
Even if Babel will supports NPM modules I do not think they would support "native ES6" NPM modules. Thus in all cases my choice is Rollup.

**Comment by GGAlanSmithee** [comment] 2016-08-25 12:13
Maybe not, Good luck anyway.

**Comment by Rich-Harris** [comment] 2016-08-30 22:02
My favoured approach (which is what Rollup itself does):

```js
// package.json
{
  ...
  "scripts": {
    "test": "mocha",
    "pretest": "npm run build",
    "build": "rollup -c"
  }
}
```

Then, inside `test.js`, just import the bundle. Personally I prefer testing the bundle to testing individual modules anyway, because I only care about whether or not the generated code works, and this way I can guarantee that transpilation and bundling haven't introduced any bugs. (Yes, you can't really unit test this way, but `¯\_(ツ)_/¯`)

**Comment by Rich-Harris** [comment] 2016-08-30 23:41
I'll close this as it doesn't look like there's anything for Rollup to do here – it's not designed to be used at runtime

**Closed by Rich-Harris** 2016-08-30 23:41 UTC

**Comment by YuryStrozhevsky** [comment] 2016-08-31 06:10
Sure, I was going to close the issue. Thanks for the notes!
