### ISSUE TITLE
file extension issues

### ISSUE THREAD

**Issue by Kflash** [rollup/rollup#795] opened 2016-07-24 23:12 UTC
It seems like latest version of Rollup force the developer to add a file extension 

`import x from 'x.js' `

and not the normal way

`import x from 'x `

Any reason for this? I also noticed the Rollup source does it this way.

This practise breaks a lot of things. E.g. if you working with TypeScript and first need to transpile all source code down to ES6. The transpilled source will now have '.ts' extension.

If you now try to bundle the transpilled source with Rollup you get issues because the typescript files isn't found.

There are other scenarios too like this. And in the TypeScript example there isn't an option itself to use that plugin. Way to buggy. And if you try to use that plugin, you will also notice that file extensions are required. As seen in this issue ticket: https://github.com/rollup/rollup-plugin-typescript/issues/52

**Comment by Kflash** [comment] 2016-07-24 23:26
Rolled back to use Rollup v. 0.32.4 solved the issue for now.

**Comment by TrySound** [comment] 2016-07-25 07:28
@Kflash As you can see [here](https://github.com/rollup/rollup/blob/master/src/utils/defaults.js#L9-L16) extension is not required.

**Comment by TrySound** [comment] 2016-07-25 07:29
Maybe the problem is that you are trying to use not relative paths?

**Comment by Kflash** [comment] 2016-07-25 07:34
The funny thing is that everything works as expected until v. 0.33.0. After that version I got issues. 
If you look at the issue I linked too, you will see that others as well experience this. 
However. I'm using TS files and that is what causing the issue. JS files works as expected.

**Comment by Kflash** [comment] 2016-07-25 07:37
@TrySound I'm using windows atm, and I tracked the issue I'm facing to this PR: https://github.com/rollup/rollup/pull/760

**Comment by Kflash** [comment] 2016-07-25 07:52
@TrySound I tried to revert the changes in this PR locale, and it works just fine! So the issue is with that PR. The issue is located to be in the CLI source code.

**Comment by TrySound** [comment] 2016-07-26 04:06
But this lines don't response for resolving in rollup itself.

**Comment by Kflash** [comment] 2016-07-26 06:28
I was running it from cli. It worked after I changed the lines. Sounds
crazy.  Further crazy is it that something from v 0.33.0 screw this up too.

Easiest to reproduce if you use Windows and try it out. I linked to another
issue ticket earlier. He have it rigged so you can try and fail

**Comment by Kflash** [comment] 2016-07-26 06:31
4 persons experience the same thing with Windows

**Comment by Kflash** [comment] 2016-08-02 04:21
Looks like this issue isn't going to be fixed? For me it's an annoying issue on Windows, so I did some digging into the source code and found out why this issue occur!

**Note!** All files except `.js` are effected both on Mac and Windows.

This function https://github.com/rollup/rollup/blob/master/src/utils/defaults.js#L9 is the evil one!

If you do this, it will automatically add the .js file extension.

```js
// import
import a from './rollup';

// will search for rollup.js
````
What if this is an TypeScript file, or CoffeScript or other file types? A error will be thrown because the file isn't found.

**Comment by Kflash** [comment] 2016-08-02 04:25
There are still a issue also with Rollup v. 0.33.1 on Windows when using the CLI. Crazy enough not on all Windows computers I tested it on, but a few.

**Comment by TrySound** [comment] 2016-08-02 04:25
@Kflash 

- `fs.stat` does not create file. So nothing is evil here.
- typescript plugin has own resolver, so this part of code has no effect on your results.

**Comment by Kflash** [comment] 2016-08-02 04:27
@TrySound  `file += '.js';` this one will add the js extension if there is no file extension. 

It uses the function isFile() to figure out if it's an vanlid file or not. If not, it add the extension.

**Comment by TrySound** [comment] 2016-08-02 04:28
Yep. It's fallback. I meant it do not create new one with that extension.

**Comment by TrySound** [comment] 2016-08-02 04:29
It's only default behavior.

**Comment by Kflash** [comment] 2016-08-02 04:30
I know, so if you import a TypeScript file like this

```js
import a from './rollup'
```
it will start to search for `rollup.js` and not `rollup.ts`  and throw an error.

**Comment by TrySound** [comment] 2016-08-02 04:32
Yep. Is that a problem for you? What is the reason to let rollup by default look for some weird ts extension? If you will look at rollup source code we even do not use fallback for js and will remove it soon.

**Comment by TrySound** [comment] 2016-08-02 04:33
try
```
import a from './rollup.ts'
```

**Comment by Kflash** [comment] 2016-08-02 04:33
If you try to test this on Rollup v. 0.32.4 it works just fine. Changed happened after 0.33.0.

Well. If you look at the issues on the TS plugin repo you will see that this is an issue for many users.

**Comment by TrySound** [comment] 2016-08-02 04:34
Well without ts plugin it shoudn't look for ts extension. So the problem with ts plugin itself.

**Comment by Kflash** [comment] 2016-08-02 04:35
In my case I'm not using that plugin. But I'm trying to figure out what changed in earlier versions

**Comment by TrySound** [comment] 2016-08-02 04:36
And how do you process typescript? Own realisation?

**Comment by Kflash** [comment] 2016-08-02 04:37
TSC

**Comment by TrySound** [comment] 2016-08-02 04:37
Can you provide some repo with repro? And we will figure out together.

**Comment by Kflash** [comment] 2016-08-02 04:39
I will if I can't solve this. I will come back to this issue soon.

**Comment by Kflash** [comment] 2016-08-02 04:55
Solved it for now by adding this expensive code snippet

```js
file += '.ts';
 if ( isFile( file ) ) return file;
```
But I guess Webpack, Browserify etc do this different.

**Comment by TrySound** [comment] 2016-08-02 05:02
Show your resolver

**Comment by Kflash** [comment] 2016-08-02 05:10
I simply let it check for TS files after JS files. But a solution to this issue could be so simply to let it check against the most common file extensions. If not - instead of returning null - throw an error suggestion to use a Rollup plugin. 

Would be better then just throw this: ` Error: Could not load null: path must be a string or Buffer`. Then at least users knows what's wrong

**Comment by TrySound** [comment] 2016-08-02 05:16
Rollup do it. For default. Throw error by yourself. This will prevent using the next resolver including default.

**Comment by Kflash** [comment] 2016-08-02 05:24
NP. Others who have some issues can continue this discussion. In fact I stopped using Rollup 1 week ago, and encountered this and some other stuff again when I tried Rollup.

**Closed** 2016-08-02 05:35 UTC
Labels: bug, windows

**Comment by Kflash** [comment] 2016-08-02 05:44
For further reading: https://github.com/rollup/rollup-plugin-typescript/issues/52

**Comment by fabiosantoscode** [comment] 2019-02-17 20:44
@nifgraup found this issue while converting Terser.

For example, in this file: https://github.com/terser-js/terser/blob/master/main.js

I haven't checked the others but `lib/compress.js` really has to have the `.js` there.

I am trying to clean up Terser code, so I made a folder `lib/compress` and put the first file there, `index.js`. Rollup still couldn't find `lib/compress` without the `/index.js`.

**Comment by nifgraup** [comment] 2019-02-20 11:37
@fabiosantoscode The only issue with rollup I found during that task was #2606, in fact I think importing by full file name is clearest.
