### ISSUE TITLE
Cyclic dependency resolution is broken

### ISSUE THREAD

**Issue by grssam** [rollup/rollup#995] opened 2016-09-27 22:44 UTC
Consider [this example](http://rollupjs.org/?version=0.36.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwTDElMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmwxLmpzJTVDJTIyJTNCJTVDbmltcG9ydCUyMCU3QiUyMEw0JTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZ1dGlscy5qcyU1QyUyMiUzQiU1Q25MMShMNCglNUMlMjIxJTVDJTIyKSklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybDEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCTDIlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRnV0aWxzLmpzJTVDJTIyJTNCJTVDbmV4cG9ydCUyMHZhciUyMEwxJTIwJTNEJTIwTDIoJTVDJTIyMiU1QyUyMiklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybDIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCTDMlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmwzLmpzJTVDJTIyJTNCJTVDbmV4cG9ydCUyMHZhciUyMEwyJTIwJTNEJTIwTDMoJTVDJTIyMyU1QyUyMiklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybDMuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCTDQlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRnV0aWxzLmpzJTVDJTIyJTNCJTVDbmV4cG9ydCUyMHZhciUyMEwzJTIwJTNEJTIwTDQoJTVDJTIyNCU1QyUyMiklMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybDQuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwdmFyJTIwTDQlMjAlM0QlMjAlNUMlMjI1JTVDJTIyJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnV0aWxzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBmcm9tJTIwJTVDJTIyLiUyRmwyLmpzJTVDJTIyJTNCJTVDbmV4cG9ydCUyMColMjBmcm9tJTIwJTVDJTIyLiUyRmw0LmpzJTVDJTIyJTNCJTIyJTdEJTVEJTdE). In cases where I have a single file exporting multiple modules as a single submodule, the output file has reference to the modules before the declaration, i.e. the dependency tree is incorrectly created somehow.

Ignore the incorrectness of the JS. The example is just there to demonstrate the bug.

**Comment by grssam** [comment] 2016-09-29 09:10
Any way I can avoid this issue apart from importing directly from the files?

**Comment by thisconnect** [comment] 2016-09-29 09:45
what is your expected result?

**Comment by grssam** [comment] 2016-09-29 10:30
@thisconnect Well, the generated JS file should not throw. Since this is strict mode, variable hoisting does not work, so for line 3 `var L3 = L4("4")` to work, `L4` should be declared before line 3.

**Comment by grssam** [comment] 2016-09-29 11:26
@Victorystick Any chances this can be fixed soon? If the devs are not able to pick this one up soon, I can help fix this bug as well, if I can get some pointers on how to debug/contribute etc.

**Comment by Victorystick** [comment] 2016-09-29 11:37
@grssam I'm a little out of the loop since the big rewrite (#902). I suggest you create a failing test case in test/function, then start looking at `sort` in `src/Bundle.js` and work your way from there.

**Comment by grssam** [comment] 2016-09-29 22:07
I debugged a bit using devtools on the rollupjs.org site and found the cause of the issue. I think the **whole cycle resolution logic is broken right now**.

The example in the original issue has an obvious cycle where `l2.js` depends on `l3.js` for module `L3`, `l3.js` depends on `utils.js` for module `L4` and then `utils.js` again depends on `l2.js` for module 'L2`.

This is detected by this code piece in [`Bundle.js#L470-L482`](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L470-L482) :

```javascript
const visit = module => {
	if ( seen[ module.id ] ) {
		hasCycles = true;
		return;
	}

	seen[ module.id ] = true;

	module.dependencies.forEach( visit );
	ordered.push( module );
};

visit( this.entryModule );
```

shortly after which, [cycle resolution code](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L484-L516) starts which looks like:

```javascript
if ( hasCycles ) {
	ordered.forEach( ( a, i ) => {
		for ( i += 1; i < ordered.length; i += 1 ) {
			const b = ordered[i];

			if ( stronglyDependsOn[ a.id ][ b.id ] ) {
			...
			}
		}
	});
}
```

So the complete cycle resolution algorithm depends on some 2D boolean map `stronglyDependsOn` which is populated [in these lines](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L443-L468). The population of this map in turn depends on the fact that `module.strongDependencies` is an array of all strong dependencies (whatever that means).

This is the core of the issue that this array (`strongDependencies`) is never populated inside `Module.js` or any other file in the final rollup bundle file. Thus, `stronglyDependsOn[ a.id ][ b.id ]` is always false in [line 489](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L489) of the cycle resolution algorithm and the execution never goes inside the if block.

@Victorystick / @Rich-Harris : I don't know the real reason of two separate arrays representing the dependency list - `strongDependencies` and `dependencies`. Maybe the above present information might make the fix real easy for someone more familiar with the code.

**Comment by grssam** [comment] 2016-09-30 12:56
I tried the test case on version `0.34.13` which was before the big rewrite. Turns out, even though that version properly applies the cycle resolution algorithm, it does not actually orders the modules correctly. It simply throws a warning asking the user to reshuffle the import order.

What I feel the main issue of this all is that in the [below code](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L470-L482)
```javascript
const visit = module => {
	if ( seen[ module.id ] ) {
		hasCycles = true;
		return;
	}
	seen[ module.id ] = true;

	module.dependencies.forEach( visit );
	ordered.push( module );
};
```
Instead of discarding (early return) the current module inside the `if ( seen[ module.id ] ) { ... }`, we should actually remove the `module` from the `ordered` array and push it back on top again. Something like:
```javascript
const visit = module => {
	if ( seen[ module.id ] ) {
		hasCycles = true;
		ordered.splice( ordered.findIndex( m => m.id == module.id ), 1 );
		ordered.push( module );
		return;
	}
	seen[ module.id ] = true;

	module.dependencies.forEach( visit );
	ordered.push( module );
};
```

**Comment by trusktr** [comment] 2016-10-04 16:44
Cool, looking forward to the solution. Can't really use rollup until fixed.

**Comment by grssam** [comment] 2016-10-04 17:04
@trusktr  - You can shift your dependencies / import statements until it work for you. You can also use version 0.34 and below to actually get warnings on what all imports to shift

**Comment by grssam** [comment] 2016-10-28 19:11
Any plans on fixing this?

**Comment by mbostock** [comment] 2016-11-07 18:55
This hit me, too. Here’s [another test case](http://rollupjs.org/?shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwRm9vJTIwZnJvbSUyMCU1QyUyMi4lMkZmb28lMkZpbmRleCU1QyUyMiUzQiU1Q24lNUNuY29uc29sZS5sb2cobmV3JTIwRm9vKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28lMkZpbmRleC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBmb29fYmFyJTIwZnJvbSUyMCU1QyUyMi4lMkZiYXIlNUMlMjIlM0IlNUNuaW1wb3J0JTIwYmFyX2ZvbyUyMGZyb20lMjAlNUMlMjIuLiUyRmJhciUyRmZvbyU1QyUyMiUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwRm9vKCklMjAlN0IlN0QlNUNuJTVDbkZvby5wcm90b3R5cGUuYmFyJTIwJTNEJTIwZm9vX2JhciUzQiU1Q25Gb28ucHJvdG90eXBlLmZvbyUyMCUzRCUyMGJhcl9mb28lM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyZm9vJTJGYmFyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMEJhciUyMGZyb20lMjAlNUMlMjIuLiUyRmJhciUyRmluZGV4JTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24oKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjBuZXclMjBCYXIlM0IlNUNuJTdEJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJhciUyRmluZGV4LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGJhcl9mb28lMjBmcm9tJTIwJTVDJTIyLiUyRmZvbyU1QyUyMiUzQiU1Q25pbXBvcnQlMjBmb29fYmFyJTIwZnJvbSUyMCU1QyUyMi4uJTJGZm9vJTJGYmFyJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBCYXIoKSUyMCU3QiU3RCU1Q24lNUNuQmFyLnByb3RvdHlwZS5mb28lMjAlM0QlMjBiYXJfZm9vJTNCJTVDbkJhci5wcm90b3R5cGUuYmFyJTIwJTNEJTIwZm9vX2JhciUzQiUyMCUyRiUyRiUyME5vdCUyMGhvaXN0ZWQlM0IlMjB1bmRlZmluZWQhJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmJhciUyRmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBGb28lMjBmcm9tJTIwJTVDJTIyLi4lMkZmb28lMkZpbmRleCU1QyUyMiUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uKCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwbmV3JTIwRm9vJTNCJTVDbiU3RCUzQiUyMiU3RCU1RCU3RA==).

**Comment by grssam** [comment] 2017-01-13 16:57
bump

/cc @Rich-Harris

**Comment by Rich-Harris** [comment] 2017-01-13 19:23
Currently working on a completely new tree-shaking approach which (among many other things, if it works out) should in theory make detection of improperly-ordered modules much easier. I need to make one point of clarification though —

> even though that version properly applies the cycle resolution algorithm, it does not actually orders the modules correctly

The purpose of that code wasn't to reorder the modules. The order is completely determined by the order of `import` declarations (per the spec), not what's in your code, and Rollup should not and will not attempt to shuffle code about to make it work. Instead, it will detect when there's a problem and invite the developer to fix it, as it used to before the 0.35 rewrite.

**Comment by grssam** [comment] 2017-01-13 19:37
The major thing in this ticket is that cyclic dependencies are not resolved correctly, the module ordering should not be a problem.

If you see the reduced test case in the original comment, you would notice that there is nothing wrong with the `import` ordering in the various files (individually). Its only when you look at the complete tree, the cycle causes an issue. Now is that something which the spec allows for the compiler (or rollup in this case) to adjust to and order the declaration of the imported modules accordingly, I am not really sure.

**Comment by Qiu-Kejian** [comment] 2017-01-16 06:17
Hit me too. Waiting for the solution.

**Comment by kaarmann** [comment] 2017-02-25 21:14
Hit me too with `sepc256k1` and `elliptic` includes. Has anyone found a temporary workaround? Thanks.

**Comment by trusktr** [comment] 2017-03-01 18:39
A workaround for anyone interested in solving cyclic ES6 module dependencies in general is to use "hoisted init functions". See here:

https://esdiscuss.org/topic/how-to-solve-this-basic-es6-module-circular-dependency-problem

The solution (thanks to those awesome people who took the time to read the problem I had) is designed to work around the problem of modules that depend on each other in a circular dependency and who need each other's export at runtime. In particular, it assumes a module needs the export of another module at runtime, but the other module needs the export of the first module at *module evaluation time*.

When circular dependencies both depend on each other's export *at runtime only*, then there isn't really a problem, and the circular dependencies should work perfectly fine. It is mainly when circular dependencies depend on each other at *module evaluation time* that problems arise.

Using the awesome ideas that those people there presented, I was able to solve my circular dependency problems. Read carefully, as there are caveats around the use of `let` due to limitations of the ES6 module implementations.

After solving circular my problems, I was able to refactor code to eliminate some circular dependencies completely, which is ultimately a better solution when possible. Use circular dependencies only as a last resort if there's no other way.

**Comment by olsonpm** [comment] 2017-05-17 19:29
Here's the updated [repro link](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEwxJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZsMS5qcyU1QyUyMiUzQiU1Q25pbXBvcnQlMjAlN0IlMjBMNCUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGdXRpbHMuanMlNUMlMjIlM0IlNUNuTDEoTDQoJTVDJTIyMSU1QyUyMikpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmwxLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QkwyJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZ1dGlscy5qcyU1QyUyMiUzQiU1Q25leHBvcnQlMjB2YXIlMjBMMSUyMCUzRCUyMEwyKCU1QyUyMjIlNUMlMjIpJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmwyLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QkwzJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZsMy5qcyU1QyUyMiUzQiU1Q25leHBvcnQlMjB2YXIlMjBMMiUyMCUzRCUyMEwzKCU1QyUyMjMlNUMlMjIpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmwzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3Qkw0JTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZ1dGlscy5qcyU1QyUyMiUzQiU1Q25leHBvcnQlMjB2YXIlMjBMMyUyMCUzRCUyMEw0KCU1QyUyMjQlNUMlMjIpJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmw0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMHZhciUyMEw0JTIwJTNEJTIwJTVDJTIyNSU1QyUyMiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJ1dGlscy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAqJTIwZnJvbSUyMCU1QyUyMi4lMkZsMi5qcyU1QyUyMiUzQiU1Q25leHBvcnQlMjAqJTIwZnJvbSUyMCU1QyUyMi4lMkZsNC5qcyU1QyUyMiUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) to work with the new site

**Comment by EmielM** [comment] 2017-09-12 20:09
In my attempts to get ReactNative bundled with rollup, I encountered this issue. I still believe this is actually more of a [RN bug](https://github.com/facebook/react-native/issues/15233), but the folks over there seem perfectly happy with their ridiculously complex code base (it's true that a few cyclic dependencies are probably the least of their horrors).

As a work-around, I have created a branch of rollup that allows for the definition of a list of edges called `weakDependencies`. In rollup's "enhanced topological sort", these dependencies are not accounted for when doing the [dfs traversing](https://github.com/rollup/rollup/blob/9d7e7003d71773e14bd9c8ea36ff0be967a9e62a/src/Bundle.js#L590)*. `weakDependencies` are defined as a list of [moduleA,moduleB] tuples where moduleA should only use moduleB in runtime.

Works pretty well, and wouldn't mind cleaning it up to submit a pull request. However I do agree that a better solution would be completely automatic in some way -- it is pretty tough to wrap your head around. I don't really see how this could be done for the generic case -- especially if you don't really control the code as is the case when compiling RN.

*(PS: while doing so, see that the `strongDependencies` var is still being used and checked, but never actually populated).

**Comment by olsonpm** [comment] 2017-09-12 20:16
this issue should be closed as there is no problem with cyclic dependencies.  what the OP posted as a problem is exactly the expected behavior per the spec

**Comment by EmielM** [comment] 2017-09-12 21:03
Point taken, but it's still annoying as hell for developers, especially when coming from runtime packagers (rn packager, webpack) that work just fine.

Here's a [simple case](
https://rollupjs.org/repl?version=0.49.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGIlMjBmcm9tJTIwJy4lMkZiJyUzQiU1Q25pbXBvcnQlMjBhJTIwZnJvbSUyMCcuJTJGYSclM0IlNUNuJTVDbmNvbnNvbGUubG9nKGElMkMlMjBiKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGIlMjBmcm9tJTIwJy4lMkZiJyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGIlMkJiJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwYSUyMGZyb20lMjAnLiUyRmEnJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAxMjMlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmlpZmUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==) vs [broken](https://rollupjs.org/repl?version=0.49.3&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGElMjBmcm9tJTIwJy4lMkZhJyUzQiU1Q25pbXBvcnQlMjBiJTIwZnJvbSUyMCcuJTJGYiclM0IlNUNuJTVDbiU1Q25jb25zb2xlLmxvZyhhJTJDJTIwYiklM0IlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBiJTIwZnJvbSUyMCcuJTJGYiclM0IlNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBiJTJCYiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJiLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGElMjBmcm9tJTIwJy4lMkZhJyUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwMTIzJTVDbiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJpaWZlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

Some thoughts:
- There is a working ordering for this case, but rollup (or: the spec) doesn't support it.
- The whole import/export spec feels *really* declarative, but *apparently the order in which you define imports can break the world*.
- Conversion from commonjs probably inflates the issue for a lot of npm packages out there.

I see that there is some [now-defunc code](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L609) (works kind-of when using `dependsOn` instead of `strongDependsOn`) tried to warn the developer when using circulars. What's the plan for this?

**Comment by olsonpm** [comment] 2017-09-12 22:04
what you are suggesting is that rollup behave differently from the spec which would be much worse

**Comment by EmielM** [comment] 2017-09-13 09:30
I can imagine this to be configurable or at least extensible through a
plugin in some way. Plugins unfortunately have very little influence on
this part of rollup (by design I guess, bundle/module instances are
serialized and never exposed to plugins).

But let's be honest about that spec. It totally sucks, at least for these
cases. It's completely unexpected - especially when coming from other
module systems - and will take developers hours of productivity to fathom
what is going on. Good error reporting on the side of rollup might help a
little here.

**Comment by grssam** [comment] 2017-09-13 09:34
One thing to note is that the spec is very young at this moment. Only a few browsers support it, no production systems have started relying on it etc. Its not wrong to imagine that as this native module feature gains popularity, devs would start complaining about this limitation.

**Comment by olsonpm** [comment] 2017-09-13 21:27
yes a configuration would work.  I imagine it being opt in, and the switch would modify the import [evaluation algorithm here](https://github.com/rollup/rollup/blob/master/src/Bundle.js#L590-L602)

as for the spec sucking, keep in mind the impact the spec has.  unlike the ephemeral code we all mostly write, specs set standards that have to be adhered to for a long time.  One pattern i've noticed with the http spec is they start simple and only evolve when demand is high.  Optimization improvements were the most notable for me in terms of complexity being added in later.  I definitely think managing circular dependencies should have been out of scope and left for userland to test both the demand and implementation.

Also worth mentioning is node has never supported it - they just throw an awkward "module not found" error that you eventually learns means a circular dependency.

**Comment by guybedford** [comment] 2018-01-24 14:04
Cyclic resolution definitely works correctly. We can possibly create a tracking issue for reenabling warnings on cyclic dependencies though.

**Closed by guybedford** 2018-01-24 14:04 UTC
Labels: bug, scope-hoisting

**Comment by trusktr** [comment] 2018-01-24 17:51
> what you are suggesting is that rollup behave differently from the spec which would be much worse

No, actually, it is you fine folks who make Rollup, Webpack, JSPM, etc, who should encourage the spec to change for the better, not the other way around.

Browser makers have done this with web specs all the time (though sometimes not enough).

Clearly, circular dependencies can be very hard to wrap our heads around the way they are spec'd.

If it is completely obvious that module A only depends on module B at runtime (not module evaluation time) then it would be great for the system to automatically resolve circs when possible.

There's no one better to do this than the people who make the module loaders. YOU have the power!

@rauschma I haven't seen any articles on solving circular dependencies using module hoisting yet. That'd be a good one for the people that will keep stumbling here! (My comment above has a link to an esdiscuss thread with some details that are gatherable after wading through the thread, not as nice as an article would be).

**Comment by olsonpm** [comment] 2018-01-24 18:44
You're right.  We should deviate from the spec so that way when you translate from one bundling software to another, or go back to vanilla browser behavior - you can keep in mind all the edge cases each one brings to the table because they couldn't all agree upon a standard.
